// Some portions generated by Co-Pilot
"use client";

import React from "react";
import { Link } from "@/i18n/navigation";
import type { BinaryAssetView } from "@/types/temurin";
import { sendDownloadEvent } from "@/utils/gtag";
import { getExtension } from "@/utils/temurin";
import { FaWindows, FaApple } from "react-icons/fa";
import { BsDownload } from "react-icons/bs";

interface OneClickDownloadProps {
  selectedVersion: string;
  releases: BinaryAssetView[];
}

const OneClickDownload: React.FC<OneClickDownloadProps> = ({
  selectedVersion,
  releases,
}) => {
  if (!releases.length) {
    return null;
  }

  const firstView = releases[0];
  const versionFormatted = firstView?.release_name ?? selectedVersion;

  let macOSLink = "#";
  let macOSDisplay = `Temurin ${versionFormatted}`;
  let macOSIsInstaller = false;
  let macOSReleaseVersion = versionFormatted;

  let windowsLink = "#";
  let windowsDisplay = `Temurin ${versionFormatted}`;
  let windowsIsInstaller = false;
  let windowsReleaseVersion = versionFormatted;

  let foundMacOSArm = false;
  let foundMacOSX64 = false;
  let foundWindowsX64 = false;
  let macOSArmJDK = false;
  let macOSX64JDK = false;
  let windowsX64JDK = false;

  releases.forEach((view) => {
    const b = view.binary;
    const bOs = b?.os ?? "";
    const bArch = b?.architecture ?? "";
    const isJDK = (b?.image_type ?? "").toUpperCase() === "JDK";
    const relName = view.release_name ?? selectedVersion;
    const instLink = b?.installer?.link ? (b.installer.link as string) : null;
    const pkgLink = b?.package?.link ? (b.package.link as string) : null;
    const pkgExt = getExtension(b?.package?.name);

    if (bOs === "mac" && bArch === "aarch64") {
      if (instLink) {
        if (!foundMacOSArm || (isJDK && !macOSArmJDK)) {
          macOSLink = instLink;
          macOSReleaseVersion = relName;
          macOSDisplay = `Temurin ${relName}, macOS aarch64 (M1) (.PKG)`;
          foundMacOSArm = true;
          macOSArmJDK = isJDK;
          macOSIsInstaller = true;
        }
      } else if (!macOSIsInstaller && pkgExt && pkgLink) {
        if (!foundMacOSArm || (isJDK && !macOSArmJDK)) {
          macOSLink = pkgLink;
          macOSReleaseVersion = relName;
          macOSDisplay = `Temurin ${relName}, macOS aarch64 (M1) (.${pkgExt.toUpperCase()})`;
          foundMacOSArm = true;
          macOSArmJDK = isJDK;
        }
      }
    }

    if (bOs === "mac" && bArch === "x64") {
      if (instLink) {
        if (!foundMacOSX64 || (isJDK && !macOSX64JDK)) {
          if (!foundMacOSArm || (isJDK && !macOSArmJDK)) {
            macOSLink = instLink;
            macOSReleaseVersion = relName;
            macOSDisplay = `Temurin ${relName}, macOS x64 (.PKG)`;
            foundMacOSX64 = true;
            macOSX64JDK = isJDK;
            macOSIsInstaller = true;
          }
        }
      } else if (!macOSIsInstaller && pkgExt && pkgLink) {
        if (!foundMacOSX64 || (isJDK && !macOSX64JDK)) {
          if (!foundMacOSArm || (isJDK && !macOSArmJDK)) {
            macOSLink = pkgLink;
            macOSReleaseVersion = relName;
            macOSDisplay = `Temurin ${relName}, macOS x64 (.${pkgExt.toUpperCase()})`;
            foundMacOSX64 = true;
            macOSX64JDK = isJDK;
          }
        }
      }
    }

    if (bOs === "windows" && bArch === "x64") {
      if (instLink) {
        if (!foundWindowsX64 || (isJDK && !windowsX64JDK)) {
          windowsLink = instLink;
          windowsReleaseVersion = relName;
          windowsDisplay = `Temurin ${relName}, Windows 64 bit (.MSI)`;
          foundWindowsX64 = true;
          windowsX64JDK = isJDK;
          windowsIsInstaller = true;
        }
      } else if (!windowsIsInstaller && pkgExt && pkgLink) {
        if (!foundWindowsX64 || (isJDK && !windowsX64JDK)) {
          windowsLink = pkgLink;
          windowsReleaseVersion = relName;
          windowsDisplay = `Temurin ${relName}, Windows 64 bit (.${pkgExt.toUpperCase()})`;
          foundWindowsX64 = true;
          windowsX64JDK = isJDK;
        }
      }
    }
  });

  return (
    <div className="flex justify-between flex-col md:flex-row w-full items-center gap-6 max-w-[1264px] mx-auto">
      {/* macOS Download Card */}
      <div className="p-6 bg-[#200E46] justify-between w-full border rounded-[24px] border-[#564873] h-[200px] flex flex-col transition-all duration-300 ease-in-out hover:border-primary shadow-[0_2px_4px_rgba(255,20,100,0.2)]">
        <span className="p-4 rounded-full w-fit bg-[#2B1A4F] border border-[#5A4D76]">
          <FaApple size={24} />
        </span>
        <div className="flex justify-between items-center gap-6">
          <div className="flex flex-col space-y-1">
            <h4 className="text-3xl font-semibold">macOS</h4>
            <h5 className="text-sm font-normal text-grey">{macOSDisplay}</h5>
          </div>
          <span className="p-2 group cursor-pointer rounded-full w-fit bg-[#2B1A4F] border border-[#5A4D76] hover:border-primary transition-all duration-300 ease-in-out">
            <Link
              href={{
                pathname: "/download",
                query: {
                  link: macOSLink,
                  vendor: "Adoptium",
                },
              }}
              aria-label="Download macOS package"
              onClick={() =>
                sendDownloadEvent({
                  link: macOSLink,
                  os: "mac",
                  arch: foundMacOSArm ? "aarch64" : "x64",
                  pkg_type: "jdk",
                  version: macOSReleaseVersion,
                  vendor: "Adoptium",
                })
              }
            >
              <BsDownload size={20} />
            </Link>
          </span>
        </div>
      </div>

      {/* Windows Download Card */}
      <div className="p-6 bg-[#200E46] justify-between w-full border rounded-[24px] border-[#564873] h-[200px] flex flex-col transition-all duration-300 ease-in-out hover:border-primary shadow-[0_2px_4px_rgba(255,20,100,0.2)]">
        <span className="p-4 rounded-full w-fit bg-[#2B1A4F] border border-[#5A4D76]">
          <FaWindows size={24} />
        </span>
        <div className="flex justify-between items-center gap-6">
          <div className="flex flex-col space-y-1">
            <h4 className="text-3xl font-semibold">Windows</h4>
            <h5 className="text-sm font-normal text-grey">{windowsDisplay}</h5>
          </div>
          <span className="p-2 group cursor-pointer rounded-full w-fit bg-[#2B1A4F] border border-[#5A4D76] hover:border-primary transition-all duration-300 ease-in-out">
            <Link
              href={{
                pathname: "/download",
                query: {
                  link: windowsLink,
                  vendor: "Adoptium",
                },
              }}
              aria-label="Download Windows package"
              onClick={() =>
                sendDownloadEvent({
                  link: windowsLink,
                  os: "windows",
                  arch: "x64",
                  pkg_type: "jdk",
                  version: windowsReleaseVersion,
                  vendor: "Adoptium",
                })
              }
            >
              <BsDownload size={20} />
            </Link>
          </span>
        </div>
      </div>
    </div>
  );
};

export default OneClickDownload;
