// Some portions generated by Co-Pilot
import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import IconSocial from "../index";

describe("IconSocial", () => {
  it("renders a single twitter icon when icon='twitter' is provided", () => {
    render(
      <IconSocial link="https://x.com/adoptium" icon="twitter" />
    );
    const links = screen.getAllByRole("link");
    expect(links[0]).toHaveAttribute("href", "https://x.com/adoptium");
    expect(links[0]).toHaveAttribute("target", "_blank");
    expect(screen.getAllByText("twitter").length).toBeGreaterThan(0);
  });

  it("renders a single github icon", () => {
    render(
      <IconSocial link="https://github.com/adoptium" icon="github" />
    );
    const links = screen.getAllByRole("link");
    const githubLink = links.find(
      (link) => link.getAttribute("href") === "https://github.com/adoptium"
    );
    expect(githubLink).toBeDefined();
    expect(screen.getAllByText("github").length).toBeGreaterThan(0);
  });

  it("renders different icon types", () => {
    const { unmount: u1 } = render(
      <IconSocial link="https://linkedin.com" icon="linkedin" />
    );
    expect(screen.getAllByText("linkedin").length).toBeGreaterThan(0);
    u1();

    const { unmount: u2 } = render(
      <IconSocial link="https://youtube.com" icon="youtube" />
    );
    expect(screen.getAllByText("youtube").length).toBeGreaterThan(0);
    u2();

    const { unmount: u3 } = render(
      <IconSocial link="https://slack.com" icon="slack" />
    );
    expect(screen.getAllByText("slack").length).toBeGreaterThan(0);
    u3();

    const { unmount: u4 } = render(
      <IconSocial link="https://mastodon.social" icon="mastodon" />
    );
    expect(screen.getAllByText("mastodon").length).toBeGreaterThan(0);
    u4();

    render(
      <IconSocial link="https://bsky.app" icon="bluesky" />
    );
    expect(screen.getAllByText("bluesky").length).toBeGreaterThan(0);
  });

  it("renders full social icons list when no props provided", () => {
    render(<IconSocial />);
    const links = screen.getAllByRole("link");
    // 7 social icons rendered (may be doubled in strict mode)
    expect(links.length).toBeGreaterThanOrEqual(7);
  });

  it("applies custom className when provided", () => {
    render(
      <IconSocial link="https://x.com" icon="twitter" className="h-8 w-8" />
    );
    const links = screen.getAllByRole("link");
    expect(links.length).toBeGreaterThan(0);
  });
});
