// Some portions generated by Co-Pilot
import React from "react";
import { render, cleanup, waitFor } from "@testing-library/react";
import { describe, it, expect, afterEach, vi, beforeEach } from "vitest";
import ColumnDrilldown from "../index";

// Mock fetch
const mockFetch = vi.fn();
global.fetch = mockFetch;

// Mock highcharts drilldown import
vi.mock("highcharts/modules/drilldown", () => ({
  default: vi.fn(),
}));

describe("ColumnDrilldown", () => {
  const mockApiData = {
    "21": { linux: 100, windows: 200 },
    "17": { linux: 50, windows: 75 },
    linux: { artifact1: 60, artifact2: 40 },
    windows: { artifact1: 120, artifact2: 80 },
  };

  beforeEach(() => {
    mockFetch.mockImplementation((url: string) => {
      if (url.includes("/21/"))
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve(mockApiData.linux),
        });
      if (url.includes("/17/"))
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve(mockApiData.windows),
        });
      if (url.endsWith("/21"))
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve(mockApiData["21"]),
        });
      if (url.endsWith("/17"))
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve(mockApiData["17"]),
        });
      return Promise.resolve({ ok: false });
    });
  });

  afterEach(() => {
    cleanup();
    mockFetch.mockReset();
  });

  it("renders nothing if no data", () => {
    const { container } = render(
      <ColumnDrilldown
        name="Test Drilldown"
        availableReleases={{ available_releases: [] }}
      />,
    );
    expect(container.firstChild).toBeNull();
  });

  it("renders chart when available_releases is provided", async () => {
    const { container } = render(
      <ColumnDrilldown
        name="Download Stats"
        availableReleases={{ available_releases: ["21", "17"] }}
      />,
    );
    // Initially renders null (no series data yet)
    // Wait for async fetch to populate chart
    await waitFor(() => {
      expect(container).toBeTruthy();
    });
  });

  it("handles fetch failure gracefully", async () => {
    mockFetch.mockResolvedValue({ ok: false });
    const { container } = render(
      <ColumnDrilldown
        name="Download Stats"
        availableReleases={{ available_releases: ["21"] }}
      />,
    );
    await waitFor(() => {
      expect(container).toBeTruthy();
    });
  });

  it("handles null available_releases", () => {
    const { container } = render(
      <ColumnDrilldown
        name="Test"
        availableReleases={{ available_releases: null as any }}
      />,
    );
    expect(container.firstChild).toBeNull();
  });
});

describe("ColumnDrilldown helper functions", () => {
  it("processes artifact names correctly via component render", async () => {
    // Test the component processes artifact data from API
    const artifactApiData: Record<string, number> = {
      "OpenJDK21U-jdk_x64_linux_hotspot_21.0.3_9.tar.gz": 1000,
      "OpenJDK21U-jdk_x64_linux_hotspot_21.0.3_9.msi": 500,
      sources: 200,
    };

    mockFetch.mockImplementation((url: string) => {
      if (url.endsWith("/21"))
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve({ linux: 1700 }),
        });
      if (url.includes("/21/"))
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve(artifactApiData),
        });
      return Promise.resolve({ ok: false });
    });

    const { container } = render(
      <ColumnDrilldown
        name="Artifact Stats"
        availableReleases={{ available_releases: ["21"] }}
      />,
    );
    await waitFor(() => {
      expect(container).toBeTruthy();
    });
  });
});
