// Some portions generated by Co-Pilot
import React from "react";
import { Link } from "@/i18n/navigation";
import { FaExternalLinkAlt } from "react-icons/fa";

interface LinkItem {
  link: string;
  name: string;
}

interface Props {
  links: LinkItem[];
  title: string;
  Icon: React.ComponentType<{ className?: string }>;
  anchorId?: string;
}

const DocumentationCard: React.FC<Props> = ({
  links,
  title,
  Icon,
  anchorId,
}) => {
  if (!title || !Icon || !links || typeof links !== "object") {
    return null;
  }

  return (
    <div
      id={anchorId}
      className="w-full md:w-1/2 lg:w-1/3 py-4 px-2 scroll-mt-25"
    >
      <h3 className="flex items-center gap-2 text-[15px] font-semibold text-white light:text-gray-900 mb-2">
        <Icon className="w-4 h-4 text-[#FF1464] light:text-rose-500 shrink-0" />
        <Link
          href={`/docs${anchorId ? "#" + anchorId : ""}`}
          className="hover:underline"
        >
          {title}
        </Link>
      </h3>
      <ul className="space-y-0">
        {links.map((link: LinkItem) => {
          const isExternal = link.link.includes("http");
          return (
            <li key={link.link}>
              {isExternal ? (
                <a
                  href={link.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1 py-1 text-sm text-[#FF1464] light:text-blue-600 hover:underline"
                >
                  {link.name}
                  <FaExternalLinkAlt size={9} className="opacity-50" />
                </a>
              ) : (
                <Link
                  href={link.link}
                  className="block py-1 text-sm text-[#FF1464] light:text-blue-600 hover:underline"
                >
                  {link.name}
                </Link>
              )}
            </li>
          );
        })}
      </ul>
    </div>
  );
};

export default DocumentationCard;
