// Some portions generated by Co-Pilot
import React from "react";
import "../InstallTabs.css";

export const PureMacOSPanel = (): React.ReactNode => {
  // Hardcoded value for latest LTS, should be replaced with actual data fetching in Next.js
  const mostRecentLts = "25";
  return (
    <div className="install-panel">
      <div className="install-block">
        <div className="install-block-title">
          Install the latest LTS version
        </div>
        <pre className="install-code">
          <code>{`brew install --cask temurin@${mostRecentLts}`}</code>
        </pre>
      </div>
      <div className="install-block">
        <div className="install-block-title">Install a specific version</div>
        <pre className="install-code">
          <code>{`brew install --cask temurin@8\nbrew install --cask temurin@${mostRecentLts}`}</code>
        </pre>
      </div>
      <div className="install-block">
        <div className="install-block-title">Uninstall a specific version</div>
        <pre className="install-code">
          <code>{`brew uninstall --cask temurin@${mostRecentLts}`}</code>
        </pre>
      </div>
      <a className="install__docs-button" href="https://docs.brew.sh/Manpage">
        Read documentation
      </a>
    </div>
  );
};

const MacOSPanel = (): React.ReactNode => {
  return <PureMacOSPanel />;
};

export default MacOSPanel;
