// Some portions generated by Co-Pilot
import React from "react";
import { render, fireEvent, cleanup } from "@testing-library/react";
import { describe, it, expect, vi, afterEach, beforeEach } from "vitest";

const mockPush = vi.fn();
vi.mock("next/navigation", () => ({
  useRouter: () => ({ push: mockPush }),
}));

import ReleaseNotesVersionSelector from "../index";

const defaultProps = {
  availableVersions: [21, 17, 11, 8],
  availableLTSVersions: [21, 17, 11, 8],
};

describe("ReleaseNotesVersionSelector", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });
  afterEach(() => {
    cleanup();
  });

  it("renders a button for each available version", () => {
    const { getAllByRole } = render(
      <ReleaseNotesVersionSelector {...defaultProps} />,
    );
    const buttons = getAllByRole("button");
    expect(buttons).toHaveLength(4);
  });

  it("clicking a version calls router.push with the correct query", () => {
    const { getAllByRole } = render(
      <ReleaseNotesVersionSelector {...defaultProps} />,
    );
    fireEvent.click(getAllByRole("button")[0]); // JDK 21
    expect(mockPush).toHaveBeenCalledWith("?version=21");
  });

  it("clicking a non-LTS version calls router.push correctly", () => {
    const { getAllByRole } = render(
      <ReleaseNotesVersionSelector
        availableVersions={[22, 21]}
        availableLTSVersions={[21]}
      />,
    );
    // LTS versions render first, so JDK 21 is button[0], JDK 22 is button[1]
    fireEvent.click(getAllByRole("button")[1]); // JDK 22 (non-LTS)
    expect(mockPush).toHaveBeenCalledWith("?version=22");
  });

  it("LTS versions get LTS badge styling", () => {
    const { container } = render(
      <ReleaseNotesVersionSelector
        availableVersions={[22, 21]}
        availableLTSVersions={[21]}
      />,
    );
    const buttons = container.querySelectorAll("button");
    // LTS versions render first: JDK 21 (LTS) is button[0]
    expect(buttons[0].textContent).toContain("Long Term Support");
    // JDK 22 (non-LTS) is button[1] and should not contain LTS text
    expect(buttons[1].textContent).not.toContain("Long Term Support");
  });

  it("renders section headers for LTS", () => {
    const { container } = render(
      <ReleaseNotesVersionSelector
        availableVersions={[22, 21]}
        availableLTSVersions={[21]}
      />,
    );
    // LTS badge in the section header
    const ltsBadge = container.querySelector(".text-pink.uppercase");
    expect(ltsBadge?.textContent).toBe("LTS");
    // Feature Releases section header for non-LTS
    const headers = container.querySelectorAll("h3");
    const texts = Array.from(headers).map((h) => h.textContent);
    expect(texts).toContain("Feature Releases");
  });
});
