// Some portions generated by Co-Pilot
import React from "react";
import { render } from "@testing-library/react";
import { describe, it, expect, vi, beforeEach } from "vitest";
import RandomContributor from "../index";
import * as useAdoptiumContributorsApiModule from "@/hooks/useAdoptiumContributorsApi";
import * as useOnScreenModule from "@/hooks/useOnScreen";

describe("RandomContributor", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("renders without crashing when contributor is null and not visible", () => {
    vi.spyOn(useOnScreenModule, "useOnScreen").mockReturnValue(false);
    vi.spyOn(useAdoptiumContributorsApiModule, "useAdoptiumContributorsApi").mockReturnValue(null);

    const { container } = render(<RandomContributor />);
    expect(container).toBeTruthy();
  });

  it("renders AnimatedPlaceholder when visible but contributor not yet loaded", () => {
    vi.spyOn(useOnScreenModule, "useOnScreen").mockReturnValue(true);
    vi.spyOn(useAdoptiumContributorsApiModule, "useAdoptiumContributorsApi").mockReturnValue(null);

    const { container } = render(<RandomContributor />);
    expect(container).toBeTruthy();
  });

  it("renders contributor info when contributor data is available", () => {
    const mockContributor = {
      login: "testuser",
      avatarUri: "https://example.com/avatar.png",
      profileUri: "https://github.com/testuser",
      contributionsCount: 5,
      commitsListUri: "https://github.com/adoptium/repo/commits?author=testuser",
      repo: "adoptium.net",
    };

    vi.spyOn(useOnScreenModule, "useOnScreen").mockReturnValue(true);
    vi.spyOn(useAdoptiumContributorsApiModule, "useAdoptiumContributorsApi").mockReturnValue(mockContributor);

    const { getByAltText } = render(<RandomContributor />);
    expect(getByAltText("Avatar of testuser")).toBeTruthy();
  });

  it("renders singular contribution text when contributionsCount is 1", () => {
    const mockContributor = {
      login: "testuser",
      avatarUri: "https://example.com/avatar.png",
      profileUri: "https://github.com/testuser",
      contributionsCount: 1,
      commitsListUri: "https://github.com/adoptium/repo/commits?author=testuser",
      repo: "adoptium.net",
    };

    vi.spyOn(useOnScreenModule, "useOnScreen").mockReturnValue(true);
    vi.spyOn(useAdoptiumContributorsApiModule, "useAdoptiumContributorsApi").mockReturnValue(mockContributor);

    const { container } = render(<RandomContributor />);
    expect(container).toBeTruthy();
  });

  it("renders plural contribution text when contributionsCount > 1", () => {
    const mockContributor = {
      login: "prolificdev",
      avatarUri: "https://example.com/avatar2.png",
      profileUri: "https://github.com/prolificdev",
      contributionsCount: 42,
      commitsListUri: "https://github.com/adoptium/repo/commits?author=prolificdev",
      repo: "temurin-build",
    };

    vi.spyOn(useOnScreenModule, "useOnScreen").mockReturnValue(true);
    vi.spyOn(useAdoptiumContributorsApiModule, "useAdoptiumContributorsApi").mockReturnValue(mockContributor);

    const { container } = render(<RandomContributor />);
    expect(container).toBeTruthy();
  });

  it("applies custom style when passed", () => {
    vi.spyOn(useOnScreenModule, "useOnScreen").mockReturnValue(false);
    vi.spyOn(useAdoptiumContributorsApiModule, "useAdoptiumContributorsApi").mockReturnValue(null);

    const customStyle = { border: "1px solid red" };
    const { container } = render(<RandomContributor style={customStyle} />);
    const div = container.firstChild as HTMLElement;
    expect(div?.style.border).toBe("1px solid red");
  });
});
