// Some portions generated by Co-Pilot
import React from "react";
import { render, waitFor } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { axe } from "vitest-axe";
import TemurinReleases from "../releases-client";

// mock loadLatestAssets
vi.mock("@/hooks", () => ({
  loadLatestAssets: vi.fn().mockReturnValue(Promise.resolve([])),
}));

// mock setURLParam to avoid window access in tests
vi.mock("@/utils/setURLParam", () => ({
  setURLParam: vi.fn(),
}));

// mock { useSearchParams } from "next/navigation"
vi.mock("next/navigation", () => ({
  useSearchParams: () => ({
    get: (key: string) => {
      if (key === "version") return "17";
      return null;
    },
    entries: () => [["version", "17"]][Symbol.iterator](),
  }),
}));

const availableReleases = {
  available_lts_releases: [8, 11, 17, 21],
  most_recent_lts: 21,
  available_releases: [8, 11, 17, 18, 21, 23, 24],
};

describe("TemurinReleases page", () => {
  it("renders correctly", async () => {
    const { container } = render(
      <TemurinReleases availableReleases={availableReleases} />,
    );
    // Wait for async effects (loadLatestAssets) to settle
    await waitFor(() => {
      expect(container.firstChild).toBeTruthy();
    });
    expect(container.firstChild).toMatchSnapshot();
  });

  it("has no accessibility violations", async () => {
    const { container } = render(
      <TemurinReleases availableReleases={availableReleases} />,
    );
    // Wait for async effects to settle before running axe
    await waitFor(() => {
      expect(container.firstChild).toBeTruthy();
    });
    const results = await axe(container);
    expect(results).toHaveNoViolations();
  });
});
