version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    groups:
      nextjs:
        patterns:
          - "next"
          - "eslint-config-next"
          - "@next/third-parties"
      mui-dependencies:
        patterns:
          - "@mui/*"
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
