= Preguntas Frecuentes
// Some portions generated by Co-Pilot
:page-authors: eddumelendez, czelabueno, jdluna, raulmj, tellison, gdams, hendrikebbers, xavierfacq
:page-based-on: f9de718632e9c01b2ec29bc34b2a2a5ca3795170

Hemos reunido unas cuantas preguntas frecuentes (FAQs) en este documento.
Si desea conversar con nosotros sobre estos tópicos, o realizar preguntas adicionales,
el mejor lugar es vía
link:/slack[Slack] o levantando un issue en el
https://github.com/adoptium/adoptium-support[canal de soporte].

== ¿Dónde están los últimos JDK de Adoptium(R)?

Los JDK de Adoptium se llaman Eclipse Temurin(TM), y las versiones que recomendamos para su
uso están disponibles en nuestra link:/temurin/releases[última página de versiones].

También contamos con todos los gestores de instalación más populares de Java, como:
https://formulae.brew.sh/cask/temurin[Homebrew], https://sdkman.io/[SDKMAN],
https://github.com/microsoft/winget-cli[winget] y https://chocolatey.org/[Chocolatey]. Temurin está disponible como
link:/installation/containers[imágenes Docker oficiales], y puede
usarlo mediante la
link:/installation/github-actions[acción de GitHub setup-java]
y como parte del soporte de Java de los proveedores de la nube.

Los instaladores de Linux están disponibles en packages.adoptium.net. Para más
información consulte link:/installation/linux[esta guía].

== ¿Cómo puedo enlazar a las últimas compilaciones de Temurin(TM)?

El
https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-two-linking-to-the-latest-jdk-or-jre[cookbook de la API de Adoptium]
contiene ejemplos de URLs estables que enlazan a JDK y JRE de Temurin específicos o a los más recientes. También puede promocionar Temurin incrustando el código de
link:/temurin/buttons[botones html]
disponible en el sitio web.

== ¿Temurin(TM) es de uso gratuito?

Sí. Los binarios de Eclipse Temurin son proporcionados para su uso sin ningún costo por Adoptium, por siempre, bajo los términos de la "GNU General Public License, version 2 with the
Classpath Exception". Usted puede utilizar, modificar y compartir libremente el código como se describe en las licencias incluidas en la descarga.

== ¿Cómo puedo ayudar en el proyecto?

El equipo de Adoptium recibe ayuda de muchas maneras. Por ejemplo:

* Cualquiera puede contribuir a los fondos que mantienen la ejecución del proyecto, ya sea
como https://www.eclipse.org/donate/adoptium/[donación única] o a través de un
link:/sponsors[patrocinio de proyecto] más estructurado.

* Las organizaciones que dependen de Adoptium son bienvenidas a unirse al
link:/members[Adoptium Working Group] y tener voz en la dirección del proyecto.

* Recibimos apoyo técnico y creativo en el proyecto para avanzar en nuestras metas
a través de promociones y marketing, escribiendo blogs sobre su experiencia con Adoptium,
respondiendo preguntas en nuestra link:/slack[activa comunidad de Slack], ayudando en
las pruebas de software y diagnosticando problemas, y
link:/docs/first-timer-support[solucionando algunos issues] que han sido reportados.

* ¡De muchas otras formas, ya sea como contribución única o como miembro del equipo a largo plazo;
únase y comparta sus ideas!

== ¿Por cuánto tiempo será soportado Eclipse Temurin?

Nuestra frecuencia de releases y nuestra declaración de soporte están disponibles
link:/support[aquí].

== ¿Eclipse Temurin ha pasado el JCK?

Sí. Cada release de Temurin ha pasado el relevante Oracle Java Compatibility Kit (JCK)
para demostrar que es una implementación compatible de la especificación Java.
Puede ver nuestro link:/temurin/tck-affidavit[affidavit del TCK] para más detalles.
Adicionalmente, los releases de Temurin deben pasar el link:/aqavit[AQAvit quality verification suite]
para asegurarse de que están listos para su uso en producción. Las pruebas AQAvit verifican que el release exhibe
un gran rendimiento, seguridad, resiliencia y resistencia, y la capacidad de pasar una gran variedad de pruebas
de compatibilidad de aplicaciones.

== ¿Dónde puedo reportar un error o problema con Eclipse Temurin?

Si sospecha que existe una vulnerabilidad de seguridad en cualquier producto del proyecto Adoptium, por favor, envíe un informe al https://www.eclipse.org/security/[Eclipse Security Team]
que gestionará y hará un seguimiento privado del problema hasta que se resuelva.

Cuando algo simplemente no se comporta como lo espera o tiene preguntas sobre
cómo configurar Temurin, por favor, háganoslo saber públicamente abriendo un
https://github.com/adoptium/adoptium-support/issues/new/choose[support issue] y trabajaremos con usted para encontrar una solución. Nuestro soporte es link:/support["soporte de comunidad"]
y los problemas se abordarán sobre la base del mejor esfuerzo. Debe dirigirse a las organizaciones que ofrecen soporte comercial si necesita un nivel de servicio garantizado para su uso en Java.

== ¿Pueden entregar Eclipse Temurin con mi imagen Docker base favorita?

Contamos con una lista definida de variantes en nuestro
https://hub.docker.com/_/eclipse-temurin[repositorio oficial de Docker] para asegurarnos de que
respondemos ágilmente a la entrega de nuevas imágenes que contienen Temurin. Docker colabora
con Adoptium para decidir qué versiones del sistema operativo base contenedor ofrecerán soporte para Temurin.

Los usuarios que deseen una distribución de Linux en contenedores que no proporcionamos
pueden seguir las instrucciones en
link:/news/2021/08/using-jlink-in-dockerfiles/[esta
guía].

== Mi escáner reporta un CVE en la imagen Docker de Eclipse Temurin. ¿Pueden solucionarlo?

Las https://hub.docker.com/_/eclipse-temurin[imágenes de contenedor de Temurin] disponibles en
Docker Hub son https://docs.docker.com/docker-hub/official_images/[imágenes oficiales]
creadas y mantenidas como un esfuerzo colaborativo entre el proyecto Adoptium y Docker, Inc.
Adoptium crea, mantiene y prueba un amplio conjunto de
https://github.com/adoptium/containers[archivos Dockerfile de Temurin] que son
https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin[utilizados por Docker]
para crear imágenes oficiales en varios sistemas operativos base.

Docker se esfuerza por garantizar que las imágenes de Temurin contengan los paquetes más actualizados
disponibles en un plazo razonable. Docker tiene su propio programa robusto de análisis de vulnerabilidades;
sin embargo, un escáner de seguridad de terceros podría marcar un problema con una imagen oficial.
Docker ha https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves[abordado varias razones]
por las que esto puede ocurrir en su FAQ. Agradecemos a Docker por continuar actualizando las
imágenes base y reconstruyendo las imágenes oficiales de manera regular.

Estamos felices de
https://github.com/adoptium/adoptium-support/issues/new/choose[recibir preguntas]
sobre las
https://hub.docker.com/_/eclipse-temurin[imágenes eclipse-temurin], pero tenga en cuenta que
en algunos casos deberemos referir el problema a Docker cuando esté relacionado con el sistema operativo base.

== ¿Soportarán mi arquitectura y sistema operativo favoritos?

Eclipse Temurin tiene la gama más amplia de soporte a plataformas a través de las múltiples versiones de
la API de Java. Cada nueva plataforma incurre en costos adicionales y en mayor demanda
sobre los recursos del proyecto, por lo que constantemente
revisamos la demanda de descargas y uso para asegurarnos de que estamos publicando versiones en plataformas relevantes para
un amplio grupo de usuarios. El conjunto actual de plataformas al que nos dirigimos en nuestros procesos de prueba
y build está listado link:/supported-platforms[aquí].

== ¿Puedo automatizar la descarga de los binarios de Eclipse Temurin?

¡Sí! Existe una completa https://api.adoptium.net/q/swagger-ui/[API de descargas]
que Adoptium provee para la descarga de compilaciones de Eclipse Temurin. Usando la API es posible obtener
información sobre las últimas compilaciones de Temurin y obtenerlas en su propia
aplicación.

Proporcionamos
https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-three-scripting-a-download-using-the-adoptium-api[un ejemplo de automatización de una descarga]
en el
https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#adoptium-api-cookbook[cookbook de la API de Adoptium].

== ¿Puede dar una charla sobre el proyecto?

Las personas involucradas en el proyecto son apasionadas por promoverlo y estamos interesados
en encontrar formas de promover el trabajo que hacemos en Adoptium y con los binarios de
Temurin, así que siéntase libre de contactarnos si tiene un foro en el que desee que participemos y veremos qué podemos hacer. En general, contactar al equipo vía Slack es la mejor forma de acercarse.
