= Frequently Asked Questions
:page-authors: gdams, HanSolo, sw-fox, aumann, hendrikebbers, xavierfacq
:page-based-on: 7ca352f4545cad6fd03722c9206d31da76063d4a

Auf dieser Seite haben wir versucht häufig gestellte Fragen (FAQs) für die Community zu beantworten.
Alle weiteren Fragen können jederzeit gerne in unsere https://adoptium.net/slack.html[Slack-Channel] gestellt
oder per Ticket im https://github.com/adoptium/adoptium-support[Support-Kanal] eingereicht werden.

== Wo kann man die neuesten Adoptium(R) JDKs finden?

Die JDKs von Adoptium heißen Eclipse Temurin. Die von uns empfohlenen Versionen kann man direkt 
https://adoptium.net/temurin/releases/[auf unserer Seite] finden.

Unsere JDKs sind auch in allen bekannten Java-Installationsmanagern wie https://formulae.brew.sh/cask/temurin[Homebrew],
https://sdkman.io/[SDKMAN], https://github.com/microsoft/winget-cli[winget] und https://chocolatey.org/[Chocolatey] vertrehten.
Zusätzlich gib es https://hub.docker.com/_/eclipse-temurin[offizielle Docker-Images] und die Möglichkeit Temurin über die
https://github.com/marketplace/actions/setup-java-jdk#basic[Github-Aktion "setup-java"] sowie als Teil der individuellen Java-Unterstützung
von Cloud-Anbietern zu verwenden.

Linux-Installationsprogramme sind unter `packages.adoptium.net` verfügbar. Weitere Informationen hierzu finden Sie https://adoptium.net/installation/linux[in diesem Leitfaden].

== Gibt es statische Links für Temurin(TM) Builds?

Das https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-two-linking-to-the-latest-jdk-or-jre[Adoptium API cookbook] beinhatet Beispiele zu statischen und stabilen URLs die zu spezifischen Temurin Versionen verlinken. Zusätzlich bieten wir https://adoptium.net/en-GB/temurin/buttons/[HTML Buttons] an, die auf Temurin downloads verweisen.

== Kann Temurin kostenlos genutzt werden?

Ja. Eclipse Temurin wird von Adoptium kostenlos unter der "GNU General Public License, version 2 with the Classpath Exception" Lizenz vertrieben.

== Was ist mit AdoptOpenJDK passiert?

Kurze Antwort: Das Projekt ist dermaßen gewachsen und um die Stabilität des Projektes in der Zukunft zu gewährleisten, haben wir uns entschieden
es in der https://projects.eclipse.org/projects/adoptium[Eclipse Foundation unterzubringen]
, https://blog.adoptopenjdk.net/2020/06/adoptopenjdk-to-join-the-eclipse-foundation/[wie bereits Ende letzten Jahres angekündigt].

Längere Antwort: Die Builds, welche Sie als AdoptOpenJDK kennen, sind jetzt "Eclipse Temurin by Adoptium"(https://adoptium.net/blog/2021/08/adoptium-celebrates-first-release/[release blog post])
Aber keine Sorge - trotz der Änderungen im Branding sind es die gleichen offenen Build-Prozesse, AQAvit-Test-Suites und hauptsächlich das gleiche Team, welches die builds erstellt.
Allerdings sind jetzt link:/members[mehr größere Unternehmen] an der Arbeitsgruppe beteiligt.

== Warum wird man von der AdoptOpenJDK Seite nicht direkt hierhin umgeleitet?

Aus folgenden zwei Gründen, erstens: Da noch immer Benutzer in der Umstellungsphase sind, haben wir die alte Seite so belassen, wie sie war, mit dem gleichen Layout und Buttons.
Über die Links auf der alten Website erhalten Sie die neuesten Temurin builds. Allerdings sollte man sich nicht darauf verlassen sondern lieber auf die Adoptium-API und -Webseite
umsteigen um Temurin Binaries herunterzuladen. Es gibt einige Varianten, welche noch nicht auf der Adoptium-Webseite verfügbar sind. Diese lassen sich jedoch link:#will-the-migration-break-my-api-links[weiterhin] über die alte Website beziehen,
weshalb wir diese nicht entfernen, da dieses dazu führen würde, dass einige Funktionen ohne Vorwarnung verschwinden würden.
Dieses ist nicht optimal und führt zu einer gewissen SEO-Verwirrung, aber wir denken, dass es im MOment die richtige Option ist.
In Zukunft wird die Adoptium-Webseite mehr als nur Temurin anbieten, weswegen eine reine Weiterleitung zwischen den Domains nicht angemessen wäre.

Zweitens: Wie bereits im vorigen Absatz erwähnt, sind einige Dinge nicht auf Adoptium.net verfügbar und aus diesem Grund wird die alte Webseite ohne explizite Weiterleitung
beibehalten, um diese Dinge weiterhin zur Verfügung zu stellen. Dazu gehören Sachen wie https://adoptopenjdk.net/upstream.html[Upstream builds] und https://adoptopenjdk.net/icedtea-web.html[IcedTea-WEB].
Würden diese Sachen einfach verschwinden, so wäre das für unsere Kunden nicht die beste Option und wir würden eine Menge Beschwerden erwarten.

== Was bedeutet der Name "Eclipse Temurin"?

Dies ist der Projekt- und Markenname für die Binaries, welche die Eclipse Foundation produziert.
Sie können diese Binaries als Nachfolger von AdoptOpenJDK Binaries betrachten. Es ist allerdings zu beachten, dass diese Binaries nur einige von vielen sind, welche schließlich
im https://github.com/adoptium/adoptium/issues/7[Eclipse Adoptium Marketplace] zur Verfügung stehen werden.
Wir verstehen, dass die Aufteilung des Namens in Adoptium/Temurin verwirrender ist als einfach nur "Adoptium", allerdings ist dieses auch ähnlich wie bei anderen Anbietern,
z.B. Amazon mit Corretto, Azul mit Zulu und andere. Das "Adoptium"-Projekt und die Arbeitsgruppe werden sich mit mehr als nur Temurin befassen weswegen es wichtig ist, diese
Unterscheidung beizubehalten.

== Wo sind die OpenJ9 builds?

Der Übergang zu Adoptium bedeutet leider, dass wir nicht mehr in der Lage sind die Builds von Eclipse OpenJ9 anzubieten.
Dieses hat nun IBM übernommen und dort sind sie nun verfügbar als "https://developer.ibm.com/languages/java/semeru-runtimes/[IBM Semeru]".
Es gibt keinen Grund, sich über diese Änderung Sorgen zu machen - auch diese Distribution ist immer noch kostenlos verfügbar.

== Wo sind die Docker-Images?

Aufgrund der begrenzten Anzahl von Personen, welche an dem Projekt arbeiten, ist die Pflege der zahlreichen Docker-Images, welche wir on AdoptOpenJDK zur Verfügung gestellt
haben, nicht mehr tragbar. Aus diesem Grund werden wir ein reduziertes Set von Docker-Images für Temurin bereitstellen.
Jene Benutzer, welche sich eine containerbasierte Linux-Distribution wünschen, für die wir kein Image zur Verfügung stellen, verweisen wir an https://adoptium.net/blog/2021/08/using-jlink-in-dockerfiles/[diese
Anleitung].

== Wo sind die Linux RPM/DEB Pakete?

Linux-Installer sind unter packages.adoptium.net verfügbar.
Weitere Informationen finden Sie in link:/installation/linux[dieser Anleitung].

== Warum beeinhalten die Pakete nicht IcedTea-Web?

Die Vereinbarungen, welche wir seit dem Umzug zur Eclipse Foundation getroffen haben, besagen, dass wir IcedTea-Web nicht mehr in unsere Installationsprogramme
aufnehmen können. Sie können diese Funktionalität jedoch immer noch, falls benötigt, hinzufügen, indem Sie https://blog.adoptopenjdk.net/2018/10/using-icedtea-web-browser-plug-in-with-adoptopenjdk/[dieser Anleitung] folgen.

== Werden durch die Migration meine API-Links ungültig?

Es gibt eine https://api.adoptium.net/q/swagger-ui/[neue Download-API]
die von Adoptium zum Herunterladen von Eclipse-Temurin-Builds bereitgestellt wird.

Die gute Nachricht ist, dass sie der API von AdoptOpenJDK sehr ähnlich sieht, so dass die Migration für all, die sie derzeit verwenden, nicht allzu schwierig ist.
Zur Zeit leitet die AdoptOpenJDK-API auf Temurin (oder Semeru) um (falls verfügbar) wenn Sie die neuesten Release-Builds anfordern.
Wir haben dies getan, da wir nicht die Zeit hatten die Community zur vollständigen Migration zu bewegen und weil wir noch nicht alles veröffentlicht haben, was bedeutet, dass es noch
fehlende Builds in der Adoptium-API gibt.
Bitte beachten Sie, dass dies eine vorübergehende Maßnahme ist und die AdoptOpenJDK API voraussichtlich dieses Verhalten nicht für immer beibehalten wird, wenngleich es zur Zeit
noch keinen Zeitplan zur Entfernung der Umleitung gibt.

== Können Sie einen Vortrag über das Projekt halten?

Die an dem Projekt beteiligten Personen sind leidenschaftlich bemüht, es zu fördern.
Wir sind sehr daran interessiert, Wege zu finden über unsere Arbeit bei Adoptium und den Temurin Binaries zu sprechen.
Falls also der Wunsch besteht, dass wir an einer Veranstaltung teilnehmen, werden wir sehen was wir tun können um dieses zu ermöglichen.
Der beste Weg um mit dem Team in Kontakt zu treten ist über den Slack-Channel.
