= 常见问题
// Some portions generated by Co-Pilot
:page-authors: zdtsw, gdams, tellison, hendrikebbers, xavierfacq
:page-based-on: f9de718632e9c01b2ec29bc34b2a2a5ca3795170

在该文件中，我们收集了一些常见问题。如果您想讨论这些话题或有其他问题，最佳途径是通过以下链接
link:/slack[Slack] 或者在
https://github.com/adoptium/adoptium-support[支持渠道]中创建一个新议题。

== 如何找到最新发布的 Adoptium(R) JDK？

Adoptium 的 JDK 称为 Eclipse Temurin，推荐您使用我们的 link:/temurin/releases[最新版本]。

我们还为各大Java 安装管理器提供功能，例如：
https://formulae.brew.sh/cask/temurin[Homebrew], 
https://sdkman.io/[SDKMAN],
https://github.com/microsoft/winget-cli[winget]， 
https://chocolatey.org/[Chocolatey]，
https://hub.docker.com/_/eclipse-temurin[official Docker images],
您还可以通过 Github 使用 Temurin https://github.com/marketplace/actions/setup-java-jdk#basic["setup-java"] action，
另外它也是云提供商 Java 支持的一部分。

Linux 安装程序包RPM/DEB可在 packages.adoptium.net 中获得。 更多信息见 link:/installation/linux[指南]。

== 如何链接到最新的 Temurin(TM) 版本？

https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-two-linking-to-the-latest-jdk-or-jre[Adoptium API cookbook]
包含了指向特定或最新的 Temurin JDK 和 JRE 的稳定链接示例。
您还可以通过网站上提供的嵌入 link:/temurin/buttons[按钮代码] 来推广 Temurin。

== Eclipse Temurin 可以免费使用吗？

是的！根据 "GNU General Public License, version 2 with the Classpath Exception" 许可证，
Adoptium 将永久免费提供 Eclipse Temurin 二进制文件供您使用。
您可以自由地使用、修改和共享这些代码，这些权限都包含在您下载的许可证中。

== 如何提供对这个项目的支持？

Adoptium 团队对各种不同方式的支持表示欢迎。 例如：

* 任何人都可以通过https://www.eclipse.org/donate/adoptium/[一次性捐赠]或者通过link:/sponsors[项目赞助]的链接资助项目，使其能够顺利运行。
* 我们鼓励依赖 Adoptium 的组织加入 Adoptium 工作组，并在项目发展方向上发表意见
* 我们欢迎技术和创意的支持，例如通过推广和营销来推进我们的目标，
写一篇关于您对 Adoptium 项目的体验博客，回答我们 link:/slack[Slack 社区]的问题，
帮助测试软件或诊断问题，link:/docs/first-timer-support[修复]已报告的问题等等。
* 还有许多其他的方式，无论是一次性赞助还是成为我们的长期成员，快来加入我们并分享您的想法！

== Eclipse Temurin支持生命周期

link:/support[在此] 阅读我们的发布和支持周期声明

== Eclipse Temurin 是否通过 JCK 验证？

当然！ 每个 Temurin 版本都通过了相关的 Oracle Java Compatibility Kit (JCK) 以证明它是与 Java 规范兼容实现的。
您可以查看我们的 link:/temurin/tck-affidavit[TCK 宣誓书] 了解详情。
此外，Temurin 版本必须通过 link:/aqavit[AQAvit 质量验证套件]以确保它们可在生产中使用。

== 如果您遇到 Eclipse Temurin 的错误或问题，应该去哪里报告？

如果您怀疑 Adoptium 项目的任何产品存在安全漏洞，请向 https://www.eclipse.org/security/[Eclipse 安全团队] 发送报告
他们将在不公开的前提下管理和跟踪问题，直到问题得到解决。
如果您遇到一些事项没有按照您的预期运行，或者您对如何配置 Temurin 有疑问，请通过发送
https://github.com/adoptium/adoptium-support/issues/new/choose[请求支持]，我们将与您一起寻求解决方案。
我们的支持是 link:/support["社区支持"]， 问题将在尽力而为的基础上得到解决。
如果您需要为您的 Java 使用提供有保证的服务，您应该联系提供商业支持的组织。

== Temurin 能用我最喜欢的 Docker 镜像来交付吗？

我们有一组 https://hub.docker.com/_/eclipse-temurin[Docker 官方存储库]，以确保我们及时响应包含Temurin的新镜像。
Docker 与 Adoptium 合作，由他们来决定为 Temurin 提供哪些操作系统容器版本的支持。

对于想要使用我们未提供的容器化Linux发行版的用户， 可以查看这些 link:/news/2021/08/using-jlink-in-dockerfiles/[指南]。

== 我的漏洞扫描程序报告 Eclipse Temurin Docker 镜像中有 CVE。 你们能修复它吗？

Docker Hub 上的 https://hub.docker.com/_/eclipse-temurin[Temurin 容器镜像] 是我们的 https://docs.docker.com/docker-hub/official_images/[官方镜像]
它们由Adoptium 项目和 Docker, Inc. 共同来维护。 
https://github.com/adoptium/containers[Temurin 镜像源文件]在 GitHub 上进行广泛的创建、维护和测试，
然后交由 https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin[Docker]根据不同操作系统制作官方镜像。

为了确保能安全使用，Docker 努力确保 Temurin 镜像包含最新的安装包。
虽然 Docker 有自己的强大漏洞扫描程序，但是，第三方安全扫描程序仍可能会标记官方镜像的问题。 
这些可能已经在 Docker 的 https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves[常见问答]中列出。
我们感谢 Docker 定期为我们重建官方镜像，并乐意接受有关https://hub.docker.com/_/eclipse-temurin[eclipse-temurin 镜像]的https://github.com/adoptium/adoptium-support/issues/new/choose[问题]，。
但请注意，在某些情况下，我们可能会将问题转交给 Docker，特别是与操作系统相关的问题。

== 您会支持我偏爱的架构和操作系统吗？

Eclipse Temurin 在多个 Java API 版本上拥有最广泛的平台支持。
每个新平台都会增加项目资源的成本和需求，因此我们不断审查下载和使用需求，以确保我们在对大量用户相关的平台上发布。
我们在构建和测试过程中针对的当前平台列表见 link:/supported-platforms[此处]。

== 可以自动下载 Eclipse Temurin 二进制文件吗？

当然！ Adoptium提供了一个 https://api.adoptium.net/q/swagger-ui/[下载 API]，可用于自动下载预编译的Eclipse Temurin。
使用API，您可以获取有关Temurin最新版本的信息，并将其加载到您的应用程序中。

我们还在 https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#adoptium-api-cookbook[Adoptium API cookbook] 中提供了一个
https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-three-scripting-a-download-using-the-adoptium-api[自动下载的示例]

== 能否和我谈一下这个项目呢？

我们项目的参与者都非常热衷于将项目推广开来。
与此同时，我们也十分渴望将我们在 Adoptium 所做的工作以及 Temurin 二进制文件一并推广。
如果您有任何论坛需要我们参与，我们将竭尽所能提供帮助。
总之，通过 Slack 联系我们的团队是与我们互动的最佳方式