= Questions Fréquemment Posées
// Some portions generated by Co-Pilot
:page-authors: xavierfacq, gdams
:page-based-on: f9de718632e9c01b2ec29bc34b2a2a5ca3795170

Nous avons rassemblé quelques questions fréquemment posées (FAQ) dans ce document.
Si vous souhaitez nous parler de ces sujets ou poser des questions supplémentaires, 
le meilleur endroit est via link:/slack[Slack] ou en déclarant un problème dans le https://github.com/adoptium/adoptium-support[canal d'assistance].

== Où se trouvent les derniers JDK Adoptium(R) ?

Les JDK d'Adoptium s'appellent Eclipse Temurin et les versions que nous recommandons d'utiliser sont 
disponibles sur notre page des link:/temurin/releases[dernières versions].

Nous figurons également dans tous les gestionnaires d'installation de Java tels que https://formulae.brew.sh/cask/temurin[Homebrew], https://sdkman.io/[SDKMAN],
https://github.com/microsoft/winget-cli[winget] et https://chocolatey.org/[Chocolatey], nous apparaissons également dans les 
https://hub.docker.com/_/eclipse-temurin[images officielles de Docker], 
vous pouvez aussi utiliser Temurin grâce à l'action Github https://github.com/marketplace/actions/setup-java-jdk#basic["setup-java"], 
ou encore dans la plupart des fournisseurs de cloud proposant Java.

Les installeurs Linux sont disponibles sur packages.adoptium.net.
Pour plus d'informations, voir link:/installation/linux[ce guide].

== Comment puis-je créer un lien vers les dernières versions de Temurin(TM) ?

Le https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-two-linking-to-the-latest-jdk-or-jre[Cookbook de l'API Adoptium]
contient des exemples d'URL stables qui renvoient vers des version spécifiques ou les dernières du JDK et du JRE de Temurin. 
Vous pouvez également promouvoir Temurin en intégrant un link:/temurin/buttons[bouton HTML]  grâce au code disponible.

== L'utilisation de Temurin est-elle gratuite ?

Oui. Les binaires d'Eclipse Temurin sont fournis gratuitement par Adoptium pour que vous puissiez les utiliser, pour toujours, 
selon les termes de la "GNU General Public License, version 2 avec le Classpath Exception". Vous pouvez librement utiliser, 
modifier et partager le code comme décrit dans les licences incluses dans le téléchargement.

== Comment puis-je aider le projet ?

L’équipe Adoptium accueille l’aide de différentes manières. Par exemple:

* N'importe qui peut contribuer aux fonds qui assurent le bon déroulement du projet, que ce soit
sous forme d'un https://www.eclipse.org/donate/adoptium/[don] ou au travers d'un link:/sponsors[mécénat de projets] plus structurés.

* Les organisations qui dépendent d'Adoptium sont encouragées à rejoindre le link:/members[Adoptium Working Group] 
et à exprimer leur voix quand à la direction du projet.

* Nous apprécions l'aide technique et créative sur le projet pour faire avancer nos objectifs, grâce à la promotion et au marketing, 
la rédaction de blogs sur votre expérience avec Adoptium, en répondant aux questions dans notre link:/slack[communauté Slack], en aidant à tester le
logiciel ou à diagnostiquer des problèmes, et en aidant à link:/docs/first-timer-support[résoudre les problèmes] qui sont signalés.

* De nombreuses autres façons, soit en tant qu'aide ponctuelle, soit en tant que membre d'une équipe à plus long terme, 
rejoignez-nous et faites-nous part de vos idées, tout simplement !

== Combien de temps Eclipse Temurin est-il pris en charge?

Notre fréquence de publication et notre déclaration de support sont disponibles link:/support[ici].

== Eclipse Temurin a-t-il passé le JCK ?

Oui. Chaque version de Temurin a passé avec succès le kit de compatibilité Oracle Java (JCK) correspondant, 
pour démontrer qu'il s'agit d'une implémentation compatible de la spécification Java.
Vous pouvez consulter notre link:/temurin/tck-affidavit[attestation TCK] pour plus de détails.
De plus, les versions de Temurin doivent passer les tests de link:/aqavit[vérification de la qualité AQAvit] pour s'assurer qu'ils sont 
prêts à être utilisés en production. 
Les tests AQAvit vérifient que la version fait preuve d'excellentes performances, de sécurité, de résilience et d'endurance, 
ainsi que de la capacité à passer une large variété de tests de compatibilité avec des applications.

== Où puis-je signaler un bug ou un problème avec Eclipse Temurin ?

Si vous soupçonnez une faille de sécurité avec un des produits du projet Adoptium,
veuillez envoyer un rapport à l'https://www.eclipse.org/security/[équipe de sécurité d'Eclipse]
qui gérera et suivra le problème en privé jusqu'à ce qu'il soit résolu.

Si quelque chose ne se comporte pas comme prévu ou que vous avez des questions au sujet de
comment configurer Temurin, veuillez-nous le faire savoir publiquement en ouvrant une https://github.com/adoptium/adoptium-support/issues/new/choose[demande de support] 
et nous verrons ensemble pour trouver une solution. Notre support est basé sur une link:/support["communauté"] donc les problèmes sont résolus dans la mesure du possible. 
Vous devriez vous rapprocher des organisations qui offrent un support commercial si vous avez besoin d'une garantie de service pour votre utilisation de Java.

== Pouvez-vous intégrer Temurin avec l'image Docker de mon système d'exploitation préféré ?

Nous avons une liste variée dans notre https://hub.docker.com/_/eclipse-temurin[dépôt officiel Docker] pour assurer la livraison de nouvelles images contenant Temurin.
Docker collabore avec Adoptium pour décider quelles versions de système d'exploitation supporteront Temurin.

Les utilisateurs qui souhaitent une distribution Linux conteneurisée que nous ne fournissons pas, peuvent 
suivre les instructions dans link:/news/2021/08/using-jlink-in-dockerfiles/[ce guide].

== Mon scanner signale un CVE dans l'image Docker Eclipse Temurin. Pouvez-vous le réparer ?

Les https://hub.docker.com/_/eclipse-temurin[containers des images Temurin] disponibles sur Docker Hub 
sont des https://docs.docker.com/docker-hub/official_images/[images officielles] créées et maintenues dans le cadre d'un effort de collaboration entre le projet Adoptium et Docker, Inc. 
Adoptium crée, maintient et teste un large éventail de https://github.com/adoptium/containers[Dockerfile avec Temurin] qui sont https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin[utilisés par Docker]
pour créer des images officielles basées sur différents systèmes d'exploitation.

Docker s'efforce de garantir que les images Temurin contiennent les mises à jour les plus récentes dans un délai raisonnable. 
Docker a son propre programme d'analyse des vulnérabilités, cependant, un scanner de sécurité tiers pourrait signaler un problème avec une image officielle. 
Docker a https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves[expliqué divers cas] dans lesquels cela peut 
arriver, à retrouver dans leur FAQ. Nous remercions Docker de continuer à actualiser les images et reconstruire régulièrement les images officielles.

Nous sommes toujours heureux de https://github.com/adoptium/adoptium-support/issues/new/choose[recevoir des questions]
à propos des https://hub.docker.com/_/eclipse-temurin[images d'eclipse-temurin], mais notez que
dans certains cas, nous devrons soumettre le problème à Docker lorsqu'il concerne le fonctionnement du système d'exploitation.

== Allez-vous prendre en charge mon architecture et mon système d'exploitation préférés ?

Eclipse Temurin offre la plus large gamme de plates-formes et de versions des API Java.
Chaque nouvelle plate-forme entraîne des coûts et des ressources supplémentaires sur le projet, 
nous examinons donc constamment les demandes de téléchargement et d'utilisation pour nous assurer que nous
publions des plates-formes pertinentes pour un large éventail d'utilisateurs. 
La liste des plates-formes que nous ciblons dans notre processus de build et de test est répertoriée link:/supported-platforms[ici].

== Puis-je automatiser le téléchargement des binaires Temurin ?

Oui! Il existe une https://api.adoptium.net/q/swagger-ui/[API de téléchargement] fournie par Adoptium pour télécharger 
les versions d'Eclipse Temurin. En utilisant l'API, il est possible d'obtenir des informations sur les dernières versions de Temurin 
et de les télécharger dans votre application.

Nous fournissons https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-trois-scripting-a-download-using-the-adoptium-api[un exemple d'automatisation d'un téléchargement ]
dans le https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#adoptium-api-cookbook[Cookbook de l'API Adoptium].

== Pouvez-vous donner une conférence sur le projet ?

Les personnes impliquées dans le projet sont passionnées par sa promotion et 
nous souhaitons trouver des moyens de promouvoir le travail que nous effectuons chez Adoptium et avec les binaires Temurin ; 
alors n'hésitez pas à nous contacter si vous avez un forum auquel vous souhaitez que nous participions et nous verrons ce que nous pourons faire. 
De manière générale, contacter l'équipe via Slack est encore le meilleur moyen de discuter avec nous.