= Häufig gestellte Fragen
// Some portions generated by Co-Pilot
:page-authors: gdams, HanSolo, sw-fox, aumann, hendrikebbers, xavierfacq
:page-based-on: f9de718632e9c01b2ec29bc34b2a2a5ca3795170

Auf dieser Seite haben wir versucht häufig gestellte Fragen (FAQs) für die Community zu beantworten.
Alle weiteren Fragen können jederzeit gerne in unserem link:/slack[Slack-Channel] gestellt
oder per Ticket im https://github.com/adoptium/adoptium-support[Support-Kanal] eingereicht werden.

== Wo kann man die neuesten Adoptium(R) JDKs finden?

Die JDKs von Adoptium heißen Eclipse Temurin(TM). Die von uns empfohlenen Versionen kann man direkt
auf unserer link:/temurin/releases[aktuellen Release-Seite] finden.

Unsere JDKs sind auch in allen bekannten Java-Installationsmanagern wie https://formulae.brew.sh/cask/temurin[Homebrew],
https://sdkman.io/[SDKMAN], https://github.com/microsoft/winget-cli[winget] und https://chocolatey.org/[Chocolatey] vertreten.
Zusätzlich gibt es link:/installation/containers[offizielle Docker-Images] und die Möglichkeit, Temurin über die
link:/installation/github-actions[Github-Aktion "setup-java"] sowie als Teil der individuellen Java-Unterstützung
von Cloud-Anbietern zu verwenden.

Linux-Installationsprogramme sind unter packages.adoptium.net verfügbar. Weitere Informationen hierzu finden Sie link:/installation/linux[in diesem Leitfaden].

== Wie kann ich auf die neuesten Temurin(TM) Builds verlinken?

Das https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-two-linking-to-the-latest-jdk-or-jre[Adoptium API Cookbook] beinhaltet Beispiele zu stabilen URLs, die zu spezifischen oder den neuesten Temurin JDKs und JREs verlinken. Zusätzlich können Sie Temurin fördern, indem Sie link:/temurin/buttons[HTML-Buttons] einbinden, die auf der Website bereitgestellt werden.

== Kann Eclipse Temurin kostenlos genutzt werden?

Ja. Eclipse Temurin wird von Adoptium kostenlos und dauerhaft unter der "GNU General Public License, version 2 with the Classpath Exception" Lizenz bereitgestellt. Sie können den Code, wie in den im Download enthaltenen Lizenzen beschrieben, frei verwenden, ändern und weitergeben.

== Wie kann ich dem Projekt helfen?

Das Adoptium-Team freut sich über Hilfe in vielen verschiedenen Formen. Zum Beispiel:

* Jeder kann zu den Mitteln beitragen, die das Projekt am Laufen halten, entweder als
https://www.eclipse.org/donate/adoptium/[einmalige Spende] oder durch eine
strukturiertere link:/sponsors[Projektförderung].

* Organisationen, die von Adoptium abhängen, sind eingeladen, der
link:/members[Adoptium-Arbeitsgruppe] beizutreten und eine Stimme in der Ausrichtung des Projekts zu erhalten.

* Wir freuen uns über technische und kreative Hilfe beim Projekt, um unsere Ziele voranzutreiben:
durch Förderung und Marketing, das Schreiben von Blogs über Ihre Erfahrungen mit Adoptium, das Beantworten
von Fragen in unserer link:/slack[aktiven Slack-Community], das Helfen beim Testen der
Software oder beim Diagnostizieren von Problemen sowie link:/docs/first-timer-support[das Beheben von gemeldeten Problemen].

* Viele weitere Möglichkeiten, entweder als einmaliges Engagement oder als langfristiges Teammitglied –
kommen Sie einfach zu uns und teilen Sie uns Ihre Ideen mit!

== Wie lange wird Eclipse Temurin unterstützt?

Unsere Veröffentlichungshäufigkeit und Supporterklärung ist link:/support[hier] verfügbar.

== Hat Eclipse Temurin den JCK bestanden?

Ja. Jede Temurin-Version hat das relevante Oracle Java Compatibility Kit (JCK) bestanden,
um zu demonstrieren, dass es eine kompatible Implementierung der Java-Spezifikation ist.
Sie können unsere link:/temurin/tck-affidavit[TCK-Erklärung] für Details einsehen.
Darüber hinaus müssen Temurin-Versionen die link:/aqavit[AQAvit-Qualitätsprüfsuite] bestehen,
um sicherzustellen, dass sie für den Produktiveinsatz bereit sind. AQAvit-Tests prüfen, ob die Version
hervorragende Leistung, Sicherheit, Belastbarkeit und Ausdauer aufweist sowie die Fähigkeit besitzt,
eine große Vielfalt von Anwendungskompatibilitätstests zu bestehen.

== Wo melde ich einen Fehler oder ein Problem mit Eclipse Temurin?

Wenn Sie eine Sicherheitslücke in einem Produkt des Adoptium-Projekts vermuten,
senden Sie bitte einen Bericht an das https://www.eclipse.org/security/[Eclipse-Sicherheitsteam],
das das Problem privat verwalten und verfolgen wird, bis es behoben ist.

Wenn etwas nicht wie erwartet funktioniert oder Sie Fragen zur Konfiguration von Temurin haben,
teilen Sie uns dies bitte öffentlich mit, indem Sie ein
https://github.com/adoptium/adoptium-support/issues/new/choose[Support-Ticket] öffnen, und wir werden
gemeinsam mit Ihnen nach einer Lösung suchen. Unser Support ist link:/support["Community-Support"],
sodass Probleme nach bestem Ermessen bearbeitet werden. Sie sollten sich an Organisationen wenden,
die kommerziellen Support anbieten, wenn Sie ein garantiertes Service-Level für Ihre Java-Nutzung benötigen.

== Können Sie Eclipse Temurin mit meinem bevorzugten Docker-Basis-Betriebssystem-Image bereitstellen?

Wir haben eine festgelegte Menge an Varianten in unserem
https://hub.docker.com/_/eclipse-temurin[offiziellen Docker-Repository], um sicherzustellen, dass
wir reaktionsfähig bei der Bereitstellung neuer Images mit Temurin sind. Docker arbeitet
mit Adoptium zusammen, um zu entscheiden, welche Basis-Betriebssystem-Container-Versionen
für Temurin unterstützt werden.

Benutzer, die eine containerisierte Linux-Distribution benötigen, für die wir kein Image bereitstellen,
können den Anweisungen in
link:/news/2021/08/using-jlink-in-dockerfiles/[dieser Anleitung] folgen.

== Mein Scanner meldet eine CVE im Eclipse Temurin Docker-Image. Können Sie das beheben?

Die https://hub.docker.com/_/eclipse-temurin[Temurin-Container-Images], die auf
Docker Hub verfügbar sind, sind https://docs.docker.com/docker-hub/official_images/[offizielle Images],
die in gemeinsamer Arbeit zwischen dem Adoptium-Projekt und Docker, Inc. erstellt und gepflegt werden.
Adoptium erstellt, pflegt und testet eine breite Palette von
https://github.com/adoptium/containers[Temurin-Dockerfile-Quelldateien], die von
https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin[Docker verwendet werden],
um offizielle Images für verschiedene Basis-Betriebssysteme zu erstellen.

Docker bemüht sich, sicherzustellen, dass die Temurin-Images die aktuellsten verfügbaren Pakete
innerhalb eines vernünftigen Zeitrahmens enthalten. Docker verfügt über ein eigenes robustes Schwachstellen-Scan-Programm,
jedoch kann ein Drittanbieter-Sicherheitsscanner ein Problem mit einem offiziellen Image melden. Docker hat
https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves[verschiedene Gründe erläutert],
warum dies in ihrem FAQ passieren kann. Wir sind Docker dankbar, dass es die
Basis-Images kontinuierlich aktualisiert und die offiziellen Images regelmäßig neu erstellt.

Wir freuen uns über
https://github.com/adoptium/adoptium-support/issues/new/choose[Fragen]
zu den
https://hub.docker.com/_/eclipse-temurin[eclipse-temurin-Images], weisen jedoch darauf hin, dass
wir in einigen Fällen das Problem an Docker weiterleiten müssen, wenn es das Basis-Betriebssystem betrifft.

== Werden Sie meine bevorzugte Architektur und mein bevorzugtes Betriebssystem unterstützen?

Eclipse Temurin bietet die breiteste Plattformunterstützung über mehrere Java-API-Versionen hinweg.
Jede neue Plattform verursacht zusätzliche Kosten und Anforderungen an die Ressourcen des Projekts,
weshalb wir die Download- und Nutzungsnachfrage kontinuierlich überprüfen, um sicherzustellen, dass wir
auf Plattformen veröffentlichen, die für eine große Anzahl von Benutzern relevant sind. Die aktuelle
Menge der Plattformen, auf die wir in unserem Build- und Testprozess abzielen, ist link:/supported-platforms[hier] aufgelistet.

== Kann ich den Download von Eclipse Temurin Binaries automatisieren?

Ja! Es gibt eine umfangreiche https://api.adoptium.net/q/swagger-ui/[Download-API]
von Adoptium zum Herunterladen von Eclipse-Temurin-Builds. Mithilfe der API ist es möglich,
Informationen über die neuesten Temurin-Builds zu erhalten und diese in Ihre eigene Anwendung zu integrieren.

Wir bieten
https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-three-scripting-a-download-using-the-adoptium-api[ein Beispiel zur Automatisierung eines Downloads]
im
https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#adoptium-api-cookbook[Adoptium API Cookbook].

== Können Sie einen Vortrag über das Projekt halten?

Die an dem Projekt beteiligten Personen sind leidenschaftlich bemüht, es zu fördern.
Wir sind sehr daran interessiert, Wege zu finden über unsere Arbeit bei Adoptium und den Temurin Binaries zu sprechen.
Falls also der Wunsch besteht, dass wir an einer Veranstaltung teilnehmen, werden wir sehen was wir tun können um dieses zu ermöglichen.
Der beste Weg um mit dem Team in Kontakt zu treten ist über den Slack-Channel.
