// Some portions generated by Co-Pilot
= Perguntas Frequentes
:page-authors: gdams, karianna, aahlenst, sxa, tellison, kemitix, Fishbowler
:page-based-on: a5b0bcea38cc3ef6e7e9a52b72ecd1680b2c92df

Reunimos algumas perguntas frequentes (FAQs) neste documento.
Se você quiser conversar conosco sobre esses tópicos ou fazer perguntas adicionais,
o melhor lugar é pelo
link:/slack[Slack] ou abrindo uma issue no
https://github.com/adoptium/adoptium-support[canal de suporte].

== Onde estão os JDKs mais recentes do Adoptium(R)?

Os JDKs do Adoptium são chamados de Eclipse Temurin(TM), e as versões que recomendamos
para uso estão disponíveis na nossa link:/temurin/releases[página de lançamentos mais recentes].

Também estamos presentes em todos os gerenciadores de instalação Java populares, como
https://formulae.brew.sh/cask/temurin[Homebrew], https://sdkman.io/[SDKMAN],
https://github.com/microsoft/winget-cli[winget] e https://chocolatey.org/[Chocolatey]. O Temurin está disponível como
link:/installation/containers[imagens Docker oficiais], e você pode
usá-lo por meio da
link:/installation/github-actions[GitHub Action setup-java]
e como parte do suporte Java de provedores de nuvem.

Instaladores Linux estão disponíveis em packages.adoptium.net. Para mais informações, consulte link:/installation/linux[este guia].

== Como posso criar um link para os builds mais recentes do Temurin(TM)?

O
https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-two-linking-to-the-latest-jdk-or-jre[Adoptium API cookbook]
tem exemplos de URLs estáveis que apontam para JDKs e JREs Temurin específicos ou mais recentes. Você também pode promover o Temurin incorporando código de
link:/temurin/buttons[botões html]
disponível no site.

== O Eclipse Temurin é gratuito?

Sim. Os binários do Eclipse Temurin são fornecidos gratuitamente pelo Adoptium,
para sempre, sob os termos da "GNU General Public License, versão 2 com a
Classpath Exception". Você pode usar, modificar e compartilhar livremente o código
conforme descrito nas licenças incluídas no download.

== Como posso ajudar o projeto?

A equipe do Adoptium aceita ajuda de muitas formas diferentes. Por exemplo:

* Qualquer pessoa pode contribuir com os fundos que mantêm o projeto funcionando
sem problemas, seja como uma https://www.eclipse.org/donate/adoptium/[doação única] ou por meio de um
link:/sponsors[patrocínio de projeto] mais estruturado.

* Organizações que dependem do Adoptium são encorajadas a ingressar no
link:/members[Adoptium Working Group] e ter voz na direção do projeto.

* Bem-vindos a ajuda técnica e criativa no projeto para avançar nossos objetivos por meio de
promoção e marketing, escrevendo blogs sobre sua experiência com o Adoptium, respondendo
perguntas em nossa link:/slack[comunidade ativa no Slack], ajudando a testar o
software ou diagnosticar problemas, e link:/docs/first-timer-support[corrigindo algumas
issues] que foram relatadas.

* Muitas outras formas, seja como uma aventura única ou como membro de longo prazo da equipe,
basta se juntar a nós e nos contar suas ideias!

== Por quanto tempo o Eclipse Temurin é suportado?

Nossa frequência de lançamentos e declaração de suporte estão disponíveis
link:/support[aqui].

== O Eclipse Temurin passou no JCK?

Sim. Cada lançamento do Temurin passou no Java Compatibility Kit (JCK) da Oracle
para demonstrar que é uma implementação compatível com a especificação Java.
Você pode ver nosso link:/temurin/tck-affidavit[TCK affidavit] para detalhes.
Além disso, os lançamentos do Temurin devem passar pela link:/aqavit[suíte de verificação de qualidade AQAvit]
para garantir que estejam prontos para uso em produção. Os testes AQAvit verificam se o lançamento apresenta
excelente desempenho, segurança, resiliência e durabilidade, e a capacidade de passar em uma ampla
variedade de testes de compatibilidade de aplicações.

== Onde devo reportar um bug ou problema com o Eclipse Temurin?

Se você suspeitar de uma vulnerabilidade de segurança em qualquer produto do projeto Adoptium,
envie um relatório para a https://www.eclipse.org/security/[Eclipse Security Team]
que gerenciará e rastreará a issue de forma privada até que seja resolvida.

Quando algo simplesmente não se comporta como esperado ou você tem dúvidas sobre
como configurar o Temurin, nos avise publicamente abrindo uma
https://github.com/adoptium/adoptium-support/issues/new/choose[issue de suporte] e trabalharemos
com você para buscar uma solução. Nosso suporte é link:/support["suporte da comunidade"],
portanto, os problemas são tratados com base no melhor esforço. Você deve contatar organizações
que oferecem suporte comercial se precisar de um nível de serviço garantido para o uso de Java.

== Vocês podem entregar o Eclipse Temurin com minha imagem base Docker favorita?

Temos um conjunto definido de variantes no nosso
https://hub.docker.com/_/eclipse-temurin[repositório Docker oficial] para garantir que
sejamos ágeis na entrega de novas imagens contendo o Temurin. O Docker colabora
com o Adoptium para decidir quais versões de contêiner do sistema operacional base
eles suportarão para o Temurin.

Usuários que desejam uma distribuição Linux containerizada que não fornecemos podem seguir
as instruções em
link:/news/2021/08/using-jlink-in-dockerfiles/[este guia].

== Meu scanner reporta um CVE na imagem Docker do Eclipse Temurin. Vocês podem corrigir?

As https://hub.docker.com/_/eclipse-temurin[imagens de contêiner Temurin] disponíveis no
Docker Hub são https://docs.docker.com/docker-hub/official_images/[imagens oficiais]
criadas e mantidas como um esforço colaborativo entre o projeto Adoptium e
a Docker, Inc. O Adoptium cria, mantém e testa um amplo conjunto de
https://github.com/adoptium/containers[arquivos Dockerfile Temurin] que são
https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin[usados pelo Docker]
para criar imagens oficiais em vários sistemas operacionais base.

O Docker se esforça para garantir que as imagens Temurin contenham os pacotes mais
atualizados disponíveis em um prazo razoável. O Docker tem seu próprio programa robusto
de varredura de vulnerabilidades; no entanto, um scanner de segurança de terceiros pode
sinalizar um problema com uma imagem oficial. O Docker
https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves[abordou várias razões]
pelas quais isso pode acontecer em seu FAQ. Somos gratos ao Docker por continuar a
atualizar as imagens base e recriar as imagens oficiais regularmente.

Ficamos felizes em
https://github.com/adoptium/adoptium-support/issues/new/choose[receber perguntas]
sobre as
https://hub.docker.com/_/eclipse-temurin[imagens eclipse-temurin], mas observe que
em alguns casos precisaremos encaminhar a issue ao Docker quando ela se relacionar ao sistema
operacional base.

== Vocês suportarão minha arquitetura e sistema operacional favoritos?

O Eclipse Temurin tem o mais amplo suporte de plataformas entre várias versões da API Java.
Cada nova plataforma gera custos adicionais e exigências nos recursos do projeto,
portanto, revisamos constantemente a demanda de downloads e uso para garantir que
estamos lançando em plataformas relevantes para um grande conjunto de usuários. O conjunto
atual de plataformas que visamos em nosso processo de build e teste está listado link:/supported-platforms[aqui].

== Posso automatizar o download de binários do Eclipse Temurin?

Sim! Há uma rica https://api.adoptium.net/q/swagger-ui/[API de download]
fornecida pelo Adoptium para baixar builds do Eclipse Temurin. Usando a API, é
possível obter informações sobre os builds mais recentes do Temurin e baixá-los
para sua própria aplicação.

Fornecemos
https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-three-scripting-a-download-using-the-adoptium-api[um exemplo de automação de download]
no
https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#adoptium-api-cookbook[Adoptium API cookbook].

== Vocês podem dar uma palestra sobre o projeto?

As pessoas envolvidas no projeto são apaixonadas por promovê-lo e
estamos ansiosos para encontrar formas de promover o trabalho que fazemos no Adoptium e com
os binários Temurin. Portanto, sinta-se à vontade para entrar em contato conosco se você tiver um
fórum no qual deseja que participemos e veremos o que podemos fazer. Em geral, contatar
a equipe pelo Slack é a melhor forma de interagir conosco.
