// Some portions generated by Co-Pilot
= よくある質問
:page-authors: gdams, karianna, aahlenst, sxa, tellison, kemitix, Fishbowler
:page-based-on: a5b0bcea38cc3ef6e7e9a52b72ecd1680b2c92df

よくある質問 (FAQ) をまとめました。
これらのトピックについてご相談されたい場合や追加のご質問がある場合は、
link:/slack[Slack] または
https://github.com/adoptium/adoptium-support[サポートチャンネル] での Issue 作成が最適です。

== Adoptium(R) の最新 JDK はどこにありますか？

Adoptium の JDK は Eclipse Temurin(TM) と呼ばれています。推奨するリリースは link:/temurin/releases[最新リリースページ] でご確認いただけます。

また、https://formulae.brew.sh/cask/temurin[Homebrew]、https://sdkman.io/[SDKMAN]、
https://github.com/microsoft/winget-cli[winget]、https://chocolatey.org/[Chocolatey] など主要な Java インストールマネージャーにも掲載されています。Temurin は
link:/installation/containers[公式 Docker イメージ] として利用可能であり、
link:/installation/github-actions[setup-java GitHub Action] を通じて使用したり、クラウドプロバイダーの Java サポートの一部として利用することもできます。

Linux インストーラーは packages.adoptium.net で入手できます。詳細については link:/installation/linux[こちらのガイド] をご覧ください。

== 最新の Temurin(TM) ビルドへのリンク方法を教えてください。

https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-two-linking-to-the-latest-jdk-or-jre[Adoptium API クックブック] に、特定または最新の Temurin JDK や JRE にリンクするための安定した URL の例が記載されています。また、ウェブサイトで提供されている HTML link:/temurin/buttons[ボタンコード] を埋め込んで Temurin を宣伝することもできます。

== Eclipse Temurin は無料で使用できますか？

はい。Eclipse Temurin バイナリは、「GNU General Public License, version 2 with the Classpath Exception」の条件のもと、Adoptium によって無償で永続的に提供されます。ダウンロードに含まれるライセンスに記載されている通り、コードを自由に使用・修正・共有できます。

== プロジェクトへの参加方法は？

Adoptium チームはさまざまな形での支援を歓迎しています。例えば:

* プロジェクトの円滑な運営を支える資金への貢献として、https://www.eclipse.org/donate/adoptium/[一回限りの寄付] または
link:/sponsors[プロジェクトスポンサーシップ] があります。

* Adoptium に依存している組織には、link:/members[Adoptium ワーキンググループ] への参加を通じてプロジェクトの方向性に意見を持つことをお勧めします。

* プロジェクトへの技術的・クリエイティブな支援も歓迎しています。Adoptium と Temurin バイナリの活動の宣伝・マーケティング、Adoptium での経験についてのブログ執筆、link:/slack[活発な Slack コミュニティ] での質問への回答、ソフトウェアのテストや問題の診断、報告されている link:/docs/first-timer-support[Issue の修正] などがあります。

* 一回限りの参加から長期的なチームメンバーとして関わるまで、さまざまな形での参加が可能です。ぜひ参加してアイデアをお聞かせください！

== Eclipse Temurin はどれくらいサポートされますか？

リリース頻度とサポートに関する声明は link:/support[こちら] でご確認いただけます。

== Eclipse Temurin は JCK に合格しましたか？

はい。各 Temurin リリースは、Java 仕様の互換性のある実装であることを示すために、関連する Oracle Java Compatibility Kit (JCK) に合格しています。詳細は link:/temurin/tck-affidavit[TCK 宣誓書] をご覧ください。
さらに、Temurin リリースは本番利用に向けた準備ができていることを確認するために link:/aqavit[AQAvit 品質検証スイート] に合格する必要があります。AQAvit テストは、リリースが優れたパフォーマンス・セキュリティ・回復力・耐久性を備え、幅広いアプリケーション互換性テストに合格できることを確認します。

== Eclipse Temurin のバグや問題はどこに報告すればよいですか？

Adoptium プロジェクトのいずれかの製品にセキュリティ上の脆弱性があると思われる場合は、問題が解決されるまでプライベートに管理・追跡する https://www.eclipse.org/security/[Eclipse セキュリティチーム] にレポートを送ってください。

Temurin が期待通りに動作しない場合や設定方法についての質問がある場合は、https://github.com/adoptium/adoptium-support/issues/new/choose[サポート Issue] を作成して公開でお知らせください。私たちが解決策を一緒に探します。サポートは link:/support[「コミュニティサポート」] であるため、問題はベストエフォートで対応されます。Java 使用における保証されたサービスレベルが必要な場合は、商業サポートを提供する組織にご相談ください。

== 好きな Docker ベース OS イメージで Eclipse Temurin を提供してもらえますか？

Temurin を含む新しいイメージの配信に迅速に対応するため、https://hub.docker.com/_/eclipse-temurin[公式 Docker リポジトリ] では一定のバリアントセットを提供しています。Docker は Adoptium と協力して、Temurin に対してサポートするベース OS コンテナバージョンを決定しています。

提供していない Linux ディストリビューションのコンテナ化されたバージョンが必要なユーザーは、
link:/news/2021/08/using-jlink-in-dockerfiles/[こちらのガイド] の手順に従ってください。

== Docker イメージのスキャナーが CVE を検出しました。修正してもらえますか？

Docker Hub で提供されている https://hub.docker.com/_/eclipse-temurin[Temurin コンテナイメージ] は、Adoptium プロジェクトと Docker, Inc. の共同作業によって作成・維持される https://docs.docker.com/docker-hub/official_images/[公式イメージ] です。Adoptium は幅広い https://github.com/adoptium/containers[Temurin Dockerfile ソースファイル] を作成・維持・テストしており、これらは Docker が様々なベース OS に対して公式イメージを作成するために https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin[使用] しています。

Docker は合理的な時間枠内で Temurin イメージに最新パッケージが含まれるよう努めています。Docker には独自の強力な脆弱性スキャンプログラムがありますが、サードパーティのセキュリティスキャナーが公式イメージの問題を検出することがあります。Docker は FAQ でこれが発生する https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves[様々な理由に対応] しています。ベースイメージを継続的に更新し、公式イメージを定期的にリビルドしてくださる Docker に感謝します。

https://hub.docker.com/_/eclipse-temurin[eclipse-temurin イメージ] に関する https://github.com/adoptium/adoptium-support/issues/new/choose[ご質問] を喜んでお受けしますが、ベース OS に関連する問題については Docker に転送する場合があります。

== 好みのアーキテクチャとオペレーティングシステムをサポートしてもらえますか？

Eclipse Temurin は複数の Java API バージョンにわたって最も広範なプラットフォームサポートを提供しています。新しいプラットフォームを追加するたびにプロジェクトのリソースへの追加コストと需要が生じるため、多くのユーザーに関連するプラットフォームでリリースできるよう、ダウンロードと使用状況の需要を常に見直しています。現在のビルドおよびテストプロセスで対象とするプラットフォームは link:/supported-platforms[こちら] にリストされています。

== Eclipse Temurin バイナリのダウンロードを自動化できますか？

はい！Adoptium が提供する豊富な https://api.adoptium.net/q/swagger-ui/[ダウンロード API] を利用して Eclipse Temurin ビルドをダウンロードできます。API を使用すると、Temurin の最新ビルドに関する情報を取得し、独自のアプリケーションにプルダウンすることが可能です。

https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#adoptium-api-cookbook[Adoptium API クックブック] に https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-three-scripting-a-download-using-the-adoptium-api[ダウンロード自動化の例] が掲載されています。

== プロジェクトについて講演していただけますか？

プロジェクトに関わるメンバーはその活動を広めることに情熱を持っており、Adoptium および Temurin バイナリでの取り組みを宣伝する機会を積極的に探しています。参加を希望するフォーラムがあればお気軽にご連絡ください。できる限り対応いたします。チームへの連絡は Slack が最も効果的な方法です。
