// Some portions generated by Co-Pilot
import React from "react";
import { render, cleanup } from "@testing-library/react";
import { describe, it, expect, afterEach, vi } from "vitest";

vi.mock("@highcharts/react", () => ({
  Chart: ({ options }: { options: { title?: { text?: string } } }) => (
    <div data-testid="highcharts-react">{options?.title?.text}</div>
  ),
}));

import StackedBarChart from "../index";

describe("StackedBarChart", () => {
  afterEach(() => {
    cleanup();
  });

  it("renders nothing if no series data", () => {
    const { container } = render(
      <StackedBarChart categories={[]} series={[]} name="Test" />,
    );
    expect(container.firstChild).toBeNull();
  });

  it("renders chart when series data is provided", () => {
    const { container } = render(
      <StackedBarChart
        categories={["JDK8", "JDK11", "JDK17"]}
        series={[
          { name: "GitHub", data: [100, 200, 300] },
          { name: "Docker", data: [50, 150, 250] },
        ]}
        name="Downloads per Version"
      />,
    );
    expect(container.firstChild).not.toBeNull();
    expect(container.querySelector(".chart")).toBeTruthy();
  });

  it("renders with percent stacking", () => {
    const { getByTestId } = render(
      <StackedBarChart
        categories={["JDK8", "JDK11"]}
        series={[{ name: "GitHub", data: [100, 200] }]}
        name="Percent Chart"
        stacking="percent"
      />,
    );
    expect(getByTestId("highcharts-react").textContent).toBe("Percent Chart");
  });

  it("renders horizontal bar chart", () => {
    const { getByTestId } = render(
      <StackedBarChart
        categories={["JDK8", "JDK11"]}
        series={[{ name: "GitHub", data: [100, 200] }]}
        name="Horizontal Chart"
        horizontal
      />,
    );
    expect(getByTestId("highcharts-react").textContent).toBe(
      "Horizontal Chart",
    );
  });
});
