// Some portions generated by Co-Pilot
import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";

const nextConfig: NextConfig = {
  reactCompiler: true,
  serverExternalPackages: ["asciidoctor"],
  experimental: {
    turbopackFileSystemCacheForDev: true,
  },
  images: {
    unoptimized: true,
    formats: ["image/avif", "image/webp"],
    remotePatterns: [
      {
        protocol: "https",
        hostname: "avatars.githubusercontent.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "github.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "newsroom.eclipse.org",
        pathname: "/**",
      },
    ],
  },
  async redirects() {
    return [
      {
        source: "/:locale/sponsors",
        destination: "/:locale/sustainers",
        permanent: true,
      },
      {
        source: "/:locale/blog/:path*",
        destination: "/:locale/news/:path*",
        permanent: true,
      },
      {
        source: "/blog/:path*",
        destination: "/news/:path*",
        permanent: true,
      },
      {
        source: "/:locale/docs/migration",
        destination: "/:locale/temurin/migration",
        permanent: true,
      },
      {
        source: "/docs/migration",
        destination: "/temurin/migration",
        permanent: true,
      },
      {
        source: "/marketplace-policy",
        destination: "/docs/marketplace-policy",
        permanent: true,
      },
      {
        source: "/qvs-policy",
        destination: "/docs/qvs-policy",
        permanent: true,
      },
      {
        source: "/:locale/support-us",
        destination: "/:locale/join-us",
        permanent: true,
      },
      {
        source: "/support-us",
        destination: "/join-us",
        permanent: true,
      },
    ];
  },
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          {
            key: "Strict-Transport-Security",
            value: "max-age=63072000; includeSubDomains; preload",
          },
        ],
      },
      {
        source: "/favicon.ico",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=604800, stale-while-revalidate=604800",
          },
        ],
      },
      {
        source: "/images/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=86400, stale-while-revalidate=604800",
          },
        ],
      },
      {
        source: "/pagefind/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=86400, stale-while-revalidate=604800",
          },
        ],
      },
      {
        source: "/docs/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=604800, stale-while-revalidate=604800",
          },
        ],
      },
    ];
  },
};

const withNextIntl = createNextIntlPlugin();
export default withNextIntl(nextConfig);

import("@opennextjs/cloudflare").then((m) => m.initOpenNextCloudflareForDev());
