// Some portions generated by Co-Pilot
import { describe, it, expect } from 'vitest';
import { render } from '@testing-library/react';
import Calendar from '../index';

describe('Calendar', () => {
  it('renders correctly', () => {
    const { container } = render(<Calendar />);
    expect(container).toBeTruthy();
  });

  it('matches snapshot', () => {
    const { container } = render(<Calendar />);
    expect(container.firstChild).toMatchSnapshot();
  });

  it('displays the calendar title', () => {
    const { container } = render(<Calendar />);
    const heading = container.querySelector('h3');
    expect(heading).toHaveTextContent('Adoptium Community Calendar');
  });

  it('renders view calendar link with correct href', () => {
    const { container } = render(<Calendar />);
    const viewCalendarLink = container.querySelector('a[href*="calendar.google.com/calendar/embed"]');
    expect(viewCalendarLink).toHaveAttribute('href', 'https://calendar.google.com/calendar/embed?src=c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com');
    expect(viewCalendarLink).toHaveAttribute('target', '_blank');
    expect(viewCalendarLink).toHaveAttribute('rel', 'noopener noreferrer');
    expect(viewCalendarLink).toHaveTextContent('View Calendar');
  });

  it('renders iCal subscription link with correct href', () => {
    const { container } = render(<Calendar />);
    const iCalLink = container.querySelector('a[href*="calendar.google.com/calendar/ical"]');
    expect(iCalLink).toHaveAttribute('href', 'https://calendar.google.com/calendar/ical/c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com/public/basic.ics');
    expect(iCalLink).toHaveTextContent('Subscribe to iCal');
  });

  it('displays calendar description text', () => {
    const { container } = render(<Calendar />);
    const description = container.querySelector('p.text-grey');
    expect(description).toHaveTextContent(/Stay up to date with the Adoptium Community meeting/);
  });
});