// Some portions generated by Co-Pilot
"use client";

import React, { useEffect } from "react";
import { highlight } from "sugar-high";
import { renderToStaticMarkup } from "react-dom/server";
import { FaClipboard, FaCheck } from "react-icons/fa";

const COPY_ICON = renderToStaticMarkup(<FaClipboard />);
const CHECK_ICON = renderToStaticMarkup(<FaCheck />);

const WRAPPER_CLASSES = "relative group";
const BUTTON_CLASSES =
  "absolute top-1/2 right-2 -translate-y-1/2 p-1.5 bg-black/35 border border-white/15 rounded text-white/45 cursor-pointer opacity-0 transition-all duration-150 leading-[0] flex items-center justify-center group-hover:opacity-100 focus-visible:opacity-100 hover:text-pink hover:border-pink/50 hover:bg-pink/10";
const COPIED_ADD = ["!text-[#4ade80]", "!border-[#4ade80]/50", "!opacity-100"];

// Highlight a single code block with sugar-high. The raw source is read from
// textContent so re-highlighting an already-highlighted block is idempotent.
function highlightElement(codeBlock: Element) {
  const code = codeBlock.textContent || "";
  codeBlock.innerHTML = highlight(code);
}

// Export the highlighting function so it can be called directly
export function highlightCode() {
  const codeBlocks = document.querySelectorAll("pre code");
  codeBlocks.forEach((codeBlock) => {
    // skip all pre tags with class no-highlight
    if (codeBlock.parentElement?.classList.contains("no-highlight")) {
      return;
    }
    highlightElement(codeBlock);
  });
}

export function addCopyButtons() {
  const codeBlocks = document.querySelectorAll("pre code");
  codeBlocks.forEach((codeBlock) => {
    const pre = codeBlock.parentElement;
    if (!pre) return;
    // Skip no-highlight blocks (e.g. ShellBox)
    if (pre.classList.contains("no-highlight")) return;
    // Skip output language blocks
    if (codeBlock.classList.contains("language-output")) return;
    // Skip if already processed
    if (pre.dataset.copyButtonAdded) return;
    pre.dataset.copyButtonAdded = "true";

    // Wrap the pre in a relative container so the button sits outside the scroll area
    const wrapper = document.createElement("div");
    wrapper.className = WRAPPER_CLASSES;
    pre.parentNode?.insertBefore(wrapper, pre);
    wrapper.appendChild(pre);

    const button = document.createElement("button");
    button.className = BUTTON_CLASSES;
    button.setAttribute("aria-label", "Copy code to clipboard");
    button.setAttribute("title", "Copy code");
    button.innerHTML = COPY_ICON;

    button.addEventListener("click", async () => {
      const code = codeBlock.textContent || "";
      try {
        await navigator.clipboard.writeText(code);
        button.innerHTML = CHECK_ICON;
        button.classList.add(...COPIED_ADD);
        setTimeout(() => {
          button.innerHTML = COPY_ICON;
          button.classList.remove(...COPIED_ADD);
        }, 2000);
      } catch {
        // Clipboard API unavailable
      }
    });

    wrapper.appendChild(button);
  });
}

// Client component that enhances code blocks with sugar-high highlighting.
// AsciiDoc content is server-rendered and present on mount, so a single pass
// is sufficient — no MutationObserver required.
export default function SyntaxHighlighter() {
  useEffect(() => {
    highlightCode();
    addCopyButtons();
  }, []);

  return null; // This component doesn't render anything
}
