// Some portions generated by Co-Pilot
import React from "react";
import { useTranslations } from "next-intl";
import { Link } from "@/i18n/navigation";
import ProfilePic from "@/components/Common/ProfilePic";

interface IBylineProps {
  author: string;
  date: string;
  identifier: string;
  readingTime?: number;
}

const Byline: React.FC<IBylineProps> = (props) => {
  const { author, date, identifier, readingTime } = props;
  const t = useTranslations("Byline");
  return (
    <div className="flex items-center gap-4">
      <ProfilePic identifier={identifier} name={author} size={30} />
      <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-2 text-sm">
        <Link
          href={`/news/author/${identifier}`}
          className="font-semibold text-pink hover:underline transition-colors"
        >
          {author}
        </Link>
        <span className="hidden sm:inline text-gray-600">·</span>
        <time className="text-gray-400 light:text-gray-500">{date}</time>
        {readingTime !== undefined && (
          <>
            <span className="hidden sm:inline text-gray-600">·</span>
            <span className="text-gray-400 light:text-gray-500">
              {t("reading-time", { minutes: readingTime })}
            </span>
          </>
        )}
      </div>
    </div>
  );
};

export default Byline;
