// Some portions generated by Co-Pilot
/**
 * Adoptium API Service
 *
 * Typed HTTP client generated from https://api.adoptium.net/q/openapi
 * using openapi-fetch + openapi-typescript.
 *
 * To regenerate types after an API change run:
 *   npm run generate:api-types
 *
 * All hooks in src/hooks/ call these functions instead of making raw
 * axios/fetch calls directly.
 */
import createClient from "openapi-fetch";
import type { paths, components } from "@/types/adoptiumApiTypes";
import type {
  paths as marketplacePaths,
  components as marketplaceComponents,
} from "@/types/marketplaceApiTypes";

export const ADOPTIUM_API_BASE = "https://api.adoptium.net";
export const MARKETPLACE_API_BASE = "https://marketplace-api.adoptium.net";

// Typed client backed by the generated OpenAPI paths
const adoptiumClient = createClient<paths>({ baseUrl: ADOPTIUM_API_BASE });
const marketplaceClient = createClient<marketplacePaths>({
  baseUrl: MARKETPLACE_API_BASE,
});

// Re-export useful schema types for consumers
export type { components };
export type Release = components["schemas"]["Release"];
export type MarketplaceBinaryAssetView =
  marketplaceComponents["schemas"]["BinaryAssetView"];
export type MarketplaceVendor = marketplaceComponents["schemas"]["Vendor"];
export type BinaryAssetView = components["schemas"]["BinaryAssetView"];
export type Attestation = components["schemas"]["Attestation"];
export type ReleaseType = components["schemas"]["ReleaseType"];
export type Architecture = components["schemas"]["Architecture"];
export type OperatingSystem = components["schemas"]["OperatingSystem"];
export type ImageType = components["schemas"]["ImageType"];

// ---------------------------------------------------------------------------
// Assets / Releases
// ---------------------------------------------------------------------------

/**
 * getLatestAssets — GET /v3/assets/latest/{feature_version}/{jvm_impl}
 * Returns latest assets for the given feature version.
 */
export async function fetchLatestAssets(
  version: number | string,
  params: {
    os?: OperatingSystem;
    architecture?: Architecture;
    image_type?: ImageType;
  } = {},
): Promise<BinaryAssetView[]> {
  const feature_version =
    typeof version === "string" ? parseInt(version, 10) : version;
  const { data, error } = await adoptiumClient.GET(
    "/v3/assets/latest/{feature_version}/{jvm_impl}",
    {
      params: {
        path: { feature_version, jvm_impl: "hotspot" },
        query: {
          vendor: "eclipse",
          ...params,
        },
      },
    },
  );
  if (error) throw error;
  return data ?? [];
}

/**
 * searchReleases — GET /v3/assets/feature_releases/{feature_version}/{release_type}
 * Returns release information for a feature version.
 */
export async function fetchFeatureReleases(
  version: number,
  releaseType: ReleaseType,
  params: {
    architecture?: Architecture;
    os?: OperatingSystem;
    image_type?: ImageType;
    page?: number;
    page_size?: number;
    before?: string;
    show_page_count?: boolean;
  } = {},
): Promise<{ data: Release[]; pagecount: number }> {
  const { data, error, response } = await adoptiumClient.GET(
    "/v3/assets/feature_releases/{feature_version}/{release_type}",
    {
      params: {
        path: { feature_version: version, release_type: releaseType },
        query: { vendor: "eclipse", ...params },
      },
    },
  );
  if (error) throw error;
  const pagecount = Number(
    response.headers.get("pagecount") ?? response.headers.get("PageCount") ?? 0,
  );
  return { data: data ?? [], pagecount };
}

// ---------------------------------------------------------------------------
// Release Notes
// ---------------------------------------------------------------------------

/**
 * getReleaseNotes — GET /v3/info/release_notes/{release_name}
 */
export async function fetchReleaseNotes(
  release_name: string,
): Promise<unknown> {
  const { data, error } = await adoptiumClient.GET(
    "/v3/info/release_notes/{release_name}",
    { params: { path: { release_name } } },
  );
  if (error) throw error;
  return data;
}

/**
 * getReleaseNames — GET /v3/info/release_names
 * Returns the most recent LTS release name (first result).
 */
export async function fetchLatestReleaseName(): Promise<string | null> {
  try {
    const { data, error } = await adoptiumClient.GET("/v3/info/release_names", {
      params: {
        query: {
          heap_size: "normal",
          image_type: "jdk",
          lts: true,
          page: 0,
          page_size: 1,
          project: "jdk",
          release_type: "ga",
          semver: false,
          sort_method: "DEFAULT",
          sort_order: "DESC",
          vendor: "eclipse",
        },
      },
    });
    if (error) return null;
    const releases = (data as { releases?: string[] })?.releases;
    return releases?.[0] ?? null;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Types (OS / Architecture enumerations)
// ---------------------------------------------------------------------------

/**
 * getOperatingSystems — GET /v3/types/operating_systems
 */
export async function fetchOperatingSystems(
  signal?: AbortSignal,
): Promise<string[]> {
  const { data, error } = await adoptiumClient.GET(
    "/v3/types/operating_systems",
    { signal },
  );
  if (error) throw error;
  return (data as string[]) ?? [];
}

/**
 * getArchitectures — GET /v3/types/architectures
 */
export async function fetchArchitectures(
  signal?: AbortSignal,
): Promise<string[]> {
  const { data, error } = await adoptiumClient.GET("/v3/types/architectures", {
    signal,
  });
  if (error) throw error;
  return (data as string[]) ?? [];
}

// ---------------------------------------------------------------------------
// Attestations
// ---------------------------------------------------------------------------

/**
 * listAttestationsForRelease — GET /v3/attestations/release_name/{release_name}
 */
export async function fetchAttestations(
  release_name: string,
  project: components["schemas"]["project"] = "jdk",
): Promise<Attestation[]> {
  const { data, error, response } = await adoptiumClient.GET(
    "/v3/attestations/release_name/{release_name}",
    {
      params: {
        path: { release_name },
        query: { project },
      },
    },
  );
  // 404 means no attestations exist for this release — not an error
  if (response.status === 404) return [];
  if (error) throw error;
  return data ?? [];
}

// ---------------------------------------------------------------------------
// Download Statistics
// (Not in the OpenAPI spec — kept as a raw fetch call)
// ---------------------------------------------------------------------------

/** GET /v3/stats/downloads/total/{release}[/{subpath}] */
export async function fetchDownloadStats(
  release: string,
  subpath = "",
): Promise<Record<string, number> | null> {
  const url = `${ADOPTIUM_API_BASE}/stats/downloads/total/${release}${subpath ? "/" + subpath : ""}`;
  const res = await fetch(url);
  if (!res.ok) return null;
  return res.json() as Promise<Record<string, number>>;
}

// ---------------------------------------------------------------------------
// Marketplace
// (Separate API — not covered by the Adoptium OpenAPI spec)
// ---------------------------------------------------------------------------

export interface MarketplaceQueryParams {
  version: number;
  os?: marketplaceComponents["schemas"]["OperatingSystem"];
  architecture?: marketplaceComponents["schemas"]["Architecture"];
  package_type?: marketplaceComponents["schemas"]["ImageType"];
  vendors?: MarketplaceVendor[];
}

/** latestForVendors — GET /v1/assets/latestForVendors */
export async function fetchMarketplaceReleases(
  params: MarketplaceQueryParams,
): Promise<MarketplaceBinaryAssetView[] | null> {
  try {
    const { data, error } = await marketplaceClient.GET(
      "/v1/assets/latestForVendors",
      {
        params: {
          query: {
            feature_version: [params.version],
            vendor: params.vendors ?? [],
            ...(params.os && params.os !== ("any" as string)
              ? { os: [params.os] }
              : {}),
            ...(params.architecture && params.architecture !== ("any" as string)
              ? { architecture: [params.architecture] }
              : {}),
            ...(params.package_type && params.package_type !== ("any" as string)
              ? { image_type: [params.package_type] }
              : {}),
          },
        },
      },
    );
    if (error) return null;
    return data ?? null;
  } catch {
    return null;
  }
}
