// Some portions generated by Co-Pilot
import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import EventCard from "../index";

// Mock the useLocale hook
vi.mock("next-intl", async () => {
  const actual = await vi.importActual("next-intl");
  return {
    ...actual as object,
    useLocale: () => "en",
  };
});

describe("EventCard", () => {
  const mockPost = {
    slug: "test-post",
    year: "2024",
    month: "03",
    metadata: {
      title: "Test Blog Post Title",
      description: "This is a test description for the blog post.",
      date: "2024-03-15",
      featuredImage: "/images/test.jpg",
      tags: ["java", "temurin"],
      author: "pmc",
    },
  };

  it("renders the post title", () => {
    render(<EventCard post={mockPost} />);
    expect(screen.getByText("Test Blog Post Title")).toBeInTheDocument();
  });

  it("renders the post description", () => {
    render(<EventCard post={mockPost} />);
    const descriptions = screen.getAllByText("This is a test description for the blog post.");
    expect(descriptions.length).toBeGreaterThan(0);
  });

  it("renders the featured image when provided", () => {
    render(<EventCard post={mockPost} />);
    const images = screen.getAllByAltText("Test Blog Post Title");
    expect(images.length).toBeGreaterThan(0);
  });

  it("renders 'Read more' link for internal posts", () => {
    render(<EventCard post={mockPost} />);
    const readMore = screen.getAllByText("Read more");
    expect(readMore.length).toBeGreaterThan(0);
  });

  it("renders 'Read article' link for external eclipse-news posts", () => {
    const externalPost = {
      ...mockPost,
      slug: "https://eclipse.org/news/1",
      metadata: {
        ...mockPost.metadata,
        tags: ["eclipse-news"],
      },
    };
    render(<EventCard post={externalPost} />);
    const readArticle = screen.getAllByText("Read article");
    expect(readArticle.length).toBeGreaterThan(0);
  });

  it("renders 'Read article' for isEclipseNews prop", () => {
    render(<EventCard post={mockPost} isEclipseNews={true} />);
    const readArticle = screen.getAllByText("Read article");
    expect(readArticle.length).toBeGreaterThan(0);
  });

  it("truncates long titles", () => {
    const longTitlePost = {
      ...mockPost,
      metadata: {
        ...mockPost.metadata,
        title: "A".repeat(100),
      },
    };
    render(<EventCard post={longTitlePost} />);
    const headings = screen.getAllByRole("heading", { level: 3 });
    expect(headings[0].textContent!.length).toBeLessThanOrEqual(93); // 90 + "..."
  });

  it("handles post without author", () => {
    const noAuthorPost = {
      ...mockPost,
      metadata: {
        ...mockPost.metadata,
        author: undefined,
      },
    };
    render(<EventCard post={noAuthorPost} />);
    const titles = screen.getAllByText("Test Blog Post Title");
    expect(titles.length).toBeGreaterThan(0);
  });
});
