// Some portions generated by Co-Pilot
import React from "react";
import { render, fireEvent } from "@testing-library/react";
import { describe, it, expect, vi } from "vitest";
import ClientPagination from "../ClientPagination";

describe("ClientPagination", () => {
  it("renders all pages when totalPages <= 7", () => {
    const onNavigate = vi.fn();
    const { getByText } = render(
      <ClientPagination currentPage={1} totalPages={5} onNavigate={onNavigate} />,
    );
    expect(getByText("1")).toBeTruthy();
    expect(getByText("2")).toBeTruthy();
    expect(getByText("5")).toBeTruthy();
  });

  it("renders Previous and Next buttons", () => {
    const onNavigate = vi.fn();
    const { getAllByText } = render(
      <ClientPagination currentPage={2} totalPages={5} onNavigate={onNavigate} />,
    );
    expect(getAllByText("Previous").length).toBeGreaterThan(0);
    expect(getAllByText("Next").length).toBeGreaterThan(0);
  });

  it("disables Previous button on first page", () => {
    const onNavigate = vi.fn();
    const { getAllByText } = render(
      <ClientPagination currentPage={1} totalPages={5} onNavigate={onNavigate} />,
    );
    const prevButtons = getAllByText("Previous").map((el) => el.closest("button")).filter(Boolean);
    // At least one previous button should be disabled
    expect(prevButtons.some((btn) => btn?.disabled)).toBe(true);
  });

  it("disables Next button on last page", () => {
    const onNavigate = vi.fn();
    const { getAllByText } = render(
      <ClientPagination currentPage={5} totalPages={5} onNavigate={onNavigate} />,
    );
    const nextButtons = getAllByText("Next").map((el) => el.closest("button")).filter(Boolean);
    expect(nextButtons.some((btn) => btn?.disabled)).toBe(true);
  });

  it("calls onNavigate with correct page when clicking Next", () => {
    const onNavigate = vi.fn();
    const { container } = render(
      <ClientPagination currentPage={2} totalPages={5} onNavigate={onNavigate} />,
    );
    // Find the Next button - it's the last button in the component
    const buttons = container.querySelectorAll("button");
    const nextButton = Array.from(buttons).find(
      (btn) => btn.textContent === "Next" && !btn.disabled,
    );
    expect(nextButton).toBeTruthy();
    fireEvent.click(nextButton!);
    expect(onNavigate).toHaveBeenCalledWith(3);
  });

  it("calls onNavigate with correct page when clicking Previous", () => {
    const onNavigate = vi.fn();
    const { container } = render(
      <ClientPagination currentPage={3} totalPages={5} onNavigate={onNavigate} />,
    );
    const buttons = container.querySelectorAll("button");
    const prevButton = Array.from(buttons).find(
      (btn) => btn.textContent === "Previous" && !btn.disabled,
    );
    expect(prevButton).toBeTruthy();
    fireEvent.click(prevButton!);
    expect(onNavigate).toHaveBeenCalledWith(2);
  });

  it("calls onNavigate when clicking a page number", () => {
    const onNavigate = vi.fn();
    const { container } = render(
      <ClientPagination currentPage={1} totalPages={5} onNavigate={onNavigate} />,
    );
    const buttons = container.querySelectorAll("button");
    const page3Button = Array.from(buttons).find(
      (btn) => btn.textContent?.trim() === "3",
    );
    expect(page3Button).toBeTruthy();
    fireEvent.click(page3Button!);
    expect(onNavigate).toHaveBeenCalledWith(3);
  });

  it("renders ellipsis for large page counts at beginning", () => {
    const onNavigate = vi.fn();
    const { getAllByText } = render(
      <ClientPagination currentPage={1} totalPages={10} onNavigate={onNavigate} />,
    );
    // Should show first and last page
    expect(getAllByText("1").length).toBeGreaterThan(0);
    expect(getAllByText("10").length).toBeGreaterThan(0);
  });

  it("renders ellipsis for large page counts at end", () => {
    const onNavigate = vi.fn();
    const { getAllByText } = render(
      <ClientPagination currentPage={10} totalPages={10} onNavigate={onNavigate} />,
    );
    expect(getAllByText("...").length).toBeGreaterThan(0);
  });

  it("renders ellipsis for large page counts in middle", () => {
    const onNavigate = vi.fn();
    const { getAllByText } = render(
      <ClientPagination currentPage={5} totalPages={10} onNavigate={onNavigate} />,
    );
    // With middle page selected, should have ellipsis on both sides
    const ellipses = getAllByText("...");
    expect(ellipses.length).toBeGreaterThanOrEqual(2);
  });

  it("highlights current page with bold styling", () => {
    const onNavigate = vi.fn();
    const { container } = render(
      <ClientPagination currentPage={2} totalPages={5} onNavigate={onNavigate} />,
    );
    // The current page button should have the "font-bold" class
    const buttons = container.querySelectorAll("button");
    const currentPageButton = Array.from(buttons).find(
      (b) => b.textContent === "2" && b.classList.contains("font-bold"),
    );
    expect(currentPageButton).toBeTruthy();
  });

  it("renders correctly with 1 page", () => {
    const onNavigate = vi.fn();
    const { container } = render(
      <ClientPagination currentPage={1} totalPages={1} onNavigate={onNavigate} />,
    );
    expect(container).toBeTruthy();
  });

  it("renders near-end pages correctly (currentPage >= totalPages - 2)", () => {
    const onNavigate = vi.fn();
    const { container } = render(
      <ClientPagination currentPage={8} totalPages={10} onNavigate={onNavigate} />,
    );
    expect(container).toBeTruthy();
    // Should show pages near the end
    expect(container.textContent).toContain("10");
  });
});
