// Some portions generated by Co-Pilot
"use client";

import { useEffect } from "react";
import Prism from "prismjs";

/**
 * Strip `sudo ` from the start of lines and `| sudo tee` → `| tee`.
 * Used to produce the "root" variant of a code block.
 */
export function stripSudo(text: string): string {
  return text
    .replace(/(^|\n)(\s*)sudo /g, "$1$2")
    .replace(/\|\s*sudo\s+tee/g, "| tee");
}

/** Returns true if the text contains `sudo` that we can meaningfully strip. */
export function containsSudo(text: string): boolean {
  return /(^|\n)\s*sudo /.test(text) || /\|\s*sudo\s+tee/.test(text);
}

/**
 * SudoToggle — injects a "user / root" tab bar above each bash code block
 * that contains `sudo`. The AsciiDoc source is authored WITH sudo (the user
 * default). Selecting "root" strips it.
 *
 * Renders nothing — works entirely via DOM injection after mount.
 */
const SudoToggle: React.FC = () => {
  useEffect(() => {
    const PROCESSED = "data-sudo-tabs";

    const processBlocks = () => {
      const codeBlocks = document.querySelectorAll(".doc-content pre code");

      // First pass: collect all sudo-relevant blocks
      const entries: Array<{
        codeEl: Element;
        pre: HTMLElement;
        originalText: string;
        rootText: string;
        userTab: HTMLButtonElement;
        rootTab: HTMLButtonElement;
        applyText: (text: string) => void;
      }> = [];

      codeBlocks.forEach((codeEl) => {
        const pre = codeEl.closest("pre") as HTMLElement | null;
        if (!pre) return;
        if (pre.getAttribute(PROCESSED)) return;

        const cls = codeEl.className || "";
        const isBash =
          cls.includes("bash") ||
          cls.includes("shell") ||
          cls.includes("language-bash") ||
          cls.includes("language-shell");
        if (!isBash) return;

        const originalText = codeEl.textContent || "";
        if (!containsSudo(originalText)) return;

        pre.setAttribute(PROCESSED, "true");

        const rootText = stripSudo(originalText);

        const wrapper = pre.parentElement;
        if (!wrapper) return;

        // Inject CSS (once)
        if (!document.getElementById("sudo-tab-styles")) {
          const style = document.createElement("style");
          style.id = "sudo-tab-styles";
          style.textContent = `
            :root {
              --sudo-bar-bg: rgba(255,255,255,0.03);
              --sudo-bar-border: rgba(255,255,255,0.08);
              --sudo-active-bg: rgba(255,255,255,0.07);
              --sudo-active-text: rgba(255,255,255,0.85);
              --sudo-inactive-text: rgba(255,255,255,0.35);
              --sudo-hover-text: rgba(255,255,255,0.6);
              --sudo-hover-bg: rgba(255,255,255,0.04);
            }
            .doc-light {
              --sudo-bar-bg: #f5f5f5;
              --sudo-bar-border: rgba(0,0,0,0.1);
              --sudo-active-bg: #ffffff;
              --sudo-active-text: #1a1a1a;
              --sudo-inactive-text: rgba(0,0,0,0.4);
              --sudo-hover-text: rgba(0,0,0,0.65);
              --sudo-hover-bg: rgba(0,0,0,0.03);
            }
            .sudo-tab-bar {
              display: none;
              align-items: center;
              gap: 2px;
              font-size: 12px;
              font-weight: 500;
              border-top-left-radius: 8px;
              border-top-right-radius: 8px;
              overflow: hidden;
              border: 1px solid var(--sudo-bar-border);
              border-bottom: none;
              background: var(--sudo-bar-bg);
              margin-bottom: -1px;
              position: relative;
              z-index: 1;
            }
            @media (min-width: 768px) {
              .sudo-tab-bar {
                display: flex;
              }
            }
            .sudo-tab-btn {
              padding: 6px 14px;
              cursor: pointer;
              border: none;
              font-size: 12px;
              font-weight: 500;
              transition: all 0.15s;
              background: transparent;
              color: var(--sudo-inactive-text);
              border-bottom: 2px solid transparent;
            }
            .sudo-tab-btn:hover {
              color: var(--sudo-hover-text);
              background: var(--sudo-hover-bg);
            }
            .sudo-tab-btn.active {
              background: var(--sudo-active-bg);
              color: var(--sudo-active-text);
              border-bottom-color: #ff1365;
            }
            .sudo-tab-btn.active:hover {
              background: var(--sudo-active-bg);
              color: var(--sudo-active-text);
            }
          `;
          document.head.appendChild(style);
        }

        const tabBar = document.createElement("div");
        tabBar.className = "sudo-tab-bar";

        const makeTab = (label: string, isActive: boolean) => {
          const btn = document.createElement("button");
          btn.textContent = label;
          btn.type = "button";
          btn.className = `sudo-tab-btn${isActive ? " active" : ""}`;
          return btn;
        };

        const userTab = makeTab("user", true);
        const rootTab = makeTab("root", false);

        const applyText = (text: string) => {
          (codeEl as HTMLElement).textContent = text;
          Prism.highlightElement(codeEl);
        };

        tabBar.appendChild(userTab);
        tabBar.appendChild(rootTab);

        pre.style.borderTopLeftRadius = "0";
        pre.style.borderTopRightRadius = "0";

        const copyWrapper = pre.closest(".group");
        if (copyWrapper && copyWrapper.parentNode) {
          copyWrapper.parentNode.insertBefore(tabBar, copyWrapper);
        } else {
          wrapper.insertBefore(tabBar, pre);
        }

        entries.push({
          codeEl,
          pre,
          originalText,
          rootText,
          userTab,
          rootTab,
          applyText,
        });
      });

      // Second pass: wire click handlers that sync ALL blocks
      const switchAll = (mode: "user" | "root") => {
        entries.forEach((entry) => {
          if (mode === "user") {
            entry.userTab.classList.add("active");
            entry.rootTab.classList.remove("active");
            entry.applyText(entry.originalText);
          } else {
            entry.rootTab.classList.add("active");
            entry.userTab.classList.remove("active");
            entry.applyText(entry.rootText);
          }
        });
      };

      entries.forEach((entry) => {
        entry.userTab.addEventListener("click", () => switchAll("user"));
        entry.rootTab.addEventListener("click", () => switchAll("root"));
      });
    };

    // Run after Prism has had time to highlight
    const timer = setTimeout(processBlocks, 300);
    return () => clearTimeout(timer);
  }, []);

  // This component renders nothing — it injects tab bars via DOM
  return null;
};

export default SudoToggle;
