// Some portions generated by Co-Pilot
import React from "react";
import { render } from "@testing-library/react";
import { describe, expect, it, vi, beforeEach, afterEach } from "vitest";
import { axe } from "vitest-axe";
import HomePage from "../page";

// Mock the data fetching functions
vi.mock("@/utils/fetchDownloadStats", () => ({
  fetchDownloadStats: vi.fn().mockResolvedValue({
    total_downloads: { total: 1000000000 },
  }),
}));

vi.mock("@/utils/fetchAvailableReleases", () => ({
  fetchAvailableReleases: vi.fn().mockResolvedValue({
    most_recent_lts: 21,
  }),
}));

// Mock the LatestNews component with a synchronous version
vi.mock("@/components/News/LatestNews", () => {
  return {
    default: () => (
      <div data-testid="mocked-latest-news">Latest News Content</div>
    ),
  };
});

vi.mock("@/components/Banner/Middle/announcements", () => ({
  currentAnnouncements: [
    {
      title: "Fake Banner for Testing",
      description: "This is a fake banner used for testing purposes only.",
      cta: "Read the Case Study",
      ctaLink: "https://example.com",
      startDate: "2012-12-21T00:00:00Z",
      endDate: "2012-12-21T23:59:59Z",
    },
  ],
}));

describe("Index page", () => {
  beforeEach(() => {
    vi.clearAllMocks();

    // Default date for all tests -> 21/12/2012 - This is the end of the world!
    // NOTE: this is important for accessibility tests
    const date = Date.UTC(2012, 11, 21, 0, 0, 0, 0);
    vi.useFakeTimers({ now: date, shouldAdvanceTime: true });
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it("renders correctly", async () => {
    const jsx = await HomePage();
    const { container } = render(jsx);
    expect(container.firstChild).toMatchSnapshot();
  });

  it("has no accessibility violations", async () => {
    const jsx = await HomePage();
    const { container } = render(jsx);
    const results = await axe(container);
    expect(results).toHaveNoViolations();
  });
});
