// Some portions generated by Co-Pilot
import React from "react";
import { Link } from "@/i18n/navigation";
import "../InstallTabs.css";

export const PureLinuxPanel = (): React.ReactNode => {
  // Hardcoded value for latest LTS, should be replaced with actual data fetching in Next.js
  const mostRecentLts = "25";
  return (
    <div className="install-panel">
      <div className="install-block">
        <div className="install-block-title">
          Install the latest LTS version (Debian or Ubuntu)
        </div>
        <pre className="install-code">
          <code>{`apt-get install temurin-${mostRecentLts}-jdk`}</code>
        </pre>
      </div>
      <div className="install-block">
        <div className="install-block-title">
          Install the latest LTS version (CentOS/RHEL/Fedora)
        </div>
        <pre className="install-code">
          <code>{`yum install temurin-${mostRecentLts}-jdk`}</code>
        </pre>
      </div>
      <div className="install-block">
        <div className="install-block-title">
          Install the latest LTS version (openSUSE/SLES)
        </div>
        <pre className="install-code">
          <code>{`zypper install temurin-${mostRecentLts}-jdk`}</code>
        </pre>
      </div>
      <Link className="install__docs-button" href="/installation/linux">
        Read documentation
      </Link>
    </div>
  );
};

const LinuxPanel = (): React.ReactNode => {
  return <PureLinuxPanel />;
};

export default LinuxPanel;
