// Some portions generated by Co-Pilot
import Ajv from "ajv"
import { describe, it, expect } from "vitest"
import members from "../members.json"
import membersSchema from "../members.schema.json"

const ajv = new Ajv()
const validate = ajv.compile(membersSchema)
const valid = validate(members)

describe("members.json", () => {
  it("should be a valid JSON schema", () => {
    if (!valid) {
      if (validate.errors) {
        const errorMessages = validate.errors
          .map(error => error.message)
          .join("\n")
        console.error("Validation errors:", errorMessages)
      } else {
        console.error(
          "AJV validation failed, but no error details were provided.",
        )
      }
    }
    expect(valid).toBeTruthy()
  })

  it("should not include Google or Rivos as strategic members", () => {
    const strategicMemberNames = members
      .filter(member => member.tier === "strategic")
      .map(member => member.name)

    expect(strategicMemberNames).not.toContain("Google")
    expect(strategicMemberNames).not.toContain("Rivos")
  })
})
