// Some portions generated by Co-Pilot
import { describe, it, expect, afterEach, vi } from "vitest";
import { fetchLatestNews } from "../eclipse";

describe("fetchLatestNews", () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("returns data from the API on success", async () => {
    const mockData = {
      news: [{ id: 1, title: "Test News" }],
      pager: { page: 1 },
    };
    vi.spyOn(globalThis, "fetch").mockResolvedValue({
      ok: true,
      json: async () => mockData,
    } as Response);

    const result = await fetchLatestNews();
    expect(result).toEqual(mockData);
  });

  it("returns default empty news and pager on error", async () => {
    vi.spyOn(globalThis, "fetch").mockResolvedValue({
      ok: false,
      json: async () => ({}),
    } as Response);
    const result = await fetchLatestNews();
    expect(result).toEqual({ news: [], pager: null });
  });
});
