// Some portions generated by Co-Pilot
import { describe, it, expect, vi, beforeEach } from "vitest";
import { fetchAvailableReleases } from "../fetchAvailableReleases";

describe("fetchAvailableReleases", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it("fetches and returns sorted available releases", async () => {
    const mockData = {
      available_lts_releases: [8, 11, 17, 21],
      available_releases: [8, 11, 17, 21, 22, 23],
      most_recent_feature_release: 23,
      most_recent_feature_version: 23,
      most_recent_lts: 21,
      tip_version: 24,
    };

    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: () => Promise.resolve(JSON.parse(JSON.stringify(mockData))),
    });

    const result = await fetchAvailableReleases();

    expect(global.fetch).toHaveBeenCalledWith(
      "https://api.adoptium.net/v3/info/available_releases",
      { next: { revalidate: 3600 } }
    );

    // Verify releases are sorted descending
    expect(result.available_releases).toEqual([23, 22, 21, 17, 11, 8]);
    expect(result.available_lts_releases).toEqual([21, 17, 11, 8]);
    expect(result.most_recent_lts).toBe(21);
    expect(result.tip_version).toBe(24);
  });

  it("throws error when response is not ok", async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: false,
      status: 500,
    });

    await expect(fetchAvailableReleases()).rejects.toThrow(
      "Network response was not ok"
    );
  });
});
