// Some portions generated by Co-Pilot
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { sendDownloadEvent } from "../gtag";

const mockGtagParams = {
  link: "https://example.com/file.tar.gz",
  os: "linux",
  arch: "x64",
  pkg_type: "jdk",
  version: "21.0.1+12",
  vendor: "eclipse",
};

describe("sendDownloadEvent", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    // Clean up window.gtag
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    delete (window as any).gtag;
  });

  it("does nothing when window is undefined", () => {
    // In jsdom window is defined, so we check the gtag branch instead
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (window as any).gtag = undefined;
    // Should not throw
    expect(() => sendDownloadEvent(mockGtagParams)).not.toThrow();
  });

  it("does nothing when window.gtag is not a function", () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (window as any).gtag = "not-a-function";
    expect(() => sendDownloadEvent(mockGtagParams)).not.toThrow();
  });

  it("calls window.gtag with correct parameters when gtag is available", () => {
    const mockGtag = vi.fn();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (window as any).gtag = mockGtag;

    sendDownloadEvent(mockGtagParams);

    expect(mockGtag).toHaveBeenCalledTimes(1);
    expect(mockGtag).toHaveBeenCalledWith("event", "download", {
      event_category: "download",
      link: mockGtagParams.link,
      event_label: `${mockGtagParams.os}-${mockGtagParams.arch}-${mockGtagParams.pkg_type}`,
      java_version: mockGtagParams.version,
      vendor: mockGtagParams.vendor,
    });
  });

  it("formats event_label correctly from os, arch and pkg_type", () => {
    const mockGtag = vi.fn();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (window as any).gtag = mockGtag;

    sendDownloadEvent({
      link: "https://example.com/file.msi",
      os: "windows",
      arch: "aarch64",
      pkg_type: "jre",
      version: "17.0.9+9",
      vendor: "eclipse",
    });

    const callArgs = mockGtag.mock.calls[0];
    expect(callArgs[2].event_label).toBe("windows-aarch64-jre");
  });
});
