// Some portions generated by Co-Pilot
import { describe, it, expect } from "vitest";
import { metadata } from "../metadata";

describe("metadata", () => {
  it("has the correct siteUrl", () => {
    expect(metadata.siteUrl).toBe("https://adoptium.net");
  });

  it("has the correct twitter handle", () => {
    expect(metadata.social.twitter).toBe("@adoptium");
  });

  it("has the expected structure", () => {
    expect(metadata).toHaveProperty("social");
    expect(metadata).toHaveProperty("siteUrl");
    expect(metadata.social).toHaveProperty("twitter");
  });
});
