// Some portions generated by Co-Pilot
import { describe, it, expect, vi, beforeEach } from "vitest";

// Mock getBlogPosts to control test data
vi.mock("@/utils/markdown", () => ({
  getBlogPosts: vi.fn(),
}));

// Mock fetchLatestNews
vi.mock("@/utils/eclipse", () => ({
  fetchLatestNews: vi.fn(),
}));

// Mock getFormattedAuthorData
vi.mock("@/utils/authors", () => ({
  getFormattedAuthorData: vi.fn((slug: string) =>
    slug === "johndoe" ? { name: "John Doe" } : null,
  ),
}));

import { getBlogPosts } from "@/utils/markdown";
import { fetchLatestNews } from "@/utils/eclipse";
import {
  getNews,
  getNewsFilters,
  getNewsByTag,
  getNewsByAuthor,
  getNewsPageData,
} from "../news";

const mockBlogPosts = [
  {
    slug: "first-post",
    year: "2024",
    month: "01",
    content: "content",
    metadata: {
      title: "First Post",
      date: "2024-01-15",
      author: "johndoe",
      description: "First post description",
      tags: ["java", "temurin"],
      featuredImage: "/img/first.jpg",
    },
  },
  {
    slug: "second-post",
    year: "2024",
    month: "03",
    content: "content",
    metadata: {
      title: "Second Post",
      date: "2024-03-20",
      author: "janedoe",
      description: "Second post description",
      tags: ["adoptium"],
      featuredImage: "/img/second.jpg",
    },
  },
  {
    slug: "third-post",
    year: "2023",
    month: "12",
    content: "content",
    metadata: {
      title: "Third Post",
      date: "2023-12-01",
      author: "johndoe",
      description: "Third post description",
      tags: ["java", "adoptium"],
      featuredImage: "/img/third.jpg",
    },
  },
];

const mockEFNews = {
  news: [
    {
      title: "EF News 1",
      date: "2024-02-10",
      link: "https://eclipse.org/news/1",
      body: "Eclipse Foundation news body content that is longer than 150 characters for testing truncation",
      image: "/images/ef-news.png",
      author: [{ full_name: "EF Author", username: "efauthor", picture: "/img/ef.jpg" }],
    },
    {
      title: "Adoptium External News",
      date: "2024-02-15",
      link: "https://adoptium.net/blog/something",
      body: "This links to adoptium.net so should be filtered out",
      image: "",
      author: [],
    },
  ],
};

describe("news utils", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.mocked(getBlogPosts).mockReturnValue(mockBlogPosts);
    vi.mocked(fetchLatestNews).mockResolvedValue(mockEFNews);
  });

  describe("getNews", () => {
    it("returns posts and totalPages with default options", async () => {
      const result = await getNews({ includeEF: false });
      expect(result.posts).toHaveLength(3);
      expect(result.totalPages).toBe(1);
    });

    it("paginates correctly", async () => {
      const result = await getNews({ numPosts: 2, page: 1, includeEF: false });
      expect(result.posts).toHaveLength(2);
      expect(result.totalPages).toBe(2);
    });

    it("returns page 2 when paginating", async () => {
      const result = await getNews({ numPosts: 2, page: 2, includeEF: false });
      expect(result.posts).toHaveLength(1);
    });

    it("sorts posts by date newest first", async () => {
      const result = await getNews({ includeEF: false });
      const dates = result.posts.map((p) => new Date(p.metadata.date).getTime());
      for (let i = 0; i < dates.length - 1; i++) {
        expect(dates[i]).toBeGreaterThanOrEqual(dates[i + 1]);
      }
    });

    it("filters by tag", async () => {
      const result = await getNews({ tag: "temurin", includeEF: false });
      expect(result.posts.every((p) => p.metadata.tags?.includes("temurin"))).toBe(true);
    });

    it("filters by author", async () => {
      const result = await getNews({ author: "John Doe", includeEF: false });
      expect(result.posts.length).toBeGreaterThan(0);
    });

    it("includes EF news when includeEF is true", async () => {
      const result = await getNews({ includeEF: true });
      // EF post should be included, adoptium.net link should be filtered
      const efPost = result.posts.find((p) =>
        p.metadata.tags?.includes("eclipse-news"),
      );
      expect(efPost).toBeDefined();
    });

    it("filters out adoptium.net links from EF news", async () => {
      const result = await getNews({ includeEF: true });
      // The adoptium.net link should NOT be in the results
      const adoptiumPost = result.posts.find((p) =>
        p.slug === "https://adoptium.net/blog/something",
      );
      expect(adoptiumPost).toBeUndefined();
    });

    it("uses 'Eclipse Foundation' as author when EF news has no author", async () => {
      vi.mocked(fetchLatestNews).mockResolvedValue({
        news: [
          {
            title: "No Author News",
            date: "2024-02-10",
            link: "https://eclipse.org/news/no-author",
            body: "Content",
            image: "/img.png",
            author: [{ full_name: "  ", username: "ef", picture: "/img.jpg" }],
          },
        ],
      });

      const result = await getNews({ includeEF: true });
      const efPost = result.posts.find((p) => p.slug === "https://eclipse.org/news/no-author");
      expect(efPost?.metadata.author).toBe("Eclipse Foundation");
    });

    it("uses default image when EF news has no image", async () => {
      vi.mocked(fetchLatestNews).mockResolvedValue({
        news: [
          {
            title: "No Image News",
            date: "2024-02-10",
            link: "https://eclipse.org/news/no-image",
            body: "Content body text",
            image: "  ",
            author: [{ full_name: "EF Author", username: "ef", picture: "/img.jpg" }],
          },
        ],
      });

      const result = await getNews({ includeEF: true });
      const efPost = result.posts.find((p) => p.slug === "https://eclipse.org/news/no-image");
      expect(efPost?.metadata.featuredImage).toBe("/images/backgrounds/ef-default-news.png");
    });
  });

  describe("getNewsFilters", () => {
    it("returns tags and authors", async () => {
      const result = await getNewsFilters({ includeEF: false });
      expect(result.tags).toContain("java");
      expect(result.tags).toContain("adoptium");
      expect(result.authors.length).toBeGreaterThan(0);
    });
  });

  describe("getNewsByTag", () => {
    it("returns posts filtered by tag", async () => {
      const result = await getNewsByTag("java", { numPosts: 10 });
      expect(result.posts.every((p) => p.metadata.tags?.includes("java"))).toBe(true);
    });
  });

  describe("getNewsByAuthor", () => {
    it("returns posts filtered by author", async () => {
      const result = await getNewsByAuthor("John Doe", { numPosts: 10 });
      expect(result.posts.length).toBeGreaterThan(0);
    });
  });

  describe("getNewsPageData", () => {
    it("filters by source=adoptium", async () => {
      // Add an eclipse-news tagged post
      vi.mocked(getBlogPosts).mockReturnValue([
        ...mockBlogPosts,
        {
          slug: "ef-post",
          year: "2024",
          month: "04",
          content: "content",
          metadata: {
            title: "EF Post",
            date: "2024-04-01",
            author: "ef",
            description: "EF post",
            tags: ["eclipse-news"],
            featuredImage: "/img/ef.jpg",
          },
        },
      ]);

      const result = await getNewsPageData({ source: "adoptium", includeEF: false });
      expect(
        result.posts.every((p) => !p.metadata.tags?.includes("eclipse-news")),
      ).toBe(true);
    });

    it("filters by source=eclipse", async () => {
      vi.mocked(getBlogPosts).mockReturnValue([
        ...mockBlogPosts,
        {
          slug: "ef-post",
          year: "2024",
          month: "04",
          content: "content",
          metadata: {
            title: "EF Post",
            date: "2024-04-01",
            author: "ef",
            description: "EF post",
            tags: ["eclipse-news"],
            featuredImage: "/img/ef.jpg",
          },
        },
      ]);

      const result = await getNewsPageData({ source: "eclipse", includeEF: false });
      expect(
        result.posts.every((p) => p.metadata.tags?.includes("eclipse-news")),
      ).toBe(true);
    });

    it("handles multiple tags (comma-separated)", async () => {
      const result = await getNewsPageData({
        tag: "java,adoptium",
        includeEF: false,
      });
      expect(
        result.posts.every(
          (p) =>
            p.metadata.tags?.includes("java") &&
            p.metadata.tags?.includes("adoptium"),
        ),
      ).toBe(true);
    });

    it("handles tag as array", async () => {
      const result = await getNewsPageData({
        tag: ["java"],
        includeEF: false,
      });
      expect(result.posts.every((p) => p.metadata.tags?.includes("java"))).toBe(true);
    });

    it("clamps page to valid range", async () => {
      // Page 0 should be clamped to 1
      const result = await getNewsPageData({ page: 0, includeEF: false });
      expect(result.posts.length).toBeGreaterThanOrEqual(0);
    });

    it("returns at least 1 total page even with no posts", async () => {
      vi.mocked(getBlogPosts).mockReturnValue([]);
      const result = await getNewsPageData({ includeEF: false });
      expect(result.totalPages).toBe(1);
    });

    it("normalizes author filter for case-insensitive comparison", async () => {
      const result = await getNewsPageData({ author: "JOHN DOE", includeEF: false });
      expect(result.posts.length).toBeGreaterThan(0);
    });
  });
});
