// Some portions generated by Co-Pilot
import { setURLParam } from "../setURLParam";
import { describe, expect, it, vi, beforeEach } from "vitest";

describe("setURLParam", () => {
  beforeEach(() => {
    window.history.replaceState = vi.fn();
    // Set up a URL with some existing params
    Object.defineProperty(window, "location", {
      writable: true,
      value: {
        href: "http://localhost/page?version=8&os=linux",
        protocol: "http:",
        host: "localhost",
        pathname: "/page",
        search: "?version=8&os=linux",
      },
    });
  });

  it("verify that setURLParam modifies window.history", () => {
    expect(window.history.replaceState).not.toHaveBeenCalled();
    setURLParam("version", "8");
    expect(window.history.replaceState).toHaveBeenCalled();
  });

  it("updates existing query param", () => {
    setURLParam("version", "17");
    expect(window.history.replaceState).toHaveBeenCalledTimes(1);
    const callArgs = vi.mocked(window.history.replaceState).mock.calls[0];
    expect(callArgs[2]).toContain("version=17");
  });

  it("removes param when value is undefined", () => {
    setURLParam("version", undefined);
    expect(window.history.replaceState).toHaveBeenCalledTimes(1);
    const callArgs = vi.mocked(window.history.replaceState).mock.calls[0];
    expect(callArgs[2]).not.toContain("version=");
  });

  it("adds new param when not present", () => {
    setURLParam("arch", "aarch64");
    const callArgs = vi.mocked(window.history.replaceState).mock.calls[0];
    expect(callArgs[2]).toContain("arch=aarch64");
  });

  it("handles boolean value", () => {
    setURLParam("flag", true);
    const callArgs = vi.mocked(window.history.replaceState).mock.calls[0];
    expect(callArgs[2]).toContain("flag=true");
  });

  it("handles numeric value", () => {
    setURLParam("version", 21);
    const callArgs = vi.mocked(window.history.replaceState).mock.calls[0];
    expect(callArgs[2]).toContain("version=21");
  });

  it("handles URL with no existing params", () => {
    Object.defineProperty(window, "location", {
      writable: true,
      value: {
        href: "http://localhost/page",
        protocol: "http:",
        host: "localhost",
        pathname: "/page",
        search: "",
      },
    });
    setURLParam("version", "8");
    expect(window.history.replaceState).toHaveBeenCalled();
    const callArgs = vi.mocked(window.history.replaceState).mock.calls[0];
    expect(callArgs[2]).toContain("version=8");
  });
});
