// Some portions generated by Co-Pilot
import { describe, it, expect } from "vitest";
import { truncateIfLonger } from "../truncateLonger";

describe("truncateIfLonger", () => {
  it("returns the original string when word count is below the threshold", () => {
    const shortText = "This is a short text";
    expect(truncateIfLonger(shortText)).toBe(shortText);
  });

  it("returns the original string when word count is exactly 40", () => {
    const words = Array(40).fill("word").join(" ");
    expect(truncateIfLonger(words)).toBe(words);
  });

  it("truncates and adds ellipsis when word count exceeds 40", () => {
    const words = Array(50).fill("word").join(" ");
    const expected = Array(40).fill("word").join(" ") + "...";
    expect(truncateIfLonger(words)).toBe(expected);
  });

  it("handles empty string", () => {
    expect(truncateIfLonger("")).toBe("");
  });

  it("handles string with only whitespace", () => {
    // The function returns the original string when word count is below threshold
    expect(truncateIfLonger("   ")).toBe("   ");
  });

  it("handles string with extra whitespace between words", () => {
    const text = "word1   word2   word3";
    expect(truncateIfLonger(text)).toBe(text);
  });

  it("handles single word", () => {
    expect(truncateIfLonger("hello")).toBe("hello");
  });
});
