// Some portions generated by Co-Pilot
"use client";

import React, {
  useRef,
  RefObject,
  useState,
  useMemo,
  useCallback,
} from "react";
import { useTranslations } from "next-intl";
import {
  useFetchReleaseNotesForVersion,
  useOnScreen,
  ReleaseNoteAPIResponse,
} from "@/hooks";
import { useSearchParams } from "next/navigation";
import "./styles.css";

export const fetchTitle = (priority: string) => {
  let title;
  switch (priority) {
    case "1":
      title =
        "P1 - Blocks development and/or testing work, production could not run.";
      break;
    case "2":
      title = "P2 - Crashes, loss of data, severe memory leak.";
      break;
    case "3":
      title = "P3 - Major loss of function.";
      break;
    case "4":
      title =
        "P4 - Minor loss of function, or other problem where easy workaround is present.";
      break;
    case "5":
      title = "P5 - Cosmetic problem like misspelt words or misaligned text.";
      break;
    case "6":
      title = "This issue is not publicly visible.";
  }
  return title;
};

export const sortReleaseNotesBy = (releaseNotes: ReleaseNoteAPIResponse) => {
  // issues/1508: Should initially be sorted by (a) priority then (b) component.
  if (releaseNotes && Array.isArray(releaseNotes.release_notes)) {
    releaseNotes.release_notes = [...releaseNotes.release_notes].sort(
      (v1, v2) => {
        let c = 0;
        if (v1.priority && v2.priority) {
          c = v1.priority.localeCompare(v2.priority);
        }
        if (c === 0 && v1.component && v2.component) {
          c = v1.component.localeCompare(v2.component);
        }
        return c;
      },
    );
  }
  return releaseNotes;
};

type SortDirection = "asc" | "desc";

interface Filters {
  priority: string;
  type: string;
  component: string;
}

const ReleaseNotesRender = () => {
  const t = useTranslations("ReleaseNotes");
  const searchParams = useSearchParams();
  const rawVersion = searchParams.get("version");
  const version = rawVersion ? rawVersion.replace(/ /g, "+") : undefined;

  const ref = useRef<HTMLDivElement | null>(null);
  const isVisible = useOnScreen(ref as RefObject<Element>, true);

  const releaseNoteDataBag = useFetchReleaseNotesForVersion(
    isVisible,
    version,
    sortReleaseNotesBy,
  );
  const releaseNotes = releaseNoteDataBag
    ? releaseNoteDataBag.releaseNoteAPIResponse
    : null;
  const releaseNotesVersion = releaseNotes ? releaseNotes.release_name : null;

  const [page, setPage] = useState(0);
  const [pageSize, setPageSize] = useState(20);
  const [sortDirection, setSortDirection] = useState<SortDirection>("asc");
  const [filters, setFilters] = useState<Filters>({
    priority: "",
    type: "",
    component: "",
  });

  // Set default type filter for jdk-xx+xx versions
  const regex = /^jdk-(2\d|\d{3,})\+\d+$/;
  const isEnhancementDefault = releaseNotesVersion?.toString
    ? regex.test(releaseNotesVersion.toString())
    : false;

  // Normalise undefined priorities to "6"
  if (releaseNotes && Array.isArray(releaseNotes.release_notes)) {
    releaseNotes.release_notes.forEach((note) => {
      if (note.priority === undefined || note.priority === null) {
        (note as { priority: string }).priority = "6";
      }
    });
  }

  // Unique values for filter dropdowns
  const { priorities, types, components } = useMemo(() => {
    const p = new Set<string>();
    const ty = new Set<string>();
    const c = new Set<string>();
    if (releaseNotes?.release_notes) {
      releaseNotes.release_notes.forEach((note) => {
        if (note.priority) p.add(note.priority);
        if (note.type) ty.add(note.type);
        if (note.component) c.add(note.component);
      });
    }
    return {
      priorities: [...p].sort(),
      types: [...ty].sort(),
      components: [...c].sort(),
    };
  }, [releaseNotes]);

  // Filter → sort → paginate
  const processedRows = useMemo(() => {
    if (!releaseNotes?.release_notes) return [];
    let rows = [...releaseNotes.release_notes];

    const activeTypeFilter =
      filters.type || (isEnhancementDefault ? "Enhancement" : "");
    if (filters.priority)
      rows = rows.filter((r) => r.priority === filters.priority);
    if (activeTypeFilter)
      rows = rows.filter((r) => r.type === activeTypeFilter);
    if (filters.component)
      rows = rows.filter((r) => r.component === filters.component);

    rows.sort((a, b) => {
      const aVal = a.priority || "";
      const bVal = b.priority || "";
      const cmp = aVal.localeCompare(bVal);
      return sortDirection === "asc" ? cmp : -cmp;
    });

    return rows;
  }, [releaseNotes, filters, sortDirection, isEnhancementDefault]);

  const totalRows = processedRows.length;
  const totalPages = Math.max(1, Math.ceil(totalRows / pageSize));
  const safePage = Math.min(page, totalPages - 1);
  const paginatedRows = processedRows.slice(
    safePage * pageSize,
    (safePage + 1) * pageSize,
  );

  const updateFilter = (field: keyof Filters, value: string) => {
    setFilters((prev) => ({ ...prev, [field]: value }));
    setPage(0);
  };

  const handleExport = useCallback(() => {
    const header = "Priority,Type,Component,Issue,Title\n";
    const csv = processedRows
      .map(
        (r) =>
          `"${r.priority || ""}","${r.type || ""}","${r.component || ""}","${r.id}","${(r.title || "").replace(/"/g, '""')}"`,
      )
      .join("\n");
    const blob = new Blob([header + csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `release-notes-${releaseNotesVersion}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }, [processedRows, releaseNotesVersion]);

  const toggleSort = () => {
    setSortDirection((prev) => (prev === "asc" ? "desc" : "asc"));
  };

  const totalP1 = releaseNotes?.release_notes?.filter(
    (note) => note.priority === "1",
  ).length;

  return (
    <div
      ref={ref}
      className="release-notes-container mx-auto w-full max-w-5xl px-6 lg:px-0 pb-20 pt-2"
    >
      {/* Version title */}
      <div className="text-center mb-10">
        <h2 className="text-[42px] font-semibold tracking-tight text-white mb-1">
          {releaseNotesVersion}
        </h2>
      </div>

      <div className="w-full">
        {!releaseNoteDataBag ? (
          <div className="flex items-center justify-center py-32">
            <div className="flex flex-col items-center gap-4">
              <div
                className="h-8 w-8 rounded-full border-2 border-white/10 border-t-pink animate-spin"
                aria-label="loading spinner"
              />
              <span className="text-sm text-white/30 tracking-wide">
                Loading release notes…
              </span>
            </div>
          </div>
        ) : (
          <div className="w-full">
            {!releaseNotesVersion || releaseNoteDataBag?.isValid === false ? (
              <div className="rounded-2xl bg-white/[0.04] backdrop-blur-xl border border-white/[0.08] p-12 text-center">
                <h2 className="text-2xl font-semibold text-white tracking-tight mb-3">
                  {t("couldnt-find-release-notes")}
                </h2>
                <span className="text-white/50 text-base">
                  {t("not-found-helper")}{" "}
                  <code className="bg-white/[0.06] px-2 py-1 rounded-md text-pink text-sm font-mono">
                    ?version=x.x.x
                  </code>
                </span>
              </div>
            ) : (
              <>
                {/* Description + stats */}
                <div className="text-center mb-10 max-w-2xl mx-auto">
                  <p className="text-base text-white/50 leading-relaxed mb-4">
                    {t("description")}
                  </p>
                  <div className="inline-flex items-center gap-2 rounded-full bg-white/[0.04] border border-white/[0.08] px-4 py-1.5">
                    <span className="w-2 h-2 rounded-full bg-pink/80" />
                    <span className="text-sm text-white/60">
                      <span className="font-medium text-white/80">
                        {totalP1}
                      </span>{" "}
                      P1 fixes
                    </span>
                  </div>
                </div>

                {/* Toolbar */}
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-6">
                  <div className="flex items-center gap-2 flex-wrap">
                    <select
                      aria-label="Filter by priority"
                      value={filters.priority}
                      onChange={(e) => updateFilter("priority", e.target.value)}
                      className="appearance-none bg-white/[0.04] text-white/70 text-sm border border-white/[0.08] rounded-lg px-3 py-2 focus:outline-none focus:border-white/20 focus:bg-white/[0.06] transition-all duration-200 cursor-pointer"
                    >
                      <option value="">All Priorities</option>
                      {priorities.map((p) => (
                        <option key={p} value={p}>
                          P{p !== "6" ? p : "?"}
                        </option>
                      ))}
                    </select>
                    <select
                      aria-label="Filter by type"
                      value={
                        filters.type ||
                        (isEnhancementDefault ? "Enhancement" : "")
                      }
                      onChange={(e) => updateFilter("type", e.target.value)}
                      className="appearance-none bg-white/[0.04] text-white/70 text-sm border border-white/[0.08] rounded-lg px-3 py-2 focus:outline-none focus:border-white/20 focus:bg-white/[0.06] transition-all duration-200 cursor-pointer"
                    >
                      <option value="">All Types</option>
                      {types.map((ty) => (
                        <option key={ty} value={ty}>
                          {ty}
                        </option>
                      ))}
                    </select>
                    <select
                      aria-label="Filter by component"
                      value={filters.component}
                      onChange={(e) =>
                        updateFilter("component", e.target.value)
                      }
                      className="appearance-none bg-white/[0.04] text-white/70 text-sm border border-white/[0.08] rounded-lg px-3 py-2 focus:outline-none focus:border-white/20 focus:bg-white/[0.06] transition-all duration-200 cursor-pointer"
                    >
                      <option value="">All Components</option>
                      {components.map((c) => (
                        <option key={c} value={c}>
                          {c}
                        </option>
                      ))}
                    </select>
                  </div>
                  <button
                    onClick={handleExport}
                    className="text-sm font-medium text-white/50 hover:text-white bg-white/[0.04] border border-white/[0.08] rounded-lg px-4 py-2 hover:bg-white/[0.08] hover:border-white/[0.14] transition-all duration-200"
                  >
                    Export CSV
                  </button>
                </div>

                {/* Table */}
                <div className="overflow-x-auto rounded-2xl border border-white/[0.08] bg-white/[0.02] backdrop-blur-xl">
                  <table
                    className="w-full text-left"
                    aria-label="Release Notes"
                  >
                    <thead>
                      <tr className="border-b border-white/[0.08]">
                        <th
                          className="px-5 py-3.5 text-white/40 font-medium text-xs tracking-wider uppercase cursor-pointer select-none hover:text-white/70 transition-colors duration-200 w-[100px]"
                          onClick={toggleSort}
                        >
                          Priority{" "}
                          <span className="text-white/20">
                            {sortDirection === "asc" ? "\u25B2" : "\u25BC"}
                          </span>
                        </th>
                        <th className="px-5 py-3.5 text-white/40 font-medium text-xs tracking-wider uppercase w-[120px]">
                          Type
                        </th>
                        <th className="px-5 py-3.5 text-white/40 font-medium text-xs tracking-wider uppercase w-[160px]">
                          Component
                        </th>
                        <th className="px-5 py-3.5 text-white/40 font-medium text-xs tracking-wider uppercase w-[130px]">
                          Issue
                        </th>
                        <th className="px-5 py-3.5 text-white/40 font-medium text-xs tracking-wider uppercase min-w-[300px]">
                          Title
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {paginatedRows.map((row, idx) => (
                        <tr
                          key={row.id}
                          data-row
                          className={`border-b border-white/[0.04] transition-colors duration-150 hover:bg-white/[0.04] ${
                            idx % 2 === 0 ? "" : "bg-white/[0.01]"
                          }`}
                        >
                          <td data-field="priority" className="px-5 py-3.5">
                            <span
                              title={fetchTitle(
                                (row.priority as string) || "6",
                              )}
                              className={`badge priority-${row.priority}`}
                            >
                              {row.priority && row.priority !== "6"
                                ? `P${row.priority}`
                                : "P?"}
                            </span>
                          </td>
                          <td
                            data-field="type"
                            className="px-5 py-3.5 text-white/60 text-sm"
                          >
                            {row.type || "Hidden"}
                          </td>
                          <td
                            data-field="component"
                            className="px-5 py-3.5 text-white/60 text-sm"
                          >
                            {row.component || ""}
                          </td>
                          <td data-field="id" className="px-5 py-3.5">
                            <a
                              target="_blank"
                              rel="noopener noreferrer"
                              href={String(row.link || "")}
                              className="issue-link"
                            >
                              {row.id}
                            </a>
                          </td>
                          <td
                            data-field="title"
                            className="px-5 py-3.5 text-white/70 text-sm leading-relaxed break-words"
                          >
                            {row.title}
                          </td>
                        </tr>
                      ))}
                      {paginatedRows.length === 0 && (
                        <tr>
                          <td
                            colSpan={5}
                            className="px-5 py-16 text-center text-white/30 text-sm"
                          >
                            No results found
                          </td>
                        </tr>
                      )}
                    </tbody>
                  </table>
                </div>

                {/* Pagination */}
                <div className="flex items-center justify-between gap-4 mt-4 px-1">
                  <div className="flex items-center gap-2 text-sm text-white/40">
                    <span>Rows</span>
                    <select
                      value={pageSize}
                      onChange={(e) => {
                        setPageSize(Number(e.target.value));
                        setPage(0);
                      }}
                      className="appearance-none bg-white/[0.04] text-white/60 border border-white/[0.08] rounded-lg px-2 py-1 text-sm focus:outline-none focus:border-white/20 transition-all duration-200 cursor-pointer"
                    >
                      {[20, 50, 75].map((size) => (
                        <option key={size} value={size}>
                          {size}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="flex items-center gap-4 text-sm text-white/40">
                    <span>
                      {totalRows > 0
                        ? `${safePage * pageSize + 1}\u2013${Math.min((safePage + 1) * pageSize, totalRows)} of ${totalRows}`
                        : "0 of 0"}
                    </span>
                    <div className="flex items-center gap-1">
                      <button
                        onClick={() => setPage((p) => Math.max(0, p - 1))}
                        disabled={safePage === 0}
                        className="w-8 h-8 flex items-center justify-center rounded-lg bg-white/[0.04] border border-white/[0.06] hover:bg-white/[0.08] disabled:opacity-25 disabled:cursor-not-allowed transition-all duration-200 text-white/60"
                      >
                        &lsaquo;
                      </button>
                      <button
                        onClick={() =>
                          setPage((p) => Math.min(totalPages - 1, p + 1))
                        }
                        disabled={safePage >= totalPages - 1}
                        className="w-8 h-8 flex items-center justify-center rounded-lg bg-white/[0.04] border border-white/[0.06] hover:bg-white/[0.08] disabled:opacity-25 disabled:cursor-not-allowed transition-all duration-200 text-white/60"
                      >
                        &rsaquo;
                      </button>
                    </div>
                  </div>
                </div>
              </>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default ReleaseNotesRender;
