// Some portions generated by Co-Pilot
= Support pour les Premiers Contributeurs d'Eclipse Adoptium(R)
:page-authors: MBoegers, hendrikebbers, gdams, tellison, Ndacyayisenga-droid
:page-based-on: 0e4cf731021aa6b80ca14281a511b2ce0584a64c
:description: Aide pour les premières contributions
:keywords: adoptium documentation contribuer première-fois
:icons: font


Chez Adoptium, nous voulons aider les gens à se lancer dans l'Open Source, Java et la communauté Java.
Il est donc très important pour nous de fournir de l'aide aux personnes qui souhaitent commencer à travailler sur des projets open source.

[NOTE]
====
Cette documentation est encore en cours d'élaboration et certains points mentionnés sont des idées pour l'avenir qui n'ont pas encore été mises en place.
====

Adoptium propose plusieurs issues étiquetées comme https://github.com/orgs/adoptium/projects/[good first issue].
Toutes ces issues sont parfaites pour commencer à travailler sur un projet open source.
Les issues fournissent des descriptions conviviales et de nombreux liens utiles vers des documentations et tutoriels pour commencer directement à travailler sur une issue.
Même si vous n'êtes pas vraiment familier avec GitHub en général, les issues renvoient vers des tutoriels conviviaux qui vous aideront à
comprendre les workflows des forks et des pull requests.

Vous pouvez trouver https://github.com/AdoptOpenJDK/IcedTea-Web/issues/706[un exemple de **`good first issue`** dans le dépôt IcedTea-Web].

Sur GitHub, vous pouvez trouver https://github.com/issues?q=org%3AAdoptium+label%3A%22good+first+issue%22+is%3Aopen[une liste de toutes les issues étiquetées **`good first issue`**].

== Modèles

Nous travaillons actuellement sur un modèle d'issue pour les issues étiquetées comme https://github.com/orgs/adoptium/projects/[good first issue].
https://gist.github.com/hendrikebbers/8e4dec9ddea5e2a420080d1314af025f[La version actuelle du modèle d'issue] et
https://gist.github.com/hendrikebbers/0f9cdd18076343b3bbe5f2d162733b6e[une section sur le « Support pour les premiers contributeurs » pour les fichiers contributing.md]
sont actuellement en développement.

== Workflow pour créer des good first issues

Chaque fois que vous estimez qu'une issue pourrait être une https://github.com/orgs/adoptium/projects/[good first issue], vous devriez l'étiqueter avec le label **`good first issue - candidate`**.
Ce faisant, elle pourra être examinée et modifiée pour devenir une https://github.com/orgs/adoptium/projects/[good first issue].

Sur GitHub, vous pouvez trouver https://github.com/issues?q=org%3AAdoptium+label%3A%22good+first+issue+-+candidate%22+is%3Aopen[une liste de toutes les issues étiquetées **`good first issue - candidate`**].

Toutes les issues étiquetées **`good first issue - candidate`** doivent être examinées et éventuellement remaniées pour devenir des issues étiquetées https://github.com/orgs/adoptium/projects/[good first issue].
Les règles suivantes doivent être appliquées :

- Le titre de l'issue doit spécifier le problème
- La description de l'issue doit être basée sur https://gist.github.com/hendrikebbers/0f9cdd18076343b3bbe5f2d162733b6e[notre modèle **`good first issue`**]
- L'issue ne devrait pas contenir de commentaires. Les commentaires rendent déjà la compréhension plus difficile pour un débutant.
Toutes les informations pertinentes dans les commentaires doivent être ajoutées à la description de l'issue.
Les commentaires doivent être supprimés par la suite.
Si cela n'est pas possible, la meilleure solution est de créer une nouvelle issue pour la https://github.com/orgs/adoptium/projects/[good first issue], de la lier à l'originale, et de fermer l'originale.
- Lors de la définition de la description de l'issue, il est toujours judicieux de renvoyer vers des documentations ou des fichiers utiles (peut-être même directement vers le code)
pour aider un nouveau contributeur à trouver le bon point de départ pour travailler sur l'issue.

Une fois l'issue remaniée et examinée, elle doit être étiquetée comme https://github.com/orgs/adoptium/projects/[good first issue] et le label **`good first issue - candidate`** doit être retiré.
De plus, nous devons étiqueter toutes ces issues avec **`help wanted`** et **`Hacktoberfest`**.

== Liens et Ressources

- https://github.com/issues?q=org%3AAdoptium+label%3A%22good+first+issue%22+is%3Aopen[Liste de toutes les issues étiquetées **`good first issue`**]
- https://github.com/issues?q=org%3AAdoptium+label%3A%22good+first+issue+-+candidate%22+is%3Aopen[Liste de toutes les issues étiquetées **`good first issue - candidate`**]
- https://gist.github.com/hendrikebbers/8e4dec9ddea5e2a420080d1314af025f[Version actuelle du modèle d'issue]
- https://gist.github.com/hendrikebbers/0f9cdd18076343b3bbe5f2d162733b6e[Version actuelle d'une section sur le « Support pour les premiers contributeurs » pour les fichiers contributing.md]
- https://github.com/AdoptOpenJDK/IcedTea-Web/issues/706[Un exemple de **`good first issue`**]
