// Some portions generated by Co-Pilot
import React from "react";
import { render, cleanup, act, fireEvent } from "@testing-library/react";
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import SudoToggle, { stripSudo, containsSudo } from "../index";

// Mock Prism so highlightElement is a no-op
vi.mock("prismjs", () => ({
  default: {
    highlightElement: vi.fn(),
  },
}));

// ─── Unit tests for pure functions ───

describe("stripSudo", () => {
  it("removes sudo at the start of a line", () => {
    expect(stripSudo("sudo apt install foo")).toBe("apt install foo");
  });

  it("removes sudo from multiple lines", () => {
    const input = "sudo apt update\nsudo apt install temurin-21-jdk";
    const expected = "apt update\napt install temurin-21-jdk";
    expect(stripSudo(input)).toBe(expected);
  });

  it("removes sudo with leading whitespace", () => {
    expect(stripSudo("  sudo dnf install foo")).toBe("  dnf install foo");
  });

  it("converts | sudo tee to | tee", () => {
    const input =
      'echo "deb ..." | sudo tee /etc/apt/sources.list.d/adoptium.list';
    const expected =
      'echo "deb ..." | tee /etc/apt/sources.list.d/adoptium.list';
    expect(stripSudo(input)).toBe(expected);
  });

  it("handles both sudo prefix and sudo tee in same text", () => {
    const input =
      "sudo apt install wget\nwget -qO - url | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null";
    const expected =
      "apt install wget\nwget -qO - url | gpg --dearmor | tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null";
    expect(stripSudo(input)).toBe(expected);
  });

  it("does not modify text without sudo", () => {
    const input = "echo hello\nls -la";
    expect(stripSudo(input)).toBe(input);
  });

  it("does not strip sudo from middle of a line (not at start)", () => {
    // "run sudo thing" — sudo is not at start of line
    expect(stripSudo("run sudo thing")).toBe("run sudo thing");
  });
});

describe("containsSudo", () => {
  it("returns true for line-start sudo", () => {
    expect(containsSudo("sudo apt install foo")).toBe(true);
  });

  it("returns true for sudo on second line", () => {
    expect(containsSudo("echo hello\nsudo dnf install bar")).toBe(true);
  });

  it("returns true for | sudo tee", () => {
    expect(
      containsSudo('echo "x" | sudo tee /etc/apt/sources.list.d/a.list'),
    ).toBe(true);
  });

  it("returns false for text without sudo", () => {
    expect(containsSudo("apt install foo")).toBe(false);
  });

  it("returns false for sudo only in middle of line", () => {
    expect(containsSudo("please run sudo later")).toBe(false);
  });

  it("returns false for empty string", () => {
    expect(containsSudo("")).toBe(false);
  });
});

// ─── DOM integration tests ───

describe("SudoToggle component", () => {
  beforeEach(() => {
    vi.useFakeTimers();
    // Clean up any injected style tags
    document.getElementById("sudo-tab-styles")?.remove();
  });

  afterEach(() => {
    vi.useRealTimers();
    cleanup();
    document.body.innerHTML = "";
    document.getElementById("sudo-tab-styles")?.remove();
  });

  /** Helper: build the doc-content DOM that SudoToggle scans */
  function setupCodeBlock(text: string, lang = "language-bash") {
    const article = document.createElement("article");
    article.className = "doc-content";

    const pre = document.createElement("pre");
    pre.className = "highlight";

    const code = document.createElement("code");
    code.className = lang;
    code.textContent = text;

    pre.appendChild(code);
    article.appendChild(pre);
    document.body.appendChild(article);

    return { article, pre, code };
  }

  it("renders nothing (returns null)", () => {
    const { container } = render(<SudoToggle />);
    expect(container.innerHTML).toBe("");
  });

  it("injects tab bars above bash code blocks with sudo", () => {
    setupCodeBlock("sudo apt install foo");

    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    const tabBars = document.querySelectorAll(".sudo-tab-bar");
    expect(tabBars).toHaveLength(1);

    const buttons = tabBars[0].querySelectorAll("button");
    expect(buttons).toHaveLength(2);
    expect(buttons[0].textContent).toBe("user");
    expect(buttons[1].textContent).toBe("root");
  });

  it("does not inject tabs for code blocks without sudo", () => {
    setupCodeBlock("echo hello world");

    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    const tabBars = document.querySelectorAll(".sudo-tab-bar");
    expect(tabBars).toHaveLength(0);
  });

  it("does not inject tabs for non-bash code blocks", () => {
    setupCodeBlock("sudo apt install foo", "language-java");

    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    const tabBars = document.querySelectorAll(".sudo-tab-bar");
    expect(tabBars).toHaveLength(0);
  });

  it("clicking root strips sudo from code", () => {
    const { code } = setupCodeBlock("sudo apt install foo");

    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    const rootBtn = document.querySelectorAll(
      ".sudo-tab-btn",
    )[1] as HTMLButtonElement;
    fireEvent.click(rootBtn);

    expect(code.textContent).toBe("apt install foo");
  });

  it("clicking user restores sudo", () => {
    const { code } = setupCodeBlock("sudo apt install foo");

    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    const buttons = document.querySelectorAll(".sudo-tab-btn");
    const userBtn = buttons[0] as HTMLButtonElement;
    const rootBtn = buttons[1] as HTMLButtonElement;

    // Switch to root first
    fireEvent.click(rootBtn);
    expect(code.textContent).toBe("apt install foo");

    // Switch back to user
    fireEvent.click(userBtn);
    expect(code.textContent).toBe("sudo apt install foo");
  });

  it("syncs all code blocks when clicking any tab", () => {
    setupCodeBlock("sudo apt install foo");
    // Add a second code block
    const article = document.querySelector(".doc-content")!;
    const pre2 = document.createElement("pre");
    pre2.className = "highlight";
    const code2 = document.createElement("code");
    code2.className = "language-bash";
    code2.textContent = "sudo dnf install bar";
    pre2.appendChild(code2);
    article.appendChild(pre2);

    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    // Click root on the first block's tab
    const firstRootBtn = document
      .querySelectorAll(".sudo-tab-bar")[0]
      .querySelectorAll(".sudo-tab-btn")[1] as HTMLButtonElement;
    fireEvent.click(firstRootBtn);

    // Both should be stripped
    const codes = document.querySelectorAll(".doc-content pre code");
    expect(codes[0].textContent).toBe("apt install foo");
    expect(codes[1].textContent).toBe("dnf install bar");

    // All root tabs should be active, user tabs inactive
    const tabBars = document.querySelectorAll(".sudo-tab-bar");
    tabBars.forEach((bar) => {
      const btns = bar.querySelectorAll(".sudo-tab-btn");
      expect(btns[0].classList.contains("active")).toBe(false); // user
      expect(btns[1].classList.contains("active")).toBe(true); // root
    });
  });

  it("does not double-process blocks", () => {
    setupCodeBlock("sudo apt install foo");

    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    // Render again (simulating re-mount)
    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    // Should still only have one tab bar
    const tabBars = document.querySelectorAll(".sudo-tab-bar");
    expect(tabBars).toHaveLength(1);
  });

  it("injects CSS styles into head only once", () => {
    setupCodeBlock("sudo apt install foo");

    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    const styles = document.querySelectorAll("#sudo-tab-styles");
    expect(styles).toHaveLength(1);
  });

  it("sets borderTopLeftRadius and borderTopRightRadius to 0 on pre", () => {
    const { pre } = setupCodeBlock("sudo apt install foo");

    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    expect(pre.style.borderTopLeftRadius).toBe("0px");
    expect(pre.style.borderTopRightRadius).toBe("0px");
  });

  it("inserts tab bar before .group wrapper when present", () => {
    const article = document.createElement("article");
    article.className = "doc-content";

    const listingBlock = document.createElement("div");
    listingBlock.className = "listingblock";

    const groupWrapper = document.createElement("div");
    groupWrapper.className = "group relative";

    const pre = document.createElement("pre");
    pre.className = "highlight";
    const code = document.createElement("code");
    code.className = "language-bash";
    code.textContent = "sudo apt install foo";
    pre.appendChild(code);

    groupWrapper.appendChild(pre);
    listingBlock.appendChild(groupWrapper);
    article.appendChild(listingBlock);
    document.body.appendChild(article);

    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    // Tab bar should be a sibling before the group wrapper, not inside it
    const tabBar = document.querySelector(".sudo-tab-bar");
    expect(tabBar).toBeTruthy();
    expect(tabBar!.nextElementSibling).toBe(groupWrapper);
  });

  it("handles | sudo tee correctly", () => {
    const { code } = setupCodeBlock(
      'echo "deb ..." | sudo tee /etc/apt/sources.list.d/adoptium.list',
    );

    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    const rootBtn = document.querySelectorAll(
      ".sudo-tab-btn",
    )[1] as HTMLButtonElement;
    fireEvent.click(rootBtn);

    expect(code.textContent).toBe(
      'echo "deb ..." | tee /etc/apt/sources.list.d/adoptium.list',
    );
  });

  it("user tab has active class by default", () => {
    setupCodeBlock("sudo apt install foo");

    render(<SudoToggle />);
    act(() => {
      vi.advanceTimersByTime(400);
    });

    const buttons = document.querySelectorAll(".sudo-tab-btn");
    expect(buttons[0].classList.contains("active")).toBe(true);
    expect(buttons[1].classList.contains("active")).toBe(false);
  });
});
