= Install Eclipse Temurin(TM)
:page-authors: gdams, karianna, tellison

link:/temurin/releases[Eclipse Temurin] is available for download in multiple
installation package formats:

* Package managers (shown above)
* link:#_installers[Installers]
* link:https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc[Programmatic API]
* link:/installation/archives[Archive files]
* link:https://hub.docker.com/_/eclipse-temurin[Container Images] (External documentation at DockerHub)

The binaries are supported on the architectures and operating systems
listed in link:/supported-platforms[Supported Platforms]. If you’re
migrating to Temurin, you can learn about the differences between Oracle
JDK and Temurin in our link:/docs/migration[Migration Guide] and any steps
that you might need to take.

== Installers

Installers are currently available for Windows(R) and macOS(R) JDK and JRE
packages. Installation steps are covered in the following sections:

* link:/installation/windows[Windows MSI installers packages]
* link:/installation/macOS[macOS PKG installer packages]
* link:/installation/linux[Linux (RPM/DEB/APK) installer packages]

__________________________________________________________________________________________________________________________

# The commit needs to come from the adoptium team, as I'm not a coder, but I figured some installation instructions out...
# For Ubuntu/Linux Mint, Ubuntu 24.04 LTS "Noble"

apt install -y wget apt-transport-https gpg
wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null
echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^UBUNTU_CODENAME/{print$2}' /etc/os-release) main" | sudo tee /etc/apt/sources.list.d/adoptium.list
sudo apt-get update
sudo apt-get install temurin-21-jdk

# In line 33, sudo had to be in front of the tee command
# In line 34, sudo had to be in front of the tee command
