// Some portions generated by Co-Pilot
import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import NewsEmptyState from "../index";

// Mock authors utility
vi.mock("@/utils/authors", () => ({
  getFormattedAuthorData: (authorId: string) => {
    if (authorId === "pmc") return { name: "PMC Author" };
    return { name: "Unknown Author" };
  },
}));

describe("NewsEmptyState", () => {
  it("renders 'No results found' heading", () => {
    render(<NewsEmptyState />);
    const headings = screen.getAllByText("No results found");
    expect(headings.length).toBeGreaterThan(0);
  });

  it("renders filter adjustment suggestion", () => {
    render(<NewsEmptyState />);
    const suggestions = screen.getAllByText("Try adjusting or clearing your filters.");
    expect(suggestions.length).toBeGreaterThan(0);
  });

  it("displays tag filter when provided", () => {
    render(<NewsEmptyState tag="java" />);
    const tags = screen.getAllByText("Tag: java");
    expect(tags.length).toBeGreaterThan(0);
  });

  it("displays formatted author name when provided", () => {
    render(<NewsEmptyState author="pmc" />);
    const authors = screen.getAllByText("Author: PMC Author");
    expect(authors.length).toBeGreaterThan(0);
  });

  it("displays formatted source name when provided", () => {
    render(<NewsEmptyState source="eclipse-news" />);
    const sources = screen.getAllByText("Source: Eclipse News");
    expect(sources.length).toBeGreaterThan(0);
  });

  it("displays all filters when all are provided", () => {
    render(<NewsEmptyState tag="java" author="pmc" source="adoptium" />);
    expect(screen.getAllByText("Tag: java").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Author: PMC Author").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Source: Adoptium").length).toBeGreaterThan(0);
  });

  it("does not display filter badges when no filters provided", () => {
    const { container } = render(<NewsEmptyState />);
    // When no filters are provided, there should be no filter badge spans
    // The container doesn't include Tag:/Author:/Source: prefixed spans
    const filterBadges = container.querySelectorAll("span.px-3");
    expect(filterBadges.length).toBe(0);
  });
});
