// Some portions generated by Co-Pilot
= 移行ガイド
:page-authors: gdams, karianna, SueChaplain, hendrikebbers, sxa, ParkerM, jiekang, HanSolo, MBoegers, ojuschugh1, adamfarley
:page-based-on: 5dc3e35770a9fd824dde93556a52db47d0896bb3
:page-keywords: java, jdk, oracle, temurin, openjdk, eclipse
:icons: font

== Eclipse Temurin への移行

Oracle JDK から Adoptium プロジェクトの OpenJDK に移行する場合、いくつかの重要な疑問があるかと思います。まず、Oracle JDK と Temurin の違い、および移行に必要な手順を確認したいことでしょう。これらの選択に関するよくある質問への回答を以下のセクションで説明します。

== Oracle JDK からの移行

以下の表は Oracle JDK 8 に存在する独自コンポーネントと、それらを置き換えるために計画または提供されている代替テクノロジーを示しています。各コンポーネントとその採用に必要な手順の詳細についてはリンクをクリックしてください。

icon:check[] - サポート済み、icon:times[] - 非サポート
[cols="35%,25%,20%,20%",options="header",]
|=======================================================================
|Oracle JDK 8 独自コンポーネント |代替コンポーネント |OpenJDK 8 |OpenJDK 11 以降
|Java Web Start |link:#_icedtea_web[IcedTea-Web] | icon:check[] |  icon:times[]   
|JavaFX |link:#_openjfx[OpenJFX] |  icon:times[]    |  icon:check[]  
|T2K フォントレンダリングエンジン
|link:#_freetype_font_rendering_library[Freetype] |  icon:check[]   |  icon:check[]  
|Monotype Lucida フォント |link:#_relicensed_lucida_fonts[再ライセンスされた Lucida フォント] |  icon:times[]    (近日公開) |  icon:times[]    (近日公開)
|Ductus 2D レンダラー |link:#_pisces_and_marlin[Pisces/Marlin] |  icon:check[]   (Pisces)
|  icon:check[]   (Marlin)
|Kodac Color Matching System (KCMS) ライブラリ |link:#_lcms[LCMS] |  icon:check[]   |  icon:check[]  
|SNMP |link:#_jmx[JMX]（または SNMP4J）を使用 |  icon:check[]   (バンドルなし) |  icon:check[]   (バンドルなし)
|サウンドドライバー |link:#_windows_sound_drivers[Windows サウンドドライバー]を使用
|  icon:check[]   (バンドルなし) |  icon:check[]   (バンドルなし)
|Java Flight Recorder (JFR) |link:#_java_flight_recorder[Java Flight Recorder] |  icon:check[]   |  icon:check[]  
|Java Mission Control (JMC) |link:#_eclipse_mission_control[Eclipse Mission Control] を使用 |  icon:check[]   |  icon:check[]  
|=======================================================================

[#_icedtea_web]
=== IcedTea-Web

Java Web Start は Oracle によって Java SE 8 で非推奨となり、Java SE 9 で削除されました。IcedTea-Web は Temurin 8 ユーザーに同等の機能を提供できます。

IcedTea-Web は https://adoptopenjdk.net/icedtea-web.html[IcedTea-Web プロジェクトページ]から Linux、Windows、macOS、ポータブルパッケージ形式でダウンロードできます。

Java Web Start と同じ方法で IcedTea-Web を使用します。詳細については、https://docs.oracle.com/javase/tutorial/deployment/webstart/developing.html[Java Web Start アプリケーションの開発]および https://docs.oracle.com/javase/tutorial/deployment/webstart/deploying.html[Java Web Start アプリケーションのデプロイ]をご覧ください。IcedTea-Web は Java Web Start と同様に動作するように設計されていますが、いくつかの既知の違いがあり、https://github.com/AdoptOpenJDK/icedtea-web[GitHub プロジェクト]に問題として報告されています。これらの違いを最小化または排除するための取り組みが継続されています。

IcedTea-Web 1.8.x および 2.0.x は Temurin 8 ビルドと互換性があります。IcedTea-Web に基づくソフトウェアが OpenJDK 11 以降に基づく JNLP アプリケーションの実行をサポートすることは知られていますが、IcedTea-Web は OpenJDK 11 以降のサポートを確認するテストを含んでおらず、Temurin 11 ビルドにはバンドルされていません。

[#_openjfx]
=== OpenJFX

2017 年に、JavaFX は Oracle JDK から切り離され OpenJDK コミュニティに提供されました。OpenJFX コミュニティは OpenJFX 11+ に注力しており、Temurin とともに使用できるバイナリを提供しています。

OpenJFX 8 はアクティブなメンテナンスが終了しています。この機能が必要な場合は OpenJFX 11 へのアップグレードをお勧めします。

[#_freetype_font_rendering_library]
=== Freetype フォントレンダリングライブラリ

OpenJDK は独自の T2K フォントライブラリの代わりにオープンソースの FreeType フォントレンダリングライブラリを使用しています。

[#_relicensed_lucida_fonts]
=== 再ライセンスされた Lucida フォント

Oracle JDK 8 で利用可能な Lucida フォントは独自のサードパーティライセンスを持っています。Adoptium は再ライセンスされた Lucida フォントを提供する予定です。これらのフォントが Freetype によってレンダリングされる際の表示問題を最小化するための取り組みが継続されています。

[#_pisces_and_marlin]
=== Pisces と Marlin

Oracle JDK 8 は Ductus という独自の 2D グラフィックスレンダラーを使用しているのに対し、OpenJDK は Pisces というオープンソースレンダラーを使用しています。OpenJDK 9 からは Marlin レンダラーが使用されています。Adoptium では Marlin を OpenJDK 8 にバックポートしたり、2 つのレンダラー間の表示問題を最小化する取り組みが計画されています。

[#_lcms]
=== LCMS

OpenJDK は独自の Kodac CMS ライブラリの代わりに Little Color Matching System（LCMS）オープンソースライブラリを使用しています。

[#_jmx]
=== JMX

Oracle JDK 8 に同梱されている独自の SNMP パッケージは OpenJDK には存在しません。代替として JMX または SNMP4J を使用してください。これらのパッケージは Temurin バイナリにはバンドルされていません。

[#_windows_sound_drivers]
=== Windows サウンドドライバー

Oracle JDK は Windows 上の Java 8 にネイティブサウンドドライバーを提供していますが、これらは OpenJDK には存在しません。代わりに Microsoft Windows で利用可能なサウンドドライバーを使用してください。

[#_java_flight_recorder]
=== Java Flight Recorder

Java Flight Recorder（JFR）は Oracle JDK から切り離され OpenJDK コミュニティに提供されました。JFR はすべてのバージョンの Temurin に含まれています。

[#_eclipse_mission_control]
=== Eclipse Mission Control

https://projects.eclipse.org/projects/adoptium.mc[Eclipse Mission Control] プロジェクトは link:/jmc[ダウンロードページ]から利用可能な JMC のダウンロードを提供しています。
