// Some portions generated by Co-Pilot
import { describe, it, expect, vi, beforeEach } from "vitest";
import axios from "axios";
import { fetchLatestEvents } from "../fetchLatestEvents";

vi.mock("axios");
const mockedAxios = vi.mocked(axios);

describe("fetchLatestEvents", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("fetches events from the Eclipse newsroom API", async () => {
    const mockEvents = [
      { id: "1", title: "Event 1", infoLink: "https://example.com", date: "2024-01-01" },
      { id: "2", title: "Event 2", infoLink: "https://example.com", date: "2024-02-01" },
    ];

    mockedAxios.get.mockResolvedValue({
      data: { events: mockEvents },
    });

    const result = await fetchLatestEvents();

    expect(mockedAxios.get).toHaveBeenCalledTimes(1);
    const calledUrl = mockedAxios.get.mock.calls[0][0];
    expect(calledUrl).toContain("https://newsroom.eclipse.org/api/events");
    expect(calledUrl).toContain("parameters%5Bpublish_to%5D=adoptium");
    expect(calledUrl).toContain("pagesize=20");
    expect(result).toEqual(mockEvents);
  });

  it("returns empty array on API error", async () => {
    mockedAxios.get.mockRejectedValue(new Error("Network error"));

    const result = await fetchLatestEvents();
    expect(result).toEqual([]);
  });
});
