// Some portions generated by Co-Pilot
import { afterEach, describe, expect, it, vi } from "vitest";
import { getAssetsForVersion } from "../fetchTemurinNightly";
import { createMockTemurinFeatureReleaseAPI } from "@/hooks/__fixtures__/hooks";
import { fetchFeatureReleases } from "@/services/adoptiumApi";

vi.mock("@/services/adoptiumApi", () => ({
  fetchFeatureReleases: vi.fn(),
}));
const mockedFetchFeatureReleases = vi.mocked(fetchFeatureReleases);

afterEach(() => {
  vi.clearAllMocks();
});

describe("getAssetsForVersion", () => {
  it("returns releases for a valid ea response", async () => {
    const mockPkg = createMockTemurinFeatureReleaseAPI(false);
    mockedFetchFeatureReleases.mockResolvedValue({
      data: [mockPkg],
      pagecount: 0,
    });

    const result = await getAssetsForVersion(
      21,
      "ea",
      5,
      new Date("2024-01-01"),
      0,
    );

    expect(result).not.toBeNull();
    expect(result?.releases).toHaveLength(1);
    expect(result?.releases[0].release_name).toBeDefined();
  });

  it("returns releases for a valid ga response", async () => {
    const mockPkg = createMockTemurinFeatureReleaseAPI(false);
    mockedFetchFeatureReleases.mockResolvedValue({
      data: [mockPkg],
      pagecount: 3,
    });

    const result = await getAssetsForVersion(
      21,
      "ga",
      10,
      new Date("2024-06-01"),
      1,
    );

    expect(result).not.toBeNull();
    expect(result?.releases).toHaveLength(1);
    expect(result?.pagecount).toBe(3);
  });

  it("returns empty releases on API error", async () => {
    mockedFetchFeatureReleases.mockRejectedValue(new Error("Server Error"));

    const result = await getAssetsForVersion(
      21,
      "ea",
      5,
      new Date("2024-01-01"),
      0,
    );

    expect(result).not.toBeNull();
    expect(result?.releases).toHaveLength(0);
    expect(result?.pagecount).toBe(0);
  });

  it("includes installer info when installer is present", async () => {
    const mockPkg = createMockTemurinFeatureReleaseAPI(true);
    mockedFetchFeatureReleases.mockResolvedValue({
      data: [mockPkg],
      pagecount: 0,
    });

    const result = await getAssetsForVersion(
      21,
      "ea",
      5,
      new Date("2024-01-01"),
      0,
    );

    expect(result).not.toBeNull();
    const binary = result?.releases[0]?.binaries?.[0];
    expect(binary).toBeDefined();
    if (binary) {
      expect(binary.installer?.link).toBeDefined();
    }
  });

  it("filters out binary types not in the ea allowed list", async () => {
    const mockPkg = createMockTemurinFeatureReleaseAPI(false);
    // Override binary type to something not in the ea allowed list
    mockPkg.binaries![0].image_type = "sources";
    mockedFetchFeatureReleases.mockResolvedValue({
      data: [mockPkg],
      pagecount: 0,
    });

    const result = await getAssetsForVersion(
      21,
      "ea",
      5,
      new Date("2024-01-01"),
      0,
    );

    expect(result).not.toBeNull();
    // sources is not in ["INSTALLER", "JDK", "JRE", "DEBUGIMAGE"] for ea
    expect(result?.releases[0]?.binaries).toHaveLength(0);
  });

  it("filters out binary types not in the ga allowed list", async () => {
    const mockPkg = createMockTemurinFeatureReleaseAPI(false);
    // Override binary type to something not in the ga allowed list
    mockPkg.binaries![0].image_type = "debugimage";
    mockedFetchFeatureReleases.mockResolvedValue({
      data: [mockPkg],
      pagecount: 0,
    });

    const result = await getAssetsForVersion(
      21,
      "ga",
      5,
      new Date("2024-01-01"),
      0,
    );

    expect(result).not.toBeNull();
    // debugimage is not in ["INSTALLER", "JDK", "JRE"] for ga
    expect(result?.releases[0]?.binaries).toHaveLength(0);
  });

  it("handles source when source is present", async () => {
    const mockPkg = createMockTemurinFeatureReleaseAPI(false);
    mockPkg.source = {
      link: "https://source_link_mock",
      name: "source_name_mock",
      size: 1000,
    };
    mockedFetchFeatureReleases.mockResolvedValue({
      data: [mockPkg],
      pagecount: 0,
    });

    const result = await getAssetsForVersion(
      21,
      "ea",
      5,
      new Date("2024-01-01"),
      0,
    );

    expect(result).not.toBeNull();
    expect(result?.releases[0]?.source).toBeDefined();
  });

  it("handles release_notes when present", async () => {
    const mockPkg = createMockTemurinFeatureReleaseAPI(false);
    mockPkg.release_notes = {
      link: "https://release_notes_link_mock",
      name: "release_notes_name_mock",
      size: 100,
    };
    mockedFetchFeatureReleases.mockResolvedValue({
      data: [mockPkg],
      pagecount: 0,
    });

    const result = await getAssetsForVersion(
      21,
      "ea",
      5,
      new Date("2024-01-01"),
      0,
    );

    expect(result).not.toBeNull();
    expect(result?.releases[0]?.release_notes).toBeDefined();
    expect(result?.releases[0]?.release_notes?.name).toBe(
      "release_notes_name_mock",
    );
  });

  it("handles invalid buildDate gracefully", async () => {
    const mockPkg = createMockTemurinFeatureReleaseAPI(false);
    mockedFetchFeatureReleases.mockResolvedValue({
      data: [mockPkg],
      pagecount: 0,
    });

    // Pass an invalid date
    const result = await getAssetsForVersion(
      21,
      "ea",
      5,
      new Date("invalid"),
      0,
    );

    expect(result).not.toBeNull();
  });

  it("handles multiple releases", async () => {
    const mockPkg1 = createMockTemurinFeatureReleaseAPI(false);
    const mockPkg2 = createMockTemurinFeatureReleaseAPI(true);
    mockedFetchFeatureReleases.mockResolvedValue({
      data: [mockPkg1, mockPkg2],
      pagecount: 0,
    });

    const result = await getAssetsForVersion(
      21,
      "ea",
      5,
      new Date("2024-01-01"),
      0,
    );

    expect(result).not.toBeNull();
    expect(result?.releases).toHaveLength(2);
  });
});
