// Some portions generated by Co-Pilot
import { renderHook, waitFor } from "@testing-library/react";
import { describe, expect, it, vi, afterEach } from "vitest";
import { useArches, useOses } from "../fetchConstants";
import {
  fetchArchitectures,
  fetchOperatingSystems,
} from "@/services/adoptiumApi";

vi.mock("@/services/adoptiumApi", () => ({
  fetchArchitectures: vi.fn(),
  fetchOperatingSystems: vi.fn(),
}));
const mockedFetchArchitectures = vi.mocked(fetchArchitectures);
const mockedFetchOperatingSystems = vi.mocked(fetchOperatingSystems);

afterEach(() => {
  vi.clearAllMocks();
});

describe("useArches", () => {
  it("URL is set correctly", async () => {
    mockedFetchArchitectures.mockResolvedValue(["mock_aarch64"]);

    const { result } = renderHook(() => useArches(true));

    await waitFor(
      () => {
        expect(result.current.length).toBeGreaterThan(0);
      },
      { interval: 1 },
    );
    expect(mockedFetchArchitectures).toHaveBeenCalledTimes(1);
    expect(result.current[0].value).toBe("mock_aarch64");
  });

  it("Result is empty on error", async () => {
    mockedFetchArchitectures.mockRejectedValue(new Error("Server Error"));

    const { result } = renderHook(() => useArches(true));
    await waitFor(
      () => {
        expect(result.current.length).toBe(0);
      },
      { interval: 1 },
    );
  });
});

describe("useOses", () => {
  it("URL is set correctly", async () => {
    mockedFetchOperatingSystems.mockResolvedValue(["mock_linux"]);

    const { result } = renderHook(() => useOses(true));

    await waitFor(
      () => {
        expect(result.current.length).toBeGreaterThan(0);
      },
      { interval: 1 },
    );
    expect(mockedFetchOperatingSystems).toHaveBeenCalledTimes(1);
    expect(result.current[0].value).toBe("mock_linux");
  });

  it("Result is empty on error", async () => {
    mockedFetchOperatingSystems.mockRejectedValue(new Error("Server Error"));

    const { result } = renderHook(() => useOses(true));
    await waitFor(
      () => {
        expect(result.current.length).toBe(0);
      },
      { interval: 1 },
    );
  });
});
