// Some portions generated by Co-Pilot
import { renderHook, waitFor } from "@testing-library/react";
import { describe, expect, it, vi, afterEach } from "vitest";
import { useFetchLatestForOS } from "../fetchLatestTemurin";
import { mockLatestTemurin } from "@/hooks/__fixtures__/hooks";
import { fetchFeatureReleases } from "@/services/adoptiumApi";

vi.mock("@/services/adoptiumApi", () => ({
  fetchFeatureReleases: vi.fn(),
}));
const mockedFetchFeatureReleases = vi.mocked(fetchFeatureReleases);

afterEach(() => {
  vi.clearAllMocks();
});

describe("useFetchLatestForOS", () => {
  it("binary URL is set correctly", async () => {
    const mockResponse = [mockLatestTemurin(false)];
    mockedFetchFeatureReleases.mockResolvedValue({
      data: mockResponse as any,
      pagecount: 0,
    });

    const { result } = renderHook(() =>
      useFetchLatestForOS(true, 11, "linux", "x64"),
    );
    await waitFor(
      () => {
        expect(result.current?.release_name).toBe("release_name_mock");
      },
      { interval: 1 },
    );
    expect(mockedFetchFeatureReleases).toHaveBeenCalledTimes(1);
  });

  it("installer is returned if available", async () => {
    const mockResponse = [mockLatestTemurin(true)];
    mockedFetchFeatureReleases.mockResolvedValue({
      data: mockResponse as any,
      pagecount: 0,
    });

    const { result } = renderHook(() =>
      useFetchLatestForOS(true, 11, "linux", "x64"),
    );
    await waitFor(
      () => {
        expect(result.current?.release_name).toBe("release_name_mock");
      },
      { interval: 1 },
    );
    expect(result.current?.link).toBe("https://installer_link_mock");
  });

  it("binary to be null on error", async () => {
    mockedFetchFeatureReleases.mockRejectedValue(new Error("Server Error"));

    const { result } = renderHook(() =>
      useFetchLatestForOS(true, 11, "linux", "x64"),
    );
    await waitFor(
      () => {
        expect(result.current).toBeNull();
      },
      { interval: 1 },
    );
  });
});
