// Some portions generated by Co-Pilot
import { describe, it, expect, vi, beforeEach } from "vitest";
import { fetchLatestEvents } from "../fetchLatestEvents";

describe("fetchLatestEvents", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it("fetches events from the Eclipse newsroom API", async () => {
    const mockEvents = [
      { id: "1", title: "Event 1", infoLink: "https://example.com", date: "2024-01-01" },
      { id: "2", title: "Event 2", infoLink: "https://example.com", date: "2024-02-01" },
    ];

    const fetchSpy = vi.spyOn(globalThis, "fetch").mockResolvedValue({
      ok: true,
      json: async () => ({ events: mockEvents }),
    } as Response);

    const result = await fetchLatestEvents();

    expect(fetchSpy).toHaveBeenCalledTimes(1);
    const calledUrl = fetchSpy.mock.calls[0][0] as string;
    expect(calledUrl).toContain("https://newsroom.eclipse.org/api/events");
    expect(calledUrl).toContain("parameters%5Bpublish_to%5D=adoptium");
    expect(calledUrl).toContain("pagesize=20");
    expect(result).toEqual(mockEvents);
  });

  it("returns empty array on API error", async () => {
    vi.spyOn(globalThis, "fetch").mockRejectedValue(new Error("Network error"));

    const result = await fetchLatestEvents();
    expect(result).toEqual([]);
  });
});
