// Some portions generated by Co-Pilot
import { renderHook, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { useFetchReleaseNotesForVersion } from "../fetchReleaseNotes";
import { createMockReleaseNotesAPI } from "@/hooks/__fixtures__/hooks";
import {
  fetchReleaseNotes as apiFetchReleaseNotes,
  fetchLatestReleaseName,
  fetchLatestAssets,
} from "@/services/adoptiumApi";

vi.mock("@/services/adoptiumApi", () => ({
  fetchReleaseNotes: vi.fn(),
  fetchLatestReleaseName: vi.fn(),
  fetchLatestAssets: vi.fn(),
}));
const mockedFetchReleaseNotes = vi.mocked(apiFetchReleaseNotes);
const mockedFetchLatestReleaseName = vi.mocked(fetchLatestReleaseName);
const mockedFetchLatestAssets = vi.mocked(fetchLatestAssets);

const mockResponse = createMockReleaseNotesAPI(1);

const sortReleaseNotesByCallback = vi.fn();

afterEach(() => {
  vi.clearAllMocks();
});

describe("useFetchReleaseNotesForVersion", () => {
  it("returns valid JSON", async () => {
    mockedFetchReleaseNotes.mockResolvedValue(mockResponse as any);

    const { result } = renderHook(() =>
      useFetchReleaseNotesForVersion(
        true,
        "sample_version",
        sortReleaseNotesByCallback,
      ),
    );
    await waitFor(
      () => {
        expect(result.current?.releaseNoteAPIResponse?.release_name).toBe(
          "release_name_mock",
        );
      },
      { interval: 1 },
    );
    expect(mockedFetchReleaseNotes).toHaveBeenCalledWith("sample_version");
  });

  it("returns null if version is not defined", async () => {
    const { result } = renderHook(() =>
      // @ts-expect-error version is intentionally undefined
      useFetchReleaseNotesForVersion(true, null, sortReleaseNotesByCallback),
    );
    expect(result.current).toBe(null);
  });

  it("checks sortReleaseNotesByCallback to be called", async () => {
    mockedFetchReleaseNotes.mockResolvedValue(mockResponse as any);

    renderHook(() =>
      useFetchReleaseNotesForVersion(
        true,
        "sample_version",
        sortReleaseNotesByCallback,
      ),
    );
    await waitFor(
      () => {
        expect(sortReleaseNotesByCallback).toHaveBeenCalledTimes(1);
      },
      { interval: 1 },
    );
  });

  it("checks sortReleaseNotesByCallback NOT to be called", async () => {
    mockedFetchReleaseNotes.mockResolvedValue(mockResponse as any);

    renderHook(() => useFetchReleaseNotesForVersion(true, "sample_version"));
    await waitFor(
      () => {
        expect(sortReleaseNotesByCallback).toHaveBeenCalledTimes(0);
      },
      { interval: 1 },
    );
  });

  it("releaseNotes to be null on error", async () => {
    mockedFetchReleaseNotes.mockRejectedValue(new Error("Server Error"));

    const { result } = renderHook(() =>
      useFetchReleaseNotesForVersion(true, "sample_version"),
    );
    await waitFor(
      () => {
        expect(result.current).toEqual({ isValid: false });
      },
      { interval: 1 },
    );
  });

  it("fetches default version when version is undefined", async () => {
    mockedFetchLatestReleaseName.mockResolvedValue("jdk-21+35");
    mockedFetchReleaseNotes.mockResolvedValue(mockResponse as any);

    const { result } = renderHook(() =>
      useFetchReleaseNotesForVersion(true, undefined),
    );
    await waitFor(
      () => {
        expect(result.current?.isValid).toBe(true);
      },
      { interval: 1 },
    );
    expect(mockedFetchReleaseNotes).toHaveBeenCalledWith("jdk-21+35");
  });

  it("resolves major version number to latest release", async () => {
    mockedFetchLatestAssets.mockResolvedValue([
      { release_name: "jdk-21.0.2+13" },
    ] as any);
    mockedFetchReleaseNotes.mockResolvedValue(mockResponse as any);

    const { result } = renderHook(() =>
      useFetchReleaseNotesForVersion(true, "21"),
    );
    await waitFor(
      () => {
        expect(result.current?.isValid).toBe(true);
      },
      { interval: 1 },
    );
    expect(mockedFetchReleaseNotes).toHaveBeenCalledWith("jdk-21.0.2+13");
  });

  it("handles getLatestVersionForMajor failure gracefully", async () => {
    const consoleSpy = vi.spyOn(console, "error").mockImplementation(() => {});
    mockedFetchLatestAssets.mockRejectedValue(new Error("Server Error"));
    mockedFetchReleaseNotes.mockResolvedValue(mockResponse as any);

    const { result } = renderHook(() =>
      useFetchReleaseNotesForVersion(true, "21"),
    );
    await waitFor(
      () => {
        expect(result.current).not.toBeNull();
      },
      { interval: 1 },
    );
    consoleSpy.mockRestore();
  });
});
