// Some portions generated by Co-Pilot
import { describe, it, expect, vi, beforeEach } from "vitest";
import { renderHook, waitFor } from "@testing-library/react";
import axios from "axios";
import { useAttestations } from "../useAttestations";

vi.mock("axios");
const mockedAxios = vi.mocked(axios);

describe("useAttestations", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns initial state when releaseName is undefined", () => {
    const { result } = renderHook(() =>
      useAttestations(undefined, ["abc123"])
    );

    expect(result.current.isLoading).toBe(false);
    expect(result.current.error).toBeUndefined();
    expect(result.current.attestations).toEqual({});
  });

  it("returns initial state when checksums is empty", () => {
    const { result } = renderHook(() =>
      useAttestations("jdk-21+35", [])
    );

    expect(result.current.isLoading).toBe(false);
    expect(result.current.error).toBeUndefined();
    expect(result.current.attestations).toEqual({});
  });

  it("fetches attestations for a valid release", async () => {
    const mockAttestations = [
      { target_checksum: "abc123", statement: "test-statement-1" },
      { target_checksum: "def456", statement: "test-statement-2" },
    ];

    mockedAxios.get.mockResolvedValue({ data: mockAttestations });

    const { result } = renderHook(() =>
      useAttestations("jdk-21+35", ["abc123", "def456"])
    );

    await waitFor(() => {
      expect(result.current.isLoading).toBe(false);
    });

    expect(mockedAxios.get).toHaveBeenCalledWith(
      expect.stringContaining("/attestations/release_name/jdk-21%2B35"),
      { params: { project: "jdk" } }
    );

    expect(result.current.attestations["abc123"]).toEqual(mockAttestations[0]);
    expect(result.current.attestations["def456"]).toEqual(mockAttestations[1]);
  });

  it("handles 404 error by caching undefined for checksums", async () => {
    const axiosError = new Error("Not Found") as any;
    axiosError.response = { status: 404 };
    mockedAxios.isAxiosError = vi.fn().mockReturnValue(true);
    mockedAxios.get.mockRejectedValue(axiosError);

    const { result } = renderHook(() =>
      useAttestations("jdk-21+35", ["abc123"])
    );

    await waitFor(() => {
      expect(result.current.isLoading).toBe(false);
    });

    expect(result.current.error).toBeUndefined();
  });

  it("sets error on non-404 errors", async () => {
    const axiosError = new Error("Server Error") as any;
    axiosError.response = { status: 500 };
    mockedAxios.isAxiosError = vi.fn().mockReturnValue(false);
    mockedAxios.get.mockRejectedValue(axiosError);

    const { result } = renderHook(() =>
      useAttestations("jdk-21+35", ["abc123"])
    );

    await waitFor(() => {
      expect(result.current.isLoading).toBe(false);
    });

    expect(result.current.error).toBeDefined();
  });

  it("deduplicates checksums", async () => {
    mockedAxios.get.mockResolvedValue({ data: [] });

    renderHook(() =>
      useAttestations("jdk-21+35", ["abc123", "abc123", "abc123"])
    );

    await waitFor(() => {
      expect(mockedAxios.get).toHaveBeenCalledTimes(1);
    });
  });

  it("filters out empty checksums", () => {
    const { result } = renderHook(() =>
      useAttestations("jdk-21+35", ["", ""])
    );

    expect(result.current.isLoading).toBe(false);
    expect(mockedAxios.get).not.toHaveBeenCalled();
  });
});
