// Some portions generated by Co-Pilot
import { renderHook, waitFor } from "@testing-library/react";
import { describe, it, expect, vi, afterEach } from "vitest";

import { useAttestations } from "../useAttestations";
import { fetchAttestations } from "@/services/adoptiumApi";

vi.mock("@/services/adoptiumApi", () => ({
  fetchAttestations: vi.fn(),
}));
const mockedFetchAttestations = vi.mocked(fetchAttestations);

afterEach(() => {
  vi.clearAllMocks();
});

const mockAttestations = [
  {
    target_checksum: "checksum-1",
    predicate_type: "https://slsa.dev/provenance/v1",
  },
];

// Test 1 Guard clause (no release name))
it("does not fetch when releaseName is undefined", async () => {
  renderHook(() => useAttestations(undefined, ["checksum-1"]));
  expect(mockedFetchAttestations).not.toHaveBeenCalled();
});

//Test 2 fetch and normalize
it("fetches attestations and normalizes by checksum", async () => {
  mockedFetchAttestations.mockResolvedValue([
    { target_checksum: "checksum-1" },
  ] as any);

  const { result } = renderHook(() =>
    useAttestations("release_name_mock", ["checksum-1"]),
  );

  await waitFor(() => {
    expect(result.current.isLoading).toBe(false);
  });

  expect(result.current.attestations["checksum-1"]).toBeDefined();
});

// Test 3 partial matches
it("sets undefined for checksums not returned by the API", async () => {
  mockedFetchAttestations.mockResolvedValue([
    { target_checksum: "checksum-1" },
  ] as any);

  const { result } = renderHook(() =>
    useAttestations("release_name_mock", ["checksum-1", "checksum-2"]),
  );

  await waitFor(() => {
    expect(result.current.isLoading).toBe(false);
  });

  expect(result.current.attestations["checksum-1"]).toBeDefined();
  expect(result.current.attestations["checksum-2"]).toBeUndefined();
});

//Test 4 404 is NOT an error
it("handles 404 responses by caching undefined attestations", async () => {
  const err = Object.assign(new Error("Not Found"), { status: 404 });
  mockedFetchAttestations.mockRejectedValue(err);

  const { result } = renderHook(() =>
    useAttestations("release_name_mock", ["checksum-1"]),
  );

  await waitFor(() => {
    expect(result.current.isLoading).toBe(false);
  });

  expect(result.current.error).toBeUndefined();
  expect(result.current.attestations["checksum-1"]).toBeUndefined();
});

//Test 5 non-404 error surfaces
it("exposes error for non-404 failures", async () => {
  mockedFetchAttestations.mockRejectedValue(new Error("Server Error"));

  const { result } = renderHook(() =>
    useAttestations("release_name_mock", ["checksum-1"]),
  );

  await waitFor(() => {
    expect(result.current.error).toBeDefined();
  });
});

//Test 6 caching prevents refetch
it("does not refetch attestations for cached checksums", async () => {
  mockedFetchAttestations.mockResolvedValue([
    { target_checksum: "checksum-1" },
  ] as any);

  const { rerender } = renderHook(
    ({ checksums }) => useAttestations("release_name_mock", checksums),
    {
      initialProps: { checksums: ["checksum-1"] },
    },
  );

  // Wait until at least one fetch has happened
  await waitFor(() => {
    expect(mockedFetchAttestations).toHaveBeenCalled();
  });

  const callsAfterFirstFetch = mockedFetchAttestations.mock.calls.length;

  // Rerender with the same checksum
  rerender({ checksums: ["checksum-1"] });

  // Allow effects to flush
  await new Promise((r) => setTimeout(r, 0));

  expect(mockedFetchAttestations.mock.calls.length).toBe(callsAfterFirstFetch);
});
