// Some portions generated by Co-Pilot
import { describe, it, expect, vi, beforeEach } from "vitest";
import { renderHook, waitFor } from "@testing-library/react";
import { useAttestations } from "../useAttestations";
import { fetchCdxas } from "@/services/adoptiumApi";

vi.mock("@/services/adoptiumApi", () => ({
  fetchCdxas: vi.fn(),
}));
const mockedFetchCdxas = vi.mocked(fetchCdxas);

describe("useAttestations", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns initial state when releaseName is undefined", () => {
    const { result } = renderHook(() => useAttestations(undefined, ["abc123"]));

    expect(result.current.isLoading).toBe(false);
    expect(result.current.error).toBeUndefined();
    expect(result.current.attestations).toEqual({});
  });

  it("returns initial state when checksums is empty", () => {
    const { result } = renderHook(() => useAttestations("jdk-21+35", []));

    expect(result.current.isLoading).toBe(false);
    expect(result.current.error).toBeUndefined();
    expect(result.current.attestations).toEqual({});
  });

  it("fetches attestations for a valid release", async () => {
    const mockAttestations = [
      { target_checksum: "ABC123", statement: "test-statement-1" },
      { target_checksum: "DEF456", statement: "test-statement-2" },
    ];

    mockedFetchCdxas.mockResolvedValue(mockAttestations as any);

    const { result } = renderHook(() =>
      useAttestations("jdk-21+35", ["abc123", "def456"]),
    );

    await waitFor(() => {
      expect(result.current.isLoading).toBe(false);
    });

    expect(mockedFetchCdxas).toHaveBeenCalledWith("jdk-21+35");

    expect(result.current.attestations["ABC123"]).toEqual(mockAttestations[0]);
    expect(result.current.attestations["DEF456"]).toEqual(mockAttestations[1]);
  });

  it("handles 404 error by caching undefined for checksums", async () => {
    const err = Object.assign(new Error("Not Found"), { status: 404 });
    mockedFetchCdxas.mockRejectedValue(err);

    const { result } = renderHook(() =>
      useAttestations("jdk-21+35", ["abc123"]),
    );

    await waitFor(() => {
      expect(result.current.isLoading).toBe(false);
    });

    expect(result.current.error).toBeUndefined();
  });

  it("sets error on non-404 errors", async () => {
    const err = new Error("Server Error");
    mockedFetchCdxas.mockRejectedValue(err);

    const { result } = renderHook(() =>
      useAttestations("jdk-21+35", ["abc123"]),
    );

    await waitFor(() => {
      expect(result.current.isLoading).toBe(false);
    });

    expect(result.current.error).toBeDefined();
  });

  it("deduplicates checksums", async () => {
    mockedFetchCdxas.mockResolvedValue([] as any);

    renderHook(() =>
      useAttestations("jdk-21+35", ["abc123", "abc123", "abc123"]),
    );

    await waitFor(() => {
      expect(mockedFetchCdxas).toHaveBeenCalledTimes(1);
    });
  });

  it("filters out empty checksums", () => {
    const { result } = renderHook(() => useAttestations("jdk-21+35", ["", ""]));

    expect(result.current.isLoading).toBe(false);
    expect(mockedFetchCdxas).not.toHaveBeenCalled();
  });
});
