// Some portions generated by Co-Pilot
"use client";

import React, { useEffect, useState } from "react";
import { useTranslations } from "next-intl";

const DocThemeToggle: React.FC = () => {
  const [isLight, setIsLight] = useState(false);
  const t = useTranslations("DocThemeToggle");

  useEffect(() => {
    const saved = localStorage.getItem("doc-theme");
    if (saved === "light") {
      setIsLight(true);
      document.documentElement.classList.add("doc-light");
    }

    // Remove doc-light when navigating away from pages with the toggle
    return () => {
      document.documentElement.classList.remove("doc-light");
    };
  }, []);

  const toggle = () => {
    const next = !isLight;
    setIsLight(next);
    if (next) {
      document.documentElement.classList.add("doc-light");
      localStorage.setItem("doc-theme", "light");
    } else {
      document.documentElement.classList.remove("doc-light");
      localStorage.setItem("doc-theme", "dark");
    }
  };

  return (
    <button
      onClick={toggle}
      className={`flex items-center gap-2 text-xs transition-colors px-2 py-1 rounded-md border ${
        isLight
          ? "text-gray-500 hover:text-gray-900 border-gray-300 hover:border-gray-400"
          : "text-gray-400 hover:text-white border-white/10 hover:border-white/20"
      }`}
      aria-label={isLight ? t("switch-to-dark") : t("switch-to-light")}
    >
      {isLight ? (
        <svg
          className="w-3.5 h-3.5"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
          />
        </svg>
      ) : (
        <svg
          className="w-3.5 h-3.5"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"
          />
        </svg>
      )}
      {isLight ? t("dark") : t("light")}
    </button>
  );
};

export default DocThemeToggle;
