// Some portions generated by Co-Pilot
import React from "react";
import { render } from "@testing-library/react";
import { describe, it, expect } from "vitest";
import AsciiDocFormatter from "../index";

describe("AsciiDocFormatter", () => {
  it("renders plain HTML content", () => {
    const { container } = render(
      <AsciiDocFormatter content="<p>Hello world</p>" />,
    );
    expect(container.querySelector("p")?.textContent).toBe("Hello world");
  });

  it("transforms external anchor tags with external-link icon", () => {
    const { container } = render(
      <AsciiDocFormatter content='<a href="https://example.com">External</a>' />,
    );
    expect(container.querySelector("a")).not.toBeNull();
  });

  it("transforms internal anchor tags to Next.js Link", () => {
    const { container } = render(
      <AsciiDocFormatter content='<a href="/docs/install">Install</a>' />,
    );
    expect(container.querySelector("a")?.getAttribute("href")).toBe(
      "/docs/install",
    );
  });

  it("suppresses script tags and keeps surrounding content", () => {
    const { container } = render(
      <AsciiDocFormatter content="<script>alert('xss')</script><p>Safe</p>" />,
    );
    // Safe sibling content still renders
    expect(container.querySelector("p")?.textContent).toBe("Safe");
  });

  it("transforms h1-h6 headings to add hoverable anchors", () => {
    const { container } = render(
      <AsciiDocFormatter content='<h2 id="section-title">Section Title</h2>' />,
    );
    const heading = container.querySelector("h2");
    expect(heading).not.toBeNull();
    expect(heading?.id).toBe("section-title");
    expect(container.querySelector('a[href="#section-title"]')).not.toBeNull();
  });

  it("renders heading without anchor when no id present", () => {
    const { container } = render(
      <AsciiDocFormatter content="<h3>No ID Heading</h3>" />,
    );
    expect(container.querySelector("h3")?.textContent).toBe("No ID Heading");
  });

  it("transforms fa-docker icon class from fa to fab", () => {
    const { container } = render(
      <AsciiDocFormatter content='<i class="fa fa-docker"></i>' />,
    );
    const icon = container.querySelector("i");
    expect(icon?.className).toContain("fab");
  });

  it("renders note admonition block as github-callout", () => {
    const html = `<div class="admonitionblock note">
      <table><tbody><tr>
        <td class="icon"><div class="title">Note</div></td>
        <td class="content">This is a note.</td>
      </tr></tbody></table>
    </div>`;
    const { container } = render(<AsciiDocFormatter content={html} />);
    expect(container.querySelector(".github-callout")).not.toBeNull();
    expect(container.querySelector(".callout-note")).not.toBeNull();
  });

  it("renders tip admonition block", () => {
    const html = `<div class="admonitionblock tip">
      <table><tbody><tr>
        <td class="icon"><div class="title">Tip</div></td>
        <td class="content">A helpful tip.</td>
      </tr></tbody></table>
    </div>`;
    const { container } = render(<AsciiDocFormatter content={html} />);
    expect(container.querySelector(".callout-tip")).not.toBeNull();
  });

  it("renders warning admonition block", () => {
    const html = `<div class="admonitionblock warning">
      <table><tbody><tr>
        <td class="icon"></td>
        <td class="content">Warning content.</td>
      </tr></tbody></table>
    </div>`;
    const { container } = render(<AsciiDocFormatter content={html} />);
    expect(container.querySelector(".callout-warning")).not.toBeNull();
  });

  it("renders caution admonition block", () => {
    const html = `<div class="admonitionblock caution">
      <table><tbody><tr>
        <td class="icon"></td>
        <td class="content">Caution content.</td>
      </tr></tbody></table>
    </div>`;
    const { container } = render(<AsciiDocFormatter content={html} />);
    expect(container.querySelector(".callout-caution")).not.toBeNull();
  });

  it("renders important admonition block", () => {
    const html = `<div class="admonitionblock important">
      <table><tbody><tr>
        <td class="icon"></td>
        <td class="content">Important content.</td>
      </tr></tbody></table>
    </div>`;
    const { container } = render(<AsciiDocFormatter content={html} />);
    expect(container.querySelector(".callout-important")).not.toBeNull();
  });

  it("renders external anchor inside an image (no external-link icon)", () => {
    const { container } = render(
      <AsciiDocFormatter content='<a href="https://example.com"><img src="img.png" alt="logo" /></a>' />,
    );
    const icon = container.querySelector(".fa-external-link");
    expect(icon).toBeNull();
  });
});
