// Some portions generated by Co-Pilot
"use client";

import React from "react";
import * as Highcharts from "highcharts";
import { Chart, type ChartOptions } from "@highcharts/react";

interface StackedBarChartProps {
  categories: string[];
  series: Array<{ name: string; data: number[]; color?: string }>;
  name: string;
  stacking?: "normal" | "percent";
  horizontal?: boolean;
}

const StackedBarChart: React.FC<StackedBarChartProps> = ({
  categories,
  series,
  name,
  stacking = "normal",
  horizontal = false,
}) => {
  if (!series.length) return null;

  const options: ChartOptions = {
    chart: {
      type: horizontal ? "bar" : "column",
      backgroundColor: "transparent",
      style: { fontFamily: "inherit" },
      animation: process.env.NODE_ENV !== "test",
    },
    colors: ["#2caffe", "#6c6de3", "#feae62", "#a259f7", "#f67280", "#43e97b"],
    accessibility: { enabled: false },
    title: {
      text: name,
      style: { color: "#fff", fontWeight: "bold", fontSize: "1.25rem" },
    },
    xAxis: {
      categories,
      labels: {
        style: { color: "#fff", fontWeight: "bold", fontSize: "0.9rem" },
      },
      lineColor: "rgba(255,255,255,0.2)",
      tickColor: "rgba(255,255,255,0.2)",
    },
    yAxis: {
      title: {
        text: stacking === "percent" ? "Percentage" : "Downloads",
        style: { color: "#fff", fontWeight: "bold", fontSize: "1rem" },
      },
      labels: {
        style: { color: "#fff", fontWeight: "bold", fontSize: "0.9rem" },
      },
      gridLineColor: "rgba(255,255,255,0.1)",
      stackLabels: {
        enabled: stacking === "normal",
        style: {
          color: "#fff",
          fontWeight: "bold",
          textOutline: "none",
          fontSize: "0.8rem",
        },
        formatter: function () {
          return Highcharts.numberFormat(this.total, 0, ".", " ");
        },
      },
    },
    legend: {
      itemStyle: { color: "#fff", fontWeight: "bold" },
      itemHoverStyle: { color: "#6ba4e7" },
    },
    tooltip: {
      backgroundColor: "#2c225a",
      borderColor: "#6ba4e7",
      style: { color: "#fff", fontWeight: "bold" },
      shared: true,
      useHTML: true,
      formatter: function (this: unknown) {
        const ctx = this as {
          points?: Array<{
            color: string;
            series: { name: string };
            y?: number;
          }>;
          x?: string;
        };
        const points = ctx.points;
        if (!points) return "";
        let s = `<span style="font-size:10px">${ctx.x}</span><table>`;
        points.forEach((point) => {
          s +=
            `<tr><td style="color:${point.color};padding:0">${point.series.name}: </td>` +
            `<td style="padding:0"><b>${Highcharts.numberFormat(point.y ?? 0, 0, ".", " ")}</b></td></tr>`;
        });
        const total = points.reduce((sum, p) => sum + (p.y ?? 0), 0);
        s += `<tr><td style="padding:0"><b>Total: </b></td><td style="padding:0"><b>${Highcharts.numberFormat(total, 0, ".", " ")}</b></td></tr>`;
        s += "</table>";
        return s;
      },
    },
    plotOptions: {
      column: {
        stacking,
        borderRadius: 4,
        borderWidth: 0,
        pointPadding: 0.1,
        shadow: false,
      },
      bar: {
        stacking,
        borderRadius: 4,
        borderWidth: 0,
        pointPadding: 0.1,
        shadow: false,
      },
    },
    series: series.map((s) => ({
      ...s,
      type: horizontal ? ("bar" as const) : ("column" as const),
    })),
  };

  return (
    <div className="chart">
      <Chart options={options} />
    </div>
  );
};

export default StackedBarChart;
