// Some portions generated by Co-Pilot
= Pacotes de instalação Windows MSI
:page-authors: gdams, karianna, SueChaplain, ParkerM, KalyanJoseph
:page-based-on: 0e4cf731021aa6b80ca14281a511b2ce0584a64c
:toc:

Os pacotes de instalação do Eclipse Temurin para Windows estão disponíveis como arquivos .msi
padrão, que podem ser executados com uma interface de usuário interativa ou silenciosamente
pela linha de comando. O instalador foi desenvolvido para uso por máquina, não por usuário,
portanto, pode haver apenas uma instalação do MSI em uma máquina para todos os usuários.

Observação: Os pacotes de instalação para Windows têm suporte apenas em sistemas
Windows x64.

== Instalação pela Interface Gráfica

Instruções para realizar uma instalação interativa usando o instalador MSI do Windows:

. link:/temurin/releases[Baixe] o arquivo `.msi`. Abra-o para iniciar o
programa de instalação.
. Leia e aceite a licença se você concordar com os termos.
. Na tela de Configuração Personalizada, você pode escolher os recursos que deseja
instalar e, opcionalmente, alterar o diretório de instalação padrão. Por
padrão, o Temurin é instalado em `C:\Program Files\Eclipse Adoptium\<package>` com
os seguintes recursos, que podem ser desmarcados, se necessário:
* Adicionar a instalação à variável de ambiente PATH
* Associar arquivos `.jar` a aplicações Java. Recursos adicionais podem
ser selecionados clicando na árvore de diretórios onde você vê uma marca de seleção
(x). Esses recursos incluem:
* Atualizar a variável de ambiente `JAVA_HOME`
. Quando tiver escolhido os recursos que deseja instalar, clique em
Avançar.
. Clique em Instalar para iniciar a instalação.
. Quando a instalação for concluída, clique em Concluir para fechar o programa.

== Instalação pela Linha de Comando

Uma instalação silenciosa permite instalar o pacote Windows com
recursos pré-selecionados sem interação do usuário, o que pode ser útil para
implantações em larga escala. Siga estas etapas:

. link:/temurin/releases[Baixe] o arquivo `.msi`.
. Escolha os recursos que deseja instalar, conforme mostrado na
tabela a seguir:
+
[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Recurso |Descrição
|`FeatureMain` |Instalação principal do Temurin (PADRÃO)

|`FeatureEnvironment` |Atualizar a variável de ambiente PATH (PADRÃO)

|`FeatureJarFileRunWith` |Associar arquivos .jar a aplicações Java
(PADRÃO)

|`FeatureJavaHome` |Atualizar a variável de ambiente JAVA_HOME

|`FeatureOracleJavaSoft` |Atualiza as chaves de registro HKLM
|=======================================================================
+
Observação: `FeatureOracleJavaSoft` pode ser usado para impedir que o Oracle Java
seja iniciado pelo `PATH` quando o Temurin for desinstalado. Reinstale o Oracle Java
se precisar restaurar as chaves de registro da Oracle.
+
Parâmetros opcionais podem ser usados para agrupar alguns recursos:
+
[cols=",",options="header",]
|======================================================================
|Parâmetro |Recursos
|`INSTALLLEVEL=1` |FeatureMain,FeatureEnvironment,FeatureJarFileRunWith
|======================================================================
. Execute o comando na estação de trabalho de destino. O exemplo a seguir
instala silenciosamente o Temurin, atualiza o PATH, associa arquivos .jar a
aplicações Java e define JAVA_HOME:
+
[source,batch]
----
msiexec /i <package>.msi ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome INSTALLDIR="c:\Program Files\Temurin\" /quiet
----
+
Observação: Você deve usar `INSTALLDIR` com FeatureMain.
+
O exemplo a seguir instala silenciosamente todos os recursos para
`INSTALLLEVEL=1`:
+
[source,batch]
----
msiexec /i <package>.msi INSTALLLEVEL=1 /quiet
----
+
Se quiser iniciar uma instalação interativa em outro idioma,
você pode usar a opção `TRANSFORMS` do instalador Windows para definir o
idioma desejado. Por exemplo, para definir o idioma da interface para alemão, use o código
`1031`, que deve ser precedido por `:`.
+
[source,batch]
----
msiexec /i <package>.msi INSTALLLEVEL=1 TRANSFORMS=:1031
----
+
Para uma lista de códigos suportados, consulte a
https://github.com/adoptium/installer/blob/master/wix/Lang/LanguageList.config[lista de idiomas].

== Reinstalação ou Atualização

Para reinstalar o Temurin em modo silencioso com os recursos padrão, execute
o seguinte comando:

[source,batch]
----
msiexec /i <package>.msi REINSTALL=ALL /quiet
----

Se quiser atualizar o Temurin em modo silencioso, execute o seguinte
comando:

[source,batch]
----
msiexec /i <package>.msi REINSTALL=ALL REINSTALLMODE=amus /quiet
----

Opções de `REINSTALLMODE`: (de
https://www.advancedinstaller.com/user-guide/control-events.html[Eventos de Controle])

* `a`: Forçar a instalação de todos os arquivos independentemente de checksum ou versão
* `m`: Reescrever todas as entradas de registro necessárias da Tabela de Registro
que vão para `HKEY_LOCAL_MACHINE`
* `o`: Reinstalar se o arquivo estiver ausente ou for uma versão mais antiga
* `u`: Reescrever todas as entradas de registro necessárias da Tabela de Registro
que vão para `HKEY_CURRENT_USER` ou `HKEY_USERS`
* `s`: Reinstalar todos os atalhos e rearmazenar em cache todos os ícones, substituindo
quaisquer atalhos ou ícones existentes

Observação: `REINSTALL=ALL` define automaticamente `REINSTALLMODE=omus`

=== Limitação de Atualização:

A atualização de arquivos `.msi` funciona apenas para os primeiros 3 dígitos do número de build
devido a uma
https://docs.microsoft.com/windows/desktop/Msi/productversion[limitação do MSI]:

* Atualizar 8.0.2.1 para 8.0.3.1 funciona.
* Atualizar 8.0.2.1 para 8.0.2.2 não funciona. Desinstale o
.msi anterior e instale o novo.
* Atualizar 8.0.2.1 para 8.1.2.1 funciona.
* Atualizar 8.0.2.1 para 11.0.2.1 não funciona. O Temurin não fornece
atualizações para versões principais. Mantenha as duas instalações ou desinstale
a mais antiga.

== Leitura de Referência

* https://www.advancedinstaller.com/user-guide/msiexec.html[Linha de Comando Msiexec.exe]
