// Some portions generated by Co-Pilot
= Paquets d'installation Windows MSI
:page-authors: gdams, karianna, SueChaplain, ParkerM, KalyanJoseph
:page-based-on: 0e4cf731021aa6b80ca14281a511b2ce0584a64c
:toc:

Les paquets d'installation Windows d'Eclipse Temurin sont disponibles en fichiers .msi standard, qui peuvent être exécutés avec une interface utilisateur interactive ou en mode silencieux depuis la ligne de commande. L'installateur est conçu pour une utilisation sur la base d'une machine, et non par utilisateur, de sorte que vous ne pouvez avoir qu'une seule installation du MSI sur une machine pour tous les utilisateurs.

Remarque : les paquets d'installation Windows sont uniquement supportés sur les systèmes Windows x64.

== Installation graphique

Instructions pour exécuter une installation interactive à l'aide de l'installateur Windows MSI :

. link:/temurin/releases[Téléchargez] le fichier `.msi`. Ouvrez-le pour lancer le programme d'installation.
. Lisez et acceptez la licence si vous êtes satisfait des conditions.
. Sur l'écran Configuration personnalisée, vous pouvez choisir les fonctionnalités à installer et éventuellement modifier le répertoire d'installation par défaut. Par défaut, Temurin s'installe dans `C:\Program Files\Eclipse Adoptium\<package>` avec les fonctionnalités suivantes, que vous pouvez désélectionner si nécessaire :
* Ajouter l'installation à la variable d'environnement PATH
* Associer les fichiers `.jar` aux applications Java. Des fonctionnalités supplémentaires peuvent être sélectionnées en cliquant sur l'arborescence de répertoires où vous voyez une coche (x). Ces fonctionnalités comprennent :
* Mettre à jour la variable d'environnement `JAVA_HOME`
. Lorsque vous avez choisi les fonctionnalités à installer, cliquez sur Suivant.
. Cliquez sur Installer pour commencer l'installation.
. Une fois l'installation terminée, cliquez sur Terminer pour fermer le programme.

== Installation en ligne de commande

Une installation silencieuse vous permet d'installer le paquet Windows avec des fonctionnalités présélectionnées sans interaction de l'utilisateur, ce qui peut être utile pour un déploiement à grande échelle. Suivez ces étapes :

. link:/temurin/releases[Téléchargez] le fichier `.msi`.
. Choisissez les fonctionnalités à installer, qui sont indiquées dans le tableau suivant :
+
[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Fonctionnalité |Description
|`FeatureMain` |Installation principale de Temurin (DÉFAUT)

|`FeatureEnvironment` |Mettre à jour la variable d'environnement PATH (DÉFAUT)

|`FeatureJarFileRunWith` |Associer les fichiers .jar aux applications Java
(DÉFAUT)

|`FeatureJavaHome` |Mettre à jour la variable d'environnement JAVA_HOME

|`FeatureOracleJavaSoft` |Met à jour les clés de registre HKLM
|=======================================================================
+
Remarque : `FeatureOracleJavaSoft` peut être utilisé pour empêcher le lancement d'Oracle Java depuis `PATH` lorsque Temurin est désinstallé. Réinstallez Oracle Java si vous devez restaurer les clés de registre Oracle.
+
Des paramètres optionnels peuvent être utilisés pour regrouper certaines fonctionnalités :
+
[cols=",",options="header",]
|======================================================================
|Paramètre |Fonctionnalités
|`INSTALLLEVEL=1` |FeatureMain,FeatureEnvironment,FeatureJarFileRunWith
|======================================================================
. Exécutez la commande sur le poste de travail cible. L'exemple suivant installe silencieusement Temurin, met à jour le PATH, associe les fichiers .jar aux applications Java et définit JAVA_HOME :
+
[source,batch]
----
msiexec /i <package>.msi ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome INSTALLDIR="c:\Program Files\Temurin\" /quiet
----
+
Remarque : vous devez utiliser `INSTALLDIR` avec FeatureMain.
+
L'exemple suivant installe silencieusement toutes les fonctionnalités pour
`INSTALLLEVEL=1` :
+
[source,batch]
----
msiexec /i <package>.msi INSTALLLEVEL=1 /quiet
----
+
Si vous souhaitez lancer une installation interactive dans une autre langue, vous pouvez utiliser l'option `TRANSFORMS` de l'installateur Windows pour définir votre choix de langue. Par exemple, pour définir la langue de l'interface en allemand, utilisez le code `1031`, qui doit être précédé de `:`.
+
[source,batch]
----
msiexec /i <package>.msi INSTALLLEVEL=1 TRANSFORMS=:1031
----
+
Pour obtenir la liste des codes supportés, consultez la
https://github.com/adoptium/installer/blob/master/wix/Lang/LanguageList.config[liste des langues].

== Réinstallation ou mise à niveau

Pour réinstaller Temurin en mode silencieux avec les fonctionnalités par défaut, exécutez la commande suivante :

[source,batch]
----
msiexec /i <package>.msi REINSTALL=ALL /quiet
----

Pour mettre à niveau Temurin en mode silencieux, exécutez la commande suivante :

[source,batch]
----
msiexec /i <package>.msi REINSTALL=ALL REINSTALLMODE=amus /quiet
----

Options de `REINSTALLMODE` : (depuis
https://www.advancedinstaller.com/user-guide/control-events.html[Control
Events])

* `a` : Forcer l'installation de tous les fichiers quelle que soit la somme de contrôle ou la version
* `m` : Réécrire toutes les entrées de registre requises depuis la table de registre qui vont vers `HKEY_LOCAL_MACHINE`
* `o` : Réinstaller si le fichier est manquant ou est une version plus ancienne
* `u` : Réécrire toutes les entrées de registre requises depuis la table de registre qui vont vers `HKEY_CURRENT_USER` ou `HKEY_USERS`
* `s` : Réinstaller tous les raccourcis et remettre en cache toutes les icônes en écrasant les raccourcis ou icônes existants

Remarque : `REINSTALL=ALL` définit automatiquement `REINSTALLMODE=omus`

=== Limitation de la mise à niveau :

La mise à niveau des fichiers `.msi` ne fonctionne que pour les 3 premiers chiffres du numéro de version en raison d'une
https://docs.microsoft.com/windows/desktop/Msi/productversion[limitation MSI] :

* La mise à niveau de 8.0.2.1 vers 8.0.3.1 fonctionne.
* La mise à niveau de 8.0.2.1 vers 8.0.2.2 ne fonctionne pas. Désinstallez le .msi précédent et installez le nouveau.
* La mise à niveau de 8.0.2.1 vers 8.1.2.1 fonctionne.
* La mise à niveau de 8.0.2.1 vers 11.0.2.1 ne fonctionne pas. Temurin ne fournit pas de mises à niveau pour les versions majeures. Conservez les deux installations ou désinstallez l'ancienne.

== Lecture de référence

* https://www.advancedinstaller.com/user-guide/msiexec.html[Ligne de commande Msiexec.exe]
