// Some portions generated by Co-Pilot
"use client";

import React, { useState } from "react";

interface AccordionItemProps {
  title: string | React.ReactNode;
  children: React.ReactNode;
}

const AccordionItem = ({ title, children }: AccordionItemProps) => {
  const [isOpen, setIsOpen] = useState(false);

  const accordionId = "accordion-collapse-body";

  return (
    <div className="accordion-item not-prose my-4 rounded-xl border border-white/10 overflow-hidden transition-colors">
      <button
        type="button"
        onClick={() => setIsOpen(!isOpen)}
        className="accordion-header flex items-center justify-between w-full px-5 py-3.5 text-left hover:bg-white/[0.03] transition-colors"
        aria-expanded={isOpen}
        aria-controls={accordionId}
      >
        <span className="accordion-title text-base font-semibold">{title}</span>
        <svg
          className={`accordion-chevron w-5 h-5 shrink-0 text-white/40 transition-transform duration-200 ${isOpen ? "rotate-180" : ""}`}
          viewBox="0 0 20 20"
          fill="currentColor"
        >
          <path
            fillRule="evenodd"
            d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z"
            clipRule="evenodd"
          />
        </svg>
      </button>
      <div
        id={accordionId}
        className={`transition-all duration-200 ${isOpen ? "max-h-[2000px] opacity-100" : "max-h-0 opacity-0 overflow-hidden"}`}
        aria-labelledby="accordion-collapse-heading"
      >
        <div className="accordion-body px-5 pb-4 prose prose-invert prose-sm max-w-none">
          {children}
        </div>
      </div>
    </div>
  );
};

export default AccordionItem;
