// Some portions generated by Co-Pilot
import React from "react";
import { render, screen, fireEvent, cleanup } from "@testing-library/react";
import { describe, it, expect, afterEach, vi } from "vitest";
import DocumentationSearch from "../index";

describe("DocumentationSearch", () => {
  afterEach(() => {
    cleanup();
    vi.restoreAllMocks();
  });

  it("renders the input", () => {
    render(<DocumentationSearch />);
    expect(screen.getByRole("textbox")).toBeInTheDocument();
  });

  it("renders with compact mode", () => {
    render(<DocumentationSearch compact />);
    expect(screen.getByRole("textbox")).toBeInTheDocument();
  });

  it("sets showResults on focus", () => {
    render(<DocumentationSearch />);
    const input = screen.getByRole("textbox");
    fireEvent.focus(input);
    // No results to display, so dropdown should not appear
    expect(screen.queryByRole("link")).not.toBeInTheDocument();
  });

  it("hides dropdown when clicking outside", () => {
    render(<DocumentationSearch />);
    const input = screen.getByRole("textbox");
    fireEvent.focus(input);
    fireEvent.mouseDown(document.body);
    expect(screen.queryById?.("doc-search-dropdown")).toBeFalsy();
  });
});
