// Some portions generated by Co-Pilot
import React from "react";
import { render, cleanup } from "@testing-library/react";
import { describe, it, expect, afterEach, vi } from "vitest";

vi.mock("highcharts-react-official", () => ({
  default: ({ options }: { options: { title?: { text?: string } } }) => (
    <div data-testid="highcharts-react">{options?.title?.text}</div>
  ),
}));

import BarChart from "../index";

describe("BarChart", () => {
  afterEach(() => {
    cleanup();
  });

  it("renders nothing if no data", () => {
    const { container } = render(<BarChart name="Test Chart" />);
    expect(container.firstChild).toBeNull();
  });

  it("renders chart when data is provided", () => {
    const data = { linux: 100, windows: 200, mac: 150 };
    const { container } = render(
      <BarChart name="Downloads by OS" data={data} />,
    );
    expect(container.firstChild).not.toBeNull();
    expect(container.querySelector(".chart")).toBeTruthy();
  });

  it("renders chart with startCaseKeys=true", () => {
    const data = { linux_arm: 100, windows_x64: 200 };
    const { container } = render(
      <BarChart name="Downloads" data={data} startCaseKeys />,
    );
    expect(container.querySelector(".chart")).toBeTruthy();
  });

  it("renders chart with empty data object", () => {
    const data = {};
    const { container } = render(<BarChart name="Empty Chart" data={data} />);
    // Empty object is truthy, so chart should render
    expect(container.querySelector(".chart")).toBeTruthy();
  });

  it("renders with single data point", () => {
    const data = { linux: 500 };
    const { container } = render(<BarChart name="Single Point" data={data} />);
    expect(container.querySelector(".chart")).toBeTruthy();
  });
});
