// Some portions generated by Co-Pilot
= Paquets d'installation macOS PKG
:page-authors: gdams, SueChaplain, karianna
:page-based-on: 0e4cf731021aa6b80ca14281a511b2ce0584a64c
:toc:

Les paquets d'installation macOS d'Eclipse Temurin sont disponibles en fichiers .pkg standard, qui peuvent être exécutés avec une interface utilisateur interactive ou en mode silencieux depuis la ligne de commande Terminal.

== Installation graphique

Instructions pour exécuter une installation interactive à l'aide de l'installateur macOS PKG :

. link:/temurin/releases[Téléchargez] le fichier `.pkg`.
. Accédez au dossier contenant le fichier et ouvrez-le pour lancer le programme d'installation, ou faites glisser l'icône vers votre dossier Applications.
. L'écran d'introduction indique l'emplacement cible de l'installation, que vous pouvez modifier ultérieurement dans le processus d'installation. Cliquez sur Continuer.
. Lisez la licence, cliquez sur Continuer et acceptez la licence si vous êtes satisfait des conditions.
. Modifiez l'emplacement cible de l'installation. Cliquez sur Installer pour terminer l'installation.

== Installation en ligne de commande

Une installation silencieuse vous permet d'installer le paquet macOS sans interaction de l'utilisateur, ce qui peut être utile pour un déploiement à grande échelle. Vous devez disposer de privilèges administrateur. Suivez ces étapes :

. link:/temurin/releases[Téléchargez] le fichier `.pkg`.
. Lancez l'application Terminal (`terminal.app`).
. Exécutez la commande suivante :
+
[source, bash]
----
installer -pkg <path_to_pkg>/<pkg_name>.pkg -target /
----
. Entrez le mot de passe administrateur.
. Temurin s'installe dans
`/Library/Java/JavaVirtualMachines/temurin-<version>.<jdk|jre>/`
