// Some portions generated by Co-Pilot
= Pacotes de instalação macOS PKG
:page-authors: gdams, SueChaplain, karianna
:page-based-on: 0e4cf731021aa6b80ca14281a511b2ce0584a64c
:toc:

Os pacotes de instalação do Eclipse Temurin para macOS estão disponíveis como arquivos .pkg
padrão, que podem ser executados com uma interface de usuário interativa ou silenciosamente
pela linha de comando do Terminal.

== Instalação pela Interface Gráfica

Instruções para realizar uma instalação interativa usando o instalador PKG do macOS:

. link:/temurin/releases[Baixe] o arquivo `.pkg`.
. Navegue até a pasta que contém o arquivo e abra-o para iniciar
o programa de instalação, ou arraste o ícone para a sua pasta de Aplicativos.
. A tela de Introdução indica o local de destino para a
instalação, que pode ser alterado posteriormente no processo de instalação. Clique em
Continuar.
. Leia a licença, clique em Continuar e aceite a licença se você concordar com os termos.
. Altere o local de destino para a instalação, se necessário. Clique em Instalar para
concluir a instalação.

== Instalação pela Linha de Comando

Uma instalação silenciosa permite instalar o pacote macOS sem
interação do usuário, o que pode ser útil para implantações em larga escala. Você deve
ter privilégios de administrador. Siga estas etapas:

. link:/temurin/releases[Baixe] o arquivo `.pkg`.
. Abra o aplicativo Terminal (`terminal.app`).
. Execute o seguinte comando:
+
[source, bash]
----
installer -pkg <path_to_pkg>/<pkg_name>.pkg -target /
----
. Insira a senha de Administrador.
. O Temurin será instalado em
`/Library/Java/JavaVirtualMachines/temurin-<version>.<jdk|jre>/`
