// Some portions generated by Co-Pilot
= macOS PKG-Installationspakete
:page-authors: gdams
:page-based-on: 0e4cf731021aa6b80ca14281a511b2ce0584a64c
:toc:

Eclipse Temurin macOS-Installationspakete sind als Standard-.pkg-Dateien
verfügbar, die mit einer interaktiven Benutzeroberfläche oder im
Hintergrund über die Terminal-Befehlszeile ausgeführt werden können.

== GUI-Installation

Anleitung zur Durchführung einer interaktiven Installation mit dem macOS
PKG-Installer:

. link:/temurin/releases[Laden Sie] die `.pkg`-Datei herunter.
. Navigieren Sie zum Ordner, der die Datei enthält, und öffnen Sie sie,
um das Installationsprogramm zu starten, oder ziehen Sie das Symbol in
Ihren Programmordner.
. Der Einführungsbildschirm zeigt den Zielort für die Installation an,
den Sie später im Installationsprozess ändern können. Klicken Sie auf
Fortfahren.
. Lesen Sie die Lizenz, klicken Sie auf Fortfahren und akzeptieren Sie
die Lizenz, wenn Sie mit den Bedingungen einverstanden sind.
. Ändern Sie den Zielort für die Installation. Klicken Sie auf
Installieren, um die Installation abzuschließen.

== Befehlszeilen-Installation

Eine stille Installation ermöglicht es Ihnen, das macOS-Paket ohne
Benutzerinteraktion zu installieren, was für eine großflächige
Bereitstellung nützlich sein kann. Sie benötigen
Administratorrechte. Befolgen Sie diese Schritte:

. link:/temurin/releases[Laden Sie] die `.pkg`-Datei herunter.
. Starten Sie die Terminal-App (`terminal.app`).
. Führen Sie den folgenden Befehl aus:
+
[source, bash]
----
installer -pkg <path_to_pkg>/<pkg_name>.pkg -target /
----
. Geben Sie das Administratorpasswort ein
. Temurin wird installiert unter
`/Library/Java/JavaVirtualMachines/temurin-<version>.<jdk|jre>/`
