// Some portions generated by Co-Pilot
import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import License from "../index";

describe("License", () => {
  it("renders the license heading", () => {
    render(<License />);
    expect(
      screen.getByRole("heading", { name: /license/i })
    ).toBeInTheDocument();
  });

  it("renders license links with correct hrefs", () => {
    render(<License />);
    const links = screen.getAllByRole("link");
    const hrefs = links.map((link) => link.getAttribute("href"));
    expect(hrefs).toContain("https://www.apache.org/licenses/LICENSE-2.0");
    expect(hrefs).toContain("https://openjdk.java.net/legal/gplv2+ce.html");
    expect(hrefs).toContain("https://openjdk.java.net/legal/assembly-exception.html");
  });

  it("renders links with target=_blank", () => {
    render(<License />);
    const links = screen.getAllByRole("link");
    links.forEach((link) => {
      expect(link).toHaveAttribute("target", "_blank");
    });
  });

  it("renders within a section element", () => {
    const { container } = render(<License />);
    expect(container.querySelector("section")).toBeInTheDocument();
  });

  it("renders list items describing the licenses", () => {
    render(<License />);
    const listItems = screen.getAllByRole("listitem");
    expect(listItems.length).toBeGreaterThanOrEqual(2);
  });
});
