// Some portions generated by Co-Pilot
import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import ShareButton from "../index";

// Mock react-share components
vi.mock("react-share", () => ({
  XShareButton: ({ children, ...props }: any) => (
    <button aria-label={props["aria-label"]}>{children}</button>
  ),
  EmailShareButton: ({ children, ...props }: any) => (
    <button aria-label={props["aria-label"]}>{children}</button>
  ),
  FacebookShareButton: ({ children, ...props }: any) => (
    <button aria-label={props["aria-label"]}>{children}</button>
  ),
  LinkedinShareButton: ({ children, ...props }: any) => (
    <button aria-label={props["aria-label"]}>{children}</button>
  ),
  RedditShareButton: ({ children, ...props }: any) => (
    <button aria-label={props["aria-label"]}>{children}</button>
  ),
  BlueskyShareButton: ({ children, ...props }: any) => (
    <button aria-label={props["aria-label"]}>{children}</button>
  ),
}));

describe("ShareButton", () => {
  const defaultProps = {
    location: "https://adoptium.net/news/2024/03/test-post",
    siteMetadata: {
      siteUrl: "https://adoptium.net",
      social: {
        twitter: "@adoptium",
      },
    },
    post: {
      title: "Test Blog Post",
      tags: ["java", "temurin"],
    },
  };

  it("renders all share buttons", () => {
    render(<ShareButton {...defaultProps} />);
    expect(screen.getByLabelText("Share on X (Twitter)")).toBeInTheDocument();
    expect(screen.getByLabelText("Share on Linkedin")).toBeInTheDocument();
    expect(screen.getByLabelText("Share on Facebook")).toBeInTheDocument();
    expect(screen.getByLabelText("Share on Reddit")).toBeInTheDocument();
    expect(screen.getByLabelText("Share on Bluesky")).toBeInTheDocument();
    expect(screen.getByLabelText("Share via Email")).toBeInTheDocument();
  });

  it("renders share buttons", () => {
    render(<ShareButton {...defaultProps} />);
    const buttons = screen.getAllByRole("button");
    // 6 share buttons (may be doubled in strict mode)
    expect(buttons.length).toBeGreaterThanOrEqual(6);
  });

  it("renders the share buttons container", () => {
    const { container } = render(<ShareButton {...defaultProps} />);
    // The share-buttons div should be in the rendered output
    expect(container.firstChild).toBeInTheDocument();
  });
});
