// Some portions generated by Co-Pilot
import { Metadata } from "next";
import { Link } from "@/i18n/navigation";
import { getTranslations } from "next-intl/server";
import {
  FaDownload,
  FaQuestion,
  FaGithub,
  FaBox,
  FaInfoCircle,
  FaGlobe,
  FaGem,
  FaUserFriends,
  FaLock,
  FaRocket,
} from "react-icons/fa";

import DocumentationHeader from "@/components/Content/Documentation/Header";
import DocumentationCard from "@/components/Content/Documentation/Card";

export const metadata: Metadata = {
  title: "Documentation",
  description:
    "Find all the resources you need to get started with Eclipse Temurin, including installation guides, support information, contribution guidelines, and more. Explore our comprehensive documentation to make the most of your Temurin experience.",
};

export default async function DocumentationPage() {
  const t = await getTranslations("DocsPage");
  return (
    <div className="min-h-screen light:bg-white">
      <DocumentationHeader />
      <div className="py-6 md:py-10 light:bg-white">
        <div className="mx-auto max-w-[1200px] w-full px-6 lg:px-8">
          {/* Getting Started */}
          <div className="pb-8 mb-6 border-b border-white/[0.06] light:border-gray-200">
            <h2 className="text-base font-semibold text-white light:text-gray-900 mb-4">
              {t("getting-started")}
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
              {[
                {
                  title: t("install-temurin"),
                  desc: t("install-temurin-desc"),
                  href: "/installation",
                },
                {
                  title: t("download-temurin"),
                  desc: t("download-temurin-desc"),
                  href: "/temurin/releases",
                },
                {
                  title: t("migration-guide"),
                  desc: t("migration-guide-desc"),
                  href: "/temurin/migration",
                },
                {
                  title: t("supported-platforms"),
                  desc: t("supported-platforms-desc"),
                  href: "/supported-platforms",
                },
              ].map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  className="group block rounded-lg border border-white/[0.06] light:border-gray-200 p-4 hover:border-white/15 light:hover:border-gray-300 light:hover:bg-gray-50 transition-colors"
                >
                  <div className="text-sm font-medium text-white light:text-gray-900 group-hover:text-[#FF1464] light:group-hover:text-blue-600 transition-colors">
                    {item.title}
                  </div>
                  <div className="mt-1 text-xs text-gray-500 light:text-gray-500">
                    {item.desc}
                  </div>
                </Link>
              ))}
            </div>
          </div>

          {/* All categories */}
          <h2 className="text-base font-semibold text-white light:text-gray-900 mb-2">
            {t("explore-by-topic")}
          </h2>
          <div className="flex flex-wrap">
            <DocumentationCard
              title="Get Temurin"
              Icon={FaDownload}
              anchorId="get-temurin"
              links={[
                {
                  name: "Install Temurin",
                  link: "/installation",
                },
                {
                  name: "Download Temurin",
                  link: "/temurin/releases",
                },
                {
                  name: "Container Images",
                  link: "https://hub.docker.com/_/eclipse-temurin",
                },
              ]}
            />
            <DocumentationCard
              title="Temurin Support"
              Icon={FaQuestion}
              anchorId="temurin-support"
              links={[
                {
                  name: "Support Guide",
                  link: "/support",
                },
                {
                  name: "Commercial Support",
                  link: "/temurin/commercial-support",
                },
                {
                  name: "Migration Guide",
                  link: "/temurin/migration",
                },
                {
                  name: "Supported Platforms",
                  link: "/supported-platforms",
                },
                {
                  name: "Submit an Issue",
                  link: "https://github.com/adoptium/adoptium-support/issues",
                },
              ]}
            />
            <DocumentationCard
              title="AQAvit Quality"
              Icon={FaGem}
              anchorId="aqavit"
              links={[
                {
                  name: "About Eclipse AQAvit",
                  link: "/aqavit",
                },
                {
                  name: "AQAvit Quality Verification",
                  link: "/docs/qvs-policy",
                },
                {
                  name: "AQAvit Verification Guide",
                  link: "/docs/aqavit-verification",
                },
              ]}
            />
            <DocumentationCard
              title="Marketplace"
              Icon={FaBox}
              anchorId="marketplace"
              links={[
                {
                  name: "Marketplace Downloads",
                  link: "/marketplace",
                },
                {
                  name: "Marketplace Listing Information",
                  link: "/docs/marketplace-policy",
                },
                {
                  name: "Marketplace Publisher Guide",
                  link: "/docs/marketplace-guide",
                },
              ]}
            />
            <DocumentationCard
              title="Contributing"
              Icon={FaUserFriends}
              anchorId="contributing"
              links={[
                {
                  name: "How To Contribute",
                  link: "/contributing",
                },
                {
                  name: "First Timer Support",
                  link: "/docs/first-timer-support",
                },
                {
                  name: "Developer Nightly Builds",
                  link: "/temurin/nightly",
                },
                {
                  name: "Join our Slack Channel",
                  link: "/slack",
                },
                {
                  name: "Code of Conduct",
                  link: "https://github.com/adoptium/.github/blob/main/CODE_OF_CONDUCT.md",
                },
              ]}
            />
            <DocumentationCard
              title="Secure Software"
              Icon={FaLock}
              anchorId="secure-software"
              links={[
                {
                  name: "Secure Software Practices",
                  link: "/docs/secure-software",
                },
                {
                  name: "SLSA Secure Supply Chain",
                  link: "/docs/slsa",
                },
                {
                  name: "Vulnerability Reporting",
                  link: "https://github.com/adoptium/adoptium/security/policy",
                },
                {
                  name: "Temurin Security Case Study",
                  link: "https://outreach.eclipse.foundation/adoptium-temurin-supply-chain-security?utm_campaign=Temurin%20Case%20Study&utm_source=website&utm_medium=adoptium%20docs",
                },
                {
                  name: "Reproducible Verification Builds",
                  link: "/docs/reproducible-verification-builds",
                },
              ]}
            />
            <DocumentationCard
              title="Governance"
              Icon={FaGlobe}
              anchorId="governance"
              links={[
                {
                  name: "About Eclipse Adoptium",
                  link: "/about",
                },
                {
                  name: "Working Group Members",
                  link: "/members",
                },
                {
                  name: "Join the Working Group",
                  link: "/join",
                },
                {
                  name: "Sponsor the Project",
                  link: "https://www.eclipse.org/org/workinggroups/sponsorship/working-group-sponsorship-agreement.pdf",
                },
              ]}
            />
            <DocumentationCard
              title="Source Code"
              Icon={FaGithub}
              anchorId="source-code"
              links={[
                {
                  name: "Adoptium on GitHub",
                  link: "https://github.com/adoptium",
                },
                {
                  name: "Repository Overview",
                  link: "https://github.com/adoptium/adoptium/blob/main/README.md",
                },
                {
                  name: "Build Scripts",
                  link: "https://github.com/adoptium/temurin-build",
                },
                {
                  name: "Installer Code",
                  link: "https://github.com/adoptium/installer",
                },
                {
                  name: "Mission Control Build",
                  link: "https://github.com/adoptium/jmc-build",
                },
              ]}
            />
            <DocumentationCard
              title="Other Resources"
              Icon={FaInfoCircle}
              anchorId="other-resources"
              links={[
                {
                  name: "Frequently Asked Questions",
                  link: "/docs/faq",
                },
                {
                  name: "Adoptium API",
                  link: "https://api.adoptium.net",
                },
                {
                  name: "Adoptium News",
                  link: "/news",
                },
                {
                  name: "Join Us",
                  link: "/join-us",
                },
                {
                  name: "Temurin Download Statistics",
                  link: "/stats/download",
                },
              ]}
            />
            <DocumentationCard
              title="Branding"
              Icon={FaRocket}
              anchorId="branding"
              links={[
                {
                  name: "Brand Guidelines",
                  link: "https://www.eclipse.org/org/artwork/guidelines/adoptium-brand-guidelines.pdf",
                },
                {
                  name: "Google Slide Template",
                  link: "https://docs.google.com/presentation/d/1ChGhqZrAHCdk5S2Ii5s5RROng1saTaTtjZzsxWJ_MPA/copy",
                },
                {
                  name: "Logo and Artwork",
                  link: "/docs/logo-styleguide/",
                },
                {
                  name: "Download Buttons",
                  link: "/temurin/buttons",
                },
                {
                  name: "Marketing Criteria",
                  link: "/docs/marketing-criteria",
                },
              ]}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
