// Some portions generated by Co-Pilot
= Criterios de marketing de Adoptium(R)
:description: Adoptium Marketing Criteria
:keywords: adoptium marketing
:orgname: Eclipse Adoptium
:page-authors: Ndacyayisenga-droid, gdams
:page-based-on: f2e6e929f64dd6ef7bd7f452d2aed14095705a31

El Grupo de Trabajo Adoptium ha definido cómo compartir y publicar un evento, noticia o publicación en redes sociales; la decisión final sobre la publicación es tomada y gestionada por el comité de marketing de Adoptium. El comité utiliza el canal de Slack de Adoptium #marketing, y esta información también se comparte a través de los canales #community y #buzz.

== Compartir un evento

El objetivo de esta sección es definir los criterios adecuados para publicar y compartir un evento en Adoptium / noticias y eventos https://adoptium.net/news/

1. El Community Manager o cualquier miembro de Adoptium puede solicitar la publicación de un evento si:

- Algunos miembros de la comunidad Adoptium asisten.
- El grupo de trabajo Adoptium es patrocinador, o
- Hay sesiones sobre Adoptium

2. Como comunidad, hacemos seguimiento de todos los posibles eventos a los que asistir mediante una lista interna https://docs.google.com/spreadsheets/d/1sSzIkTrujZRPbqq1ao6EA4E6WIQK-qqPp2QZNEChDEs/edit#gid=446200723[Adoptium_List of Conferences and Event^]. Una vez confirmado uno o más de los criterios explicados anteriormente, podemos continuar con el proceso.

3. El responsable debe solicitar la publicación enviando el evento aquí https://newsroom.eclipse.org/node/add/events. Tenga en cuenta que si se trata de un evento compartido con otros grupos de trabajo de Eclipse Foundation, la descripción será estándar y revisada por el equipo de marketing, ya que este equipo es el responsable de la moderación de eventos.

4. Recuerde compartir el evento también en el canal https://adoptium.slack.com/archives/C01BUN6GJUB[#community^].

== Compartir noticias

El objetivo de este documento es definir los criterios adecuados para publicar y compartir una noticia en Adoptium / noticias y eventos https://adoptium.net/news/

1. El Community Manager o cualquier miembro de Adoptium puede solicitar la publicación de una noticia si:

- El artículo o entrada de blog habla de alguno de los proyectos Eclipse Adoptium: https://projects.eclipse.org/projects/adoptium, creado por un tercero o por un miembro de Adoptium.
- El grupo de trabajo Adoptium patrocina o crea la noticia, o

2. Por favor, use el canal https://adoptium.slack.com/archives/C88P3DL86[#buzz^] o https://adoptium.slack.com/archives/C02BADFQZK5R[#marketing^] para informar sobre esta noticia.

3. El responsable (Community Manager o miembro de la comunidad) debe solicitar la publicación enviando la noticia aquí https://newsroom.eclipse.org/node/add/news, o enviando un correo electrónico a: news@eclipse.org

- Al enviar la noticia mediante el newsroom, en "publishing information" seleccione "Eclipse" y "Adoptium", y añada una breve introducción. Tenga en cuenta que el equipo de marketing de Eclipse modera este contenido. Tiene la oportunidad de compartir la noticia bajo las noticias de Adoptium y también como parte de los anuncios de Eclipse https://newsroom.eclipse.org/eclipse/announcements/ o noticias de la comunidad https://newsroom.eclipse.org/eclipse/community-news/

- Al enviar la noticia por correo electrónico, proporcione un resumen de la noticia, indique quién es el miembro de Adoptium involucrado, comparta su usuario en redes sociales si está de acuerdo, y solicite compartir la noticia en anuncios o noticias de la comunidad si aplica.

4. El equipo de marketing compartirá la noticia utilizando las cuentas de redes sociales de Adoptium. Si la noticia ya fue compartida, infórmelo como una nota separada en el campo de resumen o en el correo electrónico, y comparta el enlace, ya que es posible que solo amplíen la publicación existente.

== Publicaciones en redes sociales

Como parte del comité de marketing, si desea publicar algo en las redes sociales de Adoptium LinkedIn: https://www.linkedin.com/showcase/adoptium/ y Twitter: https://twitter.com/adoptium, siga estos pasos:

- Solicite al equipo de marketing de Eclipse que comparta una publicación en redes sociales enviando un correo electrónico a news@eclipse.org.
- Utilizaremos los mismos criterios para compartir noticias explicados anteriormente.
- Comparta el enlace de la noticia, explique el motivo para compartirla, indique quién es el miembro de Adoptium involucrado y comparta su usuario en redes sociales si está de acuerdo.
- Realice un proceso de revisión con otra persona del equipo de Eclipse o Adoptium antes de compartir cualquier contenido en redes sociales.
- Si un miembro específico de Adoptium es el autor de la noticia o artículo, debe mencionarse su usuario en redes sociales (con autorización previa). Si la noticia involucra a más miembros del equipo, mencione al miembro del PMC o WG. Sea específico sobre esto al solicitar una publicación en redes sociales.
