// Some portions generated by Co-Pilot
= Critères Marketing d'Adoptium(R)
:description: Critères marketing Adoptium
:keywords: adoptium marketing
:orgname: Eclipse Adoptium
:page-authors: Ndacyayisenga-droid, gdams
:page-based-on: f2e6e929f64dd6ef7bd7f452d2aed14095705a31

Le Groupe de Travail Adoptium a défini comment partager et publier un événement, une actualité ou une publication sur les réseaux sociaux ; la décision finale de publication est prise et gérée par le comité marketing d'Adoptium. Le comité utilise le canal Slack Adoptium #marketing, et ces informations sont également partagées via les canaux #community et #buzz.

== Partager un événement

L'objectif de cette partie est de définir les critères appropriés pour publier et partager un événement sur la page https://adoptium.net/news/[Adoptium / actualités et événements].

1. Le Community Manager ou tout membre d'Adoptium peut demander la publication d'un événement si :

- Des membres de la communauté Adoptium y participent.
- Le groupe de travail Adoptium sponsorise l'événement, ou
- Il y a des sessions sur Adoptium

2. En tant que communauté, nous suivons tous les événements potentiels auxquels participer à l'aide d'une liste interne https://docs.google.com/spreadsheets/d/1sSzIkTrujZRPbqq1ao6EA4E6WIQK-qqPp2QZNEChDEs/edit#gid=446200723[Adoptium_Liste des Conférences et Événements^]. Une fois que nous avons confirmé un ou plusieurs des critères expliqués ci-dessus, nous pouvons poursuivre le processus.

3. Le responsable doit demander la publication en soumettant l'événement ici https://newsroom.eclipse.org/node/add/events. Gardez à l'esprit que s'il s'agit d'un événement partagé avec d'autres groupes de travail de la Fondation Eclipse, la description sera standard et revue par l'équipe marketing, car cette équipe est responsable de la modération des événements.

4. N'oubliez pas de partager l'événement sur le canal https://adoptium.slack.com/archives/C01BUN6GJUB[#community^] également.

== Partager des actualités

L'objectif de ce document est de définir les critères appropriés pour publier et partager une actualité sur la page https://adoptium.net/news/[Adoptium / actualités et événements].

1. Le Community Manager ou tout membre d'Adoptium peut demander la publication d'une actualité si :

- L'article ou le billet de blog parle de l'un des projets Eclipse Adoptium : https://projects.eclipse.org/projects/adoptium, créé par un tiers ou par un membre d'Adoptium.
- Le groupe de travail Adoptium sponsorise ou crée l'actualité, ou

2. Veuillez utiliser le canal https://adoptium.slack.com/archives/C88P3DL86[#buzz^] ou https://adoptium.slack.com/archives/C02BADFQZK5R[#marketing^] pour informer de cette actualité.

3. Le responsable (Community Manager ou membre de la communauté) doit demander la publication en soumettant l'actualité ici https://newsroom.eclipse.org/node/add/news. Ou envoyer un e-mail à : news@eclipse.org

- Lors de la soumission de l'actualité via la newsroom, dans « informations de publication », sélectionnez « Eclipse » et « Adoptium », et ajoutez une brève introduction. Gardez à l'esprit que l'équipe marketing d'Eclipse modère ce contenu. Vous avez la possibilité de partager l'actualité sous les actualités Adoptium et également dans les annonces Eclipse https://newsroom.eclipse.org/eclipse/announcements/ ou les actualités communautaires https://newsroom.eclipse.org/eclipse/community-news/

- Lors de la soumission de l'actualité par e-mail, veuillez donner un résumé de l'actualité, qui est le membre Adoptium impliqué ; partagez leur profil de réseau social s'ils sont d'accord, et demandez de partager l'actualité dans les annonces ou les actualités communautaires si applicable.

4. L'équipe marketing partagera l'actualité via les comptes de réseaux sociaux d'Adoptium. SI l'actualité a déjà été partagée, informez en note séparée dans le champ de résumé ou l'e-mail et partagez le lien, car ils pourraient simplement amplifier la publication existante.

== Publication sur les réseaux sociaux

En tant que membre du comité marketing, si vous souhaitez publier quelque chose sur les réseaux sociaux d'Adoptium LinkedIn : https://www.linkedin.com/showcase/adoptium/ et Twitter : https://twitter.com/adoptium, veuillez suivre ces étapes :

- Demandez à l'équipe marketing d'Eclipse de partager une publication sur les réseaux sociaux en envoyant un e-mail à news@eclipse.org.
- Nous utiliserons les mêmes critères pour partager les actualités, expliqués ci-dessus.
- Partagez le lien de l'actualité, expliquez la raison du partage, indiquez qui est le membre Adoptium impliqué, et partagez leur profil de réseau social s'ils sont d'accord.
- Effectuez un processus de relecture avec quelqu'un d'autre de l'équipe Eclipse ou Adoptium avant de partager tout contenu sur les réseaux sociaux.
- Si un membre spécifique d'Adoptium est l'auteur de l'actualité ou de l'article, nous devons mentionner leur profil de réseau social (avec autorisation préalable). Si l'actualité implique davantage de membres de l'équipe, mentionnez le PMC ou le membre du groupe de travail. Soyez précis à ce sujet lors de la demande de publication sur les réseaux sociaux.
