// Some portions generated by Co-Pilot
= Adoptium(R) Marketingkriterien
:description: Adoptium Marketing Criteria
:keywords: adoptium marketing
:orgname: Eclipse Adoptium
:page-authors: Ndacyayisenga-droid, gdams
:page-based-on: f2e6e929f64dd6ef7bd7f452d2aed14095705a31

Die Adoptium-Arbeitsgruppe hat festgelegt, wie ein Ereignis, eine Neuigkeit oder ein Social-Media-Beitrag geteilt und veröffentlicht werden soll; die endgültige Entscheidung über das Veröffentlichen wird vom Adoptium-Marketingausschuss getroffen und verwaltet. Der Ausschuss nutzt den Adoptium Slack-Kanal #marketing, und diese Informationen werden auch über die Kanäle #community und #buzz geteilt.

== Ein Ereignis teilen

Das Ziel dieses Abschnitts ist es, geeignete Kriterien für die Veröffentlichung und das Teilen eines Ereignisses auf der Adoptium-Nachrichten- und Ereignisseite https://adoptium.net/news/ zu definieren.

1. Der Community-Manager oder ein beliebiges Adoptium-Mitglied kann eine Ereignisveröffentlichung beantragen, wenn:

- Einige Adoptium-Community-Mitglieder teilnehmen.
- Die Adoptium-Arbeitsgruppe sponsert, oder
- Es Sitzungen über Adoptium gibt

2. Als Community verfolgen wir alle möglichen Veranstaltungen, die wir besuchen möchten, mithilfe einer internen Liste https://docs.google.com/spreadsheets/d/1sSzIkTrujZRPbqq1ao6EA4E6WIQK-qqPp2QZNEChDEs/edit#gid=446200723[Adoptium_List of Conferences and Event^]. Sobald wir eines oder mehrere der oben erläuterten Kriterien bestätigt haben, können wir mit dem Prozess fortfahren.

3. Der Verantwortliche sollte die Veröffentlichung beantragen, indem er das Ereignis hier einreicht: https://newsroom.eclipse.org/node/add/events. Beachten Sie, dass bei einem gemeinsamen Ereignis mit anderen Eclipse Foundation-Arbeitsgruppen die Beschreibung standardisiert und vom Marketingteam überprüft wird, da dieses Team für die Ereignismoderation verantwortlich ist.

4. Denken Sie daran, das Ereignis auch im https://adoptium.slack.com/archives/C01BUN6GJUB[#community^]-Kanal zu teilen.

== Nachrichten teilen

Das Ziel dieses Dokuments ist es, geeignete Kriterien für die Veröffentlichung und das Teilen einer Neuigkeit auf der Adoptium-Nachrichten- und Ereignisseite https://adoptium.net/news/ zu definieren.

1. Der Community-Manager oder ein beliebiges Adoptium-Mitglied kann eine Nachrichtenveröffentlichung beantragen, wenn:

- Der Artikel oder Blog-Beitrag über eines der Eclipse Adoptium-Projekte spricht: https://projects.eclipse.org/projects/adoptium, erstellt von einem Dritten oder einem Adoptium-Mitglied.
- Die Adoptium-Arbeitsgruppe sponsert oder die Nachricht erstellt, oder

2. Bitte verwenden Sie den https://adoptium.slack.com/archives/C88P3DL86[#buzz^]- oder https://adoptium.slack.com/archives/C02BADFQZK5R[#marketing^]-Kanal, um über diese Neuigkeit zu informieren.

3. Der Verantwortliche (Community-Manager oder Community-Mitglied) sollte die Veröffentlichung beantragen, indem er die Neuigkeit hier einreicht: https://newsroom.eclipse.org/node/add/news. Oder senden Sie eine E-Mail an: news@eclipse.org

- Wählen Sie beim Einreichen der Neuigkeit über das Newsroom unter „Veröffentlichungsinformationen" „Eclipse" und „Adoptium" aus, und fügen Sie eine kurze Einführung hinzu. Beachten Sie, dass das Eclipse-Marketingteam diesen Inhalt moderiert. Sie haben die Möglichkeit, die Nachricht unter den Adoptium-Nachrichten und auch als Teil der Eclipse Announcements https://newsroom.eclipse.org/eclipse/announcements/ oder Community-Nachrichten https://newsroom.eclipse.org/eclipse/community-news/ zu teilen.

- Geben Sie beim Einreichen der Neuigkeit per E-Mail eine Nachrichtenzusammenfassung an, wer das beteiligte Adoptium-Mitglied ist; teilen Sie ggf. deren Social-Media-Handle (mit deren Einverständnis) und bitten Sie darum, die Neuigkeit ggf. bei Ankündigungs- oder Community-Nachrichten zu teilen.

4. Das Marketingteam wird die Neuigkeit über Adoptiums Social-Media-Konten teilen. Wenn die Nachricht bereits geteilt wurde, geben Sie dies als separaten Hinweis im Zusammenfassungsbearbeitungsfeld oder in der E-Mail an und teilen Sie den Link, da diese möglicherweise nur den aktuellen Beitrag verstärken.

== Social-Media-Beiträge

Als Teil des Marketingausschusses, wenn Sie etwas auf Adoptiums Social-Media LinkedIn: https://www.linkedin.com/showcase/adoptium/ und Twitter: https://twitter.com/adoptium veröffentlichen möchten, befolgen Sie bitte diese Schritte:

- Bitten Sie das Eclipse-Marketingteam, einen Social-Media-Beitrag zu teilen, indem Sie eine E-Mail an news@eclipse.org senden.
- Wir verwenden dieselben Kriterien für das Teilen von Nachrichten, die oben erläutert wurden.
- Teilen Sie den Nachrichtenlink, erläutern Sie den Grund für das Teilen, nennen Sie das beteiligte Adoptium-Mitglied und teilen Sie deren Social-Media-Handle (mit deren Einverständnis).
- Führen Sie einen Korrekturlese-Prozess mit einer anderen Person aus dem Eclipse- oder Adoptium-Team durch, bevor Sie Social-Media-Inhalte teilen.
- Wenn ein bestimmtes Adoptium-Mitglied die Neuigkeit oder den Artikel verfasst hat, sollten wir deren Social-Media-Handle erwähnen (mit vorheriger Genehmigung). Wenn die Neuigkeit mehr Teammitglieder impliziert, erwähnen Sie das PMC- oder WG-Mitglied. Seien Sie bei der Anforderung eines Social-Media-Beitrags diesbezüglich spezifisch.
