// Some portions generated by Co-Pilot
import {
  MarketplaceBinaryAssetView,
  fetchMarketplaceReleases,
  type MarketplaceVendor,
} from "@/services/adoptiumApi";
import type { components as marketplaceComponents } from "@/types/marketplaceApiTypes";

type Distribution = marketplaceComponents["schemas"]["Distribution"];
type OperatingSystem =
  | marketplaceComponents["schemas"]["OperatingSystem"]
  | "any";
type Architecture = marketplaceComponents["schemas"]["Architecture"] | "any";
type ImageType = marketplaceComponents["schemas"]["ImageType"] | "any";

export type MarketplaceRelease = MarketplaceBinaryAssetView;

export interface MarketplaceReleaseAsset {
  binary: {
    distribution: string;
  };
}

export async function getAllPkgsForVersion(
  version: number,
  os: string,
  architecture: string,
  package_type: string,
  vendors: string[] = [],
): Promise<MarketplaceRelease[] | null> {
  return fetchMarketplaceReleases({
    version,
    os:
      os !== "any"
        ? (os as marketplaceComponents["schemas"]["OperatingSystem"])
        : undefined,
    architecture:
      architecture !== "any"
        ? (architecture as marketplaceComponents["schemas"]["Architecture"])
        : undefined,
    package_type:
      package_type !== "any"
        ? (package_type as marketplaceComponents["schemas"]["ImageType"])
        : undefined,
    vendors: vendors as MarketplaceVendor[],
  }) as Promise<MarketplaceRelease[] | null>;
}

export function getImageForDistribution(distribution: Distribution) {
  switch (distribution) {
    case "temurin":
      return "/images/vendors/adoptium-logo.png";
    case "redhat":
      return "/images/members/redhat.svg";
    case "zulu":
      return "/images/vendors/azul-logo.png";
    case "semeru":
      return "/images/members/ibm-logo.png";
    case "microsoft":
      return "/images/members/microsoft.svg";
    default:
      return `/images/vendors/${distribution}-logo.png`;
  }
}
