// Some portions generated by Co-Pilot
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  fetchLatestAssets,
  fetchFeatureReleases,
  fetchReleaseNotes,
  fetchLatestReleaseName,
  fetchOperatingSystems,
  fetchArchitectures,
  fetchAttestations,
  fetchDownloadStats,
  fetchMarketplaceReleases,
} from "../adoptiumApi";

const { mockAdoptiumGet, mockMarketplaceGet } = vi.hoisted(() => ({
  mockAdoptiumGet: vi.fn(),
  mockMarketplaceGet: vi.fn(),
}));

vi.mock("openapi-fetch", () => ({
  default: vi.fn((options: { baseUrl: string }) => ({
    GET: options.baseUrl.includes("marketplace")
      ? mockMarketplaceGet
      : mockAdoptiumGet,
  })),
}));

afterEach(() => {
  vi.clearAllMocks();
});

// ---------------------------------------------------------------------------
// fetchLatestAssets
// ---------------------------------------------------------------------------
describe("fetchLatestAssets", () => {
  it("returns data on success", async () => {
    const mockData = [{ release_name: "jdk-21+35" }];
    mockAdoptiumGet.mockResolvedValue({ data: mockData, error: null });

    const result = await fetchLatestAssets(21);
    expect(result).toEqual(mockData);
    expect(mockAdoptiumGet).toHaveBeenCalledOnce();
  });

  it("returns empty array when data is null", async () => {
    mockAdoptiumGet.mockResolvedValue({ data: null, error: null });

    const result = await fetchLatestAssets(21);
    expect(result).toEqual([]);
  });

  it("throws on API error", async () => {
    mockAdoptiumGet.mockResolvedValue({
      data: null,
      error: { message: "not found" },
    });

    await expect(fetchLatestAssets(21)).rejects.toEqual({
      message: "not found",
    });
  });

  it("parses string version to number", async () => {
    mockAdoptiumGet.mockResolvedValue({ data: [], error: null });

    await fetchLatestAssets("17");
    const callArgs = mockAdoptiumGet.mock.calls[0][1];
    expect(callArgs.params.path.feature_version).toBe(17);
  });

  it("passes os and architecture query params", async () => {
    mockAdoptiumGet.mockResolvedValue({ data: [], error: null });

    await fetchLatestAssets(21, { os: "linux", architecture: "x64" });
    const callArgs = mockAdoptiumGet.mock.calls[0][1];
    expect(callArgs.params.query.os).toBe("linux");
    expect(callArgs.params.query.architecture).toBe("x64");
  });
});

// ---------------------------------------------------------------------------
// fetchFeatureReleases
// ---------------------------------------------------------------------------
describe("fetchFeatureReleases", () => {
  it("returns data and pagecount from header", async () => {
    const mockData = [{ release_name: "jdk-21+35" }];
    const mockHeaders = {
      get: vi.fn((key: string) => (key === "pagecount" ? "5" : null)),
    };
    mockAdoptiumGet.mockResolvedValue({
      data: mockData,
      error: null,
      response: { headers: mockHeaders },
    });

    const result = await fetchFeatureReleases(21, "ga");
    expect(result.data).toEqual(mockData);
    expect(result.pagecount).toBe(5);
  });

  it("falls back to PageCount header", async () => {
    const mockHeaders = {
      get: vi.fn((key: string) => (key === "PageCount" ? "3" : null)),
    };
    mockAdoptiumGet.mockResolvedValue({
      data: [],
      error: null,
      response: { headers: mockHeaders },
    });

    const result = await fetchFeatureReleases(21, "ga");
    expect(result.pagecount).toBe(3);
  });

  it("defaults pagecount to 0 when headers are absent", async () => {
    const mockHeaders = { get: vi.fn(() => null) };
    mockAdoptiumGet.mockResolvedValue({
      data: [],
      error: null,
      response: { headers: mockHeaders },
    });

    const result = await fetchFeatureReleases(21, "ga");
    expect(result.pagecount).toBe(0);
  });

  it("returns empty array when data is null", async () => {
    const mockHeaders = { get: vi.fn(() => null) };
    mockAdoptiumGet.mockResolvedValue({
      data: null,
      error: null,
      response: { headers: mockHeaders },
    });

    const result = await fetchFeatureReleases(21, "ga");
    expect(result.data).toEqual([]);
  });

  it("throws on API error", async () => {
    const mockHeaders = { get: vi.fn(() => null) };
    mockAdoptiumGet.mockResolvedValue({
      data: null,
      error: { message: "server error" },
      response: { headers: mockHeaders },
    });

    await expect(fetchFeatureReleases(21, "ga")).rejects.toEqual({
      message: "server error",
    });
  });
});

// ---------------------------------------------------------------------------
// fetchReleaseNotes
// ---------------------------------------------------------------------------
describe("fetchReleaseNotes", () => {
  it("returns data on success", async () => {
    const mockData = { release_name: "jdk-21+35", release_notes: [] };
    mockAdoptiumGet.mockResolvedValue({ data: mockData, error: null });

    const result = await fetchReleaseNotes("jdk-21+35");
    expect(result).toEqual(mockData);
  });

  it("throws on API error", async () => {
    mockAdoptiumGet.mockResolvedValue({
      data: null,
      error: { message: "not found" },
    });

    await expect(fetchReleaseNotes("jdk-21+35")).rejects.toEqual({
      message: "not found",
    });
  });
});

// ---------------------------------------------------------------------------
// fetchLatestReleaseName
// ---------------------------------------------------------------------------
describe("fetchLatestReleaseName", () => {
  it("returns first release name on success", async () => {
    mockAdoptiumGet.mockResolvedValue({
      data: { releases: ["jdk-21.0.3+9"] },
      error: null,
    });

    const result = await fetchLatestReleaseName();
    expect(result).toBe("jdk-21.0.3+9");
  });

  it("returns null on API error", async () => {
    mockAdoptiumGet.mockResolvedValue({
      data: null,
      error: { message: "error" },
    });

    const result = await fetchLatestReleaseName();
    expect(result).toBeNull();
  });

  it("returns null when releases array is empty", async () => {
    mockAdoptiumGet.mockResolvedValue({ data: { releases: [] }, error: null });

    const result = await fetchLatestReleaseName();
    expect(result).toBeNull();
  });

  it("returns null when data has no releases property", async () => {
    mockAdoptiumGet.mockResolvedValue({ data: {}, error: null });

    const result = await fetchLatestReleaseName();
    expect(result).toBeNull();
  });

  it("returns null when request throws", async () => {
    mockAdoptiumGet.mockRejectedValue(new Error("network error"));

    const result = await fetchLatestReleaseName();
    expect(result).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// fetchOperatingSystems
// ---------------------------------------------------------------------------
describe("fetchOperatingSystems", () => {
  it("returns list of OS strings", async () => {
    const mockData = ["linux", "windows", "mac"];
    mockAdoptiumGet.mockResolvedValue({ data: mockData, error: null });

    const result = await fetchOperatingSystems();
    expect(result).toEqual(mockData);
  });

  it("returns empty array when data is null", async () => {
    mockAdoptiumGet.mockResolvedValue({ data: null, error: null });

    const result = await fetchOperatingSystems();
    expect(result).toEqual([]);
  });

  it("throws on API error", async () => {
    mockAdoptiumGet.mockResolvedValue({
      data: null,
      error: { message: "error" },
    });

    await expect(fetchOperatingSystems()).rejects.toEqual({ message: "error" });
  });

  it("forwards AbortSignal to the request", async () => {
    mockAdoptiumGet.mockResolvedValue({ data: [], error: null });
    const signal = new AbortController().signal;

    await fetchOperatingSystems(signal);
    expect(mockAdoptiumGet).toHaveBeenCalledWith(
      "/v3/types/operating_systems",
      expect.objectContaining({ signal }),
    );
  });
});

// ---------------------------------------------------------------------------
// fetchArchitectures
// ---------------------------------------------------------------------------
describe("fetchArchitectures", () => {
  it("returns list of architecture strings", async () => {
    const mockData = ["x64", "aarch64", "ppc64le"];
    mockAdoptiumGet.mockResolvedValue({ data: mockData, error: null });

    const result = await fetchArchitectures();
    expect(result).toEqual(mockData);
  });

  it("returns empty array when data is null", async () => {
    mockAdoptiumGet.mockResolvedValue({ data: null, error: null });

    const result = await fetchArchitectures();
    expect(result).toEqual([]);
  });

  it("throws on API error", async () => {
    mockAdoptiumGet.mockResolvedValue({
      data: null,
      error: { message: "error" },
    });

    await expect(fetchArchitectures()).rejects.toEqual({ message: "error" });
  });
});

// ---------------------------------------------------------------------------
// fetchAttestations
// ---------------------------------------------------------------------------
describe("fetchAttestations", () => {
  it("returns attestations on success", async () => {
    const mockData = [{ release_name: "jdk-21+35" }];
    mockAdoptiumGet.mockResolvedValue({
      data: mockData,
      error: null,
      response: { status: 200 },
    });

    const result = await fetchAttestations("jdk-21+35");
    expect(result).toEqual(mockData);
  });

  it("returns empty array on 404", async () => {
    mockAdoptiumGet.mockResolvedValue({
      data: null,
      error: { message: "not found" },
      response: { status: 404 },
    });

    const result = await fetchAttestations("jdk-21+35");
    expect(result).toEqual([]);
  });

  it("throws on non-404 errors", async () => {
    mockAdoptiumGet.mockResolvedValue({
      data: null,
      error: { message: "server error" },
      response: { status: 500 },
    });

    await expect(fetchAttestations("jdk-21+35")).rejects.toEqual({
      message: "server error",
    });
  });

  it("returns empty array when data is null on success", async () => {
    mockAdoptiumGet.mockResolvedValue({
      data: null,
      error: null,
      response: { status: 200 },
    });

    const result = await fetchAttestations("jdk-21+35");
    expect(result).toEqual([]);
  });

  it("uses default project 'jdk'", async () => {
    mockAdoptiumGet.mockResolvedValue({
      data: [],
      error: null,
      response: { status: 200 },
    });

    await fetchAttestations("jdk-21+35");
    const callArgs = mockAdoptiumGet.mock.calls[0][1];
    expect(callArgs.params.query.project).toBe("jdk");
  });
});

// ---------------------------------------------------------------------------
// fetchDownloadStats
// ---------------------------------------------------------------------------
describe("fetchDownloadStats", () => {
  let fetchSpy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => {
    fetchSpy = vi.spyOn(global, "fetch");
  });

  afterEach(() => {
    fetchSpy.mockRestore();
  });

  it("returns parsed JSON on success", async () => {
    const mockStats = { total: 1234 };
    fetchSpy.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve(mockStats),
    } as Response);

    const result = await fetchDownloadStats("jdk-21+35");
    expect(result).toEqual(mockStats);
  });

  it("returns null when response is not ok", async () => {
    fetchSpy.mockResolvedValue({ ok: false } as Response);

    const result = await fetchDownloadStats("jdk-21+35");
    expect(result).toBeNull();
  });

  it("appends subpath to URL when provided", async () => {
    fetchSpy.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({}),
    } as Response);

    await fetchDownloadStats("jdk-21+35", "linux");
    expect(fetchSpy).toHaveBeenCalledWith(
      "https://api.adoptium.net/stats/downloads/total/jdk-21+35/linux",
    );
  });

  it("omits subpath when not provided", async () => {
    fetchSpy.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({}),
    } as Response);

    await fetchDownloadStats("jdk-21+35");
    expect(fetchSpy).toHaveBeenCalledWith(
      "https://api.adoptium.net/stats/downloads/total/jdk-21+35",
    );
  });
});

// ---------------------------------------------------------------------------
// fetchMarketplaceReleases
// ---------------------------------------------------------------------------
describe("fetchMarketplaceReleases", () => {
  it("returns data on success", async () => {
    const mockData = [{ release_name: "jdk-21+35" }];
    mockMarketplaceGet.mockResolvedValue({ data: mockData, error: null });

    const result = await fetchMarketplaceReleases({ version: 21, vendors: [] });
    expect(result).toEqual(mockData);
  });

  it("returns null when data is null", async () => {
    mockMarketplaceGet.mockResolvedValue({ data: null, error: null });

    const result = await fetchMarketplaceReleases({ version: 21, vendors: [] });
    expect(result).toBeNull();
  });

  it("returns null on API error", async () => {
    mockMarketplaceGet.mockResolvedValue({
      data: null,
      error: { message: "error" },
    });

    const result = await fetchMarketplaceReleases({ version: 21, vendors: [] });
    expect(result).toBeNull();
  });

  it("returns null when request throws", async () => {
    mockMarketplaceGet.mockRejectedValue(new Error("network error"));

    const result = await fetchMarketplaceReleases({ version: 21, vendors: [] });
    expect(result).toBeNull();
  });

  it("includes os in query when provided", async () => {
    mockMarketplaceGet.mockResolvedValue({ data: [], error: null });

    await fetchMarketplaceReleases({ version: 21, os: "linux", vendors: [] });
    const callArgs = mockMarketplaceGet.mock.calls[0][1];
    expect(callArgs.params.query.os).toEqual(["linux"]);
  });

  it("includes architecture in query when provided", async () => {
    mockMarketplaceGet.mockResolvedValue({ data: [], error: null });

    await fetchMarketplaceReleases({
      version: 21,
      architecture: "x64",
      vendors: [],
    });
    const callArgs = mockMarketplaceGet.mock.calls[0][1];
    expect(callArgs.params.query.architecture).toEqual(["x64"]);
  });

  it("includes image_type in query when package_type is provided", async () => {
    mockMarketplaceGet.mockResolvedValue({ data: [], error: null });

    await fetchMarketplaceReleases({
      version: 21,
      package_type: "jdk",
      vendors: [],
    });
    const callArgs = mockMarketplaceGet.mock.calls[0][1];
    expect(callArgs.params.query.image_type).toEqual(["jdk"]);
  });

  it("omits os from query when not provided", async () => {
    mockMarketplaceGet.mockResolvedValue({ data: [], error: null });

    await fetchMarketplaceReleases({ version: 21, vendors: [] });
    const callArgs = mockMarketplaceGet.mock.calls[0][1];
    expect(callArgs.params.query.os).toBeUndefined();
  });
});
