// Some portions generated by Co-Pilot
import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import NewsCardList from "../index";

// Mock the useLocale hook for EventCard
vi.mock("next-intl", async () => {
  const actual = await vi.importActual("next-intl");
  return {
    ...actual as object,
    useLocale: () => "en",
  };
});

const createMockPost = (overrides: Partial<any> = {}) => ({
  slug: "test-post",
  year: "2024",
  month: "03",
  metadata: {
    title: "Test Post",
    description: "Test description",
    date: "2024-03-15",
    tags: ["java"],
    ...overrides,
  },
});

describe("NewsCardList", () => {
  const defaultProps = {
    posts: [
      createMockPost({ title: "Post 1" }),
      createMockPost({ title: "Post 2" }),
      createMockPost({ title: "Post 3" }),
    ],
    previousPageNumber: null,
    previousPageLink: null,
    nextPage: "",
    currentPage: 1,
    totalPages: 1,
    baseUrl: "/news",
  };

  it("renders all posts", () => {
    render(<NewsCardList {...defaultProps} />);
    expect(screen.getAllByText("Post 1").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Post 2").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Post 3").length).toBeGreaterThan(0);
  });

  it("renders the Submit News link", () => {
    render(<NewsCardList {...defaultProps} />);
    const submitLinks = screen.getAllByText("Submit News");
    expect(submitLinks.length).toBeGreaterThan(0);
  });

  it("renders with empty posts array", () => {
    render(
      <NewsCardList
        {...defaultProps}
        posts={[]}
      />
    );
    const submitLinks = screen.getAllByText("Submit News");
    expect(submitLinks.length).toBeGreaterThan(0);
  });

  it("renders the component container", () => {
    const { container } = render(
      <NewsCardList {...defaultProps} />
    );
    expect(container.firstChild).toBeInTheDocument();
  });
});
