// Some portions generated by Co-Pilot
import React from "react";
import { render, cleanup, act } from "@testing-library/react";
import { describe, it, expect, vi, afterEach, beforeEach } from "vitest";
import DownloadTable from "../index";

vi.mock("@/hooks/fetchConstants", () => ({
  useOses: () => [
    { name: "Linux", value: "linux" },
    { name: "Mac", value: "mac" },
    { name: "Windows", value: "windows" },
  ],
  useArches: () => [
    { name: "x64", value: "x64" },
    { name: "aarch64", value: "aarch64" },
  ],
}));

vi.mock("@/hooks", () => ({
  getAllPkgsForVersion: vi.fn().mockResolvedValue([]),
}));

vi.mock("@/components/Marketplace/ReleaseSelector", () => ({
  default: () => <div data-testid="release-selector" />,
}));

vi.mock("@/components/Marketplace/VendorSelector", () => ({
  default: () => <div data-testid="vendor-selector" />,
}));

vi.mock("@/components/Marketplace/AllReleasesCard", () => ({
  default: ({ onReset }: { onReset?: () => void }) => (
    <div data-testid="all-releases-card">
      {onReset && (
        <button onClick={onReset} data-testid="reset-btn">
          Reset
        </button>
      )}
    </div>
  ),
}));

vi.mock("@/utils/setURLParam", () => ({
  setURLParam: vi.fn(),
}));

vi.mock("@/utils/detectOS", () => ({
  detectOS: vi.fn(() => 2), // WIN
  UserOS: { MAC: 0, LINUX: 1, UNIX: 3, WIN: 2 },
}));

vi.mock("next/navigation", () => ({
  useSearchParams: () => ({
    entries: () => new Map().entries(),
  }),
}));

const ltsVersions = [
  { name: "21", value: "21" },
  { name: "17", value: "17" },
];

describe("DownloadTable", () => {
  afterEach(() => {
    cleanup();
    vi.clearAllMocks();
  });

  it("renders null initially before ready", async () => {
    const { container } = render(
      <DownloadTable ltsVersions={ltsVersions} latestLTS={21} />,
    );
    // Before oses/arches populate, component returns null
    // After they populate (synchronously in mock), it should render
    expect(container).toBeTruthy();
  });

  it("renders child components when ready", async () => {
    const { findByTestId } = render(
      <DownloadTable ltsVersions={ltsVersions} latestLTS={21} />,
    );
    const releaseSelector = await findByTestId("release-selector");
    expect(releaseSelector).toBeTruthy();
    const vendorSelector = await findByTestId("vendor-selector");
    expect(vendorSelector).toBeTruthy();
  });

  it("renders with URL search params for version", async () => {
    const mockSearchParams = {
      entries: () => new Map([["version", "17"]]).entries(),
    };
    vi.doMock("next/navigation", () => ({
      useSearchParams: () => mockSearchParams,
    }));

    const { findByTestId } = render(
      <DownloadTable ltsVersions={ltsVersions} latestLTS={21} />,
    );
    const releaseSelector = await findByTestId("release-selector");
    expect(releaseSelector).toBeTruthy();
  });
});
