// Some portions generated by Co-Pilot
import React from "react";
import { render, cleanup } from "@testing-library/react";
import { afterEach, describe, it, expect } from "vitest";
import Pagination from "../index";

afterEach(() => {
  cleanup();
});

describe("News Pagination", () => {
  const baseProps = {
    currentPage: 1,
    totalPages: 5,
    baseUrl: "/news",
  };

  it("renders without previous or next links on page 1 with no links provided", () => {
    const { container, queryByText } = render(<Pagination {...baseProps} />);
    expect(container).toBeTruthy();
    // With no previousPageLink or nextPage, previous/next should not render
    expect(queryByText("Previous")).toBeNull();
    expect(queryByText("Next")).toBeNull();
  });

  it("renders previous link when previousPageNumber and previousPageLink are provided", () => {
    const { getByText } = render(
      <Pagination
        {...baseProps}
        currentPage={2}
        previousPageNumber={1}
        previousPageLink="/news"
      />,
    );
    expect(getByText("Previous")).toBeTruthy();
  });

  it("renders next link when nextPage is provided", () => {
    const { getByText } = render(
      <Pagination {...baseProps} nextPage="/news/page/2" />,
    );
    expect(getByText("Next")).toBeTruthy();
  });

  it("renders all pages when totalPages <= 7", () => {
    const { getAllByText } = render(
      <Pagination {...baseProps} totalPages={5} currentPage={3} />,
    );
    // Use getAllByText in case of multiple matches
    expect(getAllByText("1").length).toBeGreaterThan(0);
    expect(getAllByText("5").length).toBeGreaterThan(0);
  });

  it("renders ellipsis for large page counts", () => {
    const { getAllByText } = render(
      <Pagination {...baseProps} totalPages={10} currentPage={5} />,
    );
    const ellipses = getAllByText("...");
    expect(ellipses.length).toBeGreaterThanOrEqual(2);
  });

  it("renders with queryString appended to links", () => {
    const { container } = render(
      <Pagination
        {...baseProps}
        totalPages={3}
        currentPage={1}
        queryString="tag=java"
        nextPage="/news/page/2?tag=java"
      />,
    );
    expect(container).toBeTruthy();
  });

  it("renders near-beginning pages correctly (currentPage <= 3)", () => {
    const { container } = render(
      <Pagination {...baseProps} totalPages={10} currentPage={2} />,
    );
    expect(container).toBeTruthy();
    // First 5 pages should be shown
    expect(container.textContent).toContain("1");
    expect(container.textContent).toContain("5");
  });

  it("renders near-end pages correctly (currentPage >= totalPages - 2)", () => {
    const { container } = render(
      <Pagination {...baseProps} totalPages={10} currentPage={9} />,
    );
    expect(container).toBeTruthy();
    expect(container.textContent).toContain("10");
  });

  it("highlights current page with bold styling", () => {
    const { container } = render(
      <Pagination {...baseProps} totalPages={5} currentPage={3} />,
    );
    // The current page element should have the "font-bold" class
    const boldElement = container.querySelector(".font-bold.text-pink");
    expect(boldElement).toBeTruthy();
    expect(boldElement?.textContent).toBe("3");
  });

  it("links to baseUrl for page 1 in createPageLink", () => {
    const { container } = render(
      <Pagination
        {...baseProps}
        totalPages={3}
        currentPage={2}
        previousPageNumber={1}
        previousPageLink="/news"
      />,
    );
    // Should have a link back to /news (page 1)
    const links = container.querySelectorAll("a");
    const homeLink = Array.from(links).find((a) =>
      a.getAttribute("href")?.includes("/news"),
    );
    expect(homeLink).toBeTruthy();
  });
});
