/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v3/assets/feature_releases/{feature_version}/{release_type}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns release information
     * @description List of information about builds that match the current query
     */
    get: operations["searchReleases"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/assets/latest/{feature_version}/{jvm_impl}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns list of latest assets for the given feature version and jvm impl */
    get: operations["getLatestAssets"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/assets/release_name/{vendor}/{release_name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns release information
     * @description List of releases with the given release name
     */
    get: operations["getReleaseInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/assets/version/{version}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns release information about the specified version.
     * @description List of information about builds that match the current query
     */
    get: operations["searchReleasesByVersion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/attestations/release_name/{release_name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns attestations for the given release
     * @description Return the list of attestations that match the given release name
     */
    get: operations["listAttestationsForRelease"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/attestations/release_name/{release_name}/{os}/{arch}/{image_type}/{jvm_impl}/{vendor}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns matching attestations
     * @description Return the attestations that matches the given query
     */
    get: operations["listAttestationsForAssetBinary"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/attestations/target_checksum/{target_checksum}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns attestations that target the given SHA256 checksum
     * @description Return the list of attestations that have the matching target binary SHA256 checksum
     */
    get: operations["listAttestationsForTargetChecksum"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/binary/latest/{feature_version}/{release_type}/{os}/{arch}/{image_type}/{jvm_impl}/{heap_size}/{vendor}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Redirects to the binary that matches your current query
     * @description Redirects to the binary that matches your current query
     */
    get: operations["getBinary"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/binary/version/{release_name}/{os}/{arch}/{image_type}/{jvm_impl}/{heap_size}/{vendor}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Redirects to the binary that matches your current query
     * @description Redirects to the binary that matches your current query
     */
    get: operations["getBinaryByVersion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/checksum/version/{release_name}/{os}/{arch}/{image_type}/{jvm_impl}/{heap_size}/{vendor}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Redirects to the checksum of the release that matches your current query
     * @description Redirects to the checksum of the release that matches your current query
     */
    get: operations["getChecksumByVersion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/info/available_releases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns information about available releases */
    get: operations["getAvailableReleases"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/info/release_names": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of all release names */
    get: operations["getReleaseNames"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/info/release_notes/{release_name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns release notes for a release version */
    get: operations["getReleaseNotes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/info/release_versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of all release versions */
    get: operations["getReleaseVersions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/installer/latest/{feature_version}/{release_type}/{os}/{arch}/{image_type}/{jvm_impl}/{heap_size}/{vendor}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Redirects to the installer that matches your current query
     * @description Redirects to the installer that matches your current query
     */
    get: operations["getInstaller"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/installer/version/{release_name}/{os}/{arch}/{image_type}/{jvm_impl}/{heap_size}/{vendor}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Redirects to the installer that matches your current query
     * @description Redirects to the installer that matches your current query
     */
    get: operations["getInstallerByVersion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/signature/version/{release_name}/{os}/{arch}/{image_type}/{jvm_impl}/{heap_size}/{vendor}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Redirects to the signature of the release that matches your current query
     * @description Redirects to the signature of the release that matches your current query
     */
    get: operations["getSignatureByVersion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/types/architectures": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns names of architectures */
    get: operations["getArchitectures"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/types/operating_systems": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns names of operating systems */
    get: operations["getOperatingSystems"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v3/version/{version}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Parses a java version string
     * @description Parses a java version string and returns that data in a structured format
     */
    get: operations["parseVersion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    AdoptiumJvmImpl: "hotspot";
    /**
     * @default eclipse
     * @example eclipse
     * @enum {string}
     */
    AdoptiumVendor: "eclipse";
    /** @enum {string} */
    Architecture:
      | "x64"
      | "x86"
      | "x32"
      | "ppc64"
      | "ppc64le"
      | "s390x"
      | "aarch64"
      | "arm"
      | "sparcv9"
      | "riscv64";
    Attestation: {
      id?: string;
      filename?: string;
      /** Format: int32 */
      featureVersion?: number;
      /** @example jdk-21.0.5+11 */
      release_name?: string | null;
      os?: components["schemas"]["OperatingSystem"];
      architecture?: components["schemas"]["Architecture"];
      image_type?: components["schemas"]["ImageType"];
      jvm_impl?: components["schemas"]["JvmImpl"];
      vendor?: components["schemas"]["Vendor"];
      committedDate?: components["schemas"]["Instant"] | null;
      /** @description Assessor checksum of attested target */
      target_checksum?: string | null;
      /** @example Acme Ltd */
      assessor_org?: string | null;
      /** @example We claim a verified reproducible build. */
      assessor_affirmation?: string | null;
      /** @example VERIFIED_REPRODUCIBLE_BUILD */
      assessor_claim_predicate?: string | null;
      /** @example https://github.com/adoptium/temurin-attestations/blob/main/21/jdk_21_0_6_7_x64-linux_MyOrgLtd.xml */
      attestation_link?: string | null;
      /** @example https://github.com/adoptium/temurin-attestations/blob/main/21/jdk_21_0_6_7_x64-linux_MyOrgLtd.xml.sign.pub */
      attestation_public_signing_key_link?: string | null;
    };
    Binary: {
      os?: components["schemas"]["OperatingSystem"];
      architecture?: components["schemas"]["Architecture"];
      image_type?: components["schemas"]["ImageType"];
      c_lib?: components["schemas"]["CLib"] | null;
      jvm_impl?: components["schemas"]["JvmImpl"];
      package?: components["schemas"]["Package"];
      installer?: components["schemas"]["Installer"];
      heap_size?: components["schemas"]["HeapSize"];
      /**
       * Format: int64
       * @example 3899
       */
      download_count?: number;
      updated_at?: components["schemas"]["DateTime"];
      /** @example dd28d6d2cde2b931caf94ac2422a2ad082ea62f0beee3bf7057317c53093de93 */
      scm_ref?: string | null;
      project?: components["schemas"]["project"];
    };
    BinaryAssetView: {
      binary?: components["schemas"]["Binary"];
      /** @example jdk8u162-b12_openj9-0.8.0 */
      release_name?: string;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/ga/tag/jdk8u162-b12_openj9-0.8.0 */
      release_link?: string;
      vendor?: components["schemas"]["Vendor"];
      version?: components["schemas"]["VersionData"];
    };
    /** @enum {string} */
    CLib: "musl" | "glibc";
    /** @description <p>Date/time. When only a date is given the time is set to the end of the given day. <ul> <li>2020-01-21</li> <li>2020-01-21T10:15:30</li> <li>20200121</li> <li>2020-12-21T10:15:30Z</li> <li>2020-12-21+01:00</li> </ul></p> */
    DateTime: string;
    /**
     * @example normal
     * @enum {string}
     */
    HeapSize: "normal" | "large";
    /**
     * @example jdk
     * @enum {string}
     */
    ImageType:
      | "jdk"
      | "jre"
      | "testimage"
      | "debugimage"
      | "staticlibs"
      | "sources"
      | "sbom"
      | "jmods";
    Installer: {
      /** @example OpenJDK8U-jre_x86-32_windows_hotspot_8u212b04.msi */
      name?: string;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-binaries/ga/download/jdk8u212-b04/OpenJDK8U-jre_x86-32_windows_hotspot_8u212b04.msi */
      link?: string;
      /**
       * Format: int64
       * @example 82573385
       */
      size?: number;
      /** @example dd28d6d2cde2b931caf94ac2422a2ad082ea62f0beee3bf7057317c53093de93 */
      checksum?: string | null;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/ga/download/jdk8u162-b12_openj9-0.8.0/OpenJDK8-OPENJ9_x64_Linux_jdk8u162-b12_openj9-0.8.0.tar.gz.sha256.txt */
      checksum_link?: string | null;
      /** @example https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jdk_x64_linux_11.0.5_10.tar.gz.sign */
      signature_link?: string | null;
      /**
       * Format: int64
       * @example 2
       */
      download_count?: number;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/ga/download/jdk8u162-b12_openj9-0.8.0/OpenJDK8-OPENJ9_x64_Linux_jdk8u162-b12_openj9-0.8.0.tar.gz.json */
      metadata_link?: string | null;
    };
    /**
     * Format: date-time
     * @example 2022-03-10T16:15:50Z
     */
    Instant: string;
    JvmImpl: components["schemas"]["AdoptiumJvmImpl"];
    /** @enum {string} */
    OperatingSystem:
      | "linux"
      | "windows"
      | "mac"
      | "solaris"
      | "aix"
      | "alpine-linux";
    Package: {
      /** @example OpenJDK8U-jre_x86-32_windows_hotspot_8u212b04.msi */
      name?: string;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-binaries/ga/download/jdk8u212-b04/OpenJDK8U-jre_x86-32_windows_hotspot_8u212b04.msi */
      link?: string;
      /**
       * Format: int64
       * @example 82573385
       */
      size?: number;
      /** @example dd28d6d2cde2b931caf94ac2422a2ad082ea62f0beee3bf7057317c53093de93 */
      checksum?: string | null;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/ga/download/jdk8u162-b12_openj9-0.8.0/OpenJDK8-OPENJ9_x64_Linux_jdk8u162-b12_openj9-0.8.0.tar.gz.sha256.txt */
      checksum_link?: string | null;
      /** @example https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jdk_x64_linux_11.0.5_10.tar.gz.sign */
      signature_link?: string | null;
      /**
       * Format: int64
       * @example 2
       */
      download_count?: number;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/ga/download/jdk8u162-b12_openj9-0.8.0/OpenJDK8-OPENJ9_x64_Linux_jdk8u162-b12_openj9-0.8.0.tar.gz.json */
      metadata_link?: string | null;
    };
    Release: {
      /** @example VXNlci0xMA== */
      id?: string;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/ga/tag/jdk8u162-b12_openj9-0.8.0 */
      release_link?: string;
      /** @example jdk8u162-b12_openj9-0.8.0 */
      release_name?: string;
      timestamp?: components["schemas"]["DateTime"];
      updated_at?: components["schemas"]["DateTime"];
      binaries?: components["schemas"]["Binary"][];
      /**
       * Format: int64
       * @example 7128
       */
      download_count?: number;
      release_type?: components["schemas"]["ReleaseType"];
      vendor?: components["schemas"]["Vendor"];
      version_data?: components["schemas"]["VersionData"];
      source?: components["schemas"]["SourcePackage"] | null;
      release_notes?: components["schemas"]["ReleaseNotesPackage"] | null;
      /** @example https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.6%2B10/AQAvitTapFiles.tar.gz */
      aqavit_results_link?: string | null;
    };
    ReleaseNote: {
      id: string;
      title: string | null;
      priority: string | null;
      component: string | null;
      subcomponent: string | null;
      link: string | null;
      type: string | null;
      backportOf: string | null;
    };
    ReleaseNotesPackage: {
      /** @example OpenJDK8U-sources_8u232b09.tar.gz */
      name?: string;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u232-b09/OpenJDK8U-sources_8u232b09.tar.gz */
      link?: string;
      /**
       * Format: int64
       * @example 82573385
       */
      size?: number;
    };
    /**
     * @default ga
     * @enum {string}
     */
    ReleaseType: "ga" | "ea";
    /**
     * @description DEFAULT sort order is by: version, then date, then name, then id. DATE sorts by date, then version, then name, then id.
     * @default DEFAULT
     * @enum {string}
     */
    SortMethod: "DEFAULT" | "DATE";
    /**
     * @default DESC
     * @enum {string}
     */
    SortOrder: "ASC" | "DESC";
    SourcePackage: {
      /** @example OpenJDK8U-sources_8u232b09.tar.gz */
      name?: string;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u232-b09/OpenJDK8U-sources_8u232b09.tar.gz */
      link?: string;
      /**
       * Format: int64
       * @example 82573385
       */
      size?: number;
    };
    /**
     * @default all
     * @example all
     * @enum {string}
     */
    StatsSource: "github" | "dockerhub" | "all";
    Vendor: components["schemas"]["AdoptiumVendor"];
    VersionData: {
      /** Format: int32 */
      major?: number;
      /** Format: int32 */
      minor?: number;
      /** Format: int32 */
      security?: number;
      /** Format: int32 */
      patch?: number | null;
      pre?: string | null;
      /** Format: int32 */
      adopt_build_number?: number | null;
      /** @example 11.0.0+28 */
      semver?: string;
      /** @example 11.0.4+10-201907081820 */
      openjdk_version?: string;
      /** Format: int32 */
      build?: number;
      optional?: string | null;
    };
    /**
     * @description Project
     * @default jdk
     * @enum {string}
     */
    project: "jdk" | "valhalla" | "metropolis" | "jfr" | "shenandoah";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  searchReleases: {
    parameters: {
      query?: {
        /** @description Architecture */
        architecture?: components["schemas"]["Architecture"] | null;
        /** @description <p>Return binaries whose updated_at is before the given date/time. When a date is given the match is inclusive of the given day. <ul> <li>2020-01-21</li> <li>2020-01-21T10:15:30</li> <li>20200121</li> <li>2020-12-21T10:15:30Z</li> <li>2020-12-21+01:00</li> </ul></p> */
        before?: components["schemas"]["DateTime"] | null;
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Heap Size */
        heap_size?: components["schemas"]["HeapSize"] | null;
        /** @description Image Type */
        image_type?: components["schemas"]["ImageType"] | null;
        /** @description JVM Implementation */
        jvm_impl?: components["schemas"]["JvmImpl"] | null;
        /** @description Operating System */
        os?: components["schemas"]["OperatingSystem"] | null;
        /** @description Pagination page number */
        page?: number;
        /** @description Pagination page size */
        page_size?: number;
        /** @description Project */
        project?: components["schemas"]["project"] | null;
        /** @description Result sort method */
        sort_method?: components["schemas"]["SortMethod"] | null;
        /** @description Result sort order */
        sort_order?: components["schemas"]["SortOrder"] | null;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor?: components["schemas"]["Vendor"] | null;
      };
      header?: never;
      path: {
        /**
         * @description <p>
         *         Feature release version you wish to download. Feature versions are whole numbers e.g. <code>8,11,16,17,18</code>.
         *     </p>
         *     <p>
         *         Available Feature versions can be obtained from
         *         <a href="https://api.adoptium.net/v3/info/available_releases">https://api.adoptium.net/v3/info/available_releases</a>
         *     </p>
         */
        feature_version: number;
        /** @description <p>Type of release. Either a release version, known as General Availability(ga) or an Early Access(ea) </p> */
        release_type: components["schemas"]["ReleaseType"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description search results matching criteria */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Release"][];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getLatestAssets: {
    parameters: {
      query?: {
        /** @description Architecture */
        architecture?: components["schemas"]["Architecture"] | null;
        /** @description Image Type */
        image_type?: components["schemas"]["ImageType"] | null;
        /** @description Operating System */
        os?: components["schemas"]["OperatingSystem"] | null;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor?: components["schemas"]["Vendor"] | null;
      };
      header?: never;
      path: {
        /**
         * @description <p>
         *         Feature release version you wish to download. Feature versions are whole numbers e.g. <code>8,11,16,17,18</code>.
         *     </p>
         *     <p>
         *         Available Feature versions can be obtained from
         *         <a href="https://api.adoptium.net/v3/info/available_releases">https://api.adoptium.net/v3/info/available_releases</a>
         *     </p>
         */
        feature_version: number;
        /** @description JVM Implementation */
        jvm_impl: components["schemas"]["JvmImpl"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BinaryAssetView"][];
        };
      };
    };
  };
  getReleaseInfo: {
    parameters: {
      query?: {
        /** @description Architecture */
        architecture?: components["schemas"]["Architecture"] | null;
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Heap Size */
        heap_size?: components["schemas"]["HeapSize"] | null;
        /** @description Image Type */
        image_type?: components["schemas"]["ImageType"] | null;
        /** @description JVM Implementation */
        jvm_impl?: components["schemas"]["JvmImpl"] | null;
        /** @description Operating System */
        os?: components["schemas"]["OperatingSystem"] | null;
        /** @description Project */
        project?: components["schemas"]["project"] | null;
      };
      header?: never;
      path: {
        /** @description Name of the release i.e */
        release_name: string;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Release with the given vendor and name */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Release"];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description no releases match the request */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description multiple releases match the request */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  searchReleasesByVersion: {
    parameters: {
      query?: {
        /** @description Architecture */
        architecture?: components["schemas"]["Architecture"] | null;
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Heap Size */
        heap_size?: components["schemas"]["HeapSize"] | null;
        /** @description Image Type */
        image_type?: components["schemas"]["ImageType"] | null;
        /** @description JVM Implementation */
        jvm_impl?: components["schemas"]["JvmImpl"] | null;
        /** @description Include only LTS releases */
        lts?: boolean | null;
        /** @description Operating System */
        os?: components["schemas"]["OperatingSystem"] | null;
        /** @description Pagination page number */
        page?: number | null;
        /** @description Pagination page size */
        page_size?: number | null;
        /** @description Project */
        project?: components["schemas"]["project"] | null;
        /** @description <p>Type of release. Either a release version, known as General Availability(ga) or an Early Access(ea) </p> */
        release_type?: components["schemas"]["ReleaseType"] | null;
        /** @description Indicates that any version arguments provided in this request were Adoptium semantic versions */
        semver?: boolean;
        /** @description Result sort method */
        sort_method?: components["schemas"]["SortMethod"] | null;
        /** @description Result sort order */
        sort_order?: components["schemas"]["SortOrder"] | null;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor?: components["schemas"]["Vendor"] | null;
      };
      header?: never;
      path: {
        /**
         * @description Java version range (maven style) of versions to include.
         *
         *     e.g:
         *     * `11.0.4.1+11.1`
         *     * `[1.0,2.0)`
         *     * `(,1.0]`
         *
         *     Details of maven version ranges can be found at
         *         <https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html>
         */
        version: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description search results matching criteria */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Release"][];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listAttestationsForRelease: {
    parameters: {
      query?: {
        /** @description Project */
        project?: components["schemas"]["project"] | null;
      };
      header?: never;
      path: {
        /**
         * @description <p>
         *         Name of the release as displayed in github or <a href="https://adoptopenjdk.net/">https://adoptopenjdk.net/</a> e.g
         *         <code>jdk-11.0.4+11, jdk8u172-b00-201807161800</code>.
         *     </p>
         *     <p>
         *         A list of release names can be obtained from
         *         <a href="https://api.adoptium.net/v3/info/release_names">https://api.adoptium.net/v3/info/release_names</a>
         *     </p>
         */
        release_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Attestations for the given release name */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Attestation"][];
        };
      };
      /** @description No matching attestations found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listAttestationsForAssetBinary: {
    parameters: {
      query?: {
        /** @description Project */
        project?: components["schemas"]["project"] | null;
      };
      header?: never;
      path: {
        /** @description Architecture */
        arch: components["schemas"]["Architecture"];
        /** @description Image Type */
        image_type: components["schemas"]["ImageType"];
        /** @description JVM Implementation */
        jvm_impl: components["schemas"]["JvmImpl"];
        /** @description Operating System */
        os: components["schemas"]["OperatingSystem"];
        /**
         * @description <p>
         *         Name of the release as displayed in github or <a href="https://adoptopenjdk.net/">https://adoptopenjdk.net/</a> e.g
         *         <code>jdk-11.0.4+11, jdk8u172-b00-201807161800</code>.
         *     </p>
         *     <p>
         *         A list of release names can be obtained from
         *         <a href="https://api.adoptium.net/v3/info/release_names">https://api.adoptium.net/v3/info/release_names</a>
         *     </p>
         */
        release_name: string;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Attestations for the given asset binary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Attestation"][];
        };
      };
      /** @description No matching attestations found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listAttestationsForTargetChecksum: {
    parameters: {
      query?: {
        /** @description Project */
        project?: components["schemas"]["project"] | null;
      };
      header?: never;
      path: {
        /** @description Target binary SHA256 checksum */
        target_checksum: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Attestations for the given target binary SHA256 checksum */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Attestation"][];
        };
      };
      /** @description No matching attestations found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getBinary: {
    parameters: {
      query?: {
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Project */
        project?: components["schemas"]["project"] | null;
      };
      header?: never;
      path: {
        /** @description Architecture */
        arch: components["schemas"]["Architecture"];
        /**
         * @description <p>
         *         Feature release version you wish to download. Feature versions are whole numbers e.g. <code>8,11,16,17,18</code>.
         *     </p>
         *     <p>
         *         Available Feature versions can be obtained from
         *         <a href="https://api.adoptium.net/v3/info/available_releases">https://api.adoptium.net/v3/info/available_releases</a>
         *     </p>
         */
        feature_version: number;
        /** @description Heap Size */
        heap_size: components["schemas"]["HeapSize"];
        /** @description Image Type */
        image_type: components["schemas"]["ImageType"];
        /** @description JVM Implementation */
        jvm_impl: components["schemas"]["JvmImpl"];
        /** @description Operating System */
        os: components["schemas"]["OperatingSystem"];
        /** @description <p>Type of release. Either a release version, known as General Availability(ga) or an Early Access(ea) </p> */
        release_type: components["schemas"]["ReleaseType"];
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description link to binary that matches your current query */
      307: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No matching binary found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getBinaryByVersion: {
    parameters: {
      query?: {
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Project */
        project?: components["schemas"]["project"] | null;
      };
      header?: never;
      path: {
        /** @description Architecture */
        arch: components["schemas"]["Architecture"];
        /** @description Heap Size */
        heap_size: components["schemas"]["HeapSize"];
        /** @description Image Type */
        image_type: components["schemas"]["ImageType"];
        /** @description JVM Implementation */
        jvm_impl: components["schemas"]["JvmImpl"];
        /** @description Operating System */
        os: components["schemas"]["OperatingSystem"];
        /**
         * @description <p>
         *         Name of the release as displayed in github or <a href="https://adoptopenjdk.net/">https://adoptopenjdk.net/</a> e.g
         *         <code>jdk-11.0.4+11, jdk8u172-b00-201807161800</code>.
         *     </p>
         *     <p>
         *         A list of release names can be obtained from
         *         <a href="https://api.adoptium.net/v3/info/release_names">https://api.adoptium.net/v3/info/release_names</a>
         *     </p>
         */
        release_name: string;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description link to binary that matches your current query */
      307: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No matching binary found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getChecksumByVersion: {
    parameters: {
      query?: {
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Project */
        project?: components["schemas"]["project"] | null;
      };
      header?: never;
      path: {
        /** @description Architecture */
        arch: components["schemas"]["Architecture"];
        /** @description Heap Size */
        heap_size: components["schemas"]["HeapSize"];
        /** @description Image Type */
        image_type: components["schemas"]["ImageType"];
        /** @description JVM Implementation */
        jvm_impl: components["schemas"]["JvmImpl"];
        /** @description Operating System */
        os: components["schemas"]["OperatingSystem"];
        /**
         * @description <p>
         *         Name of the release as displayed in github or <a href="https://adoptopenjdk.net/">https://adoptopenjdk.net/</a> e.g
         *         <code>jdk-11.0.4+11, jdk8u172-b00-201807161800</code>.
         *     </p>
         *     <p>
         *         A list of release names can be obtained from
         *         <a href="https://api.adoptium.net/v3/info/release_names">https://api.adoptium.net/v3/info/release_names</a>
         *     </p>
         */
        release_name: string;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description link to checksum of the release that matches your current query */
      307: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No matching signature found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAvailableReleases: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Available release information */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /**
             * @description The versions for which adopt have produced a ga release
             * @example [
             *       8,
             *       9,
             *       10,
             *       11,
             *       12,
             *       13,
             *       14
             *     ]
             */
            available_releases?: number[];
            /**
             * @description The LTS versions for which adopt have produced a ga release
             * @example [
             *       8,
             *       11
             *     ]
             */
            available_lts_releases?: number[];
            /**
             * Format: int32
             * @description The highest LTS version for which adopt have produced a ga release
             * @example 11
             */
            most_recent_lts?: number;
            /**
             * Format: int32
             * @description The highest version (LTS or not) for which adopt have produced a ga release
             * @example 13
             */
            most_recent_feature_release?: number;
            /**
             * Format: int32
             * @description The highest version (LTS or not) for which we have produced a build, this may be a version that has not yet produced a ga release
             * @example 15
             */
            most_recent_feature_version?: number;
            /**
             * Format: int32
             * @description The version that is currently in development at openjdk
             * @example 15
             */
            tip_version?: number;
          };
        };
      };
    };
  };
  getReleaseNames: {
    parameters: {
      query?: {
        /** @description Architecture */
        architecture?: components["schemas"]["Architecture"] | null;
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Heap Size */
        heap_size?: components["schemas"]["HeapSize"] | null;
        /** @description Image Type */
        image_type?: components["schemas"]["ImageType"] | null;
        /** @description JVM Implementation */
        jvm_impl?: components["schemas"]["JvmImpl"] | null;
        /** @description Include only LTS releases */
        lts?: boolean | null;
        /** @description Operating System */
        os?: components["schemas"]["OperatingSystem"] | null;
        /** @description Pagination page number */
        page?: number;
        /** @description Pagination page size */
        page_size?: number;
        /** @description Project */
        project?: components["schemas"]["project"] | null;
        /** @description <p>Type of release. Either a release version, known as General Availability(ga) or an Early Access(ea) </p> */
        release_type?: components["schemas"]["ReleaseType"] | null;
        /** @description Indicates that any version arguments provided in this request were Adoptium semantic versions */
        semver?: boolean | null;
        /** @description Result sort method */
        sort_method?: components["schemas"]["SortMethod"] | null;
        /** @description Result sort order */
        sort_order?: components["schemas"]["SortOrder"] | null;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor?: components["schemas"]["Vendor"] | null;
        /**
         * @description Java version range (maven style) of versions to include.
         *
         *     e.g:
         *     * `11.0.4.1+11.1`
         *     * `[1.0,2.0)`
         *     * `(,1.0]`
         *
         *     Details of maven version ranges can be found at
         *         <https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html>
         */
        version?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of all release names */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            releases?: string[];
          };
        };
      };
    };
  };
  getReleaseNotes: {
    parameters: {
      query?: {
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor?: components["schemas"]["Vendor"] | null;
      };
      header?: never;
      path: {
        /**
         * @description <p>
         *         Name of the release as displayed in github or <a href="https://adoptopenjdk.net/">https://adoptopenjdk.net/</a> e.g
         *         <code>jdk-11.0.4+11, jdk8u172-b00-201807161800</code>.
         *     </p>
         *     <p>
         *         A list of release names can be obtained from
         *         <a href="https://api.adoptium.net/v3/info/release_names">https://api.adoptium.net/v3/info/release_names</a>
         *     </p>
         */
        release_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Release notes for the provided release */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            version_data: components["schemas"]["VersionData"];
            vendor: components["schemas"]["Vendor"];
            id: string;
            release_name: string;
            release_notes: components["schemas"]["ReleaseNote"][];
          };
        };
      };
    };
  };
  getReleaseVersions: {
    parameters: {
      query?: {
        /** @description Architecture */
        architecture?: components["schemas"]["Architecture"] | null;
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Heap Size */
        heap_size?: components["schemas"]["HeapSize"] | null;
        /** @description Image Type */
        image_type?: components["schemas"]["ImageType"] | null;
        /** @description JVM Implementation */
        jvm_impl?: components["schemas"]["JvmImpl"] | null;
        /** @description Include only LTS releases */
        lts?: boolean | null;
        /** @description Operating System */
        os?: components["schemas"]["OperatingSystem"] | null;
        /** @description Pagination page number */
        page?: number | null;
        /** @description Pagination page size */
        page_size?: number | null;
        /** @description Project */
        project?: components["schemas"]["project"] | null;
        /** @description <p>Type of release. Either a release version, known as General Availability(ga) or an Early Access(ea) </p> */
        release_type?: components["schemas"]["ReleaseType"] | null;
        /** @description Indicates that any version arguments provided in this request were Adoptium semantic versions */
        semver?: boolean | null;
        /** @description Result sort method */
        sort_method?: components["schemas"]["SortMethod"] | null;
        /** @description Result sort order */
        sort_order?: components["schemas"]["SortOrder"] | null;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor?: components["schemas"]["Vendor"] | null;
        /**
         * @description Java version range (maven style) of versions to include.
         *
         *     e.g:
         *     * `11.0.4.1+11.1`
         *     * `[1.0,2.0)`
         *     * `(,1.0]`
         *
         *     Details of maven version ranges can be found at
         *         <https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html>
         */
        version?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of all release versions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            versions?: components["schemas"]["VersionData"][];
          };
        };
      };
    };
  };
  getInstaller: {
    parameters: {
      query?: {
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Project */
        project?: components["schemas"]["project"] | null;
      };
      header?: never;
      path: {
        /** @description Architecture */
        arch: components["schemas"]["Architecture"];
        /**
         * @description <p>
         *         Feature release version you wish to download. Feature versions are whole numbers e.g. <code>8,11,16,17,18</code>.
         *     </p>
         *     <p>
         *         Available Feature versions can be obtained from
         *         <a href="https://api.adoptium.net/v3/info/available_releases">https://api.adoptium.net/v3/info/available_releases</a>
         *     </p>
         */
        feature_version: number;
        /** @description Heap Size */
        heap_size: components["schemas"]["HeapSize"];
        /** @description Image Type */
        image_type: components["schemas"]["ImageType"];
        /** @description JVM Implementation */
        jvm_impl: components["schemas"]["JvmImpl"];
        /** @description Operating System */
        os: components["schemas"]["OperatingSystem"];
        /** @description <p>Type of release. Either a release version, known as General Availability(ga) or an Early Access(ea) </p> */
        release_type: components["schemas"]["ReleaseType"];
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description link to installer that matches your current query */
      307: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No matching installer found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getInstallerByVersion: {
    parameters: {
      query?: {
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Project */
        project?: components["schemas"]["project"] | null;
      };
      header?: never;
      path: {
        /** @description Architecture */
        arch: components["schemas"]["Architecture"];
        /** @description Heap Size */
        heap_size: components["schemas"]["HeapSize"];
        /** @description Image Type */
        image_type: components["schemas"]["ImageType"];
        /** @description JVM Implementation */
        jvm_impl: components["schemas"]["JvmImpl"];
        /** @description Operating System */
        os: components["schemas"]["OperatingSystem"];
        /**
         * @description <p>
         *         Name of the release as displayed in github or <a href="https://adoptopenjdk.net/">https://adoptopenjdk.net/</a> e.g
         *         <code>jdk-11.0.4+11, jdk8u172-b00-201807161800</code>.
         *     </p>
         *     <p>
         *         A list of release names can be obtained from
         *         <a href="https://api.adoptium.net/v3/info/release_names">https://api.adoptium.net/v3/info/release_names</a>
         *     </p>
         */
        release_name: string;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description link to installer that matches your current query */
      307: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No matching installer found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getSignatureByVersion: {
    parameters: {
      query?: {
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Project */
        project?: components["schemas"]["project"] | null;
      };
      header?: never;
      path: {
        /** @description Architecture */
        arch: components["schemas"]["Architecture"];
        /** @description Heap Size */
        heap_size: components["schemas"]["HeapSize"];
        /** @description Image Type */
        image_type: components["schemas"]["ImageType"];
        /** @description JVM Implementation */
        jvm_impl: components["schemas"]["JvmImpl"];
        /** @description Operating System */
        os: components["schemas"]["OperatingSystem"];
        /**
         * @description <p>
         *         Name of the release as displayed in github or <a href="https://adoptopenjdk.net/">https://adoptopenjdk.net/</a> e.g
         *         <code>jdk-11.0.4+11, jdk8u172-b00-201807161800</code>.
         *     </p>
         *     <p>
         *         A list of release names can be obtained from
         *         <a href="https://api.adoptium.net/v3/info/release_names">https://api.adoptium.net/v3/info/release_names</a>
         *     </p>
         */
        release_name: string;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description link to signature of the release that matches your current query */
      307: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No matching signature found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getArchitectures: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  getOperatingSystems: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  parseVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Version */
        version: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
