/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/assets/feature_releases/{vendor}/{feature_version}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns release information
     * @description List of information about builds that match the current query
     */
    get: operations["searchReleases"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/latest/{vendor}/{feature_version}/{jvm_impl}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns list of latest assets for the given feature version and jvm impl */
    get: operations["getLatestAssets"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/latestForVendors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns list of latest assets for the given feature version and jvm impl */
    get: operations["latestForVendors"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/release_name/{vendor}/{release_name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns release information
     * @description List of releases with the given release name
     */
    get: operations["getReleaseInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/version/{vendor}/{version}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns release information about the specified version.
     * @description List of information about builds that match the current query
     */
    get: operations["searchReleasesByVersion"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/info/available_releases/{vendor}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns information about available releases */
    get: operations["getAvailableReleases"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/info/release_names/{vendor}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of all release names */
    get: operations["getReleaseNames"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/info/release_versions/{vendor}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns a list of all release versions */
    get: operations["getReleaseVersions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description <p>Date/time. When only a date is given the time is set to the end of the given day. <ul> <li>2020-01-21</li> <li>2020-01-21T10:15:30</li> <li>20200121</li> <li>2020-12-21T10:15:30Z</li> <li>2020-12-21+01:00</li> </ul></p> */
    APIDateTime: string;
    /** @enum {string} */
    Architecture:
      | "x64"
      | "x86"
      | "ppc64"
      | "ppc64le"
      | "s390x"
      | "aarch64"
      | "arm"
      | "sparcv9"
      | "riscv64";
    /** @description Details of a binary that can be downloaded including either or both a package and platform specific installer */
    Binary: {
      os: components["schemas"]["OperatingSystem"];
      architecture: components["schemas"]["Architecture"];
      image_type: components["schemas"]["ImageType"];
      c_lib?: components["schemas"]["CLib"];
      jvm_impl: components["schemas"]["JvmImpl"];
      /** @description Describes details of the archive */
      package?: components["schemas"]["Package"];
      /** @description Describes details of the installer archive associated with this binary */
      installer?: {
        /** @example OpenJDK8U-jre_x86-32_windows_hotspot_8u212b04.msi */
        name: string;
        /** @example https://github.com/AdoptOpenJDK/openjdk8-binaries/ga/download/jdk8u212-b04/OpenJDK8U-jre_x86-32_windows_hotspot_8u212b04.msi */
        link: string;
        /** @example dd28d6d2cde2b931caf94ac2422a2ad082ea62f0beee3bf7057317c53093de93 */
        sha256sum: string;
        /**
         * @deprecated
         * @description This value is present to avoid an API breaking change from a previous typo for sha256sum in the API. DO NOT USE THIS, it is deprecated and will be removed.
         * @example dd28d6d2cde2b931caf94ac2422a2ad082ea62f0beee3bf7057317c53093de93
         */
        sha265sum?: string;
        /** @example https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/ga/download/jdk8u162-b12_openj9-0.8.0/OpenJDK8-OPENJ9_x64_Linux_jdk8u162-b12_openj9-0.8.0.tar.gz.sha256.txt */
        sha256sum_link?: string;
        /** @example https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jdk_x64_linux_11.0.5_10.tar.gz.sign */
        signature_link?: string;
        /**
         * @description Type of the installer, i.e exe, msi, deb, dmg
         * @example msi
         */
        installerType?: string;
      }[];
      /** @description Timestamp of the creation time of the binary */
      timestamp: components["schemas"]["Date"];
      /**
       * @description Scm reference to the commit inside the vendors own repository upon which this build is based
       * @example dd28d6d2cde2b931caf94ac2422a2ad082ea62f0beee3bf7057317c53093de93
       */
      scm_ref?: string;
      /**
       * @description Scm reference to the commit inside the OpenJDK project, upon which this build is based
       * @example dd28d6d2cde2b931caf94ac2422a2ad082ea62f0beee3bf7057317c53093de93
       */
      openjdk_scm_ref: string;
      distribution: components["schemas"]["Distribution"];
      /**
       * @description Link to the aquavit results details for this binary
       * @example https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17%2B35/OpenJDK17-jdk_x64_linux_hotspot_17_35.tar.gz.aqavit.zip
       */
      aqavit_results_link: string;
      /**
       * @description Link to the tck affidavit for this binary
       * @example https://adoptium.net/tck_affidavit.html
       */
      tck_affidavit_link?: string;
    };
    BinaryAssetView: {
      binary?: components["schemas"]["Binary"];
      /** @example jdk8u162-b12_openj9-0.8.0 */
      release_name: string;
      vendor?: components["schemas"]["Vendor"];
      version?: components["schemas"]["OpenjdkVersionData"];
    };
    /** @enum {string} */
    CLib: "musl" | "glibc";
    /**
     * Format: date
     * @example 2022-03-10
     */
    Date: string;
    /** @enum {string} */
    Distribution:
      | "temurin"
      | "dragonwell"
      | "zulu"
      | "microsoft"
      | "semeru"
      | "bisheng"
      | "redhat";
    /**
     * @example jdk
     * @enum {string}
     */
    ImageType: "jdk" | "jre";
    IndexFile: {
      /**
       * @default 1.0.0
       * @example 1.0.0
       * @enum {string|object}
       */
      schema_version: "hotspot" | "openj9";
      indexes?: string[];
      releases?: string[];
    };
    /** @enum {string} */
    JvmImpl: "hotspot" | "openj9";
    OpenjdkVersionData: {
      /** Format: int32 */
      major?: number;
      /** Format: int32 */
      minor?: number | null;
      /** Format: int32 */
      security?: number | null;
      /** Format: int32 */
      patch?: number | null;
      /** Format: int32 */
      build?: number | null;
      pre?: string | null;
      optional?: string | null;
      /** @example 11.0.4+10-201907081820 */
      openjdk_version?: string;
    };
    /** @enum {string} */
    OperatingSystem:
      | "linux"
      | "windows"
      | "mac"
      | "solaris"
      | "aix"
      | "alpine_linux";
    Package: {
      /** @example OpenJDK8U-jre_x86-32_windows_hotspot_8u212b04.msi */
      name: string;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-binaries/ga/download/jdk8u212-b04/OpenJDK8U-jre_x86-32_windows_hotspot_8u212b04.msi */
      link: string;
      /** @example dd28d6d2cde2b931caf94ac2422a2ad082ea62f0beee3bf7057317c53093de93 */
      sha256sum: string;
      /**
       * @deprecated
       * @description This value is present to avoid an API breaking change from a previous typo for sha256sum in the API. DO NOT USE THIS, it is deprecated and will be removed.
       * @example dd28d6d2cde2b931caf94ac2422a2ad082ea62f0beee3bf7057317c53093de93
       */
      sha265sum?: string;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/ga/download/jdk8u162-b12_openj9-0.8.0/OpenJDK8-OPENJ9_x64_Linux_jdk8u162-b12_openj9-0.8.0.tar.gz.sha256.txt */
      sha256sum_link?: string;
      /** @example https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jdk_x64_linux_11.0.5_10.tar.gz.sign */
      signature_link?: string;
    };
    Release: {
      /** @example https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/ga/tag/jdk8u162-b12_openj9-0.8.0 */
      release_link?: string;
      /** @example jdk8u162-b12_openj9-0.8.0 */
      release_name: string;
      /** @description Timestamp of the release creation */
      last_updated_timestamp: components["schemas"]["Date"];
      binaries: components["schemas"]["Binary"][];
      vendor: components["schemas"]["Vendor"];
      openjdk_version_data: components["schemas"]["OpenjdkVersionData"];
      source?: components["schemas"]["SourcePackage"];
      /**
       * @description Link to the public key which has been used to sign binaries within this release IF signature links are provided
       * @example https://adoptium.net/publickey.asc
       */
      vendor_public_key_link?: string;
    };
    ReleaseInfo: {
      /**
       * @description The versions for which adopt have produced a ga release
       * @example [
       *       8,
       *       9,
       *       10,
       *       11,
       *       12,
       *       13,
       *       14
       *     ]
       */
      available_releases: number[];
      /**
       * @description The LTS versions for which adopt have produced a ga release
       * @example [
       *       8,
       *       11
       *     ]
       */
      available_lts_releases: number[];
      /**
       * Format: int32
       * @description The highest LTS version for which adopt have produced a ga release
       * @example 11
       */
      most_recent_lts?: number;
      /**
       * Format: int32
       * @description The highest version (LTS or not) for which we have produced a build, this may be a version that has not yet produced a ga release
       * @example 15
       */
      most_recent_feature_version?: number;
    };
    ReleaseList: {
      releases?: components["schemas"]["Release"][];
    };
    ReleaseNameList: {
      releases?: string[];
    };
    ReleaseVersionList: {
      versions: components["schemas"]["OpenjdkVersionData"][];
    };
    /**
     * @description DEFAULT sort order is by: version, then date, then name, then id. DATE sorts by date, then version, then name, then id.
     * @default DEFAULT
     * @enum {string}
     */
    SortMethod: "DEFAULT" | "DATE";
    /**
     * @description Sort results either ascending or descending based on requested sort method
     * @default DESC
     * @enum {string}
     */
    SortOrder: "ASC" | "DESC";
    SourcePackage: {
      /** @example OpenJDK8U-sources_8u232b09.tar.gz */
      name: string;
      /** @example https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u232-b09/OpenJDK8U-sources_8u232b09.tar.gz */
      link: string;
    };
    /**
     * @description The vendor of the OpenJDK distribution.
     *
     *     The following vendors are no longer receiving updates or new releases for their OpenJDK distributions:
     *
     *     <ul>
     *         <li><b>huawei</b> - Huawei OpenJDK</li>
     *         <li><b>redhat</b> - Red Hat OpenJDK</li>
     *     </ul>
     * @enum {string}
     */
    Vendor: "adoptium" | "alibaba" | "ibm" | "microsoft" | "azul";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  searchReleases: {
    parameters: {
      query?: {
        /** @description Architecture */
        architecture?: components["schemas"]["Architecture"] | null;
        /** @description <p>Return binaries whose updated_at is before the given date/time. When a date is given the match is inclusive of the given day. <ul> <li>2020-01-21</li> <li>2020-01-21T10:15:30</li> <li>20200121</li> <li>2020-12-21T10:15:30Z</li> <li>2020-12-21+01:00</li> </ul></p> */
        before?: components["schemas"]["APIDateTime"] | null;
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Image Type */
        image_type?: components["schemas"]["ImageType"] | null;
        /** @description JVM Implementation */
        jvm_impl?: components["schemas"]["JvmImpl"] | null;
        /** @description Operating System */
        os?: components["schemas"]["OperatingSystem"] | null;
        /** @description Pagination page number */
        page?: number;
        /** @description Pagination page size */
        page_size?: number;
        /** @description Result sort method */
        sort_method?: components["schemas"]["SortMethod"] & unknown;
        /** @description Result sort order */
        sort_order?: components["schemas"]["SortOrder"] & unknown;
      };
      header?: never;
      path: {
        /**
         * @description <p>
         *         Feature release version you wish to download. Feature versions are whole numbers e.g. <code>8,9,10,11,12,13</code>.
         *     </p>
         *     <p>
         *         Available Feature versions can be obtained from
         *         <a href="https://marketplace-api.adoptium.net/v1/info/available_releases">https://marketplace-api.adoptium.net/v1/info/available_releases</a>
         *     </p>
         */
        feature_version: number;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description search results matching criteria */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Release"][];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getLatestAssets: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description <p>
         *         Feature release version you wish to download. Feature versions are whole numbers e.g. <code>8,9,10,11,12,13</code>.
         *     </p>
         *     <p>
         *         Available Feature versions can be obtained from
         *         <a href="https://marketplace-api.adoptium.net/v1/info/available_releases">https://marketplace-api.adoptium.net/v1/info/available_releases</a>
         *     </p>
         */
        feature_version: number;
        /** @description JVM Implementation */
        jvm_impl: components["schemas"]["JvmImpl"];
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BinaryAssetView"][];
        };
      };
    };
  };
  latestForVendors: {
    parameters: {
      query: {
        /** @description Architecture */
        architecture?: components["schemas"]["Architecture"][];
        /**
         * @description <p>
         *         Feature release version you wish to download. Feature versions are whole numbers e.g. <code>8,9,10,11,12,13</code>.
         *     </p>
         *     <p>
         *         Available Feature versions can be obtained from
         *         <a href="https://marketplace-api.adoptium.net/v1/info/available_releases">https://marketplace-api.adoptium.net/v1/info/available_releases</a>
         *     </p>
         */
        feature_version?: number[];
        /** @description Image Type */
        image_type?: components["schemas"]["ImageType"][];
        /** @description Operating System */
        os?: components["schemas"]["OperatingSystem"][];
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"][];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BinaryAssetView"][];
        };
      };
    };
  };
  getReleaseInfo: {
    parameters: {
      query?: {
        /** @description Architecture */
        architecture?: components["schemas"]["Architecture"] | null;
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Image Type */
        image_type?: components["schemas"]["ImageType"] | null;
        /** @description JVM Implementation */
        jvm_impl?: components["schemas"]["JvmImpl"] | null;
        /** @description Operating System */
        os?: components["schemas"]["OperatingSystem"] | null;
      };
      header?: never;
      path: {
        /** @description Name of the release i.e */
        release_name: string;
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Release with the given vendor and name */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Release"];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description no releases match the request */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description multiple releases match the request */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  searchReleasesByVersion: {
    parameters: {
      query?: {
        /** @description Architecture */
        architecture?: components["schemas"]["Architecture"] | null;
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Image Type */
        image_type?: components["schemas"]["ImageType"] | null;
        /** @description JVM Implementation */
        jvm_impl?: components["schemas"]["JvmImpl"] | null;
        /** @description Include only LTS releases */
        lts?: boolean;
        /** @description Operating System */
        os?: components["schemas"]["OperatingSystem"] | null;
        /** @description Pagination page number */
        page?: number;
        /** @description Pagination page size */
        page_size?: number;
        /** @description Result sort method */
        sort_method?: components["schemas"]["SortMethod"] & unknown;
        /** @description Result sort order */
        sort_order?: components["schemas"]["SortOrder"] & unknown;
      };
      header?: never;
      path: {
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
        /**
         * @description Java version range (maven style) of versions to include.
         *
         *     e.g:
         *     * `11.0.4.1+11.1`
         *     * `[1.0,2.0)`
         *     * `(,1.0]`
         *
         *     Details of maven version ranges can be found at
         *         <https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html>
         */
        version: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description search results matching criteria */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Release"][];
        };
      };
      /** @description bad input parameter */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAvailableReleases: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReleaseInfo"];
        };
      };
    };
  };
  getReleaseNames: {
    parameters: {
      query?: {
        /** @description Architecture */
        architecture?: components["schemas"]["Architecture"] | null;
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Image Type */
        image_type?: components["schemas"]["ImageType"] | null;
        /** @description JVM Implementation */
        jvm_impl?: components["schemas"]["JvmImpl"] | null;
        /** @description Include only LTS releases */
        lts?: boolean;
        /** @description Operating System */
        os?: components["schemas"]["OperatingSystem"] | null;
        /** @description Pagination page number */
        page?: number;
        /** @description Pagination page size */
        page_size?: number;
        /** @description Result sort method */
        sort_method?: components["schemas"]["SortMethod"] & unknown;
        /** @description Result sort order */
        sort_order?: components["schemas"]["SortOrder"] & unknown;
        /**
         * @description Java version range (maven style) of versions to include.
         *
         *     e.g:
         *     * `11.0.4.1+11.1`
         *     * `[1.0,2.0)`
         *     * `(,1.0]`
         *
         *     Details of maven version ranges can be found at
         *         <https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html>
         */
        version?: string;
      };
      header?: never;
      path: {
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReleaseNameList"];
        };
      };
    };
  };
  getReleaseVersions: {
    parameters: {
      query?: {
        /** @description Architecture */
        architecture?: components["schemas"]["Architecture"] | null;
        /** @description C Lib type, typically would imply image_type has been set to staticlibs */
        c_lib?: components["schemas"]["CLib"] | null;
        /** @description Image Type */
        image_type?: components["schemas"]["ImageType"] | null;
        /** @description JVM Implementation */
        jvm_impl?: components["schemas"]["JvmImpl"] | null;
        /** @description Include only LTS releases */
        lts?: boolean;
        /** @description Operating System */
        os?: components["schemas"]["OperatingSystem"] | null;
        /** @description Pagination page number */
        page?: number;
        /** @description Pagination page size */
        page_size?: number;
        /** @description Result sort method */
        sort_method?: components["schemas"]["SortMethod"] & unknown;
        /** @description Result sort order */
        sort_order?: components["schemas"]["SortOrder"] & unknown;
        /**
         * @description Java version range (maven style) of versions to include.
         *
         *     e.g:
         *     * `11.0.4.1+11.1`
         *     * `[1.0,2.0)`
         *     * `(,1.0]`
         *
         *     Details of maven version ranges can be found at
         *         <https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html>
         */
        version?: string;
      };
      header?: never;
      path: {
        /** @description <p>Vendor of the binary. This is the organisation that produced the binary package.</p> */
        vendor: components["schemas"]["Vendor"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReleaseVersionList"];
        };
      };
    };
  };
}
