// Some portions generated by Co-Pilot
declare module "swiper/css" {
  const content: string;
  export default content;
}

declare module "swiper/css/navigation" {
  const content: string;
  export default content;
}
