// Some portions generated by Co-Pilot
// Spec-aligned types for Temurin releases
import type { components } from "@/types/adoptiumApiTypes";

/**
 * A single binary asset view from the Adoptium API.
 * Each entry represents one binary (JDK, JRE, etc.) for a specific OS/architecture.
 */
export type BinaryAssetView = components["schemas"]["BinaryAssetView"];

/**
 * A release from the Adoptium API, containing multiple binaries.
 */
export type Release = components["schemas"]["Release"];

/**
 * Version data from the Adoptium API spec (all fields optional).
 */
export type VersionData = components["schemas"]["VersionData"];

/**
 * Array of BinaryAssetView entries returned by loadLatestAssets.
 * The optional `source` property holds the SOURCES image_type entry.
 */
export interface TemurinAssets extends Array<BinaryAssetView> {
  source?: BinaryAssetView;
}

export interface Attestation {
  id: string;
  filename: string;
  featureVersion: number;
  release_name: string | null;
  os: string;
  architecture: string;
  image_type: string;
  jvm_impl: string;
  vendor: string;
  committedDate: string | null;

  /**
   * SHA256 checksum of the binary this attestation applies to.
   * This is the JOIN KEY between Binary and Attestation.
   */
  target_checksum: string;

  assessor_org: string | null;
  assessor_affirmation: string | null;
  assessor_claim_predicate: string | null;

  attestation_link: string | null;
  attestation_public_signing_key_link: string | null;
}

export type AttestationLookup = Record<string, Attestation | undefined>;
