// Some portions generated by Co-Pilot
import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import LinkText from "../index";

describe("LinkText", () => {
  it("renders an external link with target='_blank' for http URLs", () => {
    render(
      <LinkText href="https://github.com/adoptium">GitHub</LinkText>
    );
    const link = screen.getByText("GitHub");
    expect(link.tagName).toBe("A");
    expect(link).toHaveAttribute("href", "https://github.com/adoptium");
    expect(link).toHaveAttribute("target", "_blank");
    expect(link).toHaveAttribute("rel", "noreferrer");
  });

  it("renders an internal Link for relative URLs", () => {
    render(
      <LinkText href="/temurin/releases">Releases</LinkText>
    );
    const link = screen.getByText("Releases");
    expect(link).toHaveAttribute("href", "/temurin/releases");
  });

  it("applies default className when none is provided", () => {
    render(
      <LinkText href="/about">About</LinkText>
    );
    const link = screen.getByText("About");
    expect(link).toHaveClass("border-b", "border-white");
  });

  it("applies custom className when provided", () => {
    render(
      <LinkText href="/about" className="text-pink underline">About Custom</LinkText>
    );
    const link = screen.getByText("About Custom");
    expect(link).toHaveClass("text-pink", "underline");
  });

  it("renders children content correctly", () => {
    render(
      <LinkText href="/docs">
        <span>Documentation</span>
      </LinkText>
    );
    expect(screen.getByText("Documentation")).toBeInTheDocument();
  });
});
