// Some portions generated by Co-Pilot
import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import Contributors from "../index";

describe("Contributors", () => {
  it("renders the contributors section", () => {
    const { container } = render(<Contributors />);
    expect(container.firstChild).toBeInTheDocument();
  });

  it("renders the thank you text", () => {
    render(<Contributors />);
    // The useTranslations mock returns "Text" for all keys
    expect(screen.getAllByText("Text").length).toBeGreaterThan(0);
  });

  it("includes the RandomContributor component", () => {
    const { container } = render(<Contributors />);
    // RandomContributor is rendered within the component
    expect(container.querySelector("div")).toBeInTheDocument();
  });
});
