// Some portions generated by Co-Pilot
import React from "react";
import { getTranslations } from "next-intl/server";
import Author from "./Author";

interface Props {
  authors: string[];
}

const AuthorList = async ({ authors = [] }: Props) => {
  const t = await getTranslations("AuthorList");
  if (authors.length) {
    return (
      <div className="mt-10 flex-col justify-center items-start gap-4">
        <div className="doc-authors-title self-stretch text-white my-5 text-lg font-semibold leading-normal">
          {t("documentation-authors")}
        </div>
        <div className="flex flex-wrap justify-start items-center space-x-[-12px]">
          {authors.map((author) => (
            <Author username={author} key={author} size={55} />
          ))}
        </div>
      </div>
    );
  }

  return null;
};

export default AuthorList;
