// Some portions generated by Co-Pilot
import React from "react";
import { render } from "@testing-library/react";
import { describe, it, expect, vi, beforeEach } from "vitest";
import RelatedArticles from "../index";

// Mock getBlogPosts to control data
vi.mock("@/utils/markdown", () => ({
  getBlogPosts: vi.fn(),
}));

import { getBlogPosts } from "@/utils/markdown";

const mockPosts = [
  {
    slug: "post-1",
    year: "2024",
    month: "01",
    content: "",
    metadata: {
      title: "Post One",
      date: "2024-01-15",
      author: "author1",
      description: "Description one",
      tags: ["java", "temurin"],
      featuredImage: "/img/post1.jpg",
    },
  },
  {
    slug: "post-2",
    year: "2024",
    month: "02",
    content: "",
    metadata: {
      title: "Post Two",
      date: "2024-02-20",
      author: "author2",
      description: "Description two",
      tags: ["java", "adoptium"],
      featuredImage: "/img/post2.jpg",
    },
  },
  {
    slug: "post-3",
    year: "2024",
    month: "03",
    content: "",
    metadata: {
      title: "Post Three",
      date: "2024-03-10",
      author: "author3",
      description: "Description three",
      tags: ["eclipse"],
      featuredImage: "/img/post3.jpg",
    },
  },
  {
    slug: "current-post",
    year: "2024",
    month: "04",
    content: "",
    metadata: {
      title: "Current Post",
      date: "2024-04-01",
      author: "author1",
      description: "Current post description",
      tags: ["java"],
      featuredImage: "/img/current.jpg",
    },
  },
];

describe("RelatedArticles", () => {
  beforeEach(() => {
    vi.mocked(getBlogPosts).mockReturnValue(mockPosts);
  });

  it("returns null when no related articles are found", () => {
    vi.mocked(getBlogPosts).mockReturnValue([
      {
        slug: "current-post",
        year: "2024",
        month: "04",
        content: "",
        metadata: {
          title: "Current Post",
          date: "2024-04-01",
          author: "author1",
          description: "Current post description",
          tags: ["unique-tag-not-shared"],
          featuredImage: "/img/current.jpg",
        },
      },
    ]);

    const { container } = render(
      <RelatedArticles currentSlug="current-post" tags={["unique-tag-not-shared"]} />,
    );

    expect(container.firstChild).toBeNull();
  });

  it("renders related articles filtered by tags", () => {
    const { getByText } = render(
      <RelatedArticles currentSlug="current-post" tags={["java"]} />,
    );
    expect(getByText("Related Articles")).toBeTruthy();
  });

  it("excludes the current post from related articles", () => {
    const { queryByText } = render(
      <RelatedArticles currentSlug="current-post" tags={["java"]} />,
    );
    expect(queryByText("Current Post")).toBeNull();
  });

  it("shows related articles without tag filter", () => {
    const { container } = render(
      <RelatedArticles currentSlug="current-post" />,
    );
    const heading = container.querySelector("h2");
    expect(heading?.textContent).toContain("Related Articles");
  });

  it("limits articles to maxArticles prop", () => {
    const { container } = render(
      <RelatedArticles currentSlug="current-post" maxArticles={1} />,
    );
    expect(container).toBeTruthy();
  });

  it("sorts articles by date (newest first)", () => {
    const { container } = render(
      <RelatedArticles currentSlug="current-post" tags={["java"]} />,
    );
    expect(container).toBeTruthy();
  });

  it("renders with empty tags array (shows latest articles)", () => {
    const { container } = render(
      <RelatedArticles currentSlug="post-1" tags={[]} />,
    );
    const heading = container.querySelector("h2");
    expect(heading?.textContent).toContain("Related Articles");
  });
});
