// Some portions generated by Co-Pilot
import React from "react"

import { render, fireEvent, cleanup } from "@testing-library/react"
import { afterEach, describe, expect, it, vi } from "vitest"

import ShellBox from "../index"

const mockWriteText = vi.fn()
Object.assign(navigator, {
  clipboard: {
    writeText: mockWriteText,
  },
})

afterEach(() => {
  vi.clearAllMocks()
  cleanup()
})

describe("ShellBox component", (): void => {
  it("renders correctly", (): void => {
    const textToCopy = "text to be copy"
    const { container } = render(
      <ShellBox textToCopy={textToCopy}>mock-children-code</ShellBox>,
    )
    expect(container).toMatchSnapshot()
  })

  it("renders without copy button when textToCopy is not provided", (): void => {
    const { queryByLabelText } = render(
      <ShellBox>some code</ShellBox>,
    )
    expect(queryByLabelText("Copy to clipboard")).toBeNull()
  })

  it("renders with copy button when textToCopy is provided", (): void => {
    const { getAllByLabelText } = render(
      <ShellBox textToCopy="npm install temurin">npm install temurin</ShellBox>,
    )
    expect(getAllByLabelText("Copy to clipboard").length).toBeGreaterThan(0)
  })

  it("copies text to clipboard when copy button is clicked", (): void => {
    const textToCopy = "npm install temurin"
    const { container } = render(
      <ShellBox textToCopy={textToCopy}>{textToCopy}</ShellBox>,
    )
    const copyButton = container.querySelector('button[aria-label="Copy to clipboard"]')
    expect(copyButton).toBeTruthy()
    fireEvent.click(copyButton!)
    expect(mockWriteText).toHaveBeenCalledWith(textToCopy)
  })

  it("renders children correctly", (): void => {
    const { getByText } = render(
      <ShellBox>echo hello world</ShellBox>,
    )
    expect(getByText("echo hello world")).toBeTruthy()
  })
})
