// Some portions generated by Co-Pilot
const baseUrl = "https://newsroom.eclipse.org/api"

export async function fetchLatestNews() {
  const url = new URL(`${baseUrl}/news`)
  url.searchParams.append("parameters[publish_to]", "adoptium")
  url.searchParams.append("page", "1")
  url.searchParams.append("pagesize", "100")

  try {
    const response = await fetch(url.toString())
    if (!response.ok) {
      return { news: [], pager: null }
    }
    return await response.json()
  } catch {
    return { news: [], pager: null }
  }
}
