// Some portions generated by Co-Pilot

export interface DateRangeItem {
  startDate?: string;
  endDate?: string;
}

/**
 * Filters an array of items to those whose date range includes the current date.
 * Items without a startDate are considered immediately valid.
 * Items without an endDate are considered indefinitely valid.
 */
export function filterByCurrentDate<T extends DateRangeItem>(items: T[]): T[] {
  const now = new Date();
  return items.filter(
    (item) =>
      (item.startDate ? now >= new Date(item.startDate) : true) &&
      (item.endDate ? now <= new Date(item.endDate) : true),
  );
}
