// Some portions generated by Co-Pilot
import type { components } from "@/types/adoptiumApiTypes";
import { fetchExtension } from "@/utils/fetchExtension";

type SpecBinary = components["schemas"]["Binary"];

/** Convert raw bytes to MB (rounded down). */
export function getSizeMB(bytes: number | null | undefined): number {
  return Math.floor((bytes ?? 0) / 1_000_000);
}

/** Extract the file extension from a package filename, without a leading dot. */
export function getExtension(filename: string | null | undefined): string {
  const ext = fetchExtension(filename ?? "");
  return ext.startsWith(".") ? ext.slice(1) : ext;
}

/**
 * Returns the effective download link for a binary.
 * Prefers the installer link when present, otherwise falls back to the package link.
 */
export function getDownloadLink(binary?: SpecBinary): string {
  return ((binary?.installer?.link ?? binary?.package?.link) as string) ?? "";
}

/**
 * Returns the effective checksum for a binary.
 * Prefers the installer checksum when present, otherwise falls back to the package checksum.
 */
export function getDownloadChecksum(binary?: SpecBinary): string {
  return binary?.installer?.checksum ?? binary?.package?.checksum ?? "";
}

/** Returns true if the binary has an installer artifact. */
export function hasInstaller(binary?: SpecBinary): boolean {
  return !!binary?.installer?.link;
}
