// Some portions generated by Co-Pilot
"use client";

import React, { useEffect } from "react";
import Prism from "prismjs";
import { renderToStaticMarkup } from "react-dom/server";
import { FaClipboard, FaCheck } from "react-icons/fa";

// Load specific languages as needed from Prism's components directory
import "prismjs/components/prism-java";
import "prismjs/components/prism-bash";
import "prismjs/components/prism-powershell";
import "prismjs/components/prism-json";
import "prismjs/components/prism-batch";
import "prismjs/components/prism-yaml";
import "prismjs/components/prism-markup";
import "prismjs/components/prism-docker";

// Import the Shades of Purple theme
import "prism-themes/themes/prism-shades-of-purple.css";

const COPY_ICON = renderToStaticMarkup(<FaClipboard />);
const CHECK_ICON = renderToStaticMarkup(<FaCheck />);

const WRAPPER_CLASSES = "relative group";
const BUTTON_CLASSES =
  "absolute top-1/2 right-2 -translate-y-1/2 p-1.5 bg-black/35 border border-white/15 rounded text-white/45 cursor-pointer opacity-0 transition-all duration-150 leading-[0] flex items-center justify-center group-hover:opacity-100 focus-visible:opacity-100 hover:text-[#ff1365] hover:border-[#ff1365]/50 hover:bg-[#ff1365]/10";
const COPIED_ADD = ["!text-[#4ade80]", "!border-[#4ade80]/50", "!opacity-100"];

// Export the highlighting function so it can be called directly
export function highlightCode() {
  const codeBlocks = document.querySelectorAll("pre code");
  codeBlocks.forEach((codeBlock) => {
    // skip all pre tags with class no-highlight
    if (codeBlock.parentElement?.classList.contains("no-highlight")) {
      return;
    }
    if (typeof codeBlock === "object") {
      Prism.highlightElement(codeBlock);
    }
  });
}

export function addCopyButtons() {
  const codeBlocks = document.querySelectorAll("pre code");
  codeBlocks.forEach((codeBlock) => {
    const pre = codeBlock.parentElement;
    if (!pre) return;
    // Skip no-highlight blocks (e.g. ShellBox)
    if (pre.classList.contains("no-highlight")) return;
    // Skip output language blocks
    if (codeBlock.classList.contains("language-output")) return;
    // Skip if already processed
    if (pre.dataset.copyButtonAdded) return;
    pre.dataset.copyButtonAdded = "true";

    // Wrap the pre in a relative container so the button sits outside the scroll area
    const wrapper = document.createElement("div");
    wrapper.className = WRAPPER_CLASSES;
    pre.parentNode?.insertBefore(wrapper, pre);
    wrapper.appendChild(pre);

    const button = document.createElement("button");
    button.className = BUTTON_CLASSES;
    button.setAttribute("aria-label", "Copy code to clipboard");
    button.setAttribute("title", "Copy code");
    button.innerHTML = COPY_ICON;

    button.addEventListener("click", async () => {
      const code = codeBlock.textContent || "";
      try {
        await navigator.clipboard.writeText(code);
        button.innerHTML = CHECK_ICON;
        button.classList.add(...COPIED_ADD);
        setTimeout(() => {
          button.innerHTML = COPY_ICON;
          button.classList.remove(...COPIED_ADD);
        }, 2000);
      } catch {
        // Clipboard API unavailable
      }
    });

    wrapper.appendChild(button);
  });
}

// Client component that enhances code blocks with PrismJS
export default function SyntaxHighlighter() {
  useEffect(() => {
    // Run highlighting and copy buttons on every render, just like in the Gatsby implementation
    highlightCode();
    addCopyButtons();

    // Set up MutationObserver to catch dynamically added code blocks
    const observer = new MutationObserver((mutations) => {
      let shouldHighlight = false;

      mutations.forEach((mutation) => {
        if (mutation.type === "childList" && mutation.addedNodes.length) {
          // Check if any added nodes contain code blocks
          mutation.addedNodes.forEach((node) => {
            // Make sure we're dealing with an Element node before accessing Element-specific properties
            if (node.nodeType === Node.ELEMENT_NODE) {
              // TypeScript needs us to cast to Element to access tagName
              const element = node as Element;
              if (
                element.tagName === "PRE" ||
                element.tagName === "CODE" ||
                element.querySelector("pre, code")
              ) {
                shouldHighlight = true;
              }
            }
          });
        }
      });

      if (shouldHighlight) {
        highlightCode();
        addCopyButtons();
      }
    });

    // Start observing the document with the configured parameters
    observer.observe(document.body, {
      childList: true,
      subtree: true,
    });

    return () => observer.disconnect();
  }); // No dependency array means this runs on every render

  return null; // This component doesn't render anything
}
