// Some portions generated by Co-Pilot
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { render, act, cleanup } from "@testing-library/react";
import SyntaxHighlighter, { highlightCode, addCopyButtons } from "../index";

// Mock sugar-high
vi.mock("sugar-high", () => ({
  highlight: vi.fn((code: string) => `<span class="sh__line">${code}</span>`),
}));

// Mock react-icons
vi.mock("react-icons/fa", () => ({
  FaClipboard: () => null,
  FaCheck: () => null,
}));

function makeCodeBlock(
  language?: string,
  extraPreClass?: string,
): HTMLPreElement {
  const pre = document.createElement("pre");
  if (extraPreClass) pre.className = extraPreClass;
  const code = document.createElement("code");
  if (language) code.className = `language-${language}`;
  code.textContent = "echo hello";
  pre.appendChild(code);
  document.body.appendChild(pre);
  return pre;
}

function getWrapper(pre: HTMLPreElement): Element | null {
  return pre.parentElement;
}

function getCopyButton(pre: HTMLPreElement): HTMLButtonElement | null {
  return pre.parentElement?.querySelector("button") ?? null;
}

beforeEach(() => {
  document.body.innerHTML = "";
  vi.clearAllMocks();
});

afterEach(() => {
  cleanup(); // unmounts React components
  document.body.innerHTML = "";
  vi.useRealTimers();
});

// ---------------------------------------------------------------------------
// highlightCode
// ---------------------------------------------------------------------------

describe("highlightCode", () => {
  it("calls sugar-high highlight for each code block", async () => {
    const { highlight } = await import("sugar-high");
    makeCodeBlock("bash");
    makeCodeBlock("java");

    highlightCode();

    expect(highlight).toHaveBeenCalledTimes(2);
  });

  it("skips pre blocks with the no-highlight class", async () => {
    const { highlight } = await import("sugar-high");
    makeCodeBlock(undefined, "no-highlight");

    highlightCode();

    expect(highlight).not.toHaveBeenCalled();
  });

  it("does nothing when there are no code blocks", () => {
    // no pre/code in DOM — both forEach loops should be no-ops
    expect(() => highlightCode()).not.toThrow();
  });

  it("highlights blocks without no-highlight alongside those with it", async () => {
    const { highlight } = await import("sugar-high");
    makeCodeBlock("bash");
    makeCodeBlock(undefined, "no-highlight");

    highlightCode();

    expect(highlight).toHaveBeenCalledTimes(1);
  });

  it("injects the highlighted markup into the code block", async () => {
    const { highlight } = await import("sugar-high");
    (highlight as unknown as { mockClear: () => void }).mockClear?.();
    const pre = makeCodeBlock("bash");
    const code = pre.querySelector("code")!;
    code.textContent = "echo hi";

    highlightCode();

    expect(code.querySelector(".sh__line")).not.toBeNull();
  });
});

// ---------------------------------------------------------------------------
// addCopyButtons
// ---------------------------------------------------------------------------

describe("addCopyButtons", () => {
  it("does nothing when there are no code blocks", () => {
    expect(() => addCopyButtons()).not.toThrow();
  });

  it("wraps a code block in a relative-group div", () => {
    const pre = makeCodeBlock("bash");
    addCopyButtons();

    const wrapper = getWrapper(pre);
    expect(wrapper?.tagName).toBe("DIV");
    expect(wrapper?.className).toContain("relative");
    expect(wrapper?.className).toContain("group");
  });

  it("appends a button with correct aria attributes", () => {
    const pre = makeCodeBlock("bash");
    addCopyButtons();

    const button = getCopyButton(pre);
    expect(button).not.toBeNull();
    expect(button?.getAttribute("aria-label")).toBe("Copy code to clipboard");
    expect(button?.getAttribute("title")).toBe("Copy code");
  });

  it("does not add a button to no-highlight blocks", () => {
    const pre = makeCodeBlock(undefined, "no-highlight");
    addCopyButtons();

    expect(getCopyButton(pre)).toBeNull();
    // pre should not have been wrapped
    expect(pre.parentElement?.tagName).toBe("BODY");
  });

  it("does not add a button to language-output blocks", () => {
    const pre = makeCodeBlock("output");
    addCopyButtons();

    expect(getCopyButton(pre)).toBeNull();
  });

  it("does not add a second button when called twice", () => {
    const pre = makeCodeBlock("bash");
    addCopyButtons();
    addCopyButtons();

    // pre is now inside the wrapper; wrapper should have exactly one button
    const buttons = document.body.querySelectorAll("button");
    expect(buttons.length).toBe(1);
  });

  it("adds buttons to multiple independent code blocks", () => {
    makeCodeBlock("bash");
    makeCodeBlock("java");
    addCopyButtons();

    const buttons = document.body.querySelectorAll("button");
    expect(buttons.length).toBe(2);
  });

  it("copies code text to clipboard on click", async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    Object.assign(navigator, { clipboard: { writeText } });

    const pre = makeCodeBlock("bash");
    pre.querySelector("code")!.textContent = "apt install temurin-21-jdk";
    addCopyButtons();

    const button = getCopyButton(pre)!;
    await act(async () => {
      button.click();
    });

    expect(writeText).toHaveBeenCalledWith("apt install temurin-21-jdk");
  });

  it("adds copied classes after a successful copy", async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    Object.assign(navigator, { clipboard: { writeText } });

    vi.useFakeTimers({ shouldAdvanceTime: false });
    const pre = makeCodeBlock("bash");
    addCopyButtons();

    const button = getCopyButton(pre)!;
    await act(async () => {
      button.click();
      await Promise.resolve(); // flush clipboard promise microtask
    });

    expect(button.classList.contains("!opacity-100")).toBe(true);
    expect(button.classList.contains("!text-[#4ade80]")).toBe(true);
  });

  it("removes copied classes after 2 seconds", async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    Object.assign(navigator, { clipboard: { writeText } });

    vi.useFakeTimers({ shouldAdvanceTime: false });
    const pre = makeCodeBlock("bash");
    addCopyButtons();

    const button = getCopyButton(pre)!;
    await act(async () => {
      button.click();
      await Promise.resolve();
    });

    expect(button.classList.contains("!opacity-100")).toBe(true);

    act(() => {
      vi.advanceTimersByTime(2000);
    });

    expect(button.classList.contains("!opacity-100")).toBe(false);
    expect(button.classList.contains("!text-[#4ade80]")).toBe(false);
  });

  it("handles clipboard API failure gracefully", async () => {
    const writeText = vi.fn().mockRejectedValue(new Error("not allowed"));
    Object.assign(navigator, { clipboard: { writeText } });

    const pre = makeCodeBlock("bash");
    addCopyButtons();

    const button = getCopyButton(pre)!;
    await expect(
      act(async () => {
        button.click();
      }),
    ).resolves.not.toThrow();
  });
});

// ---------------------------------------------------------------------------
// SyntaxHighlighter component
// ---------------------------------------------------------------------------

describe("SyntaxHighlighter component", () => {
  it("renders nothing to the DOM", () => {
    const { container } = render(<SyntaxHighlighter />);
    expect(container.firstChild).toBeNull();
  });

  it("calls highlightCode and addCopyButtons on mount", async () => {
    const { highlight } = await import("sugar-high");
    makeCodeBlock("bash");

    await act(async () => {
      render(<SyntaxHighlighter />);
    });

    expect(highlight).toHaveBeenCalled();
    const button = document.body.querySelector("button");
    expect(button).not.toBeNull();
  });
});
