// Some portions generated by Co-Pilot
import React from "react";
import { render, fireEvent, cleanup } from "@testing-library/react";
import { describe, it, expect, vi, afterEach, beforeEach } from "vitest";

const mockPush = vi.fn();
vi.mock("next/navigation", () => ({
  useRouter: () => ({ push: mockPush }),
}));

import ReleaseNotesVersionSelector from "../index";

const defaultProps = {
  availableVersions: [21, 17, 11, 8],
  availableLTSVersions: [21, 17, 11, 8],
};

describe("ReleaseNotesVersionSelector", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });
  afterEach(() => {
    cleanup();
  });

  it("renders a button for each available version", () => {
    const { getAllByRole } = render(
      <ReleaseNotesVersionSelector {...defaultProps} />,
    );
    const buttons = getAllByRole("button");
    expect(buttons).toHaveLength(4);
  });

  it("clicking a version calls router.push with the correct query", () => {
    const { getAllByRole } = render(
      <ReleaseNotesVersionSelector {...defaultProps} />,
    );
    fireEvent.click(getAllByRole("button")[0]); // JDK 21
    expect(mockPush).toHaveBeenCalledWith("?version=21");
  });

  it("clicking a non-LTS version calls router.push correctly", () => {
    const { getAllByRole } = render(
      <ReleaseNotesVersionSelector
        availableVersions={[22, 21]}
        availableLTSVersions={[21]}
      />,
    );
    fireEvent.click(getAllByRole("button")[0]); // JDK 22 (non-LTS)
    expect(mockPush).toHaveBeenCalledWith("?version=22");
  });

  it("LTS versions get LTS badge styling", () => {
    const { container } = render(
      <ReleaseNotesVersionSelector
        availableVersions={[22, 21]}
        availableLTSVersions={[21]}
      />,
    );
    const buttons = container.querySelectorAll("button");
    // JDK 21 (LTS) should have LTS badge text
    expect(buttons[1].textContent).toContain("LTS");
    // JDK 22 (non-LTS)
    expect(buttons[0].textContent).toContain("Non-LTS");
  });

  it("renders legend for LTS and non-LTS", () => {
    const { getByText } = render(
      <ReleaseNotesVersionSelector {...defaultProps} />,
    );
    expect(getByText("LTS Version")).toBeTruthy();
    expect(getByText("Non-LTS Version")).toBeTruthy();
  });
});
