= Adoptium(R) 市场发布商指南
:description: Adoptium 市场发布商指南
:keywords: Adoptium 市场
:orgname: Eclipse Adoptium
:page-authors: tellison, gdams, jiekang, NickJavaDev88
:page-based-on: f2e6e929f64dd6ef7bd7f452d2aed14095705a31

== 简介

本文档旨在为有资格通过 link:/marketplace[Adoptium 市场]营销和推广 OpenJDK 运行时的发布商提供详细指导。

发布商可以是供应商、非营利组织、用户组，或者是任何认同 link:/docs/marketplace-policy[Adoptium 市场策略^]核心价值观的个人或团队。发布商可以提供开源或者具有商业许可的产品，且最终用户可以免费或付费使用这些产品。市场本身并不限制特定的版本、平台、使用方式或许可条款，通过市场提供的二进制文件同样可以在其他渠道发布。唯一的要求是：通过 Adoptium 市场分发的所有二进制文件，必须严格符合市场策略中所定义的兼容性和质量标准。

最终用户可以通过两种主要途径访问和使用市场：Adoptium 项目托管并维护的link:/marketplace[网站]，以及其提供的https://marketplace-api.adoptium.net/[应用程序编程接口^] (API)。

我们非常鼓励发布商与 link:/members[Adoptium 工作组]积极沟通其在市场中的参与计划。工作组将针对后续的各个步骤提供必要的指导与协助。请注意，如果下文引用的正式策略和协议与本指南存在任何冲突，一律以正式的策略和协议为准。

== 预备工作与非技术要求

潜在的发布商及其产品必须首先满足 link:/marketplace-policy[Adoptium 市场策略]中规定的各项标准。其中一项关键要求是：您需要成为 Adoptium 工作组中具备相应级别的成员。这不仅是准入门槛，也将赋予您在制定市场策略和运营事务上的话语权。当然，并非所有工作组成员都会选择成为发布商。同时，我们也欢迎最终用户加入工作组，共同帮助塑造市场产品的未来并完善相关要求。

有意在市场中发布产品的工作组成员必须签署并同意 https://www.eclipse.org/legal/documents/eclipse-adoptium-marketplace-publisher-agreement.pdf[Adoptium 市场发布商协议]。 本协议明确了 Eclipse 基金会接受并推广您产品的相关条款和条件。一旦您的产品被市场成功接纳，便能享受到一系列量身定制的营销活动支持，从而最大限度地提升这些二进制文件在该生态系统中的价值。

== 发布流程概览

Adoptium 市场网站和 API 的核心驱动力，源自于您所提供的关于符合条件产品的元数据。这些元数据需要以机器可读的 https://www.json.org/[JSON^] 格式提交，并必须附带 https://en.wikipedia.org/wiki/Digital_signature[安全数字签名^]，以确保您发布信息的真实性、完整性以及不可抵赖性。

作为发布商，您有责任进行自我认证：您需要保证元数据中描述的每一项产品信息都是准确且可靠的，并承诺严格遵守您在link:/marketplace-policy[市场策略]中勾勒的各项规定与义务。

您拥有完全的控制权来决定产品元数据的更新频率及其他细节。Adoptium 市场应用程序将利用这些信息来帮助营销您的产品，并引导用户直接前往受您控制的官方网站下载。Adoptium 本身不会托管或直接分发您的二进制文件。

当用户通过 Adoptium 市场发起下载时，他们将被引导至一个“下载后感谢页面”。您可以在该页面上配置一个专属链接，以引导用户了解更多关于您的产品、组织或者相关服务的额外信息。

== 提供发布商资料

发布商必须提供以下基本信息，以便顺利入驻市场：

 * 发布商名称：您希望在市场网站和 API 中对外展示的官方名称。
 * 徽标图像：代表您发布商身份的视觉图标，将用于网站的各种展示位。
 * 上架数据位置： Adoptium 用于检索并拉取您的市场列表元数据的基础 URL（Base URL）。
 * 签名公钥：我们将用于验证您数字签名合法性的公开密钥。
 * 下载后重定向页面：用户在启动下载您的产品后，我们应引导他们访问的网页地址。

考虑到 Adoptium 会将这些信息硬编码到市场应用程序的配置中，我们预计这些核心资料不会被频繁更改。

要提交您的发布商资料，请在 Adoptium 官方存储库中发起一个 https://github.com/adoptium/adoptium/issues/new/choose[新的发布商请求 Issue^]。如果未来您确实需要更新这些信息，也可以在同一存储库中随时提交新的 Issue。

== 通过 Oracle TCK 兼容性测试

您通过 Adoptium 市场发布的每个二进制文件，都必须完全满足您试图推广的 Java 平台版本所对应的最新 TCK 测试的所有要求。您需要全权负责在二进制文件公开发布前，确保它已经实际执行并顺利通过了这项测试。Adoptium 不会代为执行这项检查。

Adoptium 项目https://projects.eclipse.org/projects/adoptium.temurin-compliance[开发并使用了一系列工具^]，旨在让运行和分析 TCK 测试的过程变得更加简便。我们非常欢迎发布商积极参与这些技术项目，并利用这些工具来辅助完成自家产品的 TCK 测试。

== 通过 AQAvit 质量验证测试

您通过 Adoptium 市场发布的每个二进制文件，都必须完全通过您所支持版本的最新 AQAvit 测试套件的所有验证。在二进制文件正式发布前，您有责任确保上述条件得到满足，并已实际完成了测试。Adoptium 不会代您进行检查。

必须在某款二进制文件最初登录市场时，确保其满足 link:/aqavit[AQAvit 验证标准]。我们并不强制要求发布商使用后续更新的、更高版本的 AQAvit 套件对已发布的旧二进制文件进行回溯验证。只要该二进制文件一经达标并入驻，它就可以一直在市场上保持可用状态。

AQAvit 是一套在 Adoptium 项目框架下托管维护的开源测试套件。我们十分鼓励发布商参与到 AQAvit 项目中来，以便在对自身产品运行 AQAvit 测试时，获得更好的社区支持与帮助。

== 维护产品上架信息

您的市场产品上架内容存放在何处由您全权决定，只要它由您直接控制，并支持标准的 https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol[HTTP^] 请求与响应即可（例如您自己的网站服务器或 GitHub 等）。尽管 Adoptium 会通过验证数字签名来安全地接收并处理这些信息，但对于通过您提供的 URL 传达到市场的信息内容的合法性与准确性，您需要承担最终责任。

产品上架信息被封装在一个结构化的 JSON 文件中。在设计上它极具灵活性，允许单个文件中包含多个不同的构建（Builds）和版本（Versions）。这套信息的源头正是您在前面<<提供发布商信息,发布商资料>>步骤中提交的“上架数据位置”URL，相关的详细规范在 link:/docs/marketplace-listing[Adoptium 市场发布商产品上架存储库]文档中有详尽描述。

// TODO: 如何检查拉取的成功/失败日志以及架构验证？
如果您的产品上架信息没有严格遵守 link:/docs/marketplace-listing[产品上架结构规范]、市场文件 JSON 架构，或者其数字签名未能成功通过校验，那么该信息将被系统拒绝。如果您的上架文件多次由于这些原因验证失败，我们的团队将会主动与您联系。

== 构建下载后页面

// TODO: 下载后的重定向应该是基于发布商的还是基于产品的（即嵌入在元数据中）？
当用户在市场网站上决定下载您的产品时，由于实际的下载动作是在您的分发服务器上发起的，因此用户在操作后会被自动导向一个“下载后页面”。这个页面会在向用户表达感谢的同时展示您的发布商标识，并提供一个指向您指定网页的导流链接。我们设计的初衷是希望借此机会，为您引导流量，让用户深入了解您的产品、组织背景或增值服务。

需要注意的是，这一下载后页面链接仅用于网站的重定向流程，并不会被 https://marketplace-api.adoptium.net/[Adoptium 市场 API]系统采纳或使用。
