// Some portions generated by Co-Pilot
= Guide des éditeurs de la Marketplace Adoptium(R)
:description: Adoptium Marketplace Publisher Guide
:keywords: adoptium marketplace
:orgname: Eclipse Adoptium
:page-authors: tellison, gdams, jiekang
:page-based-on: f2e6e929f64dd6ef7bd7f452d2aed14095705a31

== Introduction

Ce document fournit des conseils aux éditeurs éligibles pour commercialiser et promouvoir des environnements d'exécution OpenJDK via la
link:/marketplace[Marketplace Adoptium].

Les éditeurs peuvent être des fournisseurs, des entités à but non lucratif, des groupes d'utilisateurs et d'autres entités qui partagent les valeurs incarnées dans la
link:/docs/marketplace-policy[politique de la marketplace Adoptium^].
Les éditeurs peuvent proposer des offres open source ou sous licence commerciale, utilisables sans frais ou moyennant un paiement de l'utilisateur final. La marketplace n'impose pas de conditions spécifiques de version, de plateforme, d'utilisation ou de licence, et les binaires disponibles via la marketplace peuvent également être disponibles ailleurs. Tous les binaires proposés via la marketplace Adoptium doivent satisfaire aux critères de compatibilité et de qualité définis dans la politique de la marketplace.

La marketplace est accessible aux utilisateurs finaux à la fois via un
link:/marketplace[site web]
et via une
https://marketplace-api.adoptium.net/[interface de programmation d'application^]
(API) hébergée et maintenue par le projet Adoptium.

Les éditeurs sont encouragés à discuter de leur participation à la marketplace avec le
link:/members[groupe de travail Adoptium]
qui fournira des conseils et une assistance pour les étapes décrites ci-dessous. En cas de contradiction entre les politiques et accords formels référencés ci-dessous et ce guide de l'éditeur, les politiques et accords formels prévaudront.


== Étapes préparatoires non techniques

Les éditeurs potentiels et leurs produits doivent satisfaire aux critères décrits dans la
link:/marketplace-policy[politique de la Marketplace Adoptium]. Ces critères comprennent le fait de devenir membre du groupe de travail Adoptium à un niveau approprié, vous donnant voix au chapitre dans la politique et le fonctionnement de la marketplace. Tous les membres du groupe de travail ne seront pas nécessairement des éditeurs. Les utilisateurs finaux sont également encouragés à rejoindre le groupe de travail pour aider à orienter les produits et les exigences des produits de la marketplace.

Les membres du groupe de travail qui souhaitent publier un produit sur la marketplace doivent accepter l'
https://www.eclipse.org/legal/documents/eclipse-adoptium-marketplace-publisher-agreement.pdf[accord d'éditeur de la Marketplace Adoptium]. Cet accord définit les termes et conditions selon lesquels l'Eclipse Foundation accepte la promotion de votre produit. Les produits bénéficieront d'initiatives marketing destinées à promouvoir la valeur des binaires dans ce contexte une fois acceptés sur la marketplace.


== Aperçu de la publication

Le site web et l'API de la marketplace Adoptium sont alimentés par des métadonnées que vous fournissez sur vos produits éligibles. Les métadonnées sont mises à votre disposition dans un format lisible par machine
https://www.json.org/[JSON^],
accompagnées d'une
https://en.wikipedia.org/wiki/Digital_signature[signature numérique sécurisée^]
pour garantir l'authenticité, l'intégrité et la non-répudiation des informations que vous publiez.

En tant qu'éditeur, vous êtes responsable de certifier vous-même que les informations de chaque produit décrit dans les métadonnées sont exactes et respectent vos obligations dans la
link:/marketplace-policy[politique de la Marketplace].

Vous contrôlez les métadonnées de vos produits et la fréquence à laquelle elles sont mises à jour. L'application de la marketplace Adoptium s'appuiera sur ces informations pour commercialiser vos produits et dirigera les utilisateurs vers le téléchargement de votre produit directement depuis un site sous votre contrôle. Adoptium n'héberge ni ne distribue vos binaires.

Lorsqu'un téléchargement est initié via la marketplace Adoptium, les utilisateurs seront dirigés vers une page post-téléchargement où vous pouvez fournir un lien vers des informations supplémentaires sur votre produit, votre organisation, vos services, etc.


== Fournir les informations de l'éditeur

Les éditeurs doivent fournir les informations suivantes pour être inclus dans la marketplace.

 * Nom de l'éditeur : la façon dont vous souhaitez être connu sur le site web et l'API de la marketplace.
 * Image du logo : une représentation visuelle de vous en tant qu'éditeur pour une utilisation sur le site web.
 * Emplacement des données de liste : l'URL de base qu'Adoptium utilisera pour récupérer vos métadonnées de liste de la marketplace.
 * Clé publique de signature : la clé publique que nous utiliserons pour vérifier votre signature.
 * Page post-téléchargement : la page web vers laquelle nous devons diriger les utilisateurs du site web lors du téléchargement de votre produit.
  
Nous ne vous attendons pas à les modifier fréquemment, car Adoptium les intègre dans la configuration de l'application de la marketplace.

Les informations de l'éditeur sont fournies en ouvrant une
https://github.com/adoptium/adoptium/issues/new/choose[nouvelle demande d'éditeur^]
dans le dépôt Adoptium. Vous pouvez ouvrir un nouvel incident dans le même dépôt si vous devez ensuite les modifier.


== Réussir les tests TCK Oracle

Chaque binaire que vous publiez via la marketplace Adoptium doit satisfaire pleinement toutes les exigences du TCK alors en vigueur pour la version de la plateforme Java que vous promouvez via la marketplace Adoptium. Vous êtes responsable de vous assurer que cela a été accompli avant de publier le binaire. Adoptium ne vérifiera pas cela en votre nom.

Les projets Adoptium
https://projects.eclipse.org/projects/adoptium.temurin-compliance[développent et utilisent des outils^]
qui facilitent l'exécution et l'analyse du TCK. Les éditeurs sont invités à participer au projet technique et à utiliser ces outils pour faciliter l'exécution du TCK sur leurs propres produits.


== Réussir les tests de vérification AQAvit

Chaque binaire que vous publiez via la marketplace Adoptium doit satisfaire pleinement toutes les exigences de la suite de tests AQAvit alors en vigueur pour la version que vous promouvez via la marketplace Adoptium. Vous êtes responsable de vous assurer que cela a été accompli avant de publier le binaire. Adoptium ne vérifiera pas cela en votre nom.

Le
link:/aqavit[processus de vérification AQAvit]
doit être satisfait au moment où le binaire est initialement proposé via la marketplace. Les éditeurs ne sont pas tenus de vérifier le binaire par rapport aux versions ultérieures de la suite de vérification AQAvit. Une fois qu'un binaire satisfait aux critères, il peut continuer à être proposé via la marketplace.

AQAvit est une suite de tests open source gérée au sein du projet Adoptium. Les éditeurs sont invités à participer au projet AQAvit pour obtenir de l'aide pour l'exécution d'AQAvit sur leurs propres produits.


== Informations de liste de produits

La liste de vos produits pour la marketplace peut être hébergée n'importe où sous votre contrôle direct qui prend en charge les requêtes et réponses
https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol[HTTP^],
y compris votre propre propriété web, GitHub, etc. Bien qu'Adoptium vérifie que les informations sont reçues de manière sécurisée grâce à une signature numérique basée sur des informations vérifiées, vous êtes en définitive responsable des informations fournies à la marketplace via l'URL de l'emplacement des données de liste.

Les informations de liste de produits comprennent des fichiers au format JSON structuré, avec suffisamment de flexibilité pour permettre plusieurs builds et versions. Les informations sont enracinées à l'emplacement des données de liste fourni dans les <<Providing-Publisher-Information,informations de l'éditeur>> dans le format décrit dans la documentation
link:/docs/marketplace-listing[Dépôt de liste de produits pour les éditeurs de la Marketplace Adoptium].

// TODO: How does a publisher check the logs of successful/failed pulls and schema validation?
Les informations de liste de produits seront rejetées si elles ne sont pas conformes à la
link:/docs/marketplace-listing[structure de liste de produits],
au schéma de fichier de la marketplace, ou si la signature ne vérifie pas correctement le contenu. Nous vous contacterons si le fichier de liste échoue à plusieurs reprises à ces vérifications de validation.

== Page post-téléchargement

// TODO: Should the post-download be per-publisher or per-product (i.e. embedded in the metadata).
Lorsqu'un utilisateur choisit de télécharger votre produit via le site web de la marketplace, il sera dirigé vers une page post-téléchargement au moment où le téléchargement est initié depuis votre serveur de distribution. La page post-téléchargement remerciera l'utilisateur et identifiera l'éditeur, avec un lien vers une page web de votre choix. Nous envisageons que cette page web orientera l'utilisateur vers des informations sur votre produit, votre organisation, vos services, etc.

Le lien de la page post-téléchargement n'est pas utilisé par l'
https://marketplace-api.adoptium.net/[API de la marketplace Adoptium].
