// Some portions generated by Co-Pilot
= Adoptium(R) マーケットプレイス パブリッシャーガイド
:description: Adoptium マーケットプレイス パブリッシャーガイド
:keywords: adoptium marketplace
:orgname: Eclipse Adoptium
:page-authors: tellison, gdams, jiekang
:page-based-on: f2e6e929f64dd6ef7bd7f452d2aed14095705a31

== はじめに

このドキュメントは、
link:/marketplace[Adoptium マーケットプレイス]
を通じて OpenJDK ランタイムをマーケティング・プロモーションする資格を持つパブリッシャーに向けたガイダンスです。

パブリッシャーは、
link:/docs/marketplace-policy[Adoptium マーケットプレイスポリシー^]
に体現された価値観を共有するベンダー、非営利団体、ユーザーグループ、その他の組織が対象です。
パブリッシャーはオープンソースまたは商用ライセンスのオファリングを提供でき、エンドユーザーに対して無償または有償で提供することができます。マーケットプレイスは特定のバージョン、プラットフォーム、利用方法、またはライセンス条件を要求しておらず、マーケットプレイスを通じて提供されるバイナリは他の場所でも入手可能な場合があります。Adoptium マーケットプレイスを通じて提供されるすべてのバイナリは、マーケットプレイスポリシーに定義された互換性および品質基準を満たす必要があります。

マーケットプレイスはエンドユーザーに対して、
link:/marketplace[ウェブサイト]
および Adoptium プロジェクトがホスト・運営する
https://marketplace-api.adoptium.net/[アプリケーションプログラミングインターフェース^]
（API）の両方で利用可能です。

パブリッシャーは、以下に説明する手順についてガイダンスと支援を提供する
link:/members[Adoptium ワーキンググループ]
とマーケットプレイスへの参加について協議することを推奨します。以下で参照される正式なポリシーおよび契約とこのパブリッシャーガイドとの間に矛盾がある場合は、正式なポリシーおよび契約が優先されます。


== 準備段階の非技術的手順

潜在的なパブリッシャーおよびその製品は、
link:/marketplace-policy[Adoptium マーケットプレイスポリシー]
に記載されている基準を満たす必要があります。これらの基準には、マーケットプレイスのポリシーと運営に関する発言権を得るために、適切なレベルで Adoptium ワーキンググループのメンバーになることが含まれます。ワーキンググループのすべてのメンバーがパブリッシャーになるわけではありません。エンドユーザーもマーケットプレイス製品の方向性や要件を導くためにワーキンググループへの参加が推奨されます。

マーケットプレイスに製品を公開したいワーキンググループメンバーは、
https://www.eclipse.org/legal/documents/eclipse-adoptium-marketplace-publisher-agreement.pdf[Adoptium マーケットプレイス パブリッシャー契約]
に同意する必要があります。この契約は、Eclipse Foundation が製品プロモーションを受け入れる条件を定めています。マーケットプレイスに受け入れられた製品は、このコンテキストでのバイナリの価値を促進するためのマーケティングイニシアティブから恩恵を受けます。


== 公開の概要

Adoptium マーケットプレイスのウェブサイトと API は、対象製品に関してパブリッシャーが提供するメタデータによって動作します。メタデータは
https://www.json.org/[JSON^]
機械可読形式で提供され、公開する情報の真正性、完全性、否認防止を確保するために
https://en.wikipedia.org/wiki/Digital_signature[セキュアなデジタル署名^]
とともに提供されます。

パブリッシャーとして、メタデータに記載された各製品の情報が正確であり、
link:/marketplace-policy[マーケットプレイスポリシー]
における義務に準拠していることを自己証明する責任があります。

製品のメタデータとその更新頻度はパブリッシャーが管理します。Adoptium マーケットプレイスアプリケーションはその情報を利用して製品をマーケティングし、ユーザーをパブリッシャーが管理するサイトから直接製品をダウンロードするよう誘導します。Adoptium はバイナリをホストまたは配布しません。

Adoptium マーケットプレイス経由でダウンロードが開始されると、ユーザーはダウンロード後のページに誘導され、製品、組織、サービスなどに関する追加情報へのリンクを提供することができます。


== パブリッシャー情報の提供

マーケットプレイスに掲載されるために、パブリッシャーは以下の情報を提供する必要があります。

 * パブリッシャー名：マーケットプレイスのウェブサイトと API でどのように表示されるか。
 * ロゴ画像：ウェブサイトで使用するパブリッシャーのビジュアル表現。
 * リスティングデータの場所：Adoptium がマーケットプレイスのリスティングメタデータを取得するために使用するベース URL。
 * 署名公開鍵：署名の検証に使用する公開鍵。
 * ダウンロード後のページ：製品をダウンロードする際にウェブサイトユーザーを誘導するウェブページ。

これらはマーケットプレイスアプリケーションの設定に追加されるため、頻繁な変更は想定されません。

パブリッシャー情報は、Adoptium リポジトリで
https://github.com/adoptium/adoptium/issues/new/choose[新しいパブリッシャーリクエスト issue^]
を作成することで提供されます。後で変更が必要な場合も、同じリポジトリで新しい issue を作成できます。


== Oracle TCK テストの合格

Adoptium マーケットプレイスで公開するすべてのバイナリは、Adoptium マーケットプレイスで宣伝している Java Platform バージョンの現行 TCK のすべての要件を完全に満たす必要があります。バイナリを公開する前にこれを確実にする責任はパブリッシャーにあります。Adoptium はこれを代わりに確認しません。

Adoptium プロジェクトは TCK の実行と分析を容易にする
https://projects.eclipse.org/projects/adoptium.temurin-compliance[ツールを開発・使用しています^]。
パブリッシャーはこの技術プロジェクトに参加し、これらのツールを使って自社製品で TCK を実行する作業を支援することができます。


== AQAvit 検証テストの合格

Adoptium マーケットプレイスで公開するすべてのバイナリは、Adoptium マーケットプレイスで宣伝しているバージョンの現行 AQAvit テストスイートのすべての要件を完全に満たす必要があります。バイナリを公開する前にこれを確実にする責任はパブリッシャーにあります。Adoptium はこれを代わりに確認しません。

バイナリがマーケットプレイスで最初に提供される時点で、
link:/aqavit[AQAvit 検証プロセス]
を満たす必要があります。パブリッシャーは AQAvit 検証スイートの後続リリースに対してバイナリを再検証する必要はありません。一度バイナリが基準を満たせば、マーケットプレイスで継続して提供することができます。

AQAvit は Adoptium プロジェクトで管理されているオープンソースのテストスイートです。パブリッシャーは AQAvit プロジェクトに参加して、自社製品で AQAvit を実行する作業の支援を受けることができます。


== 製品リスティング情報

マーケットプレイス向けの製品リスティングは、
https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol[HTTP^]
リクエストとレスポンスをサポートする、独自のウェブサイト、GitHub など、パブリッシャーが直接管理する任意の場所でホストできます。Adoptium は、検証済み情報に基づくデジタル署名を使用してパブリッシャーから安全に情報を受け取ることを確認しますが、リスティングデータの場所の URL を通じてマーケットプレイスに提供される情報に対しては、最終的にパブリッシャーが責任を負います。

製品リスティング情報は構造化された JSON 形式のファイルで構成され、複数のビルドやバージョンを柔軟に扱えます。情報は
link:/docs/marketplace-listing[Adoptium マーケットプレイス パブリッシャー製品リスティングリポジトリ]
ドキュメントに記載された形式で、<<Providing-Publisher-Information,パブリッシャー情報>>に指定されたリスティングデータの場所を起点とします。

// TODO: How does a publisher check the logs of successful/failed pulls and schema validation?
製品リスティング情報が
link:/docs/marketplace-listing[製品リスティング構造]、
マーケットプレイスファイルスキーマに準拠していない場合、またはシグネチャがコンテンツの検証に成功しない場合は拒否されます。リスティングファイルがこれらの検証チェックに繰り返し失敗している場合はご連絡します。

== ダウンロード後のページ

// TODO: Should the post-download be per-publisher or per-product (i.e. embedded in the metadata).
ユーザーがマーケットプレイスウェブサイトで製品のダウンロードを選択すると、配布サーバーからダウンロードが開始されると同時に、ダウンロード後のページに誘導されます。ダウンロード後のページはユーザーへの感謝を示し、パブリッシャーを識別する情報と、パブリッシャーが選択したウェブページへのリンクを含みます。このウェブページでは製品、組織、サービスなどに関する情報にユーザーを誘導することを想定しています。

ダウンロード後のページのリンクは
https://marketplace-api.adoptium.net/[Adoptium マーケットプレイス API]
では使用されません。
