// Some portions generated by Co-Pilot
= Guia do Publicador do Marketplace Adoptium(R)
:description: Adoptium Marketplace Publisher Guide
:keywords: adoptium marketplace
:orgname: Eclipse Adoptium
:page-authors: tellison, gdams, jiekang
:page-based-on: f2e6e929f64dd6ef7bd7f452d2aed14095705a31

== Introdução

Este documento fornece orientações para publicadores elegíveis para comercializar e promover runtimes OpenJDK pelo
link:/marketplace[Adoptium Marketplace].

Os publicadores podem ser fornecedores, entidades sem fins lucrativos, grupos de usuários e outros que compartilham os valores incorporados na
link:/docs/marketplace-policy[política do marketplace Adoptium^].
Os publicadores podem oferecer produtos de código aberto ou com licença comercial, cada um utilizável gratuitamente ou mediante pagamento para o usuário final. O marketplace não exige termos específicos de versão, plataforma, uso ou licença, e os binários disponíveis pelo marketplace podem também estar disponíveis em outros locais. Todos os binários oferecidos pelo Adoptium Marketplace devem atender aos critérios de compatibilidade e qualidade definidos na política do marketplace.

O marketplace está disponível para os usuários finais tanto como
link:/marketplace[site]
quanto como
https://marketplace-api.adoptium.net/[interface de programação de aplicações^]
(API) hospedada e mantida pelo projeto Adoptium.

Os publicadores são incentivados a discutir sua participação no marketplace com o
link:/members[Adoptium Working Group]
que fornecerá orientação e assistência com os passos descritos abaixo. Em caso de quaisquer contradições entre as políticas formais e acordos referenciados abaixo e este guia do publicador, as políticas formais e acordos terão precedência.


== Etapas Preliminares Não-técnicas

Os potenciais publicadores e seus produtos devem atender aos critérios descritos na
link:/marketplace-policy[Política do Adoptium Marketplace]. Esses critérios incluem tornar-se membro do working group Adoptium no nível apropriado, dando a você voz na política e operação do marketplace. Nem todo membro do working group será um publicador. Os usuários finais também são encorajados a ingressar no working group para ajudar a guiar os produtos e requisitos dos produtos do marketplace.

Os membros do working group que desejam publicar um produto no marketplace devem concordar com o
https://www.eclipse.org/legal/documents/eclipse-adoptium-marketplace-publisher-agreement.pdf[Acordo de Publicador do Adoptium Marketplace]. Este acordo estabelece os termos e condições sob os quais a Eclipse Foundation aceita a promoção do seu produto. Os produtos se beneficiarão de iniciativas de marketing destinadas a promover o valor dos binários neste contexto quando aceitos no marketplace.


== Visão Geral da Publicação

O site e a API do marketplace Adoptium são alimentados por metadados que você fornece sobre seus produtos elegíveis. Os metadados são disponibilizados por você no formato legível por máquina
https://www.json.org/[JSON^],
junto com uma
https://en.wikipedia.org/wiki/Digital_signature[assinatura digital segura^]
para garantir a autenticidade, integridade e não repúdio das informações que você publica.

Como publicador, você é responsável por autossertificar que as informações de cada produto descrito nos metadados são precisas e aderem às suas obrigações na
link:/marketplace-policy[Política do Marketplace].

Você controla os metadados dos seus produtos e a frequência com que são atualizados. A aplicação do marketplace Adoptium usará essas informações para comercializar seus produtos e direcionar os usuários para baixar seu produto diretamente de um site sob seu controle. O Adoptium não hospeda nem distribui seus binários.

Quando um download é iniciado pelo marketplace Adoptium, os usuários serão direcionados para uma página pós-download onde você pode fornecer um link para informações adicionais sobre seu produto, organização, serviços e assim por diante.


== Fornecendo Informações do Publicador

Os publicadores devem fornecer as seguintes informações para serem incluídos no marketplace.

 * Nome do publicador: como você gostaria de ser conhecido no site e na API do marketplace.
 * Imagem do logotipo: uma representação visual de você como publicador para uso no site.
 * Localização dos dados de listagem: a URL base que o Adoptium usará para recuperar seus metadados de listagem do marketplace.
 * Chave pública de assinatura: a chave pública que usaremos para verificar sua assinatura.
 * Página pós-download: a página web para a qual direcionaremos os usuários do site ao baixar seu produto.
 
Não esperamos que você mude essas informações com frequência, pois o Adoptium as adicionará na configuração da aplicação do marketplace.

As informações do publicador são fornecidas abrindo uma
https://github.com/adoptium/adoptium/issues/new/choose[nova issue de solicitação de publicador^]
no repositório Adoptium. Você pode abrir uma nova issue no mesmo repositório se precisar alterá-las posteriormente.


== Passando nos testes TCK da Oracle

Todo binário que você publicar pelo marketplace Adoptium deve satisfazer completamente todos os requisitos do TCK atual para a versão da Plataforma Java que você está promovendo pelo marketplace Adoptium. Você é responsável por garantir que isso aconteça antes de publicar o binário. O Adoptium não verificará isso em seu nome.

Os projetos Adoptium
https://projects.eclipse.org/projects/adoptium.temurin-compliance[desenvolvem e usam ferramentas^]
que facilitam a execução e análise do TCK. Os publicadores são bem-vindos a participar do projeto técnico e usar essas ferramentas para ajudar na tarefa de executar o TCK em seus próprios produtos.


== Passando nos testes de verificação AQAvit

Todo binário que você publicar pelo marketplace Adoptium deve satisfazer completamente todos os requisitos da suíte de testes AQAvit atual para a versão que você está promovendo pelo marketplace Adoptium. Você é responsável por garantir que isso aconteça antes de publicar o binário. O Adoptium não verificará isso em seu nome.

O
link:/aqavit[processo de verificação AQAvit]
deve ser satisfeito no momento em que o binário é inicialmente oferecido pelo marketplace. Os publicadores não são obrigados a verificar o binário para versões posteriores da suíte de verificação AQAvit. Uma vez que um binário atende aos critérios, ele pode continuar a ser oferecido pelo marketplace.

O AQAvit é uma suíte de testes de código aberto gerenciada no projeto Adoptium. Os publicadores são bem-vindos a participar do projeto AQAvit para obter ajuda na tarefa de executar o AQAvit em seus próprios produtos.


== Informações de Listagem do Produto

A listagem dos seus produtos para o marketplace pode ser hospedada em qualquer lugar sob seu controle direto que suporte solicitações e respostas
https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol[HTTP^],
incluindo sua própria propriedade de site, GitHub e assim por diante. Embora o Adoptium verifique que as informações são recebidas de você de forma segura usando uma assinatura digital baseada em informações verificadas, você é, em última análise, responsável pelas informações fornecidas ao marketplace por meio da URL de localização dos dados de listagem.

As informações de listagem do produto compreendem arquivos no formato JSON estruturado, com flexibilidade para permitir múltiplos builds e versões. As informações estão enraizadas na localização dos dados de listagem fornecida nas <<Providing-Publisher-Information,informações do publicador>> no formato descrito na documentação do
link:/docs/marketplace-listing[Repositório de Listagem de Produtos do Publicador do Adoptium Marketplace].

// TODO: How does a publisher check the logs of successful/failed pulls and schema validation?
As informações de listagem do produto serão rejeitadas se não aderirem à
link:/docs/marketplace-listing[estrutura de listagem de produtos],
ao esquema do arquivo do marketplace, ou se a assinatura não verificar o conteúdo com sucesso. Entraremos em contato com você se o arquivo de listagem falhar repetidamente nessas verificações de validação.

== Página pós-download

// TODO: Should the post-download be per-publisher or per-product (i.e. embedded in the metadata).
Quando um usuário escolhe baixar seu produto pelo site do marketplace, ele será direcionado para uma página pós-download enquanto o download é iniciado a partir do seu servidor de distribuição. A página pós-download agradecerá ao usuário e identificará o publicador, incluindo um link para uma página web à sua escolha. Imaginamos que essa página web levará o usuário a informações sobre seu produto, organização, serviços e assim por diante.

O link da página pós-download não é usado pela
https://marketplace-api.adoptium.net/[API do marketplace Adoptium].
