// Some portions generated by Co-Pilot
= Adoptium(R) Marketplace Publisher-Leitfaden
:description: Adoptium Marketplace Publisher Guide
:keywords: adoptium marketplace
:orgname: Eclipse Adoptium
:page-authors: tellison, gdams, jiekang
:page-based-on: f2e6e929f64dd6ef7bd7f452d2aed14095705a31

== Einführung

Dieses Dokument bietet Orientierung für Herausgeber, die berechtigt sind, OpenJDK-Laufzeitumgebungen über den
link:/marketplace[Adoptium Marketplace] zu vermarkten und zu bewerben.

Herausgeber können Anbieter, gemeinnützige Einrichtungen, Benutzergruppen und andere sein, die die in der
link:/docs/marketplace-policy[Adoptium-Marketplace-Richtlinie^] verkörperten Werte teilen.
Herausgeber können Open-Source- oder kommerziell lizenzierte Angebote bereitstellen, die jeweils kostenlos oder gegen Gebühr für den Endnutzer nutzbar sind. Der Marketplace stellt keine spezifischen Anforderungen an Version, Plattform, Nutzung oder Lizenzbedingungen, und die über den Marketplace verfügbaren Binärprodukte können auch anderweitig verfügbar sein. Alle über den Adoptium Marketplace angebotenen Binärprodukte müssen die in der Marketplace-Richtlinie definierten Kompatibilitäts- und Qualitätskriterien erfüllen.

Der Marketplace steht Endbenutzern sowohl als
link:/marketplace[Website]
als auch als
https://marketplace-api.adoptium.net/[Programmierschnittstelle^]
(API) zur Verfügung, die vom Adoptium-Projekt gehostet und gepflegt wird.

Herausgeber werden ermutigt, ihre Teilnahme am Marketplace mit der
link:/members[Adoptium-Arbeitsgruppe]
zu besprechen, die Orientierung und Unterstützung bei den unten beschriebenen Schritten bietet. Bei Widersprüchen zwischen den unten referenzierten formalen Richtlinien und Vereinbarungen und diesem Herausgeber-Leitfaden haben die formalen Richtlinien und Vereinbarungen Vorrang.


== Vorbereitende nicht-technische Schritte

Potenzielle Herausgeber und ihre Produkte müssen die in der
link:/marketplace-policy[Adoptium Marketplace-Richtlinie] beschriebenen Kriterien erfüllen. Diese Kriterien beinhalten den Beitritt zur Adoptium-Arbeitsgruppe auf einem angemessenen Niveau, was Ihnen eine Stimme in der Richtlinie und dem Betrieb des Marketplace gibt. Nicht jedes Mitglied der Arbeitsgruppe wird ein Herausgeber sein. Endnutzer werden ebenfalls ermutigt, der Arbeitsgruppe beizutreten, um die Produkte und Anforderungen der Marketplace-Produkte mitzugestalten.

Arbeitsgruppenmitglieder, die ein Produkt im Marketplace veröffentlichen möchten, müssen der
https://www.eclipse.org/legal/documents/eclipse-adoptium-marketplace-publisher-agreement.pdf[Adoptium Marketplace Publisher Agreement] zustimmen. Diese Vereinbarung legt die Bedingungen fest, unter denen die Eclipse Foundation Ihre Produktwerbung akzeptiert. Produkte profitieren von Marketinginitiativen zur Förderung des Wertes der Binärprodukte in diesem Kontext, wenn sie in den Marketplace aufgenommen werden.


== Veröffentlichungsübersicht

Die Adoptium-Marketplace-Website und API werden durch Metadaten angetrieben, die Sie über Ihre förderfähigen Produkte bereitstellen. Die Metadaten werden von Ihnen im
https://www.json.org/[JSON^]-Format
maschinenlesbar zur Verfügung gestellt, zusammen mit einer
https://en.wikipedia.org/wiki/Digital_signature[sicheren digitalen Signatur^]
zur Sicherstellung der Authentizität, Integrität und Nichtabstreitbarkeit der von Ihnen veröffentlichten Informationen.

Als Herausgeber sind Sie dafür verantwortlich, selbst zu bestätigen, dass die Informationen für jedes in den Metadaten beschriebene Produkt korrekt sind und Ihren Verpflichtungen in der
link:/marketplace-policy[Marketplace-Richtlinie] entsprechen.

Sie kontrollieren die Metadaten Ihrer Produkte und die Häufigkeit ihrer Aktualisierung. Die Adoptium-Marketplace-Anwendung nutzt diese Informationen zur Vermarktung Ihrer Produkte und leitet Benutzer dazu an, Ihr Produkt direkt von einer von Ihnen kontrollierten Website herunterzuladen. Adoptium hostet oder vertreibt Ihre Binärprodukte nicht.

Wenn ein Download über den Adoptium Marketplace initiiert wird, werden Benutzer zu einer Post-Download-Seite weitergeleitet, auf der Sie einen Link zu weiteren Informationen über Ihr Produkt, Ihre Organisation, Ihre Dienste usw. bereitstellen können.


== Herausgeberinformationen bereitstellen

Herausgeber müssen die folgenden Informationen bereitstellen, um in den Marketplace aufgenommen zu werden.

 * Herausgebername: wie Sie im Marketplace auf der Website und in der API bekannt sein möchten.
 * Logo-Bild: eine visuelle Darstellung von Ihnen als Herausgeber für die Verwendung auf der Website.
 * Listing-Datenspeicherort: die Basis-URL, die Adoptium verwendet, um Ihre Marketplace-Listing-Metadaten abzurufen.
 * Öffentlicher Signaturschlüssel: der öffentliche Schlüssel, den wir zur Verifizierung Ihrer Signatur verwenden.
 * Post-Download-Seite: die Webseite, zu der wir Website-Benutzer beim Herunterladen Ihres Produkts weiterleiten sollen.
  
Wir erwarten nicht, dass Sie diese häufig ändern, da Adoptium diese in die Marketplace-Anwendungskonfiguration aufnimmt.

Die Herausgeberinformationen werden durch Öffnen eines
https://github.com/adoptium/adoptium/issues/new/choose[neuen Herausgeber-Anforderungs-Issues^]
im Adoptium-Repository bereitgestellt. Sie können im selben Repository ein neues Issue erstellen, wenn Sie es danach ändern müssen.


== Oracle TCK-Tests bestehen

Jedes Binärprodukt, das Sie über den Adoptium Marketplace veröffentlichen, muss alle Anforderungen des aktuellen TCK für die Java-Plattformversion, die Sie über den Adoptium Marketplace bewerben, vollständig erfüllen. Sie sind dafür verantwortlich, sicherzustellen, dass dies geschehen ist, bevor Sie das Binärprodukt veröffentlichen. Adoptium wird dies nicht in Ihrem Auftrag überprüfen.

Adoptium-Projekte
https://projects.eclipse.org/projects/adoptium.temurin-compliance[entwickeln und verwenden Tools^],
die das Ausführen und Analysieren des TCK erleichtern. Herausgeber sind willkommen, am technischen Projekt teilzunehmen und diese Tools zu nutzen, um das TCK auf ihren eigenen Produkten auszuführen.


== AQAvit-Verifizierungstests bestehen

Jedes Binärprodukt, das Sie über den Adoptium Marketplace veröffentlichen, muss alle Anforderungen der aktuellen AQAvit-Testsuite für die Version, die Sie über den Adoptium Marketplace bewerben, vollständig erfüllen. Sie sind dafür verantwortlich, sicherzustellen, dass dies geschehen ist, bevor Sie das Binärprodukt veröffentlichen. Adoptium wird dies nicht in Ihrem Auftrag überprüfen.

Der
link:/aqavit[AQAvit-Verifizierungsprozess]
muss zu dem Zeitpunkt erfüllt sein, zu dem das Binärprodukt erstmals über den Marketplace angeboten wird. Herausgeber sind nicht verpflichtet, das Binärprodukt für spätere Versionen der AQAvit-Verifizierungssuite zu verifizieren. Sobald ein Binärprodukt die Kriterien erfüllt, kann es weiterhin über den Marketplace angeboten werden.

AQAvit ist eine Open-Source-Testsuite, die im Adoptium-Projekt verwaltet wird. Herausgeber sind willkommen, am AQAvit-Projekt teilzunehmen, um Hilfe beim Ausführen von AQAvit auf ihren eigenen Produkten zu erhalten.


== Produktlisting-Informationen

Ihr Produktlisting für den Marketplace kann überall unter Ihrer direkten Kontrolle gehostet werden, das
https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol[HTTP^]-Anfragen
und -Antworten unterstützt, einschließlich Ihrer eigenen Website-Eigenschaft, GitHub usw. Während Adoptium überprüft, dass die Informationen sicher von Ihnen empfangen werden, indem eine digitale Signatur auf Basis verifizierter Informationen verwendet wird, sind Sie letztendlich für die dem Marketplace über die Listing-Daten-Speicherort-URL bereitgestellten Informationen verantwortlich.

Die Produktlisting-Informationen umfassen strukturierte JSON-Formatdateien mit Flexibilität für mehrere Builds und Versionen. Die Informationen sind am in den <<Providing-Publisher-Information,Herausgeberinformationen>> angegebenen Listing-Datenspeicherort in dem in der
link:/docs/marketplace-listing[Adoptium Marketplace Publisher Produktlisting-Repository]-Dokumentation beschriebenen Format verankert.

// TODO: How does a publisher check the logs of successful/failed pulls and schema validation?
Die Produktlisting-Informationen werden abgelehnt, wenn sie nicht der
link:/docs/marketplace-listing[Produktlisting-Struktur],
dem Marketplace-Datei-Schema entsprechen oder die Signatur den Inhalt nicht erfolgreich verifiziert. Wir werden Sie kontaktieren, wenn die Listing-Datei diese Validierungsprüfungen wiederholt nicht besteht.

== Post-Download-Seite

// TODO: Should the post-download be per-publisher or per-product (i.e. embedded in the metadata).
Wenn ein Benutzer wählt, Ihr Produkt über die Marketplace-Website herunterzuladen, wird er zu einer Post-Download-Seite weitergeleitet, während der Download von Ihrem Verteilungsserver initiiert wird. Die Post-Download-Seite wird dem Benutzer danken und den Herausgeber identifizieren, einschließlich eines Links zu einer Webseite Ihrer Wahl. Wir stellen uns vor, dass diese Webseite den Benutzer zu Informationen über Ihr Produkt, Ihre Organisation, Ihre Dienste usw. führt.

Der Post-Download-Seiten-Link wird nicht von der
https://marketplace-api.adoptium.net/[Adoptium Marketplace API] verwendet.
