= Adoptium(R) Marketplace Publisher Guide
:description: Adoptium Marketplace Publisher Guide
:keywords: adoptium marketplace
:orgname: Eclipse Adoptium
:lang: en
:page-authors: tellison, gdams, jiekang

== Introduction

This document provides guidance for publishers that are eligible to market and promote OpenJDK runtimes via the
link:/marketplace[Adoptium Marketplace].

Publishers may be vendors, not-for-profit entities, user groups, and others who share the values embodied in the 
link:/marketplace-policy[Adoptium marketplace policy^].
Publishers may offer open source or commercially licensed offerings, each usable at no cost or at a fee to the end user. The marketplace does not require specific version, platform, usage or license terms, and the binaries available through the marketplace may also be available elsewhere. All binaires offered through the Adoptium marketplace must meet the compatibility and quality criteria defined in the marketplace policy.

The marketplace is available to end users as both a
link:/marketplace[website]
and an
https://marketplace-api.adoptium.net/[application programming interface^]
(API) hosted and maintained by the Adoptium project.

Publishers are encouraged to discuss their participation in the marketplace with the
link:/members[Adoptium Working Group]
who will provide guidance and assistance with the steps described below. In case of any contradictions between the formal policies and agreements referenced below and this publisher guide, the formal policies and agreements will take precedence.


== Preparatory Non-technical Steps

Potential publishers and their products must meet the criteria described in the
link:/marketplace-policy[Adoptium Marketplace Policy]. These criteria include becoming a member of the Adoptium working group at an appropriate level, granting you a voice in the policy and operation of the marketplace. Not every member of the working group will be a publisher. End users are also encouraged to join the working group to help guide the products and requirements of the marketplace products.

Working group members who wish to publish a product in the marketplace must agree to the
https://www.eclipse.org/legal/documents/eclipse-adoptium-marketplace-publisher-agreement.pdf[Adoptium Marketplace Publisher Agreement]. This agreement sets out the terms and conditions under which the Eclipse Foundation accepts your product promotion. Products will benefit from marketing initiatives intended to promote the value of the binaries in this context when accepted into the marketplace.


== Publishing Overview

The Adoptium marketplace website and API are driven by metadata that you provide about your eligible products. The metadata is made available by you in
https://www.json.org/[JSON^]
machine-readable format, together with a
https://en.wikipedia.org/wiki/Digital_signature[secure digital signature^]
to ensure the authenticity, integrity, and non-repudiation of the information you publish.

As a publisher you are responsible for self-certifying that the information for each product described in the metadata is accurate and adheres to your obligations in the
link:/marketplace-policy[Marketplace Policy].

You control your products' metadata and the frequency at which it is updated. The Adoptium marketplace application will draw upon that information to market your products, and direct users to download your product directly from a site under your control. Adoptium does not host or distribute your binaries.

When a download is initiated via the Adoptium marketplace users will be directed to a post-download page where you can provide a link to additional information about your product, organization, services, and so on.


== Providing Publisher Information

Publishers must provide the following information in order to be included in the marketplace.

 * Publisher name : how you would like to be known in the marketplace website and API.
 * Logo image : a visual representation of you as a publisher for use on the website.
 * Listing data location : the base URL that Adoptium will use to retrieve your marketplace listing metadata.
 * Signature public key : the public key we will use to verify your signature.
 * Post-download page : the webpage we should direct website users towards when downloading your product.
 
We don't expect you to change these frequently, as Adoptium will be adding these into the marketplace application configuration.

The publisher information is provided by opening a
https://github.com/adoptium/adoptium/issues/new/choose[new publisher request issue^]
in the Adoptium repository. You can raise a new issue in the same repository if you do subsequently need to change it.


== Passing the Oracle TCK tests

Every binary you publish via the Adoptium marketplace must fully satisfy all requirements of the then-current TCK for the Java Platform version you are promoting via the Adoptium marketplace. You are responsible for ensuring this has happened before you publish the binary. Adoptium will not check this on your behalf.

Adoptium projects
https://projects.eclipse.org/projects/adoptium.temurin-compliance[develop and use tools^]
that make running and analysing the TCK easier. Publishers are welcome to participate in the technical project and use these tools to help with the task of running the TCK on their own products.


== Passing the AQAvit verification tests

Every binary you publish via the Adoptium marketplace must fully satisfy all requirements of the then-current AQAvit test suite for the version you are promoting via the Adoptium marketplace. You are responsible for ensuring this has happened before you publish the binary. Adoptium will not check this on your behalf.

The
link:/aqavit[AQAvit verification process]
must be satisfied at the point the binary is initially offered through the marketplace. Publishers are not required to verify the binary to later releases of the AQAvit verification suite. Once a binary meets the criteria it may continue to be offered through the marketplace.

AQAvit is an open source test suite managed at the Adoptium project. Publishers are welcome to participate in the AQAvit project to get help with the task of running AQAvit on their own products.


== Product Listing Information

Your products listing for the marketplace can be hosted anywhere under your direct control that supports
https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol[HTTP^]
requests and responses, including your own website property, GitHub, and so on. While Adoptium will check that the information is received from you securely by using a digital signature based upon verified information, you are ultimately responsible for the information provided to the marketplace via the listing data location URL.

The product listing information comprises structured JSON format files, with flexibility to allow for multiple builds and versions. The information is rooted at the listing data location provided in the <<Providing-Publisher-Information,publisher information>> in the format described in the
link:/docs/marketplace-listing[Adoptium Marketplace Publisher Product Listing Repository]
documentation.

// TODO: How does a publisher check the logs of successful/failed pulls and schema validation?
The product listing information will be rejected if it does not adhere to the 
link:/docs/marketplace-listing[product listing structure],
marketplace file schema, or the signature does not verify the content successfully. We will contact you if the listing file is repeatedly failing these validation checks.

== Post-download page

// TODO: Should the post-download be per-publisher or per-product (i.e. embedded in the metadata).
When a user chooses to download your product via the marketplace website they will be directed to a post-download page as the download is initiated from your distribution server. The post-download page will thank the user and identify the publisher, including a link to a webpage of your choice. We envisage this webpage will lead the user to information about your product, organization, services, and so on.

The post-download page link is not used by the
https://marketplace-api.adoptium.net/[Adoptium marketplace API].

