// Some portions generated by Co-Pilot
import { Metadata } from "next";
import React from "react";
import startCase from "lodash/startCase";
import { IoCloudDownloadOutline } from "react-icons/io5";
import { FaGithub, FaDocker } from "react-icons/fa";
import PageHeader from "@/components/Common/PageHeader";
import { fetchDownloadStats } from "@/utils/fetchDownloadStats";
import { fetchAvailableReleases } from "@/utils/fetchAvailableReleases";
import PieChart from "@/components/Dashboard/PieChart";
import ColumnDrilldown from "@/components/Dashboard/ColumnDrilldown";
import StackedBarChart from "@/components/Dashboard/StackedBarChart";
import StatsNav from "@/components/Dashboard/Nav";

export const metadata: Metadata = {
  title: "Download Dashboard",
  description: "View download statistics for Temurin releases",
};

function formatCompact(n: number): string {
  if (n >= 1_000_000_000) return (n / 1_000_000_000).toFixed(1) + "B";
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + "M";
  if (n >= 1_000) return (n / 1_000).toFixed(1) + "K";
  return n.toLocaleString();
}

export default async function DownloadStatsPage() {
  const availableReleases = await fetchAvailableReleases();
  (availableReleases.available_releases ?? []).sort((a, b) => a - b);

  const data = await fetchDownloadStats();
  const total = data.total_downloads.total;
  const totalDocker = data.total_downloads.docker_pulls;
  const totalGithub = data.total_downloads.github_downloads;

  // Source breakdown pie chart
  let totalPieChartData: Array<{ name: string; y: number }> = [];
  if (data && data.total_downloads) {
    totalPieChartData = Object.keys(data.total_downloads)
      .filter((key) => key !== "total")
      .map((key) => ({
        name: startCase(key),
        y: data.total_downloads[key as keyof typeof data.total_downloads],
      }));
  }

  // GitHub downloads per version (Docker Hub API doesn't expose per-version
  // pull counts, so we only chart GitHub data at version granularity)
  const githubVersionKeys = Object.keys(data.github_downloads ?? {}).sort(
    (a, b) => parseInt(a, 10) - parseInt(b, 10),
  );
  const versionLabels = githubVersionKeys.map((k) => `JDK ${k}`);
  const githubPerVersion = githubVersionKeys.map(
    (k) => (data.github_downloads ?? {})[k] ?? 0,
  );

  // Top 5 versions by GitHub downloads
  const topVersions = githubVersionKeys
    .map((k, i) => ({ name: `JDK ${k}`, total: githubPerVersion[i] }))
    .sort((a, b) => b.total - a.total)
    .slice(0, 5);

  // GitHub downloads pie breakdown by version
  const githubPieData = githubVersionKeys
    .map((k, i) => ({ name: `JDK ${k}`, y: githubPerVersion[i] }))
    .filter((d) => d.y > 0)
    .sort((a, b) => b.y - a.y);

  return (
    <div>
      <PageHeader
        title="Adoptium Download Stats"
        subtitle="Live download and Docker pull statistics for all Adoptium releases."
        className="max-w-3xl text-center mb-8"
      />
      <StatsNav />
      <div className="flex flex-col items-center min-h-screen py-8 px-2">
        {/* Summary stat cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 w-full max-w-5xl mb-8">
          <div className="flex flex-col items-center bg-white/5 rounded-2xl shadow-lg p-6">
            <IoCloudDownloadOutline
              style={{ fontSize: 32, color: "#6ba4e7" }}
            />
            <h2 className="text-3xl font-bold text-white mt-2 mb-1">
              {formatCompact(total)}
            </h2>
            <p className="text-sm text-gray-300 text-center">Total Downloads</p>
          </div>
          <div className="flex flex-col items-center bg-white/5 rounded-2xl shadow-lg p-6">
            <FaGithub style={{ fontSize: 32, color: "#feae62" }} />
            <h2 className="text-3xl font-bold text-white mt-2 mb-1">
              {formatCompact(totalGithub)}
            </h2>
            <p className="text-sm text-gray-300 text-center">
              GitHub Downloads
            </p>
          </div>
          <div className="flex flex-col items-center bg-white/5 rounded-2xl shadow-lg p-6">
            <FaDocker style={{ fontSize: 32, color: "#2caffe" }} />
            <h2 className="text-3xl font-bold text-white mt-2 mb-1">
              {formatCompact(totalDocker)}
            </h2>
            <p className="text-sm text-gray-300 text-center">
              Docker Official Image Pulls
            </p>
          </div>
        </div>

        {/* Top 5 versions by GitHub downloads */}
        <div className="w-full max-w-5xl mb-8">
          <h3 className="text-lg font-semibold text-white mb-3">
            Most Popular Versions (GitHub Downloads)
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
            {topVersions.map((v, i) => (
              <div
                key={v.name}
                className="flex flex-col items-center bg-white/5 rounded-xl p-4 border border-white/10"
              >
                <span className="text-xs font-bold text-gray-400 mb-1">
                  #{i + 1}
                </span>
                <span className="text-lg font-bold text-white">{v.name}</span>
                <span className="text-sm text-pink">
                  {formatCompact(v.total)}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Source breakdown pie */}
        <div className="flex flex-col md:flex-row gap-8 w-full max-w-5xl mb-8">
          <div className="bg-white/5 rounded-2xl shadow-lg p-4 flex-1 min-w-[320px]">
            <PieChart
              data={totalPieChartData}
              name="Downloads by Source"
              showInLegend
              dataLabels
              colors={["#feae62", "#2caffe"]}
            />
          </div>
          <div className="bg-white/5 rounded-2xl shadow-lg p-4 flex-1 min-w-[320px]">
            <PieChart
              data={githubPieData}
              name="GitHub Downloads by Version"
              showInLegend
              dataLabels
              colors={[
                "#feae62",
                "#6c6de3",
                "#2caffe",
                "#a259f7",
                "#f67280",
                "#43e97b",
              ]}
            />
          </div>
        </div>

        {/* GitHub downloads per version bar chart */}
        <div className="w-full max-w-5xl bg-white/5 rounded-2xl shadow-lg p-6 mb-8">
          <StackedBarChart
            categories={versionLabels}
            series={[
              {
                name: "GitHub Downloads",
                data: githubPerVersion,
                color: "#feae62",
              },
            ]}
            name="GitHub Downloads per Version"
          />
        </div>

        {/* Detailed drilldown */}
        <div className="w-full max-w-5xl bg-white/5 rounded-2xl shadow-lg p-6 mt-4">
          <h3 className="text-xl font-semibold text-white mb-4">
            GitHub Release Downloads (Drilldown)
          </h3>
          <ColumnDrilldown
            availableReleases={{
              available_releases: (
                availableReleases.available_releases ?? []
              ).map(String),
            }}
            name="GitHub Release Downloads"
          />
        </div>
      </div>
    </div>
  );
}
