// Some portions generated by Co-Pilot
import React from "react";
import { render } from "@testing-library/react";
import { describe, it, expect, vi } from "vitest";

vi.mock("next-intl/server", () => ({
  getTranslations: vi.fn().mockResolvedValue((key: string) => key),
}));

import AuthorList from "../index";

describe("AuthorList", () => {
  it("renders an entry for each author", async () => {
    const ui = await AuthorList({ authors: ["octocat", "hubot"] });
    const { container } = render(ui);

    const authorLinks = container.querySelectorAll("a");
    expect(authorLinks.length).toBe(2);
    // Translation mock echoes the key back.
    expect(container.textContent).toContain("documentation-authors");
  });

  it("renders nothing when there are no authors", async () => {
    const ui = await AuthorList({ authors: [] });
    const { container } = render(ui);
    expect(container.firstChild).toBeNull();
  });
});
