// Some portions generated by Co-Pilot
import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import Cta from "../index";

describe("Cta", () => {
  const defaultProps = {
    title: "Get Started",
    description: "Download Temurin today and start building.",
    linkText: "Download Now",
    link: "/temurin/releases",
  };

  it("renders the description text", () => {
    render(<Cta {...defaultProps} />);
    const descriptions = screen.getAllByText("Download Temurin today and start building.");
    expect(descriptions.length).toBeGreaterThan(0);
  });

  it("renders the link button with correct text", () => {
    render(<Cta {...defaultProps} />);
    const buttons = screen.getAllByRole("button", { name: "Download Now" });
    expect(buttons.length).toBeGreaterThan(0);
  });

  it("renders a link with the correct href", () => {
    render(<Cta {...defaultProps} />);
    const links = screen.getAllByRole("link");
    const ctaLink = links.find(
      (link) => link.getAttribute("href") === "/temurin/releases"
    );
    expect(ctaLink).toBeDefined();
  });

  it("renders within a section element", () => {
    const { container } = render(<Cta {...defaultProps} />);
    expect(container.querySelector("section")).toBeInTheDocument();
  });
});
