// Some portions generated by Co-Pilot
"use client";

import Image from "next/image";
import { useMemo } from "react";
import { useTranslations } from "next-intl";
import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay } from "swiper/modules";
import "swiper/css";
import adoptersData from "@/data/adopters.json";
import { shuffle } from "@/utils/shuffle";

interface Adopter {
  name: string;
  logo: string;
  url: string;
  tier: string;
  featured?: boolean;
  logo_white?: string;
  logoPadding?: string;
}

const LogoCarousel = () => {
  const featuredAdopters = useMemo(
    () =>
      shuffle(
        (adoptersData as Adopter[]).filter((adopter) => adopter.featured),
      ),
    [],
  );
  const t = useTranslations("LogoCarousel");

  return (
    <div className="max-w-[1160px] w-full mx-auto py-8 lg:py-16 xl:px-0 px-8">
      <h2 className="text-center text-xl font-normal leading-7 text-grey">
        {t("title")}
      </h2>
      <Swiper
        modules={[Autoplay]}
        className="mt-6"
        loop={true}
        speed={2000}
        allowTouchMove={false}
        autoplay={{
          delay: 0,
          disableOnInteraction: false,
        }}
        slidesPerView={1.5}
        breakpoints={{
          376: { slidesPerView: 2 },
          481: { slidesPerView: 3 },
          769: { slidesPerView: 4 },
          1025: { slidesPerView: 6 },
        }}
      >
        {featuredAdopters.map((adopter, index) => (
          <SwiperSlide key={index}>
            <div className="flex items-center justify-center h-[100px] px-4">
              <Image
                width={200}
                height={100}
                src={`/images/${adopter.logo_white}`}
                alt={adopter.name}
                className="w-auto h-auto object-contain mx-auto max-h-[100px]"
                style={{ padding: adopter.logoPadding || 0 }}
              />
            </div>
          </SwiperSlide>
        ))}
      </Swiper>
    </div>
  );
};

export default LogoCarousel;
