// Some portions generated by Co-Pilot
import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import Tags from "../index";

describe("Tags", () => {
  it("renders nothing when tags array is empty", () => {
    const { container } = render(<Tags tags={[]} />);
    expect(container.firstChild).toBeNull();
  });

  it("renders nothing when tags is undefined", () => {
    const { container } = render(<Tags />);
    expect(container.firstChild).toBeNull();
  });

  it("renders tag links for each tag", () => {
    render(<Tags tags={["java", "temurin", "release"]} />);
    expect(screen.getByText("#java")).toBeInTheDocument();
    expect(screen.getByText("#temurin")).toBeInTheDocument();
    expect(screen.getByText("#release")).toBeInTheDocument();
  });

  it("renders links with encoded tag names", () => {
    render(<Tags tags={["java"]} />);
    const links = screen.getAllByRole("link", { name: "#java" });
    expect(links[0]).toHaveAttribute("href", "/news?tag=java");
  });

  it("handles special characters in tag names", () => {
    render(<Tags tags={["c++"]} />);
    const links = screen.getAllByRole("link", { name: "#c++" });
    expect(links[0]).toHaveAttribute("href", "/news?tag=c%2B%2B");
  });

  it("renders the correct number of links", () => {
    render(<Tags tags={["a", "b", "c", "d"]} />);
    const links = screen.getAllByRole("link");
    // 4 tags (may be doubled in strict mode)
    expect(links.length).toBeGreaterThanOrEqual(4);
  });
});
