// Some portions generated by Co-Pilot
import React from "react";
import { render } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { axe } from "vitest-axe";
import TemurinPage from "../page";

vi.mock("@/utils/fetchAvailableReleases", () => ({
  fetchAvailableReleases: vi.fn().mockResolvedValue({
    most_recent_lts: 21,
  }),
}));

// Mock the LatestNews component with a synchronous version
vi.mock("@/components/News/LatestNews", () => {
  return {
    default: () => (
      <div data-testid="mocked-latest-news">Latest News Content</div>
    ),
  };
});

describe("TemurinIndex page", () => {
  it("renders correctly", async () => {
    const jsx = await TemurinPage();
    const { container } = render(jsx);
    expect(container.firstChild).toMatchSnapshot();
  });

  it("has no accessibility violations", async () => {
    const jsx = await TemurinPage();
    const { container } = render(jsx);
    const results = await axe(container);
    expect(results).toHaveNoViolations();
  });
});
