// Some portions generated by Co-Pilot
import React from "react"
import { render, screen } from "@testing-library/react"
import { describe, expect, it, vi } from "vitest"
import { axe } from "vitest-axe"
import Members from "../page"

vi.mock("@/components/Logos", () => {
  return {
    __esModule: true,
    default: () => <div />,
    LogoType: {},
  }
})

describe("Members page", () => {
  it("renders correctly", () => {
    const { container } = render(<Members />)
    expect(container.firstChild).toMatchSnapshot()
  })

  it("does not mention removed members in the page copy", () => {
    render(<Members />)

    expect(
      screen.getAllByText(
        "Collaborate with leading Java vendors like Microsoft, Red Hat, IBM, and Alibaba.",
      ),
    ).not.toHaveLength(0)
    expect(screen.queryByText(/Google/)).not.toBeInTheDocument()
    expect(screen.queryByText(/Rivos/)).not.toBeInTheDocument()
  })

  it("has no accessibility violations", async () => {
    const { container } = render(<Members />)
    const results = await axe(container)
    expect(results).toHaveNoViolations()
  })
})
