// Some portions generated by Co-Pilot
import React from "react";
import {
  render,
  screen,
  fireEvent,
  act,
  cleanup,
} from "@testing-library/react";
import { describe, it, expect, vi, afterEach, beforeEach } from "vitest";
import Banner from "../index";

vi.mock("@/utils/shuffle", () => ({
  shuffle: <T,>(arr: T[]): T[] => arr,
}));

vi.mock("../banners", () => ({
  currentBanners: [
    {
      title: "Test Banner Title",
      description: "Test banner description",
      cta: "Click here",
      ctaLink: "https://example.com/test",
      startDate: "2020-01-01T00:00:00Z",
      endDate: "2099-12-31T23:59:59Z",
    },
  ],
}));

vi.mock("@/components/Common/Icon", () => ({
  PinkIcon: () => <div data-testid="pink-icon" />,
}));

describe("Banner", () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
    cleanup();
  });

  it("renders banner with title and description", async () => {
    render(<Banner />);
    await act(async () => {
      vi.runAllTimers();
    });
    expect(screen.getByText("Test Banner Title")).toBeTruthy();
    expect(screen.getByText("Test banner description")).toBeTruthy();
  });

  it("renders CTA link", async () => {
    render(<Banner />);
    await act(async () => {
      vi.runAllTimers();
    });
    const link = screen.getByRole("link", { name: /Click here/i });
    expect(link.getAttribute("href")).toBe("https://example.com/test");
  });

  it("renders dismiss button after mount", async () => {
    render(<Banner />);
    await act(async () => {
      vi.runAllTimers();
    });
    const dismissButton = screen.getByLabelText("Dismiss banner");
    expect(dismissButton).toBeTruthy();
  });

  it("dismisses banner when close button is clicked", async () => {
    render(<Banner />);
    await act(async () => {
      vi.runAllTimers();
    });
    const dismissButton = screen.getByLabelText("Dismiss banner");
    fireEvent.click(dismissButton);
    // Banner starts fading out (opacity-0 class added)
    const bannerDiv = screen
      .getByText("Test Banner Title")
      .closest("[class*=transition-opacity]");
    expect(bannerDiv?.className).toContain("opacity-0");
    // After timeout, banner is fully dismissed
    await act(async () => {
      vi.advanceTimersByTime(700);
    });
    expect(screen.queryByText("Test Banner Title")).toBeNull();
  });
});

describe("Banner with no valid banners", () => {
  afterEach(() => {
    cleanup();
    vi.resetModules();
  });

  it("renders nothing when no banners are active", async () => {
    vi.resetModules();
    vi.doMock("../banners", () => ({
      currentBanners: [
        {
          title: "Expired Banner",
          description: "This banner has expired",
          cta: "Click",
          ctaLink: "/expired",
          startDate: "2020-01-01T00:00:00Z",
          endDate: "2020-12-31T23:59:59Z",
        },
      ],
    }));
    const { default: BannerFresh } = await import("../index");
    const { container } = render(<BannerFresh />);
    expect(container).toBeTruthy();
  });
});

describe("Banner with release banner priority", () => {
  afterEach(() => {
    cleanup();
    vi.resetModules();
  });

  it("prioritizes release banner when available", async () => {
    vi.resetModules();
    vi.doMock("../banners", () => ({
      currentBanners: [
        {
          title: "Regular Banner",
          description: "Regular",
          cta: "Go",
          ctaLink: "/regular",
          startDate: "2020-01-01T00:00:00Z",
          endDate: "2099-12-31T23:59:59Z",
        },
        {
          title: "Release Banner",
          description: "Release",
          cta: "View",
          ctaLink: "/release",
          startDate: "2020-01-01T00:00:00Z",
          endDate: "2099-12-31T23:59:59Z",
          releaseBanner: true,
        },
      ],
    }));
    const { default: BannerFresh } = await import("../index");
    const { container } = render(<BannerFresh />);
    expect(container).toBeTruthy();
  });
});
