// Some portions generated by Co-Pilot
import React from "react";
import { render, screen, cleanup } from "@testing-library/react";
import { describe, it, expect, afterEach, vi } from "vitest";

vi.mock("next-intl/server", () => ({
  getTranslations: vi.fn().mockResolvedValue((key: string) => key),
}));

import DocumentationHeader from "../index";

// Mock DocumentationSearch and DocThemeToggle
vi.mock("@/components/Content/Documentation/Search", () => ({
  __esModule: true,
  default: () => <div data-testid="doc-search" />,
}));
vi.mock("@/components/DocThemeToggle", () => ({
  __esModule: true,
  default: () => <button data-testid="doc-theme-toggle" />,
}));

describe("DocumentationHeader", () => {
  afterEach(() => {
    cleanup();
  });

  it("renders the Documentation title and subtitle", async () => {
    render(await DocumentationHeader());
    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent(
      "title",
    );
    expect(screen.getByText("subtitle")).toBeInTheDocument();
  });

  it("renders the DocumentationSearch component", async () => {
    render(await DocumentationHeader());
    expect(screen.getByTestId("doc-search")).toBeInTheDocument();
  });

  it("renders the DocThemeToggle component", async () => {
    render(await DocumentationHeader());
    expect(screen.getByTestId("doc-theme-toggle")).toBeInTheDocument();
  });

  it("renders the breadcrumb navigation", async () => {
    render(await DocumentationHeader());
    expect(screen.getByText("home")).toBeInTheDocument();
    expect(screen.getByLabelText("Breadcrumb")).toBeInTheDocument();
  });
});
