// Some portions generated by Co-Pilot
import React from "react";
import { render, screen, cleanup } from "@testing-library/react";
import { describe, it, expect, afterEach, vi } from "vitest";

vi.mock("next-intl", () => ({
  useTranslations: () => {
    const t = (key: string) => key;
    t.rich = (key: string) => key;
    return t;
  },
  useLocale: () => "en",
}));

import DocumentationHeader from "../index";

// Mock DocumentationSearch and DocThemeToggle
vi.mock("@/components/Content/Documentation/Search", () => ({
  __esModule: true,
  default: () => <div data-testid="doc-search" />,
}));
vi.mock("@/components/DocThemeToggle", () => ({
  __esModule: true,
  default: () => <button data-testid="doc-theme-toggle" />,
}));

describe("DocumentationHeader", () => {
  afterEach(() => {
    cleanup();
  });

  it("renders the Documentation title and subtitle", () => {
    render(<DocumentationHeader />);
    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent(
      "title",
    );
    expect(screen.getByText("subtitle")).toBeInTheDocument();
  });

  it("renders the DocumentationSearch component", () => {
    render(<DocumentationHeader />);
    expect(screen.getByTestId("doc-search")).toBeInTheDocument();
  });

  it("renders the DocThemeToggle component", () => {
    render(<DocumentationHeader />);
    expect(screen.getByTestId("doc-theme-toggle")).toBeInTheDocument();
  });

  it("renders the breadcrumb navigation", () => {
    render(<DocumentationHeader />);
    expect(screen.getByText("home")).toBeInTheDocument();
    expect(screen.getByLabelText("Breadcrumb")).toBeInTheDocument();
  });
});
