// Some portions generated by Co-Pilot
import { fetchDownloadStats } from "@/utils/fetchDownloadStats";
import { fetchAvailableReleases } from "@/utils/fetchAvailableReleases";
import HeroSection from "@/components/HeroSection";
import PowerOfTemurin from "@/components/PowerOfTemurin";
import DownloadCounter from "@/components/Download/Counter";
import BentoGrid from "@/components/TemurinFeatures/BentoGrid";
import WGProjects from "@/components/WorkingGroup/Projects";
import Testimonials from "@/components/Testimonials";
import LatestNews from "@/components/News/LatestNews";
import ContributorsHome from "@/components/Contributors/home";
import BannerMiddle from "@/components/Banner/Middle";
import Link from "next/link";

export default async function HomePage() {
  let total_downloads = 1000000000;
  try {
    total_downloads = (await fetchDownloadStats()).total_downloads.total;
  } catch {}
  const availableReleases = await fetchAvailableReleases();
  const latestLTS = availableReleases.most_recent_lts ?? 25;
  return (
    <div className="bg-[#14003c]">
      <HeroSection latestLTS={latestLTS} />
      <BannerMiddle />
      <PowerOfTemurin />
      <DownloadCounter total={total_downloads} />
      <BentoGrid />
      <WGProjects />
      <Testimonials type="member" />
      <div className="flex justify-center my-10">
        <Link
          href="/join-us"
          className="flex items-center justify-center w-[280px] h-[56px] rounded-2xl text-[#FF1464] text-lg font-medium gradient-border border-2 border-pink-500/0 transition-all duration-300 hover:border-pink-500/100 hover:text-pink hover:scale-105"
        >
          Join Us
        </Link>
      </div>
      <LatestNews />
      <ContributorsHome />
    </div>
  );
}
