// Some portions generated by Co-Pilot
= Support Temurin(TM)
:page-authors: gdams
:page-based-on: 8d3e6bb8724190dec8e19e3c79ffd3ee5c45855d
:toc:
:partialDir: _partials
// En-têtes des colonnes du tableau
:col-java-version: Version Java
:col-first-availability: Première disponibilité
:col-latest-release: Dernière version
:col-next-release-due: Prochaine version prévue
:col-end-of-availability: Fin de disponibilité
// Abréviations des mois
:month-jan: Jan
:month-feb: Fév
:month-mar: Mar
:month-apr: Avr
:month-may: Mai
:month-jun: Juin
:month-jul: Juil
:month-aug: Août
:month-sep: Sep
:month-oct: Oct
:month-nov: Nov
:month-dec: Déc
// Autres chaînes traduisibles
:at-least: Au moins

== Support communautaire

Nous sommes prêts à garantir la qualité de nos binaires de release, c'est pourquoi chaque build identifié comme un release bénéficie du support de la communauté Adoptium(R). Notre support signifie que vous pouvez https://github.com/adoptium/adoptium-support/issues/new/choose[signaler un problème] pour décrire un bug que vous avez trouvé dans le build, et nous travaillerons avec vous et l'équipe de développement appropriée pour le résoudre. Toutes les corrections que nous identifions seront livrées dans le cadre du prochain release d'Adoptium.

En tant que communauté de développeurs open source, notre engagement est de trier tous les problèmes signalés et de les défendre dans le projet de code source approprié. Bien entendu, si le problème provient de la façon dont nous compilons et testons le code, nous pouvons le corriger directement. Pour un support dédié avec des accords de niveau de service, vous devriez contacter des entreprises commerciales proposant un support sur les binaires Temurin. Lisez https://medium.com/@javachampions/java-is-still-free-3-0-0-ocrt-2021-bca75c88d23b[Java Is Still Free (3.0.0)] pour des informations générales sur les options de support Java.

== Support commercial

Nous comprenons que certains utilisateurs préfèrent un support commercial payant pour Eclipse Temurin. Eclipse ne fournit pas de tels services, mais veuillez consulter notre page link:/temurin/commercial-support[Support commercial] où une liste d'entreprises offrant un support contractuel est maintenue.

== Feuille de route des releases

La fréquence des releases de Temurin est guidée par le calendrier de nos dépendances.

OpenJDK fournit une nouvelle version de fonctionnalités tous les six mois, et une mise à jour de maintenance/sécurité basée sur chaque version active tous les trois mois. Les dates de publication du projet OpenJDK sont généralement le https://www.oracle.com/security-alerts/[troisième mardi] de janvier, avril, juillet et octobre. Nous suivons ce calendrier pour publier les releases binaires d'Adoptium afin de vous garantir les builds les plus récents et les plus sécurisés.

De plus, depuis 2021, tous les deux ans, une version de fonctionnalités est désignée comme release Long Term Support (LTS). Nous supporterons les releases LTS pendant au moins quatre ans. Cette garantie vous permettra de rester sur un flux de code bien défini et vous donnera le temps de migrer vers le prochain release LTS nouveau, stable, lorsqu'il sera disponible.

Sur la base de cette feuille de route, voici le calendrier montrant les dates de publication actuelles des différentes versions d'OpenJDK utilisées pour compiler Eclipse Temurin. Notez que les dates ci-dessous proviennent de la https://www.java.com/releases[page du projet OpenJDK upstream] et ne doivent pas être considérées comme la date à laquelle le projet Adoptium aura des binaires disponibles – il y aura un court délai par rapport à ces dates pendant que nous terminons nos cycles de compilation et de test approfondis, qui peuvent prendre jusqu'à trois semaines. Notre https://calendar.google.com/calendar/embed?src=c_56d7263c0ceda87a1678f6144426f23fb53721480b5ff71b073afb51091e5492%40group.calendar.google.com[Calendrier Google avec nos cycles de release] montre les durées de cycle prévues pour chacun de nos releases. Nous donnons toujours la priorité aux plateformes les plus populaires, qui apparaissent généralement dans les quelques jours suivant ces dates.

include::{partialDir}/support-table.adoc[]

^[1]^ En tant que philosophie générale, Adoptium continuera à compiler des binaires pour les releases LTS tant que le code source upstream correspondant est activement maintenu.

^[2]^ Fin de vie de service/support – ce flux de code n'est plus maintenu. Aucun autre build d'Eclipse Temurin n'est prévu.
