// Some portions generated by Co-Pilot
= Temurin(TM) サポート
:page-authors: gdams, karianna, sxa, tellison, SueChaplain, mvitz, ParkerM, M-Davies, Malax, lasombra, jeffalder, hendrikebbers, douph1, andrew-m-leonard, mr-david-owens, DanHeidinga, sophia-guo, zdtsw, adamfarley, garydgregory, mtughan, xavierfacq
:page-based-on: 9b172485685c1f2ba719dd4c31624e4dc6d63a8b
:toc:
:partialDir: _partials
// Table column headers
:col-java-version: Java バージョン
:col-first-availability: 初回提供日
:col-latest-release: 最新リリース
:col-next-release-due: 次回リリース予定日
:col-end-of-availability: 提供終了日
// Month abbreviations
:month-jan: 1月
:month-feb: 2月
:month-mar: 3月
:month-apr: 4月
:month-may: 5月
:month-jun: 6月
:month-jul: 7月
:month-aug: 8月
:month-sep: 9月
:month-oct: 10月
:month-nov: 11月
:month-dec: 12月
// Other translatable strings
:at-least: 少なくとも

== コミュニティサポート

リリース品質のバイナリを提供することにコミットしており、リリースとして識別された各ビルドは Adoptium(R) コミュニティを通じてサポートを受けられます。サポートは、ビルドで見つけたバグを説明するための https://github.com/adoptium/adoptium-support/issues/new/choose[問題の報告]を行うことができ、適切な開発チームと連携して解決に取り組みます。特定された修正は次の Adoptium リリースの一部として提供されます。

オープンソース開発者のコミュニティとして、報告されたすべての問題をトリアージし、適切なソースコードプロジェクトでそれらを推進することにコミットしています。もちろん、問題がコードのビルドおよびテスト方法から生じている場合は直接修正できます。サービスレベルアグリーメントを伴う専用サポートについては、Temurin バイナリのサポートを提供している商業企業にお問い合わせください。Java サポートオプションに関する背景情報については、https://medium.com/@javachampions/java-is-still-free-3-0-0-ocrt-2021-bca75c88d23b[Java Is Still Free（3.0.0）]をお読みください。

== 商業サポート

Eclipse Temurin の商業的な有償サポートを好むユーザーもいることは承知しています。Eclipse はそのようなサービスを提供していませんが、契約サポートを提供する企業のリストを管理している link:/temurin/commercial-support[商業サポート]ページをご覧ください。

== リリースロードマップ

Temurin のリリース頻度は依存関係のスケジュールに基づいています。

OpenJDK は 6 ヶ月ごとに新しいフィーチャーリリースを提供し、各アクティブなリリースに基づくメンテナンス/セキュリティアップデートを 3 ヶ月ごとに提供します。OpenJDK プロジェクトからのリリース日は通常、1月、4月、7月、10月の https://www.oracle.com/security-alerts/[第 3 火曜日]です。最新のセキュアなビルドを確実に提供するために、Adoptium からのバイナリリリース公開にはこのスケジュールに従います。

さらに、2021年以降 2 年ごとに 1 つのフィーチャーリリースが長期サポート（LTS）リリースとして指定されます。LTS リリースは少なくとも 4 年間サポートします。この保証により、明確に定義されたコードストリームに留まることができ、次の新しい安定した LTS リリースが利用可能になったときに移行する時間が得られます。

このロードマップに基づき、Eclipse Temurin をビルドするために使用されるさまざまな OpenJDK リリースの現在のリリース日のタイムテーブルを以下に示します。以下の日付は https://www.java.com/releases[上流の OpenJDK プロジェクトページ]からのものであり、Adoptium プロジェクトがバイナリを利用可能にする日付ではないことに注意してください。最大 3 週間を要する広範なビルドおよびテストサイクルを完了するため、これらの日付から短い遅延があります。https://calendar.google.com/calendar/embed?src=c_56d7263c0ceda87a1678f6144426f23fb53721480b5ff71b073afb51091e5492%40group.calendar.google.com[リリースサイクルを示す Google カレンダー]では、各リリースの予想サイクル長を確認できます。最も人気のあるプラットフォームを常に優先し、これらの日付の数日以内に提供するようにしています。

include::{partialDir}/support-table.adoc[]

^[1]^ 一般的な方針として、Adoptium は対応するアップストリームソースがアクティブにメンテナンスされている限り、LTS リリースのバイナリのビルドを継続します。

^[2]^ サービス/サポートのEnd of Life — このコードストリームはメンテナンスされなくなりました。Eclipse Temurin のさらなるビルドは計画されていません。
