// Some portions generated by Co-Pilot
"use client";

import React from "react";
import { Link } from "@/i18n/navigation";
import { useTranslations } from "next-intl";
import type { BinaryAssetView, TemurinAssets } from "@/types/temurin";
import { FaRegFileCode } from "react-icons/fa";
import { GrNotes, GrInstall } from "react-icons/gr";
import { GiFlatPlatform } from "react-icons/gi";

interface ReleaseLinksProps {
  selectedVersion: string;
  releases: BinaryAssetView[] | TemurinAssets;
}

const ReleaseLinks: React.FC<ReleaseLinksProps> = ({
  selectedVersion,
  releases,
}) => {
  const t = useTranslations("Temurin.Releases.ReleaseLinks");
  if (!releases.length) {
    return null;
  }

  // TemurinAssets has an optional `source` property (SOURCES image type)
  const sourceView =
    "source" in releases ? (releases as TemurinAssets).source : undefined;

  let releaseNotesUrl = "/temurin/release-notes";
  if (sourceView?.release_name) {
    releaseNotesUrl = `/temurin/release-notes/?version=${sourceView.release_name}`;
  }

  const installationGuideUrl = "/installation";
  const supportedPlatformsUrl = "/supported-platforms";

  let sourceCodeUrl = "#";
  if (sourceView?.binary?.package?.link) {
    sourceCodeUrl = sourceView.binary.package.link as string;
  }
  if (sourceCodeUrl === "#") {
    const vNum = parseInt(selectedVersion, 10);
    if (!isNaN(vNum)) {
      sourceCodeUrl = `https://github.com/adoptium/temurin${vNum}-binaries`;
    }
  }

  return (
    <section
      className="w-full max-w-[1264px] mx-auto"
      data-testid="release-links-section"
    >
      <ul
        className="flex md:flex-row flex-col gap-4 lg:gap-8 items-start w-full justify-start sm:justify-center sm:items-center my-8"
        data-testid="release-links-list"
      >
        <Link href={releaseNotesUrl}>
          <li
            className="flex gap-3 group items-center text-white hover:text-primary transition-all duration-300 ease-in-out text-xl font-normal cursor-pointer"
            data-testid="release-notes-link"
          >
            <span className="group">
              <GrNotes />
            </span>
            {t("release-notes")}
          </li>
        </Link>

        <Link href={installationGuideUrl}>
          <li
            className="flex gap-3 group items-center text-white hover:text-primary transition-all duration-300 ease-in-out text-xl font-normal cursor-pointer"
            data-testid="installation-guide-link"
          >
            <span className="group">
              <GrInstall />
            </span>
            {t("installation-guide")}
          </li>
        </Link>

        <Link href={supportedPlatformsUrl}>
          <li
            className="flex gap-3 group items-center text-white hover:text-primary transition-all duration-300 ease-in-out text-xl font-normal cursor-pointer"
            data-testid="supported-platforms-link"
          >
            <span className="group">
              <GiFlatPlatform />
            </span>
            {t("supported-platforms")}
          </li>
        </Link>

        <Link href={sourceCodeUrl} target="_blank">
          <li
            className="flex gap-3 group items-center text-white hover:text-primary transition-all duration-300 ease-in-out text-xl font-normal cursor-pointer"
            data-testid="source-code-link"
          >
            <span className="group">
              <FaRegFileCode />
            </span>
            {t("source-code")}
          </li>
        </Link>
      </ul>
    </section>
  );
};

export default ReleaseLinks;
