// Some portions generated by Co-Pilot
import React from "react";
import { render, screen, fireEvent, cleanup } from "@testing-library/react";
import { describe, it, expect, vi, afterEach } from "vitest";
import AllReleaseCard from "../index";
import type { MarketplaceRelease } from "@/hooks";

vi.mock("@/components/Download/ChecksumModal", () => ({
  default: ({
    open,
    setOpen,
  }: {
    open: boolean;
    setOpen: (v: boolean) => void;
  }) =>
    open ? (
      <div data-testid="checksum-modal">
        <button onClick={() => setOpen(false)}>Close</button>
      </div>
    ) : null,
}));

vi.mock("@/components/Common/AnimatedPlaceholder", () => ({
  default: ({ children }: { children: React.ReactNode }) => (
    <div>{children}</div>
  ),
}));

vi.mock("@/hooks", () => ({
  getImageForDistribution: () => "/images/test-vendor.png",
}));

vi.mock("@/utils/gtag", () => ({
  sendDownloadEvent: vi.fn(),
}));

vi.mock("@/utils/fetchExtension", () => ({
  fetchExtension: () => "tar.gz",
}));

const mockRelease: MarketplaceRelease = {
  release_name: "jdk-21.0.3+9",
  vendor: "eclipse",
  binary: {
    architecture: "x64",
    distribution: "temurin",
    image_type: "jdk",
    jvm_impl: "hotspot",
    os: "linux",
    scm_ref: "abc123",
    timestamp: new Date("2024-04-01T00:00:00Z"),
    package: {
      link: new URL("https://example.com/download.tar.gz"),
      name: "OpenJDK21U-jdk_x64_linux.tar.gz",
      sha256sum: "sha256abc123",
      sha256sum_link: new URL("https://example.com/sha256"),
      signature_link: new URL("https://example.com/sig"),
      size: 200000000,
    },
    download_count: 1000,
  },
};

describe("AllReleaseCard", () => {
  afterEach(() => {
    cleanup();
  });

  it("renders loading state when results is null", () => {
    const { container } = render(<AllReleaseCard results={null} />);
    expect(container.firstChild).not.toBeNull();
    // Should show skeleton/animated placeholders
    const pulseElements = container.querySelectorAll(".animate-pulse");
    expect(pulseElements.length).toBeGreaterThan(0);
  });

  it("renders no results state when results is empty array", () => {
    const { getByText } = render(<AllReleaseCard results={[]} />);
    expect(getByText(/No distributions found/i)).toBeTruthy();
  });

  it("calls onReset when reset button is clicked in empty state", () => {
    const onReset = vi.fn();
    const { getByText } = render(
      <AllReleaseCard results={[]} onReset={onReset} />,
    );
    const resetButton = getByText(/Reset Filters/i);
    fireEvent.click(resetButton);
    expect(onReset).toHaveBeenCalledTimes(1);
  });

  it("does not show reset button in empty state when onReset is not provided", () => {
    const { queryByText } = render(<AllReleaseCard results={[]} />);
    expect(queryByText(/Reset Filters/i)).toBeNull();
  });

  it("renders release cards when results are provided", () => {
    const { container } = render(<AllReleaseCard results={[mockRelease]} />);
    expect(container.firstChild).not.toBeNull();
    // Release name should appear
    const releaseNameEls = container.querySelectorAll("h3");
    expect(releaseNameEls.length).toBeGreaterThan(0);
  });

  it("opens checksum modal when checksum button is clicked", () => {
    render(<AllReleaseCard results={[mockRelease]} />);
    const checksumButtons = screen.queryAllByLabelText("View checksum");
    expect(checksumButtons.length).toBeGreaterThan(0);
    fireEvent.click(checksumButtons[0]);
    expect(screen.getByTestId("checksum-modal")).toBeTruthy();
  });

  it("renders multiple releases", () => {
    const releases = [
      mockRelease,
      { ...mockRelease, release_name: "jdk-17.0.10+7" },
    ];
    const { container } = render(<AllReleaseCard results={releases} />);
    const cards = container.querySelectorAll(".rounded-xl");
    expect(cards.length).toBeGreaterThan(0);
  });
});
