// Some portions generated by Co-Pilot
= Politique de la Suite de Vérification de Qualité AQAvit(TM)
:description: Politique QVS Adoptium
:keywords: adoptium AQAvit qualité politique
:orgname: Eclipse Adoptium
:page-authors: tellison, gdams, HanSolo
:page-based-on: f2e6e929f64dd6ef7bd7f452d2aed14095705a31

== Présentation

https://projects.eclipse.org/projects/adoptium.aqavit[AQAvit^]
est le projet d'évaluation de la qualité pour les environnements d'exécution Java SE et les technologies associées. AQAvit prend un environnement d'exécution Java fonctionnellement complet et s'assure que toutes les qualités supplémentaires sont présentes pour le rendre adapté à une utilisation en production. Ces critères de qualité incluent de bonnes performances, une sécurité exceptionnelle, la résilience et l'endurance, ainsi que la capacité à réussir une grande variété de suites de tests d'applications.

== Vérification de Produit Logiciel AQAvit

Les tests Eclipse AQAvit sont
https://projects.eclipse.org/projects/adoptium.aqavit/developer[mis à disposition du public^]
gratuitement en tant que logiciel open source. Vous pouvez forker, copier ou modifier le logiciel AQAvit sous réserve des termes de la licence logicielle.

Des
https://github.com/adoptium/aqa-tests/releases[versions désignées de la suite de vérification de qualité AQAvit^]
(QVS) sont disponibles sous la
https://www.eclipse.org/legal/eclipse-foundation-quality-verification-suite-license.php[Licence de Suite de Vérification de Qualité de la Fondation Eclipse^]
(QVSL). Un produit logiciel sera considéré comme « vérifié » par la QVS AQAvit s'il satisfait pleinement et complètement toutes les exigences de la QVS AQAvit telles que décrites dans la QVSL.

Il n'est pas nécessaire d'être membre du groupe de travail Adoptium pour produire un produit logiciel vérifié AQAvit.

== Déclarations Factuelles sur les Tests AQAvit

Tout le monde peut exécuter les suites de tests AQAvit et faire des déclarations factuellement correctes sur les résultats.

« AQAvit » est une marque déposée de la Fondation Eclipse et est gérée conformément à la
https://www.eclipse.org/legal/logo_guidelines.php[Politique de Directives pour les Logos et Marques de la Fondation Eclipse^].
En tant que tel, l'utilisation des marques d'Eclipse ou de toute description similaire n'est pas autorisée en association avec un logiciel ou des services connexes. Vous ne pouvez utiliser le terme « AQAvit » et le logo du projet AQAvit qu'avec l'autorisation de la Fondation Eclipse.

Les modifications de cette politique sont effectuées par le
link:/members[Comité de Direction du Groupe de Travail Adoptium].
