= AQAvit(TM) Quality Verification Suite Policy
:description: Adoptium QVS Policy
:keywords: adoptium AQAvit quality policy
:orgname: Eclipse Adoptium
:lang: en
:page-authors: gdams, HanSolo, hendrikebbers, xavierfacq
:page-based-on: edd131f41d548b815a7edbcf59848b8161fbc9e6

== Überblick

https://projects.eclipse.org/projects/adoptium.aqavit[AQAvit^]
ist das Qualitätsbewertungsprojekt für Java SE Runtimes und zugehörige Technologien. AQAvit nimmt eine funktional vollständige Java-Runtime und stellt sicher, dass sie alle Qualitätskriterien erfüllt, welche sie für den Einsatz in der Produktion eignet.
Zu diesen Qualitätskriterien gehören gute Leistung, außergewöhnliche Sicherheit, Robustheit und Langlebigkeit, sowie die Fähigkeit, eine Vielzahl von Anwendungstestsuiten zu bestehen.

== AQAvit Software Produktüberprüfung

Eclipse AQAvit tests sind
https://projects.eclipse.org/projects/adoptium.aqavit/developer[frei für die Öffentlichkeit verfügbar^]
als Open Source lizensierte Software. 
at no charge as open source licensed software. Sie können die AQAvit-Software gemäß den Bedingungen der Softwarelizenz forken, kopieren oder modifizieren.

Nominierte
https://github.com/adoptium/aqa-tests/releases[Versionen der AQAvit Qualitätstestsuite^]
(QVS) sind verfügbar unter der 
https://www.eclipse.org/legal/eclipse-foundation-quality-verification-suite-license.php[Eclipse Foundation Quality Verification Suite License^] (QVSL). Ein Softwareprodukt gilt als von der AQAvit QVS "verifiziert", wenn es alle Anforderungen der AQAvit QVS, wie in der QVSL beschrieben, vollständig erfüllt und einhält.

Es ist nicht notwendig, ein Mitglied der Adoptium-Arbeitsgruppe zu sein, um ein AQAvit-geprüftes Softwareprodukt zu erstellen.

== Fakten über AQAvit Tests

Jeder kann die AQAvit-Testsuiten ausführen und sachlich korrekte Aussagen über die Ergebnisse machen.

"AQAvit" ist ein eingetragenes Warenzeichen der Eclipse Foundation und wird gemäß der https://www.eclipse.org/legal/logo_guidelines.php[Eclipse Foundation Guidelines for Eclipse Logos & Trademarks Policy^] gehandhabt.
Daher ist die Verwendung von der Eclipse Marke oder ähnlichen Bezeichnungen in Verbindung mit Software oder damit verbundenen Dienstleistungen nicht gestattet. Sie dürfen den Begriff "AQAvit" und das Logo des AQAvit-Projekts
nur mit der Genehmigung der Eclipse Foundation verwenden.

Änderungen an dieser Richtlinie werden durch das
link:/members[Adoptium Working Group Steering Committee] gemacht.
