// Some portions generated by Co-Pilot
import { useTranslations, useLocale } from "next-intl";
import { capitalize } from "@/utils/capitalize";
import { getExtension, getSizeMB } from "@/utils/temurin";
import type { Release } from "@/types/temurin";

const TemurinNightlyTable = ({
  results,
  openModalWithChecksum,
}: {
  results: { releases: Release[] };
  openModalWithChecksum: (checksum: string) => void;
}) => {
  const t = useTranslations("Temurin.Nightly");
  const locale = useLocale();
  if (!results || !results.releases || results.releases.length === 0) {
    return (
      <div className="text-center text-gray-400 py-8">{t("no-results")}</div>
    );
  }
  return (
    <div className="overflow-x-auto rounded-xl bg-[#1B1132]">
      <table className="min-w-full divide-y divide-[#3E3355]">
        <thead className="bg-[#26193F]">
          <tr>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
              {t("platform")}
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
              {t("architecture")}
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
              {t("type")}
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
              {t("build-tag")}
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
              {t("date")}
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
              {t("binary")}
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
              {t("installer")}
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
              SHA256
            </th>
          </tr>
        </thead>
        <tbody className="bg-[#1B1132] divide-y divide-[#3E3355]">
          {results.releases.flatMap((release: Release) =>
            (release?.binaries ?? []).map((binary, idx) => {
              const pkgLink = binary.package?.link as string | undefined;
              const pkgChecksum = binary.package?.checksum ?? "";
              const pkgExt = getExtension(binary.package?.name);
              const instLink = binary.installer?.link as string | undefined;
              const instExt = getExtension(binary.installer?.name);
              const timestamp = release.timestamp ?? release.updated_at;
              return (
                <tr
                  key={`${release.release_name}-${binary.os}-${binary.architecture}-${binary.image_type}-${idx}`}
                >
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-300">
                    {capitalize(binary.os ?? "")}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-300">
                    {binary.architecture}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-300">
                    {capitalize(binary.image_type ?? "")}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-200">
                    {release.release_name}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-300">
                    {timestamp
                      ? new Date(timestamp).toLocaleDateString(locale, {
                          year: "numeric",
                          month: "short",
                          day: "numeric",
                        })
                      : ""}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-pink">
                    {pkgLink ? (
                      <a
                        href={pkgLink}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        {pkgExt} ({getSizeMB(binary.package?.size)} MB)
                      </a>
                    ) : (
                      <span className="text-gray-500">
                        {t("download-not-available")}
                      </span>
                    )}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-pink">
                    {instLink ? (
                      <a
                        href={instLink}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        {instExt}
                      </a>
                    ) : (
                      <span className="text-gray-500">
                        {t("download-not-available")}
                      </span>
                    )}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-300">
                    <button
                      className="text-pink"
                      onClick={() => openModalWithChecksum(pkgChecksum)}
                    >
                      {t("checksum")}
                    </button>
                  </td>
                </tr>
              );
            }),
          )}
        </tbody>
      </table>
    </div>
  );
};

export default TemurinNightlyTable;
