// Some portions generated by Co-Pilot
import React from "react"
import Image from "next/image"

interface ProfilePicProps {
  identifier: string
  name: string
  size?: number
}

const ProfilePic = ({ identifier, name, size = 50 }: ProfilePicProps) => {
  return (
    <Image
      src={`/images/authors/${identifier}.jpg`}
      alt={name}
      width={size}
      height={size}
      className="ml-2 mb-0 rounded-full"
    />
  )
}

export default ProfilePic
