// Some portions generated by Co-Pilot
import React from "react";
import { render, cleanup } from "@testing-library/react";
import { describe, it, expect, afterEach, vi } from "vitest";
import NavBar from "../index";

vi.mock("@/i18n/navigation", () => ({
  Link: ({ children }: any) => <a>{children}</a>,
  usePathname: () => "",
}));

describe("NavBar", () => {
  afterEach(() => {
    cleanup();
  });

  it("should match the snapshot", () => {
    const { container } = render(<NavBar locale="en" />);
    expect(container.firstChild).toMatchSnapshot();
  });
});
