// Some portions generated by Co-Pilot
import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import TemurinFeatures from "../index";

describe("TemurinFeatures", () => {
  it("renders the features section", () => {
    const { container } = render(<TemurinFeatures />);
    expect(container.querySelector(".temurin-features")).toBeInTheDocument();
  });

  it("renders the title text", () => {
    render(<TemurinFeatures />);
    // useTranslations mock returns "Text" for all keys
    expect(screen.getAllByText("Text").length).toBeGreaterThan(0);
  });

  it("renders the Download Temurin button", () => {
    render(<TemurinFeatures />);
    const buttons = screen.getAllByRole("button", { name: /download temurin/i });
    expect(buttons.length).toBeGreaterThan(0);
  });

  it("renders navigation buttons for the swiper", () => {
    render(<TemurinFeatures />);
    const prevButtons = screen.getAllByLabelText(/previous feature/i);
    const nextButtons = screen.getAllByLabelText(/next feature/i);
    expect(prevButtons.length).toBeGreaterThan(0);
    expect(nextButtons.length).toBeGreaterThan(0);
  });

  it("renders feature slides", () => {
    render(<TemurinFeatures />);
    // Features include images with alt text from translations
    const images = screen.getAllByRole("img");
    expect(images.length).toBeGreaterThan(0);
  });

  it("renders a link to temurin releases page", () => {
    render(<TemurinFeatures />);
    const links = screen.getAllByRole("link");
    const releaseLink = links.find(
      (link) => link.getAttribute("href") === "/temurin/releases"
    );
    expect(releaseLink).toBeDefined();
  });
});
