// Some portions generated by Co-Pilot
"use client";

import React from "react";
import { Link, usePathname } from "@/i18n/navigation";
import type { SidebarSection } from "@/services/asciidocService";

function isActive(pathname: string, href: string): boolean {
  return pathname === href || pathname === `${href}/`;
}

interface DocSidebarProps {
  section: SidebarSection;
}

const DocSidebar: React.FC<DocSidebarProps> = ({ section }) => {
  const pathname = usePathname();

  return (
    <nav className="w-full" aria-label="Documentation navigation">
      <div className="mb-3">
        <p className="text-xs font-semibold uppercase tracking-wider text-gray-400 light:text-gray-500 mb-3 px-3">
          {section.title}
        </p>
      </div>
      <ul className="space-y-0.5">
        {section.items.map((item) => {
          const active = isActive(pathname, item.href);
          return (
            <li key={item.href}>
              <Link
                href={item.href}
                className={`block px-3 py-2 rounded-md text-sm transition-colors duration-150 ${
                  active
                    ? "bg-pink/10 text-pink font-medium border-l-2 border-pink"
                    : "text-gray-300 hover:bg-white/5 hover:text-white light:text-gray-900 light:hover:bg-gray-100 light:hover:text-gray-900"
                }`}
              >
                {item.title}
              </Link>
            </li>
          );
        })}
      </ul>
    </nav>
  );
};

export default DocSidebar;
