// Some portions generated by Co-Pilot
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { render, screen, fireEvent, cleanup } from "@testing-library/react";
import DocThemeToggle from "../index";

describe("DocThemeToggle", () => {
  beforeEach(() => {
    document.documentElement.classList.remove("doc-light");
    localStorage.clear();
  });

  afterEach(() => {
    cleanup();
  });

  it("renders with light mode label by default", () => {
    render(<DocThemeToggle />);
    const button = screen.getByRole("button");
    expect(button.textContent).toContain("Light");
  });

  it("has correct aria-label when in dark mode", () => {
    render(<DocThemeToggle />);
    const button = screen.getByRole("button");
    expect(button).toHaveAttribute("aria-label", "Switch to light mode");
  });

  it("toggles to light mode on click", () => {
    render(<DocThemeToggle />);
    const button = screen.getByRole("button");

    fireEvent.click(button);

    expect(button).toHaveAttribute("aria-label", "Switch to dark mode");
    expect(button.textContent).toContain("Dark");
    expect(document.documentElement.classList.contains("doc-light")).toBe(true);
    expect(localStorage.getItem("doc-theme")).toBe("light");
  });

  it("toggles back to dark mode on second click", () => {
    render(<DocThemeToggle />);
    const button = screen.getByRole("button");

    fireEvent.click(button); // to light
    fireEvent.click(button); // back to dark

    expect(button.textContent).toContain("Light");
    expect(document.documentElement.classList.contains("doc-light")).toBe(
      false,
    );
    expect(localStorage.getItem("doc-theme")).toBe("dark");
  });

  it("restores light mode from localStorage on mount", () => {
    localStorage.setItem("doc-theme", "light");

    render(<DocThemeToggle />);
    const button = screen.getByRole("button");

    expect(button.textContent).toContain("Dark");
    expect(document.documentElement.classList.contains("doc-light")).toBe(true);
  });

  it("stays dark when localStorage has dark value", () => {
    localStorage.setItem("doc-theme", "dark");

    render(<DocThemeToggle />);
    const button = screen.getByRole("button");

    expect(button.textContent).toContain("Light");
    expect(document.documentElement.classList.contains("doc-light")).toBe(
      false,
    );
  });
});
